### ISSUE TITLE
How to prevent navigation on webview when a URL link is clicked

### ISSUE THREAD

**Issue by wsangtoki** [atom/electron#4191] opened 2016-01-22 02:00 UTC
Hi, 
I looked into the following sentence in **will-navigate** event (https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md) documentation.

>Calling event.preventDefault() does NOT have any effect.

So how can we prevent webview from navigating to other page? I intent to launch default browser when user clicks on a URL link on webview.
Here is my code on the renderer process.

```javascript
 webview.addEventListener('will-navigate', function(e) {
        e.preventDefault();
        require('electron').shell.openExternal(e.url);
 });
```
With this code, when I click the URL link on webview, webview will navigate to the new page and default browser also opened showing the new page. I want webview to stop navigating to the new page.

**Comment by xywz** [comment] 2016-01-22 07:47
Duplicate of #1378.

**Closed** 2016-01-22 18:35 UTC

**Comment by kunkinkan** [comment] 2016-06-11 18:00
I don't see a solution posted?

**Comment by mkinawy** [comment] 2016-09-09 09:59
this works for me for preventing navigation via user clicking on links and notifying the app about the requested url. Using preload and injecting this:
```
document.addEventListener('DOMContentLoaded', function () {
  document.addEventListener('click', function (e) {
    e.preventDefault();
    e.stopPropagation();
    setTimeout(function () {
      var path = e.target.href;
      ipcRenderer.sendToHost('element-clicked', path);
    }, 100);
    return false;
  }, true);
});
```
please note the 3rd param at the `document.addEventListener('click', fn, true)`

**Comment by msudgh** [comment] 2018-07-07 20:12
## Unsafe solution
On `will-navigate` event, In `renderer process` for just preventing clicking you can stop the navigating by `stop` method.
```ts
webview.addEventListener('will-navigate', (e: any) => {
    webview.stop()
})
```

it makes stop web view to navigation.
