### ISSUE TITLE
Couldn't load PDF Plugin on Windows

### ISSUE THREAD

**Issue by shoaibmerchant** [atom/electron#1826] opened 2015-05-31 00:54 UTC
I just went through the issues & releases related to printing in windows it seems to be resolved now but I am still unable to print from the BrowserWindow.

OS: Windows 8.1
Electron version: v0.27.1

The log entries on the console 
```
[7784:0531/061037:WARNING:printing_handler_win.cc(37)] Couldn't load PDF plugin
[10420:0531/061037:ERROR:print_web_view_helper.cc(711)] Failure in OnPrintingDon
e
[10420:0531/061219:WARNING:raw_channel_win.cc(473)] WriteFile: The pipe is being
 closed. (0xE8)
[10420:0531/061219:WARNING:channel.cc(549)] Failed to send message to ack remove
 remote endpoint (local ID 1, remote ID 1)
[10420:0531/061219:WARNING:channel.cc(315)] RawChannel write error
```

To describe my use case, I am generating some html from the page (renderer) and then using ipc to send it to the browser script (main.js) , the browser script writes the html and creates a BrowserWindow and loads the newly created html file. On showing the browser window I trigger the print (tried with a timeout too). The browserwindow shows up fine but the printing fails with the above mentioned error.

```
  ipc.on('print-window', function(event, data) {
    
    var BrowserWindow = require('browser-window');

    var print_window = new BrowserWindow({ width: 300, height: 500, show: false });

    print_window.on('closed', function() {
      print_window = null;
    });

    var stylesheet = '<link rel="stylesheet" href="css/tbl_prnt.css" type="text/css" />';
    var print_doc = '<html><head><title>my div</title>' +  stylesheet + '</head><body >' + data + '</body></html>';
    
    fs.writeFileSync("src/print.html", print_doc);

    print_window.loadUrl('file://' + __dirname + '\\src\\print.html');
    print_window.show();

    print_window.openDevTools();
    setTimeout(function(){
      print_window.print();  
    }, 3000);
    
    // print_window.close();

  });
```

Thanks for the help!

**Comment by hokein** [comment] 2015-05-31 06:57
Looks like you are missing the `pdf.dll` library.

**Comment by shoaibmerchant** [comment] 2015-05-31 07:22
Yes I read in your PR regarding pdf.dll that it is included if required to decrease package size. Can you let me know how to go about adding it to my build?

**Comment by hokein** [comment] 2015-05-31 08:45
The above sample code looks fine to me. It should be worked. Could you please provide a completed minimal sample code for reproducing the issue?

 >  Can you let me know how to go about adding it to my build?

So are you building `electron` with your own custom modication? The `pdf.dll` is shipped in `libchromiumcontent`. `electron` just does some dynamic loading during `print` API invoking. So You don't need to adding it for your building.

**Comment by shoaibmerchant** [comment] 2015-05-31 19:45
I will share a sample code in a day or two. Thanks!

>The pdf.dll is shipped in libchromiumcontent. electron just does some dynamic >loading during print API invoking. So You don't need to adding it for your >building.

Yes this is what I thought too, just wanted to confirm.

**Comment by zcbenz** [comment] 2015-06-01 04:27
If you are building a custom build, you should run `./script/create-dist.py` to generate a complete distribution that includes all required files. I'm closing this since it doesn't seem to be a bug.

**Comment by shoaibmerchant** [comment] 2015-06-01 04:31
I am not generating a custom build, this is while running the app with the latest electron prebuilt.

**Closed** 2015-06-01 04:54 UTC
Labels: bug, windows

**Comment by shoaibmerchant** [comment] 2015-06-01 04:58
Awesome thanks, i had just finished setting up a sample repo.
