### ISSUE TITLE
'hex' Buffer encoding doesn't parse clipboard data correctly

### ISSUE THREAD

**Issue by Morhaus** [atom/electron#634] opened 2014-09-07 10:37 UTC
Hey.

When retrieving a hexadecimal string from the user's clipboard and converting it to a Buffer via `new Buffer string, 'hex'`, it seems that the second half of the string isn't parsed correctly and defaults to a random byte string.

```coffeescript
document.addEventListener 'paste', (evt) ->
  str1 = evt.clipboardData.getData 'Text'
  str2 = 'F1F2F3F4'
  buf1 = new Buffer str1, 'hex'
  buf2 = new Buffer str2, 'hex'
  str1 === str2 # => true
  buf1.toString 'hex' # => 'f1f20000'
  buf2.toString 'hex' # => 'f1f2f3f4'
```

**Comment by bpasero** [comment] 2015-05-21 14:27
@zcbenz I think this issue is back again. Could it be that since Electron is now using raw io.js that your patch is not in? I have a case where data from the clipboard has the wrong representation in the buffer.

**Comment by zcbenz** [comment] 2015-05-22 01:48
@bpasero Can you provide a example? The code in this issue and [my test](https://github.com/atom/electron/commit/b360122b35cfeeaa93da810b862ee0951484a8db) seem to work fine.

**Comment by bpasero** [comment] 2015-05-23 16:43
@zcbenz I can still reproduce this issue with 0.26.1. Its a bit hard to repro, but here are the steps:
- run electron 0.26.1 after downloading it, no need to write our own app
- open devtools
- after the opening body element add ```<textarea id="tt"></textarea>"```
- use another editor to copy the following value into the clipboard: Jøhänñéß
- paste into the text area
- use the devtools and type ```new Buffer(document.getElementById("tt").value).toString()```

=> the resulting string is: "Jøhän" and we lost some bytes. When you inspect the buffer you will see that its byte length is only 7.

**Comment by bpasero** [comment] 2015-05-24 08:15
Btw I just realized that your patch for external buffers is actually in your fork of io.js (https://github.com/atom/node/commit/07fac12412545e23891c602c3d3fab2ac6d39f20). So this issue I am seeing might not even be the same.

**Comment by zcbenz** [comment] 2015-05-27 07:27
Fixed with patch https://github.com/atom/node/commit/b772c19a8f9db65673184822fb294235eff9c364.

**Closed** 2015-05-27 07:27 UTC
Labels: bug

**Comment by bpasero** [comment] 2015-05-27 08:16
Oh nice, thanks. Waiting for the Electron update :)
