### ISSUE TITLE
no event for "ondrop"

### ISSUE THREAD

**Issue by songRT** [atom/electron#3886] opened 2015-12-21 10:43 UTC
ever since I update my program to 0.36.0.no event "ondrop",waiting for solutions

**Comment by zcbenz** [comment] 2015-12-22 10:57
Can you provide a reproducible example?

**Comment by songRT** [comment] 2015-12-24 03:24
the code was defined in a <webview> tag,the implants just like
<div id="holder">
  Drag your file here
</div>

<script>
  var holder = document.getElementById('holder');
  holder.ondragover = function () {
    return false;
  };
  holder.ondragleave = holder.ondragend = function () {
    return false;
  };
  holder.ondrop = function (e) {
    e.preventDefault();
    var file = e.dataTransfer.files[0];
    console.log('File you dragged here is', file.path);
    return false;
  };
</script>

**Comment by zcbenz** [comment] 2015-12-24 03:32
This is a duplicate of #2897, it has been a long time [upstream bug](https://code.google.com/p/chromium/issues/detail?id=412373).

**Closed by zcbenz** 2015-12-24 03:32 UTC

**Comment by songRT** [comment] 2015-12-24 03:47
Thank you very much
