### ISSUE TITLE
Whenever Electron app is open, other application windows not drawn properly

### ISSUE THREAD

**Issue by pmadhur** [atom/electron#4332] opened 2016-02-02 18:16 UTC
If I open Electron app, all other windows are not drawn properly. Attached gif shows what I mean. 
I am on Windows 7 64 bit professional. Actually I had encountered this issue with vscode, I was suggested that I report it here because with Electron.exe the same problem appears.

![image1](https://cloud.githubusercontent.com/assets/16571328/12759396/24f720c2-c9e1-11e5-95e2-8375c3759824.gif)

![image2](https://cloud.githubusercontent.com/assets/16571328/12759398/2b38100e-c9e1-11e5-83f1-4f5fceb2f872.gif)

If I change my windows theme from Windows 7 Basic to Windows Classic, the problem does not appear.

![image3](https://cloud.githubusercontent.com/assets/16571328/12759403/323aef5c-c9e1-11e5-9ff3-d46605494751.png)

I have tried on different Windows 7 machines, all of them have the same problem.

**Comment by felixrieseberg** [comment] 2016-02-03 01:31
I will try to reproduce the issue.

**Comment by paulcbetts** [comment] 2016-02-03 01:33
This is a dupe of #1821

**Comment by felixrieseberg** [comment] 2016-02-03 01:36
Well then, let's close in favor of that one - I'll still try to see what the heck is actually going on here.

**Closed by felixrieseberg** 2016-02-03 01:36 UTC
Labels: more-information-needed, windows

**Comment by pmadhur** [comment] 2016-02-12 15:39
@felixrieseberg could you find something? would like to use vscode, but unfortunately cannot use because of this problem.
