### ISSUE TITLE
electron does nothing

### ISSUE THREAD

**Issue by freakypie** [atom/electron#4771] opened 2016-03-12 15:54 UTC
* Electron version:0.37.0
* Operating system: windows 7

running electron does nothing as far as i can tell

> /c/GitHub/sandbox (master) $ electron .
> (no output)
> /c/GitHub/sandbox (master) $ electron --help
> (no output)

**Comment by zcbenz** [comment] 2016-03-13 01:52
This is a duplicate of #4770.

**Closed by zcbenz** 2016-03-13 01:52 UTC

**Comment by freakypie** [comment] 2016-03-13 03:10
I'm not sure that #4770 is related. I don't get any popups, or any windows at all.

**Comment by ejoebstl** [comment] 2017-03-09 14:58
1 Up. Not related to #4770.

**Comment by ejoebstl** [comment] 2017-03-09 15:27
*Heads up* 

Electron and nightmare run nicely on native windows. You can work with them without using Bash for Windows.

**Comment by brenca** [comment] 2017-03-09 16:50
[This](https://github.com/Microsoft/BashOnWindows/issues/333) might be relevant
