### ISSUE TITLE
download file doesn't work properly

### ISSUE THREAD

**Issue by boboai612** [atom/electron#1950] opened 2015-06-12 01:20 UTC
Below is my code to reproduce problem:

function downloadFile(fileName, content){
    var aLink = document.createElement('a');
    var blob = new Blob([content]);
    var evt = document.createEvent("HTMLEvents");
    evt.initEvent("click", false, false);
    aLink.download = fileName;
    aLink.href = URL.createObjectURL(blob);
    aLink.dispatchEvent(evt);
}

This function work well in chrome but atom/electron.

Then, I tried the other way like this:
<pre>
&lt;a href="http://example.com/xxx.zip" download="xxx.zip"&gt;download&lt;/a&gt;
</pre>
it also doesn't work properly

**Comment by 50Wliu** [comment] 2015-06-12 01:22
What do you mean by "doesn't work properly"?  Can you clarify?

**Comment by boboai612** [comment] 2015-06-12 01:24
It doesn't  show the file download dialog

**Comment by boboai612** [comment] 2015-06-12 01:26
both v0.27.3 and v0.23.0

**Comment by thesbros** [comment] 2015-06-12 05:56
A "file download dialog" [doesn't show up for me](https://html5-demos.appspot.com/static/a.download.html) in Chrome. It just downloads the file like normal, what is the expected behavior? Can you screenshot it?

**Comment by zcbenz** [comment] 2015-06-12 07:38
This is a duplicate of #1909.

**Closed by zcbenz** 2015-06-12 07:38 UTC
Labels: needs-reproduction
