### ISSUE TITLE
HiDPI menus on Linux seem to be double-sized

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#1228] opened 2015-03-10 18:23 UTC
1. Set up HiDPI on a Linux Laptop
2. Open an Atom Shell app with a menu

![](http://cl.ly/image/3k3y0W431o04/content#png)

Content is scaled correctly, but menus appear to be double-scaled (i.e. they're already being doubled, then we're doubling them again)

```bash
% cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.1
DISTRIB_CODENAME=rebecca
DISTRIB_DESCRIPTION="Linux Mint 17.1 Rebecca"
```

**Comment by zcbenz** [comment] 2015-03-10 20:24
This is a known Chromium bug:
https://code.google.com/p/chromium/issues/detail?id=403302

**Comment by zcbenz** [comment] 2015-03-20 01:51
Chromium has launched a fix for this, which will be available in Chrome 43:
https://chromium.googlesource.com/chromium/src.git/+/aa051ee8d1a7ff725225d783d1a96663d5aedb08

**Comment by paulcbetts** [comment] 2015-03-20 04:07
I know this is a super pain in the butt, but if we can add https://chromium.googlesource.com/chromium/src.git/+/aa051ee8d1a7ff725225d783d1a96663d5aedb08%5E%21 to our patches folder and it applies cleanly, it'd be huge for us at Slack

**Comment by zcbenz** [comment] 2015-03-20 06:30
Lots of Atom users [complain about it](https://github.com/atom/atom/issues/3826) too, so I think it is reasonable to include it in our patches. But I need to verify whether it actually solves the problem.

**Comment by zcbenz** [comment] 2015-03-23 06:35
@paulcbetts After looking into it I found that patch depends on lots of other DPI related changes which are not available in Chrome 41, and it is not practical to add all of them to our patches. So I'll take another look when Chrome 42 becomes stable.

**Comment by paulcbetts** [comment] 2015-03-23 06:42
:cool: :+1:

**Comment by shatsar** [comment] 2015-03-24 15:16
Same issue here, with a Chromebook Pixel running Gnome Shell with Crouton, let's wait for Chrome 42 ;)

**Comment by mrmylanman** [comment] 2015-04-22 02:23
Just wanted to state that it looks like this is still an issue in version 0.193. I installed Chrome 42 to see if it was exhibiting similar behavior when launched with the `--force-device-scale-factor=2.0` flag, and it does. All menus seem to be double the size that they should be (for a total of 4x scaling, I guess?). 

Looks like we have to wait for Chrome/Chromium to get things sorted out.

**Comment by johanhelsing** [comment] 2015-05-20 07:45
Chromium v 43 just went stable, does this mean this issue can be resolved now?

**Comment by hackel** [comment] 2015-05-21 20:55
Ha!  I landed here because I just installed Chrome 43 and it exhibits the bug of doubling the size of *everything*.  Atom .194 still looks great, though! (Ubuntu 15.04, 128 dpi display)

**Comment by fdinardo** [comment] 2015-05-24 11:44
Hi guys,
I just update chromium at 43.0.2357.65 (64-bit). The bug in Chromium was fixed and works really fine, but in Atom (v. 0.201) I still have the double menu issue! I don't know if this should depends on my personal settings (I don't think so). 

<pre>
S.O.:      Linux 4.0.4-2-ARCH x86_64
D.E.:      GNOME Shell 3.16.2
atom:      0.201
chromium:  43.0.2357.65 (64-bit)
</pre>

**Comment by ijuma** [comment] 2015-05-24 12:51
Atom 0.201 is still based on Chrome 41. There is a PR to update it to Chrome 42 (https://github.com/atom/atom/pull/6877) and only after that will it be updated to Chrome 43.

**Comment by zcbenz** [comment] 2015-06-09 05:56
Chrome43 has fixed this.

**Closed by zcbenz** 2015-06-09 05:56 UTC
Labels: blocked, bug, linux

**Comment by wackywendell** [comment] 2015-06-09 14:29
Hurray!

**Comment by varemenos** [comment] 2015-06-09 22:27
That's Chromium 43, not Chrome. Right?
I could swear, I've read somewhere that they are taking different approaches at fixing HiDPI on Linux (Chrome was preparing a project called Aura or Aurora)

**Comment by fdinardo** [comment] 2015-07-03 11:12
![atomissue](https://cloud.githubusercontent.com/assets/7387557/8498267/04ce9eba-2185-11e5-9660-58882ec553e1.png)

With version 1.0 the problem is still there.
Any ideas?

**Comment by johanhelsing** [comment] 2015-09-09 08:06
I still have this issue with the latest `electron-prebuilt` npm package (which uses chrome 45).
![screenshot from 2015-09-09 10-02-33](https://cloud.githubusercontent.com/assets/2620557/9756391/2413e3b8-56da-11e5-8484-18b803bbe313.png)

As you can see, both tooltips and menus are double sized. I'm running electron 0.32.0 and chrome 45.

**Comment by dcbishop** [comment] 2015-09-10 23:26
I have this problem too.

The recent Chromium version update made the text in the menus actually visible, before you couldn't see the options due to the large size causing the text to go outside the visible area, making Atom basically unusable (unless you don't need the menus).

Now the menus are still huge, but the options are visible despite their size.
