### ISSUE TITLE
Black screen / crash bug

### ISSUE THREAD

**Issue by pavelzaruba** [atom/electron#4814] opened 2016-03-15 15:16 UTC
Downloading several MB through XMLHttpRequest causes black screen on Windows 32 bit.

Download and extract content of [test_case.zip](https://github.com/atom/electron/files/174110/test_case.zip).
Run the following command as Admin user from the folder where you extracted the content.

`del data&fsutil file createnew data 300000000&electron .`

It creates ~300 MB file called _data_ and then runs the electron test case which downloads the file through XMLHttpRequest object. At the end half of the window is painted with black color. Resizing the window repaints the whole window with black color.

You might need bigger file (~600 MB) for Electron 0.37.2.

* Electron version: 0.36.7, 0.37.2
* Operating system: Windows 7 32 bit

**Comment by pavelzaruba** [comment] 2016-03-21 16:12
The latest Chrome crashes with the script: [chrome_crash_script_win32.zip](https://github.com/atom/electron/files/182653/chrome_crash_script_win32.zip)
So it's likely Chrome bug.

**Comment by zcbenz** [comment] 2016-03-27 12:58
I can reproduce the same crash with Chrome on OS X, I suggest reporting this to Chromium's issues list instead, and I'm closing this since we are not able to solve it on Electron's side.

**Closed by zcbenz** 2016-03-27 12:58 UTC

**Comment by pavelzaruba** [comment] 2016-03-30 08:57
All right, the bug is [reported](https://bugs.chromium.org/p/chromium/issues/detail?id=599028).
