### ISSUE TITLE
Scrolling performance is bad with Electron

### ISSUE THREAD

**Issue by 72lions** [atom/electron#2332] opened 2015-07-24 14:52 UTC
Hi, anything that I load into Electron has a very bad scrolling performance. It's super laggy. When I try them on Safari or Chrome, scrolling is what you would expect. Smooth.

Any idea why is this happening and are there any way to improve the scrolling performance?

**Comment by YuriSolovyov** [comment] 2015-07-24 15:49
Did you tried to profile your app?

**Comment by 72lions** [comment] 2015-07-24 15:54
Yes I did. On chrome is consistent at 60fps. It's just a page with a table with 500 rows. No events no nothing. 
It's super slow on electron. 

I'm sending this message from a glorified calculator. Please excuse any syntactical errors. 




On Fri, Jul 24, 2015 at 8:50 AM -0700, "Yuri" <notifications@github.com> wrote:












Did you tried to profile your app?

**Comment by zcbenz** [comment] 2015-07-28 07:42
Can you open the `chrome://gpu` url in both Chrome and Electron and check if there is any difference?

**Comment by bengotow** [comment] 2015-08-10 22:34
Hey @72lions — we use Electron and haven't run into any inconsistencies between it and Chromium re: scrolling performance, even in lists with tons of items. I'd definitely try using the Chromium Developer Tools profiler and see if your nodejs app is doing anything else. Since the renderer process runs your NodeJS code and renders, things like scrolling and CSS animations can be severely impacted by javascript you're running.

It might also be worth adding `transform: translate3d(0,0,0);` to the CSS style of your scroll container (the div with overflow:auto/scroll). This forces that div to be GPU-composited and generally makes scrolling more smooth :-)

**Comment by bkniffler** [comment] 2015-08-16 01:03
Hey, I'm experiencing slow css animations in electron, while animations are fluid within chrome/safari. I've noticed the performance is ok when running in a small window, performance getting worse while enlarging the window.

This is electron
```
Version Information
Data exported	8/16/2015, 1:56:45 AM
Chrome version	Chrome/43.0.2357.65
Operating system	Mac OS X 10.10.4
Software rendering list version	10.7
Driver bug list version	7.27
ANGLE commit id	unknown hash
2D graphics backend	Skia
Command Line Args	--no-sandbox --allow-file-access-from-files --enable-avfoundation --enable-npapi
Driver Information
Initialization time	32
Sandboxed	false
GPU0	VENDOR = 0x10de, DEVICE= 0x0fd5
GPU1	VENDOR = 0x8086, DEVICE= 0x0166 *ACTIVE*
Optimus	true
AMD switchable	false
Driver vendor	
Driver version	10.6.31
Driver date	
Pixel shader version	1.20
Vertex shader version	1.20
Machine model name	MacBookPro
Machine model version	10.1
GL_VENDOR	Intel Inc.
GL_RENDERER	Intel HD Graphics 4000 OpenGL Engine
GL_VERSION	2.1 INTEL-10.6.31
```

This is chrome 
```
Version Information
Data exported	16.8.2015, 01:55:07
Chrome version	Chrome/44.0.2403.155
Operating system	Mac OS X 10.10.4
Software rendering list version	10.8
Driver bug list version	8.19
ANGLE commit id	fa9744b09e24
2D graphics backend	Skia
Command Line Args	Chrome.app/Contents/MacOS/Google Chrome --enable-avfoundation --flag-switches-begin --flag-switches-end
Driver Information
Initialization time	4
Sandboxed	true
GPU0	VENDOR = 0x10de, DEVICE= 0x0fd5
GPU1	VENDOR = 0x8086, DEVICE= 0x0166 *ACTIVE*
Optimus	true
AMD switchable	false
Driver vendor	
Driver version	10.6.31
Driver date	
Pixel shader version	1.20
Vertex shader version	1.20
Max. MSAA samples	8
Machine model name	MacBookPro
Machine model version	10.1
GL_VENDOR	Intel Inc.
GL_RENDERER	Intel HD Graphics 4000 OpenGL Engine
GL_VERSION	2.1 INTEL-10.6.31
```

**Comment by bengotow** [comment] 2015-08-16 02:27
// edit: I just tried v0.25.1 instead of the latest 0.30.4, and it's as snappy as chrome.

Wow that's really interesting—I noticed that rendering performance suffered when you made Electron windows larger, but I figured the same thing happened in Chrome.

Is it possible that Electron is double buffering the window or introducing additional compositing to enable window transparency? Trying to think of other things that were introduced between 0.25.1 and 0.30.4.

@bkniffler do you have a small Electron app that could be used as a test case? I'd be happy to try it in more releases from 0.25 => 0.30 and see if I can narrow it down. @zcbenz anything else that would be helpful to you?

**Comment by bengotow** [comment] 2015-08-16 02:46
Did a bit more digging. Is the window you're creating frameless or transparent? Both of those cause Electron to `setOpaque: NO` on the window, and it seems that causes Mac OS X to do a lot more compositing in the redraw cycle. There are some folks talking about setOpaque / refresh rate during resize in normal Cocoa NSWindows here: http://www.cocoabuilder.com/archive/cocoa/323446-extremely-low-fps-during-transparent-nswindow-resize.html

**Comment by bkniffler** [comment] 2015-08-16 10:28
No, its neiter frameless nor transparent, here is the relevant options:
```javascript


mainWindow = new BrowserWindow({
      width: 1280,
      height: 720,
      'min-width': 800,
      'min-height': 600,
      frame: true
   });
```

Here is a small app that would not work smoothly on 0.30.4: https://www.dropbox.com/s/4migszm7rq3gvps/electron2.zip?dl=0

For some reason, the animations are not played on 0.25.1, need to check why, but you could compare it to running in the browser.

**Comment by frankhale** [comment] 2015-08-16 14:43
@bkniffler, I just ran your small app located here, https://www.dropbox.com/s/4migszm7rq3gvps/electron2.zip?dl=0

This app runs smoothly in Chrome and in Electron 0.30.4 on my machine. At least with my eyes running in both platforms looks exactly the same on my Windows 8.1 machine. The scrolling of the background is very smooth.

**Comment by bengotow** [comment] 2015-08-18 01:45
It looks like this commit to brightray is causing the performance regression: https://github.com/atom/brightray/commit/1c79219c5c8e8636208f1aaf2c937d11acba34ea. I've been doing some testing with Quartz Debug, and that change makes Mac OS X think the entire contents of the Electron window need to be composited as a "non-opaque region". @bkniffler your sample app runs smoothly for me as well, but it might be that I have a more powerful GPU so the compositing workload isn't noticeable. (On a Macbook Pro - Late 2013) On my machine, Quartz Debug shows ~48fps before that change and ~40fps afterward.

This change happened between 0.30.0 and 0.30.1. Try out 0.30.0 and see if it works better for you.

It seems that this same code was added to Chromium briefly and then rolled back out because it also caused performance regressions there. Going to see if there's a better way to achieve the rounded corners. https://code.google.com/p/chromium/issues/detail?id=396264

**Comment by bkniffler** [comment] 2015-08-18 12:30
I just ran 0.30.0 vs 0.30.1 on my Macbook Pro Retina 2012 with Intel + Nvidia 650m (switching with gfxCardStatus). 

With 0.30.0 and Nvidia its ~60 Frames.
With 0.30.0 and Intel its ~40 Frames.
With 0.30.1 and Nvidia its ~60 Frames.
With 0.30.0 and Intel its ~22 Frames.

**Comment by daiyam** [comment] 2015-08-21 17:22
I've the same issue on my old mini.
With 0.30.4, scrolling is sluggish.
With 0.30.0, it's smooth.

**Comment by zcbenz** [comment] 2015-08-25 05:48
> It looks like this commit to brightray is causing the performance regression: atom/brightray@1c79219.

@bengotow Excellent investigation, I believe that's the reason of this. In the original issue the Chromium guys said linking with 10.9 SDK should have this fixed, I will have a try.

**Comment by kevinsawicki** [comment] 2015-08-25 23:28
> In the original issue the Chromium guys said linking with 10.9 SDK should have this fixed, I will have a try.

Atom is close to merging the upgrade to `0.30.5`, do you think we should wait?

Would a fix for this be back ported to the `0.30.x` stream?

**Closed** 2015-08-26 08:36 UTC
Labels: bug, mac

**Comment by zcbenz** [comment] 2015-08-26 08:40
v0.30.6 has been published with the fix.

**Comment by kevinsawicki** [comment] 2015-08-26 13:46
:green_heart: :ship:

**Comment by v3ss0n** [comment] 2015-08-31 10:54
So we are going to have Electron in Atom soon?!

**Comment by thomasjo** [comment] 2015-08-31 11:38
> So we are going to have Electron in Atom soon?!

Yes. Just subscribe to https://github.com/atom/atom/pull/7877 to monitor progress, etc.

**Comment by Salar-codeing** [comment] 2022-03-26 20:00
> ```js
> frame: true
> ```

This actually works
