### ISSUE TITLE
session.cookies.remove not working in 0.36.1

### ISSUE THREAD

**Issue by lin-chao** [atom/electron#3896] opened 2015-12-22 12:25 UTC
i find my program can not clear cookies ,if i used 0.36.1 both mac and win.

then i do a test.

code is here:
```
"use strict"
const app = require('electron').app
const BrowserWindow = require('electron').BrowserWindow

app.on('window-all-closed', () => {
  app.quit()
})

app.on('ready', () => {

  let mainWindow = new BrowserWindow({
    "width": 800,
    "height": 800,
    "center": true
  })

  let mainWindowContents = mainWindow.webContents

  let session = mainWindowContents.session

  mainWindowContents.loadURL("https://www.google.com.hk")

  mainWindowContents.on('did-stop-loading', () => {

    // get all cookies and remove them
    session.cookies.get({}, (error, cookies) => {
      let len = cookies.length
      console.log(len)
      cookies.forEach((cookie) => {
        let name = cookie.name
        session.cookies.remove({
          name: name
        }, function(error) {
          console.log(name)
        })
      })
    })

  })

})

```

in 0.36.1,it not working, and catch a error:
```
TypeError: Error processing argument -1.
    at TypeError (native)
    at /Users/linchao/Documents/code/electron-test/main.js:31:23
    at Array.forEach (native)
    at Function.<anonymous> (/Users/linchao/Documents/code/electron-test/main.js:28:13)
```

but the test code working fine before 0.36.1,will console cookies num and display all removed cookies names.

thanks.

**Comment by zcbenz** [comment] 2015-12-23 03:03
This is a duplicate of #3860.

**Closed by zcbenz** 2015-12-23 03:03 UTC
