### ISSUE TITLE
用bootstrap框架开发出的页面，在浏览器上下拉，翻页等都能实现，在electron不能实现

### ISSUE THREAD

**Issue by kcsm-lqk** [atom/electron#4949] opened 2016-03-30 06:16 UTC
Operating system:XP W7-32
用bootstrap框架开发出的页面，在浏览器上下拉，翻页等都能实现，用electron不能,这是为什么，请教

**Comment by kevinsawicki** [comment] 2016-03-30 23:42
I put this into Google Translate and it reported this back:

```
Operating system: XP W7-32
With bootstrap framework developed page on the browser drop-down, flip, etc. can be achieved with electron can not, which is why, ask
```

It looks like you are having trouble with bootstrap? Can you include some reproduction steps or more details about the issue you are seeing?

Thanks!

**Comment by kcsm-lqk** [comment] 2016-03-31 04:21
@kevinsawicki 
thanks for your help,I'm a Chinese student and I'm not good at 
English,I hope I can express my problem.

It looks like jquery.js and bootstrap.js do not work.I use the following method to solve the problem.

Html Code
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    
    <link href="css/bootstrap.min.css" rel="stylesheet">

	<script>
	//Rename Electron require 重命名require
	window.nodeRequire = require;
	delete window.require;
	delete window.exports;
	delete window.module;
	</script>
  </head>
  <body>
  
  	
    <script type="text/javascript" src="js/jquery-2.2.2.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
  </body>

When I want to use electron or nodejs library,For example I  want to use nodejs library 'fs' ，my js code is: var fs = nodeRequire('fs')

By this way  I can use  nodejs library, jquery.js normally.Is this method feasible?

**Comment by mbilker** [comment] 2016-03-31 15:13
If you use a `preload` script when setting up a [BrowserWindow](http://electron.atom.io/docs/v0.37.3/api/browser-window/#class-browserwindow) and set `nodeIntegration` to `false` you can expose certain node functions you want your scripts to have access to.

An example can be found [here](http://electron.atom.io/docs/v0.37.3/api/process/#event-loaded).

**Comment by kevinsawicki** [comment] 2016-03-31 15:30
@mbilker thanks for the help.

Closing as duplicate of #254

**Closed by kevinsawicki** 2016-03-31 15:30 UTC
Labels: more-information-needed

**Comment by Bingyy** [comment] 2016-04-11 14:30
I have encountered this issue as well by the way.
The solution is simple, write the code inside <head> tag :

    <script type="text/javascript">
      var $ = jQuery = require('./js/jquery-1.12.3.min.js');
    </script>
It works!
