### ISSUE TITLE
Electron 0.31.1 crashing

### ISSUE THREAD

**Issue by tommoor** [atom/electron#2681] opened 2015-09-01 23:59 UTC
This has begun happening regularly, it seems as though it is since the latest release (move to 31) however I guess something that's changed in our code over the last week could have begun to trigger it too.

Hopefully you can parse something from the crash reports - I have lots of these if you would like more :smile: 

https://gist.github.com/tommoor/68b6a726b444323379b1
https://gist.github.com/tommoor/1e37324a3e61cbd004e0

**Comment by zcbenz** [comment] 2015-09-02 00:42
Can you see if there are `.dmp` files generated under `/tmp/YourApp Crashes`? You probably need to start crash-reporter to generate those files.

**Comment by tommoor** [comment] 2015-09-02 00:45
I do have a single .dmp file but it's from yesterday so it seems as though it probably isn't related to these. I've been running the crash-reporter. I can upload if you'd be able to tell if it was relevant?

**Comment by zcbenz** [comment] 2015-09-02 02:03
If there is only one file then it might not be relevant. From the crash report when crash happens when executing JavaScript in V8, and the `SIGILL` exception also indicates it is caused by bad CPU instruction, I'm wondering whether it is a V8 bug.

Anyway Chrome 45 has entered the stable channel, I would like to update Electron to Chrome 45 first and then see if it still exists.

**Comment by zcbenz** [comment] 2015-09-09 04:37
@tommoor Can you try if it crashes on v0.32.0? If it still crashes you can start the crash reporter with no parameters, and it'll send the crash report to our server.

**Comment by tommoor** [comment] 2015-09-09 20:38
Will give her a try.

**Comment by zcbenz** [comment] 2015-09-17 13:06
Closing until more information is provided.

**Closed by zcbenz** 2015-09-17 13:06 UTC
Labels: bug, crash

**Comment by jorangreef** [comment] 2015-09-22 08:39
If it helps, I updated from v0.30.4 to v0.33.0 and am now consistently getting crashes on Windows 10 when running a test simulation which does a lot of fs and ipc and network work. The same simulation was stable on v0.30.4. I am going to go back to that for now.
