### ISSUE TITLE
Rendering differences between OSX and Linux

### ISSUE THREAD

**Issue by dbkaplun** [atom/electron#3307] opened 2015-11-02 23:26 UTC
There are minor rendering differences for Electron on OSX and Linux that are causing [tests](https://travis-ci.org/dbkaplun/domscii/jobs/88532553) to fail. Certain pixel values are off by one.

See also segmentio/nightmare#326

**Comment by zcbenz** [comment] 2015-11-03 02:28
Can you provide an example? It is probably an issue of Chromium.

**Comment by zcbenz** [comment] 2015-11-16 14:30
Closing until more information is provided.

**Closed by zcbenz** 2015-11-16 14:30 UTC
Labels: more-information-needed

**Comment by tongbin** [comment] 2020-05-14 14:25
<img width="1142" alt="Screen Shot 2020-05-14 at 10 19 48 PM" src="https://user-images.githubusercontent.com/8870302/81945829-2665ef80-9631-11ea-9231-523e8d1ea448.png">

The toper one is rendered by centos, the bottom one is rendered by macos. the screen shot is taken by cypress snapshot. With cypress version 4.4.1.

However I'm not sure it's caused by screen resolution. And how could I set it. I'll do more investigation.
