### ISSUE TITLE
Chinese font not working

### ISSUE THREAD

**Issue by RCyril** [atom/electron#1987] opened 2015-06-16 14:39 UTC
Hi,

Chinese font not working in my app and all symbols are replaced by squares...
An Idea ? 

Thanks
Cyril

**Comment by zcbenz** [comment] 2015-06-17 03:38
This is a duplicate of #1605.

Currently you have to choose a font in your CSS to work around it.

**Closed by zcbenz** 2015-06-17 03:38 UTC

**Comment by tworry** [comment] 2016-03-09 14:03
I've download NotoSansSC.otf,and put it in my app,but the Chinese font still not working while English characters is Noto Sans.how can I make it work?have 2 be woff?

**Comment by skelly2015** [comment] 2019-02-21 08:13
I encountered with this same issue. Is this issue fixed in Electron or do we have to always use the workaround? I tried to use monospace font-family but it didn't work for me.

**Comment by mankeheaven** [comment] 2019-06-25 06:44
4 years later, it's still not be resolved.
chinese font can not be rendered properly as rendered with browser.
