### ISSUE TITLE
BrowserWindow - `min_width` and `min_height` aren't respected in El Capitan

### ISSUE THREAD

**Issue by DoWhileGeek** [atom/electron#3319] opened 2015-11-03 18:23 UTC
I'm not sure about previous versions of electron or electron in other versions of OSX, but neither of these properties actually limit resizing below what they are set to.

**Comment by zcbenz** [comment] 2015-11-04 09:10
Can you try whether v0.34.1 works?

**Comment by zcbenz** [comment] 2015-11-05 05:39
I'm unable to reproduce on 10.11.1.

**Comment by Swinkid** [comment] 2015-11-12 16:09
Can confirm issue. Running latest Max OSX & electron-prebuilt.

Unable to install 0.34.1 due to el capitan changing privileges and therefore unable to install. Have tried running in sudo.

Another issue is possibly unable to disable resizing on frameless window, however I'm unable to test this on another OS at the moment.

**Comment by zcbenz** [comment] 2015-11-13 03:23
@Swinkid Regarding "latest", which version of OS X and electron did you mean?

**Comment by Swinkid** [comment] 2015-11-13 09:31
@zcbenz 10.11.1 El captian :)

**Comment by zcbenz** [comment] 2015-11-13 12:55
@Swinkid Can you provide a simple example?

**Comment by Swinkid** [comment] 2015-11-13 13:17
@zcbenz 

>app.on('ready', function() {
> // Create the browser window.
> mainWindow = new BrowserWindow({
>     frame: false,
>     resizable: false,
>     width: 800,
>     height: 600,
>     minWidth: 800,
>     maxWidth: 800,
>     maxHeight: 600,
>     minHeight: 600
> });
>
> // and load the index.html of the app.
> mainWindow.loadUrl('http://localhost:3000/');
>
>  mainWindow.on('closed', function() {
>    mainWindow = null;
>  });
>
>});

Im still able to resize the frame, regardles (max/min widths are there because i tried to see if i had to set them etc..)

**Comment by zcbenz** [comment] 2015-11-13 13:18
@Swinkid You have to use `min-width` instead of `minWidth` for now, the latter form is currently only on master branch.

**Comment by zcbenz** [comment] 2015-11-16 14:30
Closing until more information is provided.

**Closed by zcbenz** 2015-11-16 14:30 UTC
Labels: more-information-needed
