### ISSUE TITLE
BrowserWindow.getFocusedWindow() always returns undefined, even after focus event

### ISSUE THREAD

**Issue by radiovisual** [atom/electron#4942] opened 2016-03-29 21:56 UTC
* Electron version: electron-prebuilt@0.36.12
* Operating system: MAC OS X Yosemite 10.10.5

I have this sample setup:

```js
const BrowserWindow = electron.BrowserWindow;
// ... rest of electron boilerplate

function createMainWindow() {
	const win = new electron.BrowserWindow({
		width: 600,
		height: 400
	});

	win.on('blur', blurHandler);
	win.on('focus', blurHandler);

	win.loadURL(`file://${__dirname}/index.html`);
	win.on('closed', onClosed);

	return win;
}

function blurHandler() {
	let focusedWindow = BrowserWindow.getFocusedWindow();
	if (focusedWindow) {
		console.log('There is a focused window!');
	} else {
		console.log('no focused window. :(');
	}
}
```
The above code simply calls `blurHandler()` on the `blur` and `focus` events.

**The expected behavior:** is to get the console output of "`There is a focused window!`" when I click back (to get focus) on the only Electron window, and to get the output of "`no focused window. :(`" when I click on any other application windows, or otherwise trigger the `blur` event on the electron window.

**The actual behavior:**  No matter the method of gaining focus on the electron window I can never get the `BrowserWindow.getFocusedWindow()` method to return anything except `undefined`. My log just looks like this:

<pre>
no focused window. :(
no focused window. :(
no focused window. :(
no focused window. :(
no focused window. :(
no focused window. :(
</pre>

Can anyone see what I am doing wrong here, or have I found a bug?

**Comment by zcbenz** [comment] 2016-03-31 13:37
This is a duplicate of #984, the workaround is to wrap your call in `setImmediate`.

**Closed by zcbenz** 2016-03-31 13:37 UTC
