### ISSUE TITLE
App: setUserTasks: can't give more than one argument

### ISSUE THREAD

**Issue by adam-lynch** [atom/electron#4407] opened 2016-02-07 18:34 UTC
The task shows fine:

```javascript
app.setUserTasks([{
  title: 'Hello world',
  description: 'This is shown in a tooltip',
  arguments: '--hello-world',
  program: process.execPath,
  iconPath: process.execPath,
  iconIndex: 0
}]);
```

Doesn't show:

```javascript
app.setUserTasks([{
  title: 'Hello world',
  description: 'This is shown in a tooltip',
  arguments: '--hello-world --another',
  program: process.execPath,
  iconPath: process.execPath,
  iconIndex: 0
}]);
```

Windows 8.1. Electron 0.36.7.

**Comment by zcbenz** [comment] 2016-02-15 08:51
I'm not able to reproduce, can you try calling `app.setAppUserModelId` to set an application user model ID before calling `app.setUserTasks`?

**Comment by zcbenz** [comment] 2016-02-21 14:04
Closing until more information is provided.

**Closed by zcbenz** 2016-02-21 14:04 UTC
Labels: more-information-needed
