### ISSUE TITLE
'AppleSystemUIFont' and 'font: caption' not behaving as expected

### ISSUE THREAD

**Issue by bmathews** [atom/electron#3305] opened 2015-11-02 16:38 UTC
I've noticed this in a couple apps powered by electron. The 'system' font isn't being correctly determined. You can see it on this text input. 

![image](https://cloud.githubusercontent.com/assets/848347/10887578/a36f32c0-813c-11e5-96d3-12fc5507e827.png)

CSS `font: caption` doesn't work like it does on Chrome, either. https://css-tricks.com/font-caption/

I'm on El Capitan.

**Comment by zcbenz** [comment] 2015-11-03 02:03
I can also reproduce on 10.10, we probably need an upgrade of Chrome in Electron to fix this, it seems to be fixed in recent Chrome versions: https://code.google.com/p/chromium/issues/detail?id=521034.

**Comment by chanpory** [comment] 2015-12-04 22:13
I can reproduce this issue as well on El Capitan. Is there away to change the user-agent stylesheet, so that the Google oAuth dialog does not appear with incorrect fonts? From a user's perspective, this makes the dialog appear fake and untrustworthy.

**Comment by zcbenz** [comment] 2016-01-07 08:45
Unable to reproduce in 0.36.2 anymore, Chrome 47 seems to have fixed the problem.

**Closed by zcbenz** 2016-01-07 08:45 UTC
Labels: blocked, bug, osx
