### ISSUE TITLE
Pages in webview lacking any script tags will not run preload JS until devtools are opened

### ISSUE THREAD

**Issue by techninja** [atom/electron#3164] opened 2015-10-21 03:57 UTC
...or until a script tag is added. I've found that the following is sufficient to get it started.
```javascript
<script>""</script>
```
I suspect this has to do with a Chromium "no-JavaScript-efficiency" thing that is not being taken into account with the preload. Found on 0.34.0

I found this while battling a strange yet currently unticketable issue where if you open devtools for a webview on the `did-start-loading` event, jQuery does not have access to the `document` object (or something) and dies during require, wwhich does **not** happen if devtools is opened _after) `did-finish-load`.

**Comment by techninja** [comment] 2015-10-21 04:25
Apparently this is a something very close to, or a dupe of #1117

The page, HTML, and CSS load and render fine for me, but no scripts run. I'll be using a script placeholder in the mean time.

**Comment by zcbenz** [comment] 2015-10-21 05:28
Yeah it is a duplicate of #1117.

**Closed by zcbenz** 2015-10-21 05:28 UTC
