### ISSUE TITLE
Initial browser-window background color

### ISSUE THREAD

**Issue by astoilkov** [atom/electron#3474] opened 2015-11-17 15:42 UTC
We have a dark application background. However, the browser-window initially shows as white(which causes flickering) and we want to make it custom color so it matches our application background(which will  prevent the flickering).

**Comment by etiktin** [comment] 2015-11-17 23:11
This is a duplicate of electron/#861.

To minimize the effect you can start your app hidden (pass show=false to the BrowserWindow ctor) and show it once the dom-ready event is fired.
You probably also want to set background color for resize, so use the background-color key in BrowserWindow ctor (see the BrowserWindow doc for more information).

**Closed** 2015-11-18 09:29 UTC

**Comment by astoilkov** [comment] 2015-11-18 12:14
Thanks!

**Comment by Ph0enixKM** [comment] 2018-02-04 09:33
`window.setBackgroundColor(color)`

Where "color" is a hexadecimal string and "window" is your window

Happy Coding!
