### ISSUE TITLE
WebView tag doesn't fire beforeunload on host refresh

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#1929] opened 2015-06-10 21:46 UTC
To repro:

1. Put a WebView in a BrowserWindow
1. In the WebVIew's context, set a beforeunload handler: `window.addEventListener('beforeunload', () => /* something */)`
1. Call `thatBrowserWindow.reload()`

Your WebView's beforeunload won't be called. Even if you remove the WebView from the DOM in the *renderer's* `window` on its way out, it won't be called.

**Comment by zcbenz** [comment] 2015-06-12 06:01
I can add support for `beforeunload` in webview, but it won't have any difference with `unload`, since you can not prevent destroying a webview.

**Comment by paulcbetts** [comment] 2015-06-12 07:00
@zcbenz That's fine, I just want to clean up some stuff up. If `unload` does work then that's fine too

**Comment by zcbenz** [comment] 2015-07-23 03:57
As state by https://code.google.com/p/chromium/issues/detail?id=396643:

> We made an explicit decision to NOT support the beforeunload/unload events in <webview>. It should be possible for a Chrome App to be killed at any point in time and so beforeunload cannot fire reliably. We should not have developers assuming this will work, when it only works some of the time. It seems the event DOES fire some of the time.

not emitting `beforeunload` should be the expected behavior, so I'm closing this.

**Closed by zcbenz** 2015-07-23 03:57 UTC
Labels: bug, webview

**Comment by JLarky** [comment] 2017-11-03 03:24
On similar note I noticed that there're not much of clean up happening inside webview, for example websockets are not getting closed
