### ISSUE TITLE
Global Key shortcuts not passing down the line

### ISSUE THREAD

**Issue by RealOrangeOne** [atom/electron#3348] opened 2015-11-05 20:57 UTC
I'm trying to create an application that registers events on key presses. The registering works fine, and the events are triggered properly, but the keypress isnt passed forwards onto the OS for any other program to process. 
Yes I'm using single character ('x' etc.), and obviously there are security implications of this (no I'm not writing anything malicious), but it would still be nice to be able to bind to keys and them still pass to other programs on the OS.
Any help would be great, sorta forgot to check this was possible before I started developing the rest of it :+1:

**Comment by zcbenz** [comment] 2015-11-06 03:04
This is a duplicate of #1338.

You probably want to write a native module to solve this yourself, I'm afraid no one is interested in working on this for now.

**Closed by zcbenz** 2015-11-06 03:04 UTC
