### ISSUE TITLE
No ARM build of Electron ==> No Visual Studio Code for ARM Linux

### ISSUE THREAD

**Issue by ststeiger** [atom/electron#2052] opened 2015-06-25 06:46 UTC
There is no ARM build of Electron.
This prevents Visual Studio Code from being compiled for ARM Linux.

https://code.visualstudio.com/Issues/Detail/17414

**Comment by zcbenz** [comment] 2015-06-25 11:50
This is a duplicate of #366.

**Closed by zcbenz** 2015-06-25 11:50 UTC
