### ISSUE TITLE
Session.on('will-download') event not firing

### ISSUE THREAD

**Issue by stevenmwade** [atom/electron#2957] opened 2015-10-01 22:23 UTC
Main:

    var session = mainWindow.webContents.session;
    session.on('will-download', function(event, item, webContents) {
             // event.preventDefault();
       item.on('updated', function() {
           console.log('Received bytes: ' + item.getReceivedBytes());
       });
       console.log('play more Queen');
       item.on('done', function(e, state) {
           if (state == "completed") {
              console.log("Download successfully");
           } else {
              console.log("Download is cancelled or interrupted that can't be resumed");
          }
        });
    });

Render:

    dialog.showSaveDialog({ title: 'Output Downloader', defaultPath: '/' + testName },
                    function (id) {
                        var fileStream = fs.createWriteStream(id, {defaultEncoding: 'binary'});
                        fileStream.on('open', function(fd) {
                            $http.get('http://yoursite.com/download/' + testName)
                                .success(function(data, status, headers, config){
                                    fileStream.write(data);
                                    fileStream.end();
                                })
                                .error(function(data, status, headers, config){
                                    console.log('product download failed');
                                });
                        });
                    });

The files are being downloaded, but the `will-download` event is not firing for us to get the progress.

**Comment by hokein** [comment] 2015-10-02 02:29
I think the behavior is expected. Can you try it on Chromium to see whether the download save dialog will prompt? The `will-download` event in Electron is aligned with Chomium's download feature, usually if Chromium prompts the download save dialog, then `will-download` event in Electron will be emitted respectively.

For the usage of `will-download`, a [spec code](https://github.com/atom/electron/blob/master/spec/api-session-spec.coffee#L92-L123) is a good reference.

**Comment by stevenmwade** [comment] 2015-10-02 02:32
@hokein The save dialog prompts and works as intended, but `will-download` still does not fire.

**Comment by stevenmwade** [comment] 2015-10-02 19:05
Chromium save dialog prompts and `will-download` does not fire. So, not sure why this is closed. Is the save being programmed in a way that does not hit that event?

**Comment by JCummings01** [comment] 2015-10-02 19:38
@hokein I don't think you understand @stevenmwade question because your answer doesn't seem like a solution.

**Comment by hokein** [comment] 2015-10-03 03:06
Oops... Reopen now.

**Comment by zcbenz** [comment] 2015-10-03 05:47
It depends on what is `$http` in the code, if it is a node module or `jQuery` then current behavior is expected. Please provide a full demo app that can reproduce this.

**Comment by JCummings01** [comment] 2015-10-05 16:50
@zcbenz How would you suggest making a Get request without a node module(request, etc) or jQuery, within Electron?

**Comment by stevenmwade** [comment] 2015-10-05 19:17
@zcbenz @hokein Ok, I'm sorry, but you two seem to be saying two different things. If opening up the save dialog window will cause the `will-download` event, why does the call inside of it make a difference? 

Maybe I'm just not clear on how you expect this to run and what way you want it to be programmed to actually have that functionality available and if the request happens inside `will-download` I fail to see how `downloadItem` can have it's properties.

**Comment by MichaelOstermann** [comment] 2015-10-05 21:38
I believe the issue here is that you are using the save dialog to pick a path, but you are actually "downloading" and saving the file *yourself* via a custom http request that has nothing to do with Electron itself.

There are several ways to let Electron download files so that you get your events, one example would be having a link `<a href="url" download></a>` and if there is no user-action involved, you can programmatically trigger a click, or depending on the `content-disposition` header of the response, you can just plain open the file in your BrowserWindow via `window.location.replace(url)`.

Note though that `setDownloadPath` is currently broken #2987.

**Comment by zcbenz** [comment] 2015-10-06 12:52
@MichaelOstermann should have explained it clearly, so I'm closing this.

**Closed by zcbenz** 2015-10-06 12:52 UTC
Labels: more-information-needed

**Comment by stevenmwade** [comment] 2015-10-06 13:45
@MichaelOstermann That clears up the statement that it should fire when the open save dialog window opens, but doesn't that mean that you have no control to have a save dialog to allow the user to choose it's path? We've tried something similar and it just downloads with no indication that it has started (that might just be because it was before the update) or the ability to choose a path, which we need both. Also, how does this work if we need to hit a server to get signed URLs? Does this mean we can have no access to the save dialog since it not a direct link to the download or because it does trigger a download(eventually) that we will have access to that event?

**Comment by MichaelOstermann** [comment] 2015-10-06 14:04
The methods I described above will open the dialog automatically, as for the urls, what's the difference between `$http.get('http://yoursite.com/download/' + testName)` and say `window.location = 'http://yoursite.com/download/' + testName`?

Electron will open the file dialog as necessary - if you open it manually, you make yourself responsible for manually downloading and manually handling anything else such as, progress, download indicators, etc. as well. In your code you have `.success` and `.error` promised handlers anyway!

If your file dialog does not automatically open, you might want to open a separate issue - it should open whenever your BrowserWindow is about to download a file.

**Comment by stevenmwade** [comment] 2015-10-06 14:08
@MichaelOstermann So even though we send it to our server to get signed URLs before it downloads, it should still directly download it using Electron? If so, that will make that easy (hopefully we don't get those other issues again).

There wouldn't be much different and the `.success` is really not that useful for us anyway because we need updates.

**Comment by MichaelOstermann** [comment] 2015-10-06 14:14
I don't know exactly what you are planning to do, I can only say that I have an Electron App where I have a bunch of `<a href="..." download>` elements on which users can click, as well as dynamic links that get opened via `window.location = ...;`, which does open the file dialog for me in both cases. Upon selecting a path, it will save to that location!

Regarding the http request updates, in that case you might want to pick a different library that can handle this feature, but you should try to get this to work via Electron :)

**Comment by stevenmwade** [comment] 2015-10-06 14:18
@MichaelOstermann We definitely will. Our problem is that we need to generate a signed URL to have more secure downloads (we are downloading software) that happens when you click download, and then it fires the download. So I'm guessing the best way to do that is just to use window.location after we get that URL.

**Comment by JCummings01** [comment] 2015-10-07 17:16
@MichaelOstermann Thank you for your help

**Comment by ousamox** [comment] 2019-11-25 11:10
You can use `session` from `electron` package like this :

```
const { ......., session } = require('electron');

session.defaultSession.on('will-download', function(event, downloadItem, webContents){
    let totalByte = downloadItem.getTotalBytes();
    let totalMByte = parseFloat((totalByte / 1000000).toFixed(2));
    ....
    downloadItem.on('updated', function (event, state) {
          let receviedBytes = event.sender.getReceivedBytes();
          // state have values : interrupted or progressing
    });
});
```

Its worked for me
