### ISSUE TITLE
Unable to start electron

### ISSUE THREAD

**Issue by vladzzag** [atom/electron#2803] opened 2015-09-16 14:17 UTC
Hello, everyone!
I'm using ```electron-prebuilt@0.32.3``` and Node.js v0.12.7. When I execute ```electron``` there is an error:
```
$ electron 
[13276:0916/171055:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
module.js:338
    throw err;
    ^

Error: Cannot find module '/home/vlad/.nvm/versions/node/v0.12.7/lib/node_modules/electron-prebuilt/dist/resources/atom.asar/browser/lib/init.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:125:18)
    at node.js:977:3
```

Here is content of ```/home/vlad/.nvm/versions/node/v0.12.7/lib/node_modules/electron-prebuilt/dist/```:
```
content_shell.pak  icudtl.dat       libnode.so      LICENSE           snapshot_blob.bin
electron           libgcrypt.so.11  libnotify.so.4  natives_blob.bin  version
```

**Comment by vladzzag** [comment] 2015-09-16 14:45
On Windows 10 the same.

**Comment by britishd** [comment] 2015-09-16 14:50
Folders locales and resources seems to be missing...

**Comment by geovanisouza92** [comment] 2015-09-16 14:54
+1

**Comment by kjellski** [comment] 2015-09-16 14:54
I'm on Windows 8, same here Node v4 + electron 0.32.3

**Comment by vladzzag** [comment] 2015-09-16 14:57
OK.. In release archives folder "resources" exists.. So, maybe something wrong with npm package :)

**Comment by jscappini** [comment] 2015-09-16 15:00
After manually pasting both resources and locales folders inside electron-prebuild/dist folder everything seems to work fine. Weird, looks like npm isn't downloading all deps.

**Comment by kjellski** [comment] 2015-09-16 15:04
@vladzzag You shed some light, thanks!
I can confirm, as @jscappini said, it now works fine, I've just extractred the zip from github to:
    
    node_modules/electron-prebuilt/dist

It now works again :)

**Comment by geovanisouza92** [comment] 2015-09-16 15:08
Ubuntu 14.04 / Node 0.12.7 / npm 2.11.3 / electron 0.32.3

The workaround from @kjellski works fine!

**Comment by maxogden** [comment] 2015-09-16 15:34
Sorry, was due to a temporary bug in zip extraction https://github.com/mafintosh/electron-prebuilt that is fixed now

Reinstalling `electron-prebuilt` should fix the issue

**Closed by maxogden** 2015-09-16 15:34 UTC

**Comment by marsinvasion** [comment] 2015-10-22 21:38
I'm having the same problem on windows. It works fine on mac

I'm using electron packager with electron v0.34.0
