### ISSUE TITLE
window.opener changes to null after navigation

### ISSUE THREAD

**Issue by bgnq** [atom/electron#2464] opened 2015-08-10 07:02 UTC
To connect with Trello API, this is done in a popup after filling access, I have a blank page ... 
Could you help me ?

Thank you !

You try connect with this access : 
login : jerryxilimm-9589@yopmail.com
password : jerryxilimm-9589

My code test : 

Package.json : 
```json
{
  "name"    : "NQ trello",
  "version" : "0.1.0",
  "main"    : "main.js"
}
```

Main.js :  
```javascript
var app = require('app');
var BrowserWindow = require('browser-window');
require('crash-reporter').start();

var mainWindow = null;


app.on('window-all-closed', function() {
  if (process.platform != 'darwin')
    app.quit();
});


app.on('ready', function() {

  mainWindow = new BrowserWindow({
    width: 800, 
    height: 600,
    'node-integration': false
  });
  
  mainWindow.loadUrl('file://' + __dirname + '/index.html');

  mainWindow.on('closed', function() {
    mainWindow = null;
  });
});
```

Index.html : 
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, maximum-scale=1.0" />
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no, maximum-scale=1" media="(device-height: 568px)" 
	<title>Test</title>

	
	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
	<script type="text/javascript" src="https://api.trello.com/1/client.js?key=6c3067ffd2a5feda29e39e1c8df9e3a8"></script>
    <script type="text/javascript">
    	$(document).ready(function () {
    		$('#login').click(function(ev){
    			Trello.authorize({
		            type: 'popup', 
		            response_type: 'token', 
		            name: 'TEST',
		            expiration: '30days', 
		            interactive: true,
		            success: function (data){
		                alert('Connexion OK');
		            },
		            error: function () {
		                alert('Connexion KO');
		            }
		        });

    			ev.preventDefault();
    		});


    		function getMe(){
    			Trello.get('members/me', {}, function (data){
                    alert(JSON.stringify(data));
                }, function (){
                    alert('Don\'t retrieve information about me....')
                });
    		}
    	});
    </script>
</head>
<body ontouchstart="">
    <div id="app">
    	<a href="#" id="login">LOGIN</a>
    </div>
</body>
</html>
```

**Comment by fatihky** [comment] 2015-08-11 08:07
Can you change `$(document).ready(function () {` to `$(document).ready(function (event) {`?

**Comment by bgnq** [comment] 2015-08-11 08:14
the problem is not there, it's back after authentfication not working.
The same project with nw.js works but I wanted to do it with electron but it must have a blockage with the credentials of this style

Thank for your help

**Comment by iwege** [comment] 2015-08-11 16:22
That page content is:
```
<html><head><script>
if(window.opener) {
  window.opener.postMessage("a12604079bc38702c86eb79b4905fdc2640f", "file://")
}
</script></head></html>
```
But the `window.opener` is `null`, so you can't get anything from mainWindow.

You can add this code to `main.js` to open the window devtools
```
app.on('browser-window-focus',function(event,win){
  if(!win.isDevToolsOpened()){
    win.openDevTools();
  }
})
```

**Comment by bgnq** [comment] 2015-08-11 16:34
OK, thank for this trick.
As a result, I don't use trello auth with electron ?

Thank

**Comment by iwege** [comment] 2015-08-11 16:40
Maybe you can't use the trello/client.js directly. You can hack it for your case.

**Comment by bgnq** [comment] 2015-08-11 16:54
Change client.js, it's not possible, window.opener.postMessage don't is in this script.
Or get the webcontent and parse it with yourself => it's complicated for this simple problem.
in conclusion, it's not possible with electron... :(

Thank for your responses.

**Comment by zcbenz** [comment] 2015-08-24 05:04
The `window.opener` changes to `null` after page navigation, so the popup window can no longer tell the parent window of the result, it is a bug of Electron.

**Comment by zcbenz** [comment] 2015-08-31 13:05
Turns out this is an duplicate of #1959. Our implementation of window.opener relies on node integration, and since the login button sends a POST request, the new page no longer has node integration and thus `window.opener` becomes `null`.

**Closed by zcbenz** 2015-08-31 13:05 UTC
Labels: bug
