### ISSUE TITLE
Create a Method to Bundle Electron Apps with the Electron Executable

### ISSUE THREAD

**Issue by medemi68** [atom/electron#3624] opened 2015-11-29 23:50 UTC
Hello Everyone!

I was wondering if it would be possible to implement a method so that users who develop Electron-based apps could bundle their applications with the electron executable as to help obscure their source code further.

As it currently stands, it's rather simple for someone to obtain the source code of your application regardless of whether or not you bundle it into an .asar file. 

Although not entirely secure, as it currently stands NW.JS has a method for bundling their .nw files (which is basically a ZIP File renamed) with their executable. I can't quite remember exactly how it was done (because it's been a while since I've used electron or nw.js), but I explain it briefly in this other Github post for Electron-packager.

https://github.com/maxogden/electron-packager/issues/152

Here is the command line tool for bundling .nw files into an executable with Node-Webkit

    copy /B nw.exe+app.nw app.exe

The only issue with this is that even if electron adopted this kind of method it would still not be entirely secure. There are still ways that you could get the source code. 

The only way I see this working is if someone built a tool to create a custom version of electron that had a sort of encryption key in it that would decrypt the .asar file and run it's contents that way. Because other than that I see no other way of doing this..

Any suggestions?

If I've missed something, please let me know. I'm just getting back into electron after a long while of doing other things.

Thanks

**Comment by etiktin** [comment] 2015-11-30 00:31
There's a discussion about source code protection at https://github.com/atom/electron/issues/3041

**Comment by zcbenz** [comment] 2015-11-30 07:38
Closing as a duplicate of #3041, which is closed since we won't work on it, but we will accept pull requests that implement reasonable solution for source protection.

**Closed by zcbenz** 2015-11-30 07:38 UTC

**Comment by Omar25py** [comment] 2023-04-19 06:31
you can protect code with enigma virtual box, this have an API you can use to code inside to increase security, and i test this ...i tried to read renderer.js and virtual box dont show file
