### ISSUE TITLE
Onload trello login lost $

### ISSUE THREAD

**Issue by nqteam** [atom/electron#1515] opened 2015-04-28 16:53 UTC
Hello,

With this url : https://trello.com/login on load to electron, I have got this error : 

[15405:0428/185059:INFO:CONSOLE(2)] "Uncaught ReferenceError: $ is not defined", source: https://trello.com/login (2)

would you have any idea?

thank
Baptiste

code : 

var app = require('app');
var BrowserWindow = require('browser-window');
require('crash-reporter').start();

var mainWindow = null;

app.on('window-all-closed', function() {
  if (process.platform != 'darwin')
    app.quit();
});

app.on('ready', function() {

  mainWindow = new BrowserWindow({width: 800, height: 600});
  mainWindow.loadUrl('https://trello.com/login');

  mainWindow.on('closed', function() {
    mainWindow = null;
  });
});

**Comment by steelbrain** [comment] 2015-04-28 17:27
Related https://github.com/atom/electron/issues/254

**Comment by paulcbetts** [comment] 2015-04-28 17:29
Dupe of #254, host Trello in a `webview` tag that has `node-integration: false` set

**Closed by paulcbetts** 2015-04-28 17:29 UTC

**Comment by nqteam** [comment] 2015-04-29 06:34
Thanks, with my code sample, our fix works ! :)
But in my real app, the popup https://trello.com/login opened with API trello (https://trello.com/docs/gettingstarted/clientjs.html), also the popup opens alone and not with "new BrowserWindow"
How to define "node-integration": false with the popup automatic opened with JavaScript ?

Thanks

**Comment by zcbenz** [comment] 2015-04-30 09:00
> How to define "node-integration": false with the popup automatic opened with JavaScript ?

Currently there is no way to do that, you should probably have to hack the code to not using `window.open`.
