### ISSUE TITLE
[0.33.x Mac OS X] Child process crashes after a while with signal SIGABRT

### ISSUE THREAD

**Issue by bpasero** [atom/electron#2999] opened 2015-10-05 17:43 UTC
I am now using Electron 0.33.6 for some hours in VS Code and run into an issue that I cannot really reproduce or explain but it happens always after some time of usage (30 minutes). It might be just memory related when memory consumption reaches a certain limit.

What I know is that a process (forked with child_process) is crashing with a SIGABRT signal, which seems to indicate an issue deep down in node or at least in a C++ layer above with memory allocation. We do have a crash dump when this happens: https://gist.github.com/bpasero/bbe9001163baca220057

I will try to reproduce this on Windows tomorrow.

I wonder if this is related or duplicate to: https://github.com/atom/electron/issues/2889

**Comment by zcbenz** [comment] 2015-10-06 13:07
Yeah it is a duplicate of #2889, I need to back port a patch from V8 to fix it.

**Closed by zcbenz** 2015-10-06 13:07 UTC

**Comment by bpasero** [comment] 2015-10-07 05:46
@zcbenz allright, good to know its something in reach :)
