### ISSUE TITLE
Blurry rendering on High-DPI after Chrome 45 upgrade

### ISSUE THREAD

**Issue by CharlieHess** [atom/electron#3349] opened 2015-11-05 21:39 UTC
We're seeing text / image blurriness on high-DPI displays, after the Chrome 45 upgrade (Windows only).

Slack 1.2.2 (Electron 0.30.5) on the left
Slack 1.2.5 (Electron 0.34.1) on the right
![slack-dpi-bug](https://cloud.githubusercontent.com/assets/1865957/10982279/399227ea-83c1-11e5-80ea-000a19b9d761.png)

Any idea what would cause this?

**Comment by zcbenz** [comment] 2015-11-06 03:01
Did you turn off `direct-write`?

**Comment by paulcbetts** [comment] 2015-11-06 04:27
@zcbenz We're seeing this on Windows 10, where we hard-code `direct-write: true`, though I'll double-check

**Comment by zcbenz** [comment] 2015-11-06 08:57
It is hard to say what has happened, you can do following comparisons to have a better idea:

* Open the Slack website in Electron window and see if it has the same problem.
* Export the page in Slack app to local HTML file, then open it in Chrome browser and check whether it is a bug of Chrome.
* Open the exported page in default app to check whether it is caused by the settings of BrowserWindow.

**Comment by zcbenz** [comment] 2015-11-16 14:31
Closing until more information is provided.

**Comment by paulcbetts** [comment] 2015-11-16 17:27
Atom is seeing a raft of new font issues reported in the last week or two:

https://github.com/atom/atom/issues/9596
https://github.com/atom/atom/issues/9454
https://github.com/atom/atom/issues/9226
https://github.com/atom/atom/issues/9161

**Comment by as-cii** [comment] 2015-11-16 22:50
Looking at those issues it would seem like this is not related just to a specific platform: given that the Slack team is observing similar issues too, I'd agree that this could be related to a Chromium :bug:.

So, based on @paulcbetts's investigation, there are a couple of things we should probably do to fix this:

1. Make sure we're running the latest Squirrel version. It seems like AppCompat was messing with DPI stuff and this has been fixed in the last versions (https://github.com/Squirrel/Squirrel.Windows/pull/478)
2. Upgrade Electron's Chromium Version. It seems like the Chromium team is aware of this problem and they've been discussing it [over here](https://code.google.com/p/chromium/issues/detail?id=484400): unfortunately, a fix hasn't landed yet, so I _think_ the only two options here would be to:
  * Wait for a fix to land on the next Chrome versions;
  * Or, if that's not going to happen anytime soon, patch libchromiumcontent ourselves;

As far as I can tell, they're already working on a fix (https://code.google.com/p/chromium/issues/detail?id=485650) and the plan is to :shipit: in time for Chrome 49.

@zcbenz: I am going to reopen this issue, but I'd like to hear your thoughts about it :thought_balloon:. From the changelogs it's not clear if some sort of fix has been shipped on Chrome 48, but it's probably worth having a :eyes: at it.

**Comment by as-cii** [comment] 2015-11-16 23:05
Also, since this seems to affect a pretty big portion of Atom's user base, do you think downgrading to the previous version of Electron in Atom could be an option? It would be a sort of a bummer but we're not really sure about how long it's going to take to fix that problem in the Chromium codebase.

Thoughts?

/cc: @nathansobo @benogle

**Comment by etiktin** [comment] 2015-11-17 00:24
The fix mentioned in https://code.google.com/p/chromium/issues/detail?id=484400 looks pretty simple. Can any one confirm that rounding the scale factor solves the visual issues (can be tested by passing --force-device-scale-factor with the new factor)?

**Comment by zcbenz** [comment] 2015-11-17 01:48
I'll apply the patch in Chromium of blacklisting device-scaling-factor < 1.3 and see whether it fixes the problem.

**Comment by albuic** [comment] 2015-11-17 02:19
@etiktin 
I confirm that --force-device-scale-factor=1 worked for me (Debian with i3wm). Hope you will find a fix for everybody ! ;-)

**Comment by zcbenz** [comment] 2015-11-17 08:17
@paulcbetts @as-cii Most reports I saw were on Linux, the fix for crbug.com/484400 is only available on Linux and I will apply the patch in Electron, but I'm still unsure on how to fix it on Windows.

**Comment by zcbenz** [comment] 2015-11-24 14:29
v0.34.4 has been published with the fix for Linux, v0.35.1 included the fix too. However I'm not sure whether it really fixed the problem since I can not find a machine to test it, please report back if it is still there.

/cc @as-cii

**Comment by as-cii** [comment] 2015-11-24 15:06
Thanks, @zcbenz. I'll make sure to open a PR on Atom that upgrades Electron to the latest version, so that we can test if this fix solves the issue on Linux once for all. After having a second :eyes: on the Windows reports for blurry text on Atom, I feel like it _could_ be related to another issue (subpixel font scaling + tiling), although at this point I am not sure what's triggering this behavior on the Slack app.

**Comment by soren121** [comment] 2015-11-24 18:20
I built [microsoft/vscode](https://github.com/microsoft/vscode) on Linux with Electron 0.34.4 and the blurry text is indeed fixed! Thanks.

**Comment by zcbenz** [comment] 2016-01-07 08:43
So on Linux high DPI already works fine, which fixed most of the feedbacks on high DPI problem. For Windows I don't know whether Chrome 47 has fixed the problem, but I'm assuming it has.

**Closed by zcbenz** 2016-01-07 08:43 UTC
Labels: bug, linux, windows

**Comment by mattconsto** [comment] 2016-02-22 16:06
At least for me, Chrome 47/48 hasn't fixed the issue. Only the code is blurry, which I fixed with --force-device-scale-factor=1, which has the unfortunate side effect of making the menu bar and file tree smaller than it should be. I've noticed this issue with a few websites in Chrome such as Google Drive so I've switched to using Firefox for editing stuff there.

I'm running Windows 8.1 64bit on a 1920x1080 screen at whatever Larger scaling is (I 'think' it may be 1.5 but honestly I'm not sure). Before writing this I downloaded the Atom installer and reinstalled it, to no avail.

**Comment by paulcbetts** [comment] 2016-02-22 18:34
@mattconsto fwiw, switching your DPI to either 1.0 (i.e. 100%) or 2.0 (200%) will work around your issue (and also generally makes other apps look better too)

**Comment by mattconsto** [comment] 2016-02-23 09:25
@paulcbetts I have a 14" laptop, so doing so makes everything look really tiny, and I can't set my DPI to 200% without Windows 10. I prefer a few applications to look blurry or small than everything look small, which is why --force-device-scale-factor=1 is a better work around for me. I have come to except that for some applications I'll need to disable device scaling.

**Comment by felixrieseberg** [comment] 2016-08-10 15:52
It's worth pointing out that Chromium M53 will [enable "use zoom for dsf" by default](https://codereview.chromium.org/2173243002/patch/1/10001), meaning that this change should eventually trickle down to Electron and fix a lot of the blurriness discussed here.
