### ISSUE TITLE
New api electron

### ISSUE THREAD

**Issue by saiberz** [atom/electron#3760] opened 2015-12-10 14:35 UTC
Why do i get this error
```App threw an error when running [TypeError: Cannot read property 'start' of undefined]```

trying to run:  ``` npm start```
```js
const electron = require('electron');
const app = electron.app;  // Module to control application life.
const BrowserWindow = electron.BrowserWindow;  // Module to create native browser window.
app.on('ready', function() {
  // Create the browser window.
  mainWindow = new BrowserWindow({width: 800, height: 600});

  // and load the index.html of the app.
  mainWindow.loadURL('file://' + __dirname + '/index.html');

})
```

but if use 
```js
const electron = require('electron');
const app = require('app');
const BrowserWindow = require('browser-window')
```
it works nice

Tested in:
OSX El Capitan
node: v4.0.0 ^ npm: 2.14.2 ^     "electron-prebuilt": "^0.35.4"
node: v5.1.1 ^ npm: 3.3.12 ^     "electron-prebuilt": "^0.35.4"

**Comment by zcbenz** [comment] 2015-12-10 15:32
Duplicate of #3708.

**Closed by zcbenz** 2015-12-10 15:32 UTC
