### ISSUE TITLE
Suddenly developer windows stopped working

### ISSUE THREAD

**Issue by ruifortes** [atom/electron#2251] opened 2015-07-16 18:05 UTC
Hello.
Suddenly developer windows stopped working. Not even in the default_app

It only appear in the taskbar as a blank window and doesn't even open the real window.

This may be related to a windows bug that manifested that also appeared suddenly.

My Windows 7 suddenly stopped expanding %APPDATA% in the environment variables.
I couldn't fix windows bug (even installed a hotfix)
see:  https://support.microsoft.com/en-us/kb/2913826

Could this be related to the broken developer tools window?
Can someone help? Is there any quick workaround in order to be able to debug until this is fixed?

Thanks

**Comment by zcbenz** [comment] 2015-07-16 22:23
Electron needs to access `%APPDATA%` for reading/writing some settings, but it could be caused by other issues though since your Windows seems to be heavily broken.

I'm closing this since we won't try to make Electron work on a broken Windows, I think your best choice is to reinstall Windows.

**Closed by zcbenz** 2015-07-16 22:23 UTC

**Comment by ruifortes** [comment] 2015-07-17 09:40
oh,the pain.....the pain!!!
