### ISSUE TITLE
crash when Ctrl+W on <textarea>  or <input>, with default electron menu on

### ISSUE THREAD

**Issue by frantic1048** [atom/electron#2841] opened 2015-09-20 14:30 UTC
When I leave the electron window with default electron menu (not using any `setMenu()`),

pressing `Ctrl+W` on `<textarea>` and `<input>` causes electron crash.

I found this when creating keybindings for my app.

**Kernel:** Linux 4.1.6-1-ARCH
**OS:** Arch Linux (2015-09-19)
**Electron version:** v0.33.0
**Electron package:** electron-prebuilt
**Xorg:** 1.17.2

**Operation:**

1. make focus on `<textarea>` or `<input>`
2. press `Ctrl+W` 

electron crashes and log as below:

```
[19748:0920/221959:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[19778:0920/221959:INFO:renderer_main.cc(200)] Renderer process started
The program 'electron' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 252 error_code 3 request_code 40 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Addition:** If I use `setMenu(null);` in the `app.js` to the window. That will not crash.

**Minimal Sample:**

index.html

```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
</head>
<body>
<input type="text">
<textarea name="name" rows="8" cols="40"></textarea>
</body>
</html>
```

app.js

```javascript
var app = require('app');  // Module to control application life.
var BrowserWindow = require('browser-window');  // Module to create native browser window.

// Report crashes to our server.
require('crash-reporter').start();

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the javascript object is GCed.
var win = null;

// Quit when all windows are closed.
app.on('window-all-closed', function() {
  if (process.platform != 'darwin')
    app.quit();
});

// This method will be called when atom-shell has done everything
// initialization and ready for creating browser windows.
app.on('ready', function() {
  // Create the browser window.
  win = new BrowserWindow({
      title: 'ctrl+w on textarea crash test'
  });

  // disable default elctron menu.
  // win.setMenu(null);

  // and load the index.html of the app.
  win.loadUrl('file://' + __dirname + '/index.html');

  // Emitted when the window is closed.
  win.on('closed', function() {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    win = null;
  });
});
```

package.json

```json
{
  "name": "crash-test",
  "version": "0.0.0",
  "main": "app.js",
  "dependencies": {
    "electron-prebuilt": "^0.32.3"
  }
}
```

**Comment by zcbenz** [comment] 2015-09-21 04:23
I can confirm this, we probably need to do some more shutdown work when closing window on Linux.

**Comment by zcbenz** [comment] 2015-10-04 08:47
Fixed with https://github.com/atom/brightray/pull/149.

**Closed by zcbenz** 2015-10-04 08:47 UTC
Labels: bug, crash, linux

**Comment by Elycin** [comment] 2017-01-08 08:18
Perhaps I can explain here although i'm new to the electron framework myself, but may know what's happening here.

Electron is built on top of the chromium browser framework, and natively in chromium pressing CTRL + W will intentionally close the browser window.

Perhaps there's a way to block it that I am unaware of but,  It's not a bug but rather a native feature. You can try the same thing in google chrome and get the same results.

Regards,
Andrew
