### ISSUE TITLE
Unhandled Exceptions: setImmediate is not defined in _tls_wrap.js

### ISSUE THREAD

**Issue by alregner** [atom/electron#3761] opened 2015-12-10 15:17 UTC
I am using Electron 0.35.0 32 bit on Windows 10 and I am getting the following error when after and SSL request is made using the https node module.

![setimmediate2](https://cloud.githubusercontent.com/assets/14017241/11718956/ca2b45e0-9f58-11e5-9f6e-465d79338f29.png)
  

![setimmediate1](https://cloud.githubusercontent.com/assets/14017241/11718974/dfdda6bc-9f58-11e5-8d91-aee177dae031.png)

Looks like it is related to #2866 and #2916 and solution would be similar: NativeModule.require('timers').setImmediate(destroySSL, this);

**Comment by zcbenz** [comment] 2015-12-11 02:51
This is a duplicate of #2984 and I'm closing this as won't fix. You can find a workaround in #2984, and it is also documented in http://electron.atom.io/docs/v0.35.0/api/process/#event-39-loaded-39.

**Closed by zcbenz** 2015-12-11 02:51 UTC
