### ISSUE TITLE
Clicking notification on Windows doesn't focus the app even with window.focus in click handler

### ISSUE THREAD

**Issue by jwheare** [atom/electron#4766] opened 2016-03-12 10:42 UTC
* Electron version: v0.36.9
* Operating system: Windows 10

Unlike on OS X, clicking a web notification triggered on Windows 10 doesn't focus the app, even with a `window.focus()` in the click handler. The click handler is called, but the focus call does nothing.

**Comment by zcbenz** [comment] 2016-03-13 12:14
This is a duplicate of #2867.

**Closed by zcbenz** 2016-03-13 12:14 UTC
