### ISSUE TITLE
instanceof bug on Windows

### ISSUE THREAD

**Issue by jameslk** [atom/electron#1586] opened 2015-05-06 02:35 UTC
I've come across a strange bug on 64-bit Windows where `instanceof` does not behave correctly in the browser frame when using it against an object whose prototype inherits from a function defined in a different module under `node_modules`.

### Example
For example, let's say there are two functions `B` and `D` and these files:
```
test.js
```
```
d.js (contains the D function)
```
```
node_modules/b_module/b.js (contains the B function)
```

If `D`'s prototype points to an instance of `B` and both `B` and `D` are `require`d into `test.js`, then on Windows, if test.js uses instaneof to check whether D inherits from B, it will return `false`.

### Code samples
I've gone ahead and created a sample project with the code here to see the bug in action:
https://github.com/jameslk/electron-instanceof-bug

Here's some screenshots showing the discrepency:

### Running NodeJS:
![screen shot 2015-05-05 at 8 05 20 pm](https://cloud.githubusercontent.com/assets/774411/7486563/44b92418-f364-11e4-8526-fcd1974a792a.png)

### Running ElectronJS on Windows (from the browser frame dev tools):
![screen-shot-2015-05-05-at-8 06 59-pm-2](https://cloud.githubusercontent.com/assets/774411/7486696/31499992-f366-11e4-9d0a-9c2e406a8386.png)

### Running ElectronJS on Mac
This bug only appears to happen under Windows. I tried it on Mac and got the expected results.
![screen shot 2015-05-05 at 8 27 34 pm](https://cloud.githubusercontent.com/assets/774411/7486634/3e47840c-f365-11e4-9359-20ba432bf2f9.png)

I have not tested Linux yet.

**Comment by fitriawulan** [comment] 2015-05-06 03:29
False

**Comment by paulcbetts** [comment] 2015-05-06 03:29
What does io.js 64-bit report?

**Comment by jameslk** [comment] 2015-05-06 17:25
I downloaded io.js 1.6.3 (the same version that electron is using) and couldn't replicate the issue on Windows:

```bash
$ iojs test.js
true 'should be true because c has A in its prototype chain'
true 'should be true because d has B in its prototype chain'
```

**Comment by jameslk** [comment] 2015-05-06 17:32
For now, I'm going to have to use something like [Browserify](http://browserify.org/) to circumvent this issue since using the native `require` is breaking some of the dependencies in my project that rely upon `instanceof`.

**Comment by zcbenz** [comment] 2015-05-08 03:04
This is a duplicate of #1289.

**Closed by zcbenz** 2015-05-08 03:04 UTC

**Comment by jameslk** [comment] 2015-05-08 04:09
@zcbenz Thanks for clarifying the issue.

It seems like the best solution for loading browser dependencies is to use
```html
<script>require(...dependency...);</script>
```
in loaded HTML files in the future, instead of
```html
<script src="...dependency..."></script>
```
as is traditionally done. This avoids the issue with the case-sensitive path duplications.
