### ISSUE TITLE
ipc-message event.isTrusted appears twice

### ISSUE THREAD

**Issue by OlsonDev** [atom/electron#3776] opened 2015-12-11 10:10 UTC
Note `isTrusted` is in this object twice:
![image](https://cloud.githubusercontent.com/assets/308072/11741141/99603a2e-9fbc-11e5-8e0f-829d3fd09afa.png)

```javascript
webview.addEventListener('ipc-message', function(e) {
    console.log(e);
});
```

Electron v0.36.0, Windows 10

**Comment by zcbenz** [comment] 2015-12-14 03:10
This is a bug of Chrome 47, you can reproduce by creating an `Event` object.

<img width="589" alt="screen shot 2015-12-14 at 11 04 59 am" src="https://cloud.githubusercontent.com/assets/639601/11772003/b32318f8-a252-11e5-857f-8aac3fefe6b2.png">

I'm closing this since it is not a big deal, and we are not able to fix it on Electron's side. If you are interested, you can report it to Chromium's issues list.

**Closed by zcbenz** 2015-12-14 03:10 UTC

**Comment by OlsonDev** [comment] 2015-12-14 11:34
Apologies for not realizing it was a Chromium issue. I found [this issue](https://code.google.com/p/chromium/issues/detail?id=556726) reported on the Chromium tracker. Thanks!
