### ISSUE TITLE
Request: it would be nice to have Electron for Raspberry Pi or any other arm device?

### ISSUE THREAD

**Issue by leualemax** [atom/electron#1702] opened 2015-05-15 19:54 UTC
so I'm developing a solution for needy schools here in Brazil, and it would be cool to make the currently online app available for Raspberry Pi offline (low price solution for needy schools thats does even have chairs), electron running it would be a great help.

**Comment by leualemax** [comment] 2015-05-15 19:54
ps. Sorry guys for my poor brazilian`s public education english!  =)

**Comment by C4Grey** [comment] 2015-05-17 20:09
As far as I know, there are no ARM-compatible versions of io.js, but there are [NodeJS for ARM](http://elinux.org/Node.js_on_RPi). So if your app not consumes some platfom API-features, you can try to make a client-server web application and migrate to NodeJS. Of course, you will be forced to change a lot of things(for example, a way of working with the JS contexts). On the other hand, you can consider an option to use a mini PC based on Intel Atom CPU, something like [MinnowBoard](http://www.technodisti.com/online-store/boards/minnowboard-max-single-core-detail.html). It will be more expensive than RPi, but it will allow you to keep your Electron-based application.

**Comment by paulcbetts** [comment] 2015-05-17 20:19
I'm not sure that either @zcbenz or I have the hardware to make this happen - you need a machine with a _lot_ of RAM (3+ GB) to link libchromiumcontent, so we either need to figure out how to cross-compile to ARM, or find an ARM machine with a ton of memory

**Comment by baconface** [comment] 2015-05-17 21:15
I don't follow io.js closely but I believe it has ARM support.

Currently on ARM releases for my web apps I use this [NW.js ARM Build](https://github.com/nwjs/nw.js/issues/1151#issuecomment-78030735). Unsure of the stack they specifically used but this is NW.js version 0.12.0 which is an io.js build.

According to [this article](https://github.com/nodejs/evangelism/blob/master/weekly-updates/weekly-update.2015-02-27.md#arm-offers-support-for-iojs-on-armv8) and [this article](https://medium.com/node-js-javascript/io-js-week-of-april-17th-e4c6f2db7659) io.js on ARM is not only possible but officially supported.

**Comment by GeorgS** [comment] 2015-05-18 13:57
+1

**Comment by mgcrea** [comment] 2015-05-18 22:15
:+1:

**Comment by thedaniel** [comment] 2015-05-19 00:30
Thanks for the request! This is a duplicate of #366, so I am going to close this one. Adding an ARM target (necessary to run on the Pi) is probably a reasonably large amount of work, and the core team doesn't have plans to do it right now. As always though, we'd love to accept / review PRs from the community if anyone out there wants to make it happen.

**Closed by thedaniel** 2015-05-19 00:30 UTC

**Comment by paulcbetts** [comment] 2015-05-19 00:34
> As always though, we'd love to accept / review PRs from the community if anyone out there wants to make it happen.

If you've got the hardware or the patience to set up the cross-compile env, I think it might not actually be that bad. If someone wants to give this a go, get into the Atom Slack room and I'll give them some advice

**Comment by v3ss0n** [comment] 2015-07-09 08:59
Now we have electron builds for ARM . Has anyone tried that on android? need X11 right?

**Comment by timofonic** [comment] 2015-11-14 14:25
Any news? There's (https://crosswalk-project.org/)[Crosstalk Project], that supports other systems. What about merging efforts with Adobe? :)

This would make [Atom for Touch Devices](https://crosswalk-project.org/) possible!

**Comment by TigerC10** [comment] 2016-04-05 21:33
https://www.hackster.io/craig-mulligan/electron-on-raspberry-pi-c8bce1

**Comment by imrehg** [comment] 2017-03-21 11:56
@leualemax check out this tutorial + starter project:  [ElectronJS with Raspberry Pi Made Easy As Pie](https://resin.io/blog/electronjs-the-ultimate-guide/)

**Comment by ekinakyurek** [comment] 2017-06-02 22:21
Is there an electron build for armv6 devices(raspberry pi zero w)?

**Comment by LoganArnett** [comment] 2017-06-29 18:52
@ekinakyurek Were you able to track down an answer to your question? I am also interested in trying to run electron on a pi zero

**Comment by steffenmllr** [comment] 2017-09-16 21:31
Any news on this @ekinakyurek @LoganArnett ? trying to get electron running on a zero with no success so far.

**Comment by doej1367** [comment] 2018-10-11 21:10
> 
> 
> I'm not sure that either @zcbenz or I have the hardware to make this happen - you need a machine with a _lot_ of RAM (3+ GB) to link libchromiumcontent, so we either need to figure out how to cross-compile to ARM, or find an ARM machine with a ton of memory

What about emulators? Are there some that would do the job? (jeah, i've no idea about this compileing stuff yet, but it's an idea that i wanted to mention here)

I found this issue trying to get nbrowser running on a raspberry pi zero which I need for node-red and that [nbrowser](https://flows.nodered.org/node/node-red-contrib-nbrowser) needs electron. But the raspberry pi zero still has an armv6.

Fun fact: it all began with the wish to automate to monitor the price of a laptop on that website: https://www.notebooksbilliger.de/hp+15+da0104ng.
