### ISSUE TITLE
Electron is leaking Xorg connections over time and on every desktop notification causing Xorg to stop accept clients

### ISSUE THREAD

**Issue by bundyo** [atom/electron#2922] opened 2015-09-28 11:38 UTC
Last week I installed the Slack app for Linux and after a while my desktop stopped opening new windows. Trying from console Xorg complained that it reached its max number of clients, which I think by default is 255 (could be changed in Xorg code only):

    Maximum number of clients reached
    Can't open display.

After some digging turned out that Xorg indeed reached its max number of clients. Since the xrestop didn't report anything suspicious (beside the number of clients) I started killing apps to check which one was causing the issue. Turned it was the Slack app, which freed about 200 connections. Looks like its leaking Xorg connections over time. I suspect the opening and closing the app through the tray icon is doing this, but it was rather inconsistent. However every desktop notification did leak one Xorg connection on every call.

You can monitor the Xorg connections through:

    lsof -p [Xorg PID] | grep /tmp/.X11-unix/X0 | wc -l

xrestop reports the new connections as unknown, for instance:

    79 - <unknown> ( PID:  ?   ):
      res_base      : ox400000
      res_mask      : ox1fffff
      windows       : 0
      GCs           : 0
      fonts         : 0
      pixmaps       : 0
      pictures      : 0
      glyphsets     : 0
      colormaps     : 0
      passive grabs : 0
      cursors       : 0
      unknowns      : 0
      pixmap bytes  : 0
      other bytes   : ~0
      total bytes   : ~0

Closing the app frees them, but not before that.

**Comment by patrys** [comment] 2015-09-28 17:12
Can confirm on Fedora 23. Running Slack alone results in Xorg eventually running out of client connections. Running Atom alone never resulted in the problem though which makes me think that either Atom leaks much slower, Atom does not hit the particular usage pattern that leads to a bug or the problem is specific to Slack and is not necessarily related to Electron.

**Comment by zcbenz** [comment] 2015-09-30 05:34
After some testing I think it is not a bug of Notification, but from something else.

To verify that you can create a notification in Slack by sending slackbot a `/remind me in 2s to notify`, and then print the number of connections to Xorg with `sudo lsof | grep /tmp/.X11-unix/X0 | wc -l`. And you can find that the number doesn't change when the notification shows and disapears.

**Comment by bundyo** [comment] 2015-09-30 09:03
I've added Some Web Notifications to an empty app and they doesn't seem to spawn new connections. Must be something else. I see that Slack app also modifies the icon on notification, I'll try that too.

**Comment by raelgc** [comment] 2015-10-01 11:19
@bundyo As a workaround, I can suggest you to use the open souce Slack client: https://github.com/raelgc/scudcloud

**Comment by bundyo** [comment] 2015-10-01 11:53
Well, I didn't open the bug for that :) Still have to test the icons, but more pressing matters here due to a release.

**Comment by bundyo** [comment] 2015-10-05 08:13
Okay, after being unable to reproduce this, I've took a glimpse in Slack's code and it seems they create their own transparent notification windows and are not using Web Notifications.

**Comment by zcbenz** [comment] 2015-10-05 11:50
Cool, I'm closing this until we can get a way to reproduce this in Electron.

**Closed by zcbenz** 2015-10-05 11:50 UTC
Labels: more-information-needed

**Comment by bundyo** [comment] 2015-10-09 09:06
Looks like Slack fixed the issue in the latest 1.2.4 version - a new notification doesn't spawn a ghost Xorg connection anymore. There are almost no changes in the notification scripts and the wrapper object, but they did upgrade to 0.33.6, so I guess the issue was in Electron, but fixed since 0.30.5.

So that's a wrap. :)

**Comment by paulcbetts** [comment] 2015-10-09 17:00
@bundyo It was also a bug in our code, https://github.com/paulcbetts/node-system-idle-time/compare/7909062001452523f85680d7035cd35282188605...1.0.4

**Comment by gmmeyer** [comment] 2015-10-11 06:17
:+1: Thank you all very much!
