### ISSUE TITLE
Resizable false option does not work on Linux

### ISSUE THREAD

**Issue by tommoor** [atom/electron#1853] opened 2015-06-03 16:39 UTC
Create a browser window with the `resizable: false` attribute in options - on OSX this acts as expected and is not able to be resized, on Linux you can still resize.

**Comment by hokein** [comment] 2015-06-04 05:01
Can be reproduced on Ubuntu 12.04.  Having test v0.27, and v0.22, the `resizable` option makes no effects.

**Comment by brrd** [comment] 2015-06-05 18:40
This is a duplicate of #953

**Comment by zcbenz** [comment] 2015-06-08 04:56
@brrd Thanks!

**Closed by zcbenz** 2015-06-08 04:56 UTC
Labels: bug, linux
