### ISSUE TITLE
'dom-ready' and 'did-finish-load' events were fired twice for the unreachable url in the webview.

### ISSUE THREAD

**Issue by ssreekanth** [atom/electron#2666] opened 2015-08-31 16:57 UTC
With the following code, i noticed that 'dom-ready' and 'did-finish-load' events were fired twice.

**main.js**
```javascript
app.on('ready', function() {
    mainWindow = new BrowserWindow({
        width: 480,
        height: 640,
        resizable: false
    }); 
    mainWindow.loadUrl('file://' + __dirname + '/main.html');

    mainWindow.on('closed', function() {
        mainWindow = null;
    }); 

    ipc.on('child:open', function(event) {
        console.log('main.js :: ipc msg child:open received');
        openChildWindow();
    }); 

    openChildWindow = function() {
        if (!!childWindow) {
            console.log('main.js :: child window already open, sending msg to it');
            childWindow.webContents.send('url', "http://www.yahoo.com");
        } else {
            console.log('main.js :: create a new child window');
            childWindow = new BrowserWindow({
                width: 1080,
                height: 640,
            }); 
            childWindow.loadUrl('file://' + __dirname + '/child.html');

            childWindow.webContents.on('dom-ready', function() {
                console.log('main.js :: new child window loaded. sending url to the child window.');
                childWindow.webContents.send('url', "http://domain.tld");
                childWindow.show();
            }); 

            childWindow.on('closed', function() {
                console.log('main.js :: child window closed');
                childWindow = null;
            }); 
        }
    };
});
```

**main.html**
```javascript
<html>  
<head>  
</head> 
<body>
    main window
    <button onclick="openChild()"> open child </button>
    <script>
        var ipc = require('ipc');
        function openChild() {
            console.log('open child button clicked. sending child:open ipc msg to main process');
            ipc.sendSync('child:open');
        }
    </script>
</body>     
</html>
```

**child.html**
```javascript
<html>
<head>
</head>
<body>
    child window
    <webview src="about:blank" id="content" autosize="on"></webview>
    <script>
        var ipc = require('ipc');
        var webview = document.getElementById('content');
        
        ipc.on('url', function(url) {
            console.log('child :: url received: ' + url);
            webview.src = url;
        });
        
        webview.addEventListener('did-fail-load', function(e) {
            console.log('child :: failed to load - ' + webview.src);
            console.log('e : ' + JSON.stringify(e));
        });

        webview.addEventListener('did-finish-load', function() {
            console.log('child :: finished loading - ' + webview.src);
        });

        webview.addEventListener('dom-ready', function() {
            console.log('child :: dom-ready fired - ' + webview.src);
        });

        webview.addEventListener('did-get-response-details', function() {
            console.log('child :: got response - ' + webview.src);
        });
    </script>
</body>
</html>
```

**Console log output**
```
[80101:0830/180437:INFO:CONSOLE(11)] "open child button clicked. sending child:open ipc msg to main process", source: file:///Users/sreekanth/Downloads/_personal_work/sandbox/sample-electron-connect/main.html (11)
main.js :: ipc msg child:open received
main.js :: create a new child window
main.js :: new child window loaded. sending url to the child window.
[80101:0830/180437:INFO:CONSOLE(15)] "child :: url received: http://domain.tld", source: file:///Users/sreekanth/Downloads/_personal_work/sandbox/sample-electron-connect/child.html (15)
[80101:0830/180438:INFO:CONSOLE(29)] "child :: dom-ready fired - http://domain.tld/", source: file:///Users/sreekanth/Downloads/_personal_work/sandbox/sample-electron-connect/child.html (29)
[80101:0830/180438:INFO:CONSOLE(25)] "child :: finished loading - http://domain.tld/", source: file:///Users/sreekanth/Downloads/_personal_work/sandbox/sample-electron-connect/child.html (25)
[80101:0830/180438:INFO:CONSOLE(20)] "child :: failed to load - http://domain.tld/", source: file:///Users/sreekanth/Downloads/_personal_work/sandbox/sample-electron-connect/child.html (20)
[80101:0830/180438:INFO:CONSOLE(21)] "e : {"errorCode":-105,"errorDescription":""}", source: file:///Users/sreekanth/Downloads/_personal_work/sandbox/sample-electron-connect/child.html (21)
[80101:0830/180438:INFO:CONSOLE(29)] "child :: dom-ready fired - http://domain.tld/", source: file:///Users/sreekanth/Downloads/_personal_work/sandbox/sample-electron-connect/child.html (29)
[80101:0830/180438:INFO:CONSOLE(25)] "child :: finished loading - http://domain.tld/", source: file:///Users/sreekanth/Downloads/_personal_work/sandbox/sample-electron-connect/child.html (25)
```

The last 2 lines of the console logs indicate that the dom-ready and did-finish-load events got fired twice, for the unreachable url.. Is this the expected behavior? Or is it a bug?

**Comment by zcbenz** [comment] 2015-09-01 02:19
Related: #2646.

**Comment by deepak1556** [comment] 2015-09-07 21:36
Which version of Electron are you seeing this ? with the latest i get the expected output.

```
❯ ../shell/out/D/electron ./dialog-app
[14669:0907/215331:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[14690:0907/215331:INFO:renderer_main.cc(200)] Renderer process started
[14669:0907/215333:INFO:CONSOLE(10)] "open child button clicked. sending child:open ipc msg to main process", source: file:///home/robo/github/hello-atom/dialog-app/b.html (10)
main.js :: ipc msg child:open received
main.js :: create a new child window
[14704:0907/215333:INFO:renderer_main.cc(200)] Renderer process started
main.js :: new child window loaded. sending url to the child window.
[14669:0907/215333:INFO:CONSOLE(12)] "child :: url received: http://domain.tld", source: file:///home/robo/github/hello-atom/dialog-app/child.html (12)
[14716:0907/215333:INFO:renderer_main.cc(200)] Renderer process started
[14723:0907/215333:INFO:renderer_main.cc(200)] Renderer process started
[14669:0907/215333:INFO:CONSOLE(26)] "child :: dom-ready fired - about:blank", source: file:///home/robo/github/hello-atom/dialog-app/child.html (26)
[14669:0907/215333:INFO:CONSOLE(22)] "child :: finished loading - about:blank", source: file:///home/robo/github/hello-atom/dialog-app/child.html (22)
[14669:0907/215334:INFO:CONSOLE(17)] "child :: failed to load - about:blank", source: file:///home/robo/github/hello-atom/dialog-app/child.html (17)
[14669:0907/215334:INFO:CONSOLE(18)] "e : {"errorCode":-105,"errorDescription":""}", source: file:///home/robo/github/hello-atom/dialog-app/child.html (18)
[14669:0907/215334:INFO:CONSOLE(26)] "child :: dom-ready fired - http://domain.tld/", source: file:///home/robo/github/hello-atom/dialog-app/child.html (26)
[14669:0907/215334:INFO:CONSOLE(22)] "child :: finished loading - http://domain.tld/", source: file:///home/robo/github/hello-atom/dialog-app/child.html (22)

```

the finish-load and dom-ready event are fired for the unreachable url because it loads default network error [page](https://code.google.com/p/chromium/codesearch#chromium/src/content/public/common/url_constants.cc&q=chromewebdata&sq=package:chromium&l=55), if you check `window.location.href` of the webview it will be
```
"data:text/html,chromewebdata"
```

anyways `webview.src` is highly unreliable here to test the url realted to the events, maybe `fail-load` and `finish-load` should carry corresponding url as payload @zcbenz ?

**Comment by zcbenz** [comment] 2015-09-30 06:01
In latest electron I'm not able to reproduce, seems that it gets fixed by some other commits.

**Closed by zcbenz** 2015-09-30 06:01 UTC
Labels: bug, webview

**Comment by ibc** [comment] 2020-12-18 10:38
This happens in Electron 10 everytime.

**Comment by apsgangwar** [comment] 2025-08-06 19:44
Reasons for multiple `did-finish-load` triggers:
- Initial `about:blank` load:
  - When a new BrowserWindow or webview is created, it initially loads an `about:blank` page. This initial load can trigger a `did-finish-load` event.
- Subsequent `loadURL()` call:
  - After the `about:blank` page loads, a subsequent call to `webContents.loadURL()` to load your intended content will trigger another `did-finish-load` event upon completion of that load.
