### ISSUE TITLE
[suggest] native progress bar support

### ISSUE THREAD

**Issue by jwu** [atom/electron#3564] opened 2015-11-24 03:42 UTC
I found browserWindow support progressBar but it is show on taskbar. Any chance that electron can be able to support native progress bar like this:

<img width="457" alt="screen shot 2015-11-24 at 11 35 37 am" src="https://cloud.githubusercontent.com/assets/174891/11357143/8c6a4208-929f-11e5-9bec-205d1f6d120d.png">

In my understanding, the difficult thing might be: How to update the progress when we call showProgressBar? because it might block the process in executing the next block of the code.

**Comment by zcbenz** [comment] 2015-11-24 10:47
This is a duplicate of #2470 which was closed as won't fix.

**Closed by zcbenz** 2015-11-24 10:47 UTC
