### ISSUE TITLE
Cannot find module '../protocol'

### ISSUE THREAD

**Issue by KevinMartin** [atom/electron#4619] opened 2016-02-26 23:07 UTC
* Electron version: v0.36.7, v0.36.9 (not sure about other versions)
* Operating system: Windows

On Mac, it works fine.
 
<img width="568" alt="screen shot 2016-02-26 at 5 21 00 pm" src="https://cloud.githubusercontent.com/assets/510957/13367856/b16e087e-dcb3-11e5-892d-e58653f225f6.png">

Happens while Installing and Uninstalling (packaged with `Squirrel.Windows`). Doesn't happen when you run the application directly.

**Comment by zcbenz** [comment] 2016-02-27 03:37
Does this start to happen from recently or is this your first time making a installer? I want to know whether it is a regression or you did something wrong.

**Comment by KevinMartin** [comment] 2016-02-27 15:51
First time.

The code is something like:
```js
// main.js
'use strict';

const UpdateManager = require('./update-manager.js');

if (UpdateManager.handleStartupEvent()) {
	return;
}

...
```

```js
// update-manager.js
'use strict';

const path				= require('path');
const { EventEmitter }	= require('events');
const { spawn }			= require('child_process');
const { version }		= require('./package.json');

const { app, autoUpdater, dialog } = require('electron');

const exeName	= path.basename(process.execPath);
const appFolder	= path.resolve(process.execPath, '..');
const updateExe	= path.join(appFolder, 'Update.exe');

function createShortcuts(callback) {
    ...
}

function removeShortcuts(callback) {
   ...
}

class UpdateManager extends EventEmitter {
    ...

    static handleStartupEvent() {
		if (process.platform !== 'win32') {
			return false;
		}

		switch (process.argv[1]) {
			case '--squirrel-firstrun':
				// show welcome screen;
				//return false;
				break;

			case '--squirrel-install':
				createShortcuts(app.quit);
				break;

			case '--squirrel-updated':
				createShortcuts(app.quit);
				break;

			case '--squirrel-uninstall':
				removeShortcuts(app.quit);
				break;

			case '--squirrel-obsolete':
				app.quit();
				break;

			default:
				return false;
		}

		return true;
	}

    ...
}
```

**Comment by KevinMartin** [comment] 2016-02-27 15:57
I was able to find an issue on another Electron app: itchio/itch#202 which received multiple reports of the same issue, though it was in regards to `app.makeSingleInstance()`, not the auto updater.

**Comment by zcbenz** [comment] 2016-02-28 02:39
Can you make a full example app? I think the bug is related to when you called `app.quit`, but I can not find a way to reproduce it.

**Comment by KevinMartin** [comment] 2016-02-29 02:02
Turns out I was using the wrong `appFolder` and consequently wrong `updateExe`. I was catching the error, but whenever I would use the correct path, I wouldn't get that error anymore.

**Comment by zcbenz** [comment] 2016-03-03 11:59
Closing since it is not a bug.

**Closed by zcbenz** 2016-03-03 11:59 UTC

**Comment by joshuapinter** [comment] 2019-03-28 17:08
As stated [here](https://github.com/electron-userland/electron-forge/issues/489#issuecomment-387937956), I had to change:

```js
if ( require( "electron-squirrel-startup" ) ) app.quit();
```

to:

```js
if ( require( "electron-squirrel-startup" ) ) app.exit();
```

And the issue went away.
