### ISSUE TITLE
Notification Center behaviour question on OS X & Windows 10

### ISSUE THREAD

**Issue by z-ax** [atom/electron#4907] opened 2016-03-24 18:24 UTC
Greetings! Was trying hard to find some info, but didn't, so please point if I missed.
Trying to figure out behaviour in Notification Center ("NC"), don't really understand why it works now as it is:

1. After checking the NC on Windows 10 and get out of it - all notifications are gone (cleared, `close` even for each is triggered). Why is that so? App is still running. For other apps notifications remain.
* After closing the app all notifications are cleared from the NC on both OS as well. Can they persist and open app if it's not running, with some params inside, etc?
* Is there an option to handle `close` on OS X? (f.e. to clear it inside app's Notification section as well).
* Is `tag` not supported on Windows? Able to send several notifications with the same `tag`.
* Is it possible to get list of app's notifications in NC?
* Is it possible to clear all app's notifications programmatically (without having links to them after constructing)?

* Electron version: v0.37.2
* Operating system: OS X 10.11.4, Windows 10 build 10240

P.S. I'm not a native apps developer, so may not know some stuff and hope for an answer - might help others here as well. Thank you in advance.

**Comment by ykulinichenko** [comment] 2016-03-28 10:42
having the same problem

**Comment by felixrieseberg** [comment] 2016-03-28 20:23
Hey, if you're interested in what's going inside Electron, you can find the code [over here](https://github.com/atom/brightray/tree/master/browser) (look for the notification files). The implementations are fairly simple on all three platforms, so if you can't immediately find a feature, it's probably not there - people would probably really like a PR though ;-)

On Windows, we're not using the latest and greatest Windows 10 notifications, but instead the Windows 8 notification APIs (ensuring that they run well on 8, 8.1, 10). I'm not sure if that's the reason, but that might be why they are not persistent.

**Comment by z-ax** [comment] 2016-03-29 15:49
Thank you for reply, @felixrieseberg. It cleared a part, still digging into this.

Slack's notifications are persistent (and it's built on top of Electron as far as we know), so should be a way to do that :) Also, Slack's notifications are persistent on OS X as well - after app's quit they are still in NC.

I still hope someone already has knowledge about this issue to get answers or links to read, for people who aren't into native desktop apps development and actual APIs, known issues, behaviours, etc :)

**Comment by felixrieseberg** [comment] 2016-03-29 17:36
Slack has had notifications before I added them and if I remember correctly, the ones on Windows are even totally custom.

However, if you have ideas on how to improve the C code, I'd love to take a look and see if we can put it in Electron core. I can certainly see the use case for both OS X and Windows.

**Comment by z-ax** [comment] 2016-03-29 19:21
Checking this question with the team and customer, so if it's decided to have this functionality for our app - will definitely let you know :)

**Comment by zcbenz** [comment] 2016-03-31 12:21
> After checking the NC on Windows 10 and get out of it - all notifications are gone (cleared, close even for each is triggered). Why is that so? App is still running. For other apps notifications remain.
> After closing the app all notifications are cleared from the NC on both OS as well. Can they persist and open app if it's not running, with some params inside, etc?

Duplicate of #3916.

> Is there an option to handle close on OS X? (f.e. to clear it inside app's Notification section as well).
> Is tag not supported on Windows? Able to send several notifications with the same tag.
> Is it possible to get list of app's notifications in NC?
> Is it possible to clear all app's notifications programmatically (without having links to them after constructing)?

Currently we only support HTML5 notifications, for others I'm merging them to #3359.

**Closed by zcbenz** 2016-03-31 12:21 UTC
