### ISSUE TITLE
[Unity] Notifications showing as alerts

### ISSUE THREAD

**Issue by markbaas** [atom/electron#4462] opened 2016-02-12 23:34 UTC
Perhaps this worked in previous versions of Ubuntu, at least not in 16.04. On unity electron wants to use unity specific variables, this code breaks that:
https://github.com/atom/brightray/blob/master/browser/linux/libnotify_notification.cc#L31
```
// Look for the presence of libunity as our hint that we're under Ubuntu.
  base::FileEnumerator enumerator(base::FilePath("/usr/lib"),
                                  false, base::FileEnumerator::FILES);
  base::FilePath haystack;
  while (!((haystack = enumerator.Next()).empty())) {
    if (base::StartsWith(haystack.value(), "/usr/lib/libunity-",
                         base::CompareCase::SENSITIVE)) {
      unity_result = true;
      break;
    }
  }
```
Instead it should look at running processes IMO.

**Comment by paulcbetts** [comment] 2016-02-13 03:33
Dupe of #465, subscribe there instead

**Closed by paulcbetts** 2016-02-13 03:33 UTC
