### ISSUE TITLE
ServiceWorker does not allow 'file://' origin

### ISSUE THREAD

**Issue by rogeru** [atom/electron#2831] opened 2015-09-19 00:34 UTC
I am trying to intercept image load request from my HTML to https requests. Specifically my app has a URL "images/test.png" in the HTML and electron tries to load that with a file scheme  "file:///images/test.png". I would like to rewrite this request to https://mydomain.com/images/test.png

For this I was trying to use a service worker since they allow to intercept the network requests and modify the URL.

The problem is that electron (well chromium) does not allow "file://" origin. Chromium states that Service Workers require a secure origin, such as HTTPS. 

The exact error is:
"Failed to register a ServiceWorker: The URL protocol of the current origin ('file://') is not supported."

Is there a way to get around that with electron?

A somewhat related Chromium submit is https://codereview.chromium.org/1191793003/#ps40001

**Comment by zcbenz** [comment] 2015-09-21 03:20
We can provide a `webFrame.registerURLSchemeAsAllowingServiceWorkers` API for this.

**Comment by paulcbetts** [comment] 2015-09-21 03:24
It seems as if many Chrome APIs are moving to HTTPS-only, it'd be great to have a single "registerURLSchemeAsPrivileged" method to encompass all of these features instead of having to one-off all of them

**Comment by zcbenz** [comment] 2015-09-21 03:25
> It seems as if many Chrome APIs are moving to HTTPS-only, it'd be great to have a single "registerURLSchemeAsPrivileged" method to encompass all of these features instead of having to one-off all of them

:+1:

**Comment by deepak1556** [comment] 2015-09-21 04:14
`registerURLSchemeAsPrivileged` sounds good, but should it allow `file` and like scheme or we can just allow custom schemes which are registered as standard ? Otherwise will `file` like schemes elevated as privileged lead to origin issues ?

**Comment by zcbenz** [comment] 2015-09-21 04:22
@deepak1556 A simpe wrapper around blink APIs should be enough, we don't need to make the API do too much things unless it is proven that we have to.

**Comment by rogeru** [comment] 2015-09-21 12:15
Thanks. So until we have this new API Service Workers cannot be used since only https is supported by Chrome, correct? Service a worker via https on a web server won't work either due to cross origin.

**Closed** 2015-09-22 01:59 UTC
Labels: beginner, enhancement

**Comment by PhilJ** [comment] 2015-12-20 15:36
Any updates here? 

Currently I receiving this error on the console, if I try to register a service worker from a `file`path: `error when registering sw DOMException: Failed to register a ServiceWorker: A bad HTTP response code (-1) was received when fetching the script.`

I tried to register the file protocol at every method, but still no luck so far

    electron.webFrame.registerURLSchemeAsPrivileged('file');
    electron.webFrame.registerURLSchemeAsSecure('file');
    electron.webFrame.registerURLSchemeAsBypassingCSP('file');

    app.on('ready', () => {
        electron.protocol.registerServiceWorkerSchemes(['file:']);
    });

Has anybody been able to successfully register a service worker via `file:///`?

**Comment by deepak1556** [comment] 2015-12-20 15:47
@PhilJ 'file' scheme has been registered to enable service worker by default from v0.36.0 . which version of electron are you on ? 

Have verified working with https://github.com/GoogleChrome/samples/tree/gh-pages/service-worker . Could you provide sample app in case it doesn't work for you, thanks!

**Comment by PhilJ** [comment] 2015-12-20 23:16
Thanks for your response and the test case. I'm using Electron 0.36.1, so the file protocol should be supported for service workers.

I reduced the problem to the simple registration of an service worker and it still fails on my machine, even though it is fully covered by your test case. `sw.js` exists under this path (when i copy the path from the error to a browser instance the file is loaded). However this is not relevant for the error, it does not change if I remove the worker file.

    // client/index.html
    <script>
    navigator.serviceWorker.register('sw.js', {scope: './'})
    .then(function () {
      console.log('sw registered')
    })
    .catch(function (error) {
      console.log('error when registering sw', error)
    });
    </script>

    // client/sw.js
    self.addEventListener('fetch', function (event) {
      console.log(event);
    });

    // main.js
    app.on('ready', () => {
        mainWindow = new BrowserWindow({ width: 1200, height: 1000 });
        mainWindow.loadURL(`file://${__dirname}/client/index.html`);
    });

On the console I receive an error, that the registration failed. The network monitor shows a strange error, I guess the browser must have somehow blocked the request.

![screen shot 2015-12-21 at 00 06 09](https://cloud.githubusercontent.com/assets/181198/11920736/2abb0b90-a777-11e5-8c6b-e5acb4acb77f.png)

Any idea what could be different about my environment, that causes this behaviour?

**Comment by deepak1556** [comment] 2015-12-22 21:05
@PhilJ could you try clearing sw storage data using `session.clearStorageData` and retry.

**Comment by havenchyk** [comment] 2015-12-23 13:01
@deepak1556 I also have this kind of problem with `0.36.0`. Also reported issue #3897

**Comment by havenchyk** [comment] 2015-12-23 13:39
@deepak1556 after `session.clearStorageDate` I have the same message:

> Failed to register a ServiceWorker: No URL is associated with the caller's document

**Comment by havenchyk** [comment] 2015-12-23 14:37
@PhilJ In my case the problem was in the old version of `electron-prebuilt`

**Comment by PhilJ** [comment] 2016-02-23 21:58
The problem for me was caused by `electron-compile`, which still suffers by that issue. I'm now using gulp for build an service workers work like a charm now.

**Comment by paulcbetts** [comment] 2016-02-24 19:37
> The problem for me was caused by electron-compile, which still suffers by that issue. 

Can you file a bug for this?

**Comment by VandeurenGlenn** [comment] 2016-07-24 12:33
Maybe replacing request.url could be a solution (temporary)?

`var request = new Request(urlWithCacheBusting,
              {credentials: 'same-origin'});
 request.url = urlWithCacheBusting.replace(/file:\/\/\/(.*):\//, '');`

**Comment by rahul-dutt-sharma** [comment] 2018-01-23 08:00
Hey, I am able to make a Fetch request but unable to save the response in the `Caches` API's cache I have to create an cached app read from an in memory webui.zip file

Is this even possible?

I get the error that file:// request is unsupported by the cache api
