### ISSUE TITLE
Wrong size webview content

### ISSUE THREAD

**Issue by cmplx** [atom/electron#4882] opened 2016-03-22 20:22 UTC
* Electron version: from ~0.36.6 to 0.37.2
* Operating system: win7

Content of webview element is  always 300px x 150px, but border of webview normal and corresponds width and heigth 

http://s30.postimg.org/jk6ukg6n5/elec.png

**Comment by kavikah** [comment] 2016-03-23 17:45
I am seeing the same issue. Mac build is fine, however Win 7 is giving me the same sizing issue. I have regressed to Electon pre 0.36.6 to build out my app in the time being.

**Comment by simonhochrein** [comment] 2016-03-27 14:35
I have been having this problem on the latest version
I fixed it by injecting the extra CSS into the webview shadow DOM
It was a lot closer to the right size

**Comment by christoth** [comment] 2016-03-28 15:43
Can you provide a sample Gist that will reproduce the problem?
Specifically the HTML for the page that hosts/contains the webview.
Thanks

**Comment by simonhochrein** [comment] 2016-03-28 18:47
```javascript
document.getElementById("my-webview").shadowRoot.firstChild.innerText("object{position:absolute;width:100%;height:100%;}");
```
Than it will always be full width

**Comment by christoth** [comment] 2016-03-29 00:48
@simonhochrein. That solution will not work with flexbox layouts.  I will try to find a solution for both flexbox and regular layout (that may not take up 100% of the height/width). I just need a couple-few example to test against.
Thanks.

**Comment by simonhochrein** [comment] 2016-03-29 00:56
I forgot the flexbox part of CSS
Flex:1
On Mar 28, 2016 7:49 PM, christoth <notifications@github.com> wrote:@simonhochrein. That solution will not work with flexbox layouts.  I will try to find a solution for both flexbox and regular layout (that may not take up 100% of the height/width). I just need a couple-few example to test against.
Thanks.

**Comment by cmplx** [comment] 2016-03-29 08:38
@christoth For example: I used index.html and add webview tag. [GIST](https://gist.github.com/cmplx/2a4a4f4f9143b32e1fd0)

**Comment by christoth** [comment] 2016-03-29 11:28
@cmplx Explicitly setting the display style will break the flexbox layout of the webview/browserplugin.
Is it correct to assume that you would like to explicitly size the webview to width: 640px & 480px?
Any specific reason for display:inline-block?

**Comment by cmplx** [comment] 2016-03-29 12:28
@christoth In my case , I need change size of webview. Hmm... after remove  display:inline-block;  it`s work. Is this behavior  correct ?

**Comment by christoth** [comment] 2016-03-29 14:51
Yes, it should work as long as you don't override the display style 
property of the webview.

**Comment by zcbenz** [comment] 2016-03-31 11:21
Closing since this has been answered.

**Closed by zcbenz** 2016-03-31 11:21 UTC
Labels: webview
