### ISSUE TITLE
Electron 0.26.1 is not support Chinese language

### ISSUE THREAD

**Issue by lealife** [atom/electron#1758] opened 2015-05-23 13:24 UTC
![image](https://cloud.githubusercontent.com/assets/1699428/7784248/998f40d6-0191-11e5-8fd7-979b776ecb66.png)

Ubuntu 14.04 LTS

**Comment by zcbenz** [comment] 2015-05-24 02:28
This is a duplicate of #1605.

**Closed by zcbenz** 2015-05-24 02:28 UTC
