### ISSUE TITLE
Crash when clicking notification (GNOME3)

### ISSUE THREAD

**Issue by markbaas** [atom/electron#2294] opened 2015-07-21 21:27 UTC
When receiving a notification electron crashes with:
```
(electron:8526): libnotify-CRITICAL **: notify_notification_close: assertion 'NOTIFY_IS_NOTIFICATION (notification)' failed
[8526:0721/170311:ERROR:browser_main_loop.cc(219)] GLib-GObject: invalid uninstantiatable type '(null)' in cast to 'GObject'
[8526:0721/170311:ERROR:browser_main_loop.cc(219)] GLib-GObject: g_object_get_data: assertion 'G_IS_OBJECT (object)' failed
```

I'm not sure about other environments, but it happens while using GNOME3.

**Comment by markbaas** [comment] 2015-07-22 15:23
Some more info:

It only happens when clicking the notification in GNOME3. Probably Gnome tries to give focus to the window and Electron somehow doesn't know what to respond.

**Comment by markbaas** [comment] 2015-08-13 21:00
Still occurs in 0.30.4:

(electron:24449): libnotify-CRITICAL **: notify_notification_close: assertion 'NOTIFY_IS_NOTIFICATION (notification)' failed
[24449:0813/165808:ERROR:browser_main_loop.cc(219)] GLib-GObject: invalid uninstantiatable type '-g-type-private--GTypeFlags' in cast to 'GObject'
[24449:0813/165808:ERROR:browser_main_loop.cc(219)] GLib-GObject: g_object_get_data: assertion 'G_IS_OBJECT (object)' failed
Failed to get crash dump id.

**Comment by zcbenz** [comment] 2015-08-14 01:02
Which Linux distribution are you using? I tested on Ubuntu 14.04 with GNOME 3.

**Comment by paulcbetts** [comment] 2015-08-14 01:05
@zcbenz Ubuntu uses its own magic notifier that isn't what GNOME 3 Official uses, gotta try latest Fedora

**Comment by markbaas** [comment] 2015-08-14 03:42
I'm using fedora 22, should be gnome 3.16.

**Comment by markbaas** [comment] 2015-09-24 13:26
Same problem in KDE

**Comment by zcbenz** [comment] 2015-10-04 12:41
I'm unable to reproduce on Fedora 22 with GNOME 3 for v0.33.4, can you try if it still happens to on v0.33.4?

**Comment by zcbenz** [comment] 2015-10-20 03:12
Closing until more information is provided.

**Comment by markbaas** [comment] 2015-10-20 13:49
I am no longer running GNOME 3, but on KDE with Fedora 23, I still have the same issue. Odd you can't reproduce it.

```
var app = require('app');  // Module to control application life.
var BrowserWindow = require('browser-window');  // Module to create native browser window.
var proc = require('child_process');

// Initial vars
url = 'https://web.whatsapp.com';
domain = url.replace(/https?:\/\/(\w+\.)?(\w+)\.(\w+)\/?.*/, "$2.$3");


// Report crashes to our server.
require('crash-reporter').start();

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is GCed.
var mainWindow = null;

// Quit when all windows are closed.
app.on('window-all-closed', function() {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform != 'darwin') {
    app.quit();
  }
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
app.on('ready', function() {
  // Create the browser window.
  mainWindow = new BrowserWindow({width: 1024, height: 768,
    "node-integration": false,
    "icon": "/home/mark/.local/share/webapps/WhatsApp/WhatsApp.png",
    "auto-hide-menu-bar": true});

  // and load the index.html of the app.
  // mainWindow.loadUrl('file://' + __dirname + '/index.html');
  mainWindow.loadUrl(url, {'userAgent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36'});

  // Emitted when the window is closed.
  mainWindow.on('closed', function() {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });

  mainWindow.webContents.on('new-window', function(event, url, frameName, disposition) {
    outDomain = url.replace(/https?:\/\/(\w+\.)?(\w+)\.(\w+)\/?.*/, "$2.$3");
    if (domain !== outDomain) {
      proc.exec("xdg-open " + url);
      event.preventDefault();
    }

  });

  mainWindow.webContents.on('context-menu', function(event) {
    alert('haha')
  })
});
```

```
{
  "name": "WhatsApp",
  "version": "0.1.0",
  "main": "main.js",
  "devDependencies": {
    "electron-prebuilt": ""
  },
  "dependencies": {
  }
}
```

**Comment by GyozaGuy** [comment] 2015-11-24 18:22
I've been seeing the same issue with Electron 0.35.1 on GNOME 3.16.4 (Ubuntu 15.10).

**Comment by jacobmischka** [comment] 2015-11-25 05:05
It crashes when clicking on a notification created by electron, but not necessarily one that points to electron, if that's useful at all. If you cause an electron window to open, but it doesn't have focus, gnome will make a notification saying "[app] is ready", and clicking on that behaves as it would. 

I'm unsure if that's helpful at all, I don't know how these notifications work exactly.

**Comment by phillip-white-sociomantic** [comment] 2015-12-03 15:53
Same issue for me. Using Cinnamon on Mint. Clicking on the notification causes the app to crash and close. even when the app is in focus on the screen.

**Comment by GyozaGuy** [comment] 2015-12-03 17:18
I'm still seeing this with Electron 0.35.2 as well. A similar issue with Windows was fixed in this release, but apparently not GNOME.

**Comment by ajthemacboy** [comment] 2015-12-09 15:08
Me too, Ubuntu 15.10 and the latest version of Electron. Please fix!

**Comment by zcbenz** [comment] 2015-12-10 13:27
The biggest trouble for me is I never succeeded to reproduce this issue, I have 4 Linux distributions installed and each with various DEs, every one of them works fine.

**Comment by phillip-white-sociomantic** [comment] 2015-12-10 15:21
I#m actually wrapping webpages in Electron with https://www.npmjs.com/package/nativefier. Possibly you can generate one with this and try?

**Comment by ajthemacboy** [comment] 2015-12-10 15:35
I'm on Ubuntu GNOME, if that makes a difference.

**Comment by zcbenz** [comment] 2015-12-11 03:10
Can you delete the `libnotify.so` file in the Electron distribution and see whether it solves the crash?

**Comment by ajthemacboy** [comment] 2015-12-12 17:30
Where is the 'electron distribution?' I'm using the Discord client; https://github.com/XNBlank/discord-linux/releases

**Closed** 2015-12-24 03:16 UTC
Labels: bug, linux, linux-distribution-specific, machine-dependent

**Comment by gameslayer** [comment] 2016-06-02 09:26
Same issue on Xubuntu 14.04
