### ISSUE TITLE
CMD + C / CMD + V (clipboard) not working

### ISSUE THREAD

**Issue by AgtLucas** [atom/electron#1902] opened 2015-06-08 12:47 UTC
Hello folks,

I'm trying to use that [clipboard](https://github.com/atom/electron/blob/master/docs/api/clipboard.md) module to, you know, be able to Copy and Paste stuff into some inputs on my app, but, no joy (Only `console.log()` the clipboard value works).

I've tried this in both OS X and Windows 7 and already read another issues, such: https://github.com/atom/electron/issues/916 https://github.com/atom/electron/issues/1729 https://github.com/atom/electron/issues/1878

Any ideas?

Thanks!

**Comment by steelbrain** [comment] 2015-06-08 12:58
Umm, are you using an keydown event on the document and checking if it's the v and c key and the ctrl key is pressed and then invoking the clipboard module?

**Comment by AgtLucas** [comment] 2015-06-08 13:42
@steelbrain Nops. There's another way to use that?

**Comment by AgtLucas** [comment] 2015-06-08 14:01
Just an update. It's working on Windows 8.

**Comment by zcbenz** [comment] 2015-06-09 05:53
I tried with `clipboard.writeText('text')`, it seems to write "text" to clipboard successfully?

**Comment by yoshuawuyts** [comment] 2015-06-09 14:41
You might want to implement a `menu` as shown in - https://github.com/moose-team/friends/issues/123#issuecomment-106843964

**Comment by bengotow** [comment] 2015-06-12 03:10
Yep, fwiw I put this example together a few days ago that creates the standard application menus and enables copy/paste: https://github.com/bengotow/electron-sample-apps/tree/master/menus

**Comment by zcbenz** [comment] 2015-06-12 07:37
Closing since it doesn't seem to be a bug.

**Closed by zcbenz** 2015-06-12 07:37 UTC

**Comment by thardes2** [comment] 2017-06-28 08:16
Why is this not a bug? This is not really a common way to solve such behaviour?

**Comment by dskvr** [comment] 2018-01-13 18:54
Definitely a bug.

**Comment by zlab** [comment] 2018-08-06 11:13
Why ignore this?

**Comment by saikksub** [comment] 2018-08-22 06:53
I am trying to read image from electron clipboard. Anyone have working solution for this?

**Comment by BeAce** [comment] 2018-11-16 05:58
> Yep, fwiw I put this example together a few days ago that creates the standard application menus and enables copy/paste: https://github.com/bengotow/electron-sample-apps/tree/master/menus

I agree with you. You cannot disable the menu `edit` but I do't know why.

```javascript
const subMenuEdit = {
      label: 'Edit',
      submenu: [
        { label: 'Undo', accelerator: 'Command+Z', selector: 'undo:' },
        { label: 'Redo', accelerator: 'Shift+Command+Z', selector: 'redo:' },
        { type: 'separator' },
        { label: 'Cut', accelerator: 'Command+X', selector: 'cut:' },
        { label: 'Copy', accelerator: 'Command+C', selector: 'copy:' },
        { label: 'Paste', accelerator: 'Command+V', selector: 'paste:' },
        {
          label: 'Select All',
          accelerator: 'Command+A',
          selector: 'selectAll:'
        }
      ]
    };
```
