### ISSUE TITLE
Prevent source code leak

### ISSUE THREAD

**Issue by dhoomm** [atom/electron#4115] opened 2016-01-15 11:31 UTC
The doumentation mentions at http://electron.atom.io/docs/v0.27.0/tutorial/application-distribution/
>you can also package your app into an asar archive to avoid exposing your app's source code to users.

I was able to view the source code at \resources\app.asar after installation. Was able to even edit the file (used Notepad++). (e.g. "Welcome to" edited to "to Welcome") and the app worked normally.

**Comment by zcbenz** [comment] 2016-01-15 15:26
This is a duplicate of https://github.com/atom/electron/issues/3041, currently we don't have a way to safely prevent users from modifying app's source code.

**Closed by zcbenz** 2016-01-15 15:26 UTC
