### ISSUE TITLE
Windows: Cannot navigate menu using keyboard left / right

### ISSUE THREAD

**Issue by bpasero** [atom/electron#1923] opened 2015-06-10 07:29 UTC
On Windows the Menu does not behave very native. For one, pressing Alt should select the first menu ("File"). Then, pressing Arrow-Left or Right I cannot navigate between the menu items. Arrow-Up and down works within the menu.

**Comment by zcbenz** [comment] 2015-06-10 08:42
This is a duplicate of #1700.

**Closed by zcbenz** 2015-06-10 08:42 UTC
