### ISSUE TITLE
Node modules running slower from Electron

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#4020] opened 2016-01-07 15:10 UTC
I'm using the `tasklist` Node module in my Electron app to return what apps I have running on my system to prevent the same app running multiple times.

However I have found that running the module from Electron takes almost 2x longer to run than if called directly. I've started asking about the module here: https://github.com/sindresorhus/tasklist/issues/4

Is there any reason why calling the module inside Electron takes 2x longer? For comparison I have found that running it from NodeJS takes 3-4 seconds to complete, but from Electron it takes over 8 seconds before I see the same results and with no other code taking place before it.

**Comment by sindresorhus** [comment] 2016-01-07 16:17
You should probably provide a simple spawning example app that reproduces the issue.

**Comment by iamdriz** [comment] 2016-01-08 10:30
Here is a simple example:
~~~
var childProcess = require('child_process');
childProcess.execFile('tasklist', function(err, result) {
     console.log(result);
});
~~~

This takes about a second to complete. However when running the tasklist module it is taking about 3-4 seconds when running this:
~~~
var tasklist = require('tasklist');
tasklist(function(err, tasks) {
    console.log(tasks);
});
~~~

So there is serious overhead with the module approach over the native call.

But when this same code is run inside Electron it then takes even longer, nearly doubling it.

**Comment by zcbenz** [comment] 2016-01-11 03:20
I benchmarked with following code and here is the result:

Code: 

```js
console.time('execFile');
var childProcess = require('child_process');
childProcess.execFile('tasklist', function(err, result) {
  console.timeEnd('execFile');
});

console.time('tasklist');
var tasklist = require('tasklist');
tasklist().then(data => {
  console.timeEnd('tasklist');
});
```

Result:

```
execFile: 108.000ms
tasklist: 386.000ms
```

So `tasklist` is much slower than the `execFile` call, but the result of running the code in Node is exactly the same. (Most time should have been spent on `Promise`.)

I don't know why the `tasklist` call is so slow on your machine, 3-4 seconds is absolutely not normal, I think the problem is on your machine so I'm closing this. It is probably caused by your anti-virus programs.

**Closed by zcbenz** 2016-01-11 03:20 UTC

**Comment by iamdriz** [comment] 2016-01-11 11:54
@zcbenz Thanks for testing this. However we don't have any anti-virus software on the machine we tested this code on. Any ideas for what else could be making it run slow?
