### ISSUE TITLE
webview element doesn't load immediately when put into several tabs

### ISSUE THREAD

**Issue by wsangtoki** [atom/electron#4162] opened 2016-01-20 02:43 UTC
Hi,

I am new to electron. I tried to build my own Internet browser with several tabs using electron. Each tab contains a webview element. I have put src value to each webview element but I found when I launch the browser only the webview in active tab was immediately loading. The rest of the webviews were not loading. It only starts to load if I select the tab belongs to the webview.

I want the webviews to load immediately when the browser launch. How can I do that?

**Comment by Tribex** [comment] 2016-01-20 12:07
Try using opacity and z-index to hide the tabs instead of display.

**Comment by zcbenz** [comment] 2016-01-20 22:42
This is a duplicate of #1682, in your case, @Tribex's advice should work well.

**Closed by zcbenz** 2016-01-20 22:42 UTC
