### ISSUE TITLE
Can’t open new browserwindow in final build.

### ISSUE THREAD

**Issue by sebakerckhof** [atom/electron#4486] opened 2016-02-15 13:30 UTC
Hello,

I'm building an electron application that works like this:
The main browserwindow has node integration set to false and has a preload script that gives access to a couple of things. One of those things is the ability to spawn a new browser window with the same configuration, like:

//part of preload.js
...
GlobalVariable = {
...
  open: url => {
		//window.open(url)
		const win = new BrowserWindow({
			title:'Foo',
			webPreferences:{
				nodeIntegration: false,
				preload: path.join(__dirname, 'preload.js')
			},
		});
		win.focus();

		var webContents = win.webContents;
		webContents.on('did-fail-load',console.log);

		if(url[url.length-1] !== '/') url += '/'
		win.loadURL(url);
	}
...
}
...
This works perfect while developing (running via node-electron). But when build (using electron-packager) it fails to open new browser windows.

Version 0.36.7

**Comment by zcbenz** [comment] 2016-02-16 13:12
Since Atom and all other Electron apps can open new windows, I have to assume the problem is in your own code.

**Comment by sebakerckhof** [comment] 2016-02-16 14:06
I'll try to come up with a minimal reproduction

**Comment by zcbenz** [comment] 2016-03-05 13:02
Closing until more information is provided.

**Closed by zcbenz** 2016-03-05 13:02 UTC
Labels: more-information-needed

**Comment by sebakerckhof** [comment] 2016-03-09 09:59
Yeah, I just figured it was a problem with node-mdns which was not being rebuild correctly for electron. Still wonder why it dit work in development mode though.
