### ISSUE TITLE
Meteor Electron App Not showing anything on windows

### ISSUE THREAD

**Issue by prasadnpawar** [atom/electron#2991] opened 2015-10-05 12:40 UTC
I used Electrify package for my meteor app and then I did the packaging of my meteor app. But when I ran it then it launches Electron but it is not showing anything except my app name as a Titale for Electron window.
Does anybody know the solution?

Thanks.

**Comment by etiktin** [comment] 2015-10-05 16:02
I think it's better if you ask this in [Electrify ](https://github.com/arboleya/electrify), since it might be a specific issue to that module. 
If you eventually find that the problem is with Electron, please provide a minimal code example so we can reproduce it.

**Comment by zcbenz** [comment] 2015-10-06 12:49
I'm closing this since this issues belongs to Electrify.

**Closed by zcbenz** 2015-10-06 12:49 UTC
