### ISSUE TITLE
Remote getter not working

### ISSUE THREAD

**Issue by RX14** [atom/electron#4529] opened 2016-02-17 21:37 UTC
Electron version: `v0.36.7`
OS: linux

Code:

```js
"use strict";
class GetterTest {
    get foo() {
        return "bar"
    }
}

global.foo = new GetterTest();

console.log(global.foo.foo)

const electron = require("electron");
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;

var window = null;

app.on("ready", () => {
    window = new BrowserWindow();

    window.loadURL(`file://${__dirname}/index.html`);
});
```

```html
<html>
    <head>
    <script>
var remote = require("remote");
var foo = remote.getGlobal("foo");

console.log(foo.foo);
    </script>
    </head>
</html>
```

Expected: both `console.log` statements print "bar".

Actual: only `console.log` on main process prints "bar", the chrome debug console shows "undefined".

**Comment by zcbenz** [comment] 2016-02-18 11:57
This is a duplicate of #4066.

**Closed by zcbenz** 2016-02-18 11:57 UTC

**Comment by RX14** [comment] 2016-02-18 18:37
Oops, I searched for a while but couldn't find a duplicate issue. Seems github search is a bit shit.

**Comment by RX14** [comment] 2016-02-18 22:59
Ah, it turns out that the property was enumerable, yet I was using webContents.send, which doesn't support this. Why is webContents.send different?
