### ISSUE TITLE
Webview preloads don't run if the guest content has no scripts

### ISSUE THREAD

**Issue by ErinCall** [atom/electron#3205] opened 2015-10-25 18:42 UTC
Suppose you have three files, `index.html`, `preloadme.js`, and `empty.html`.

`index.html`:

```HTML
...
<webview preload="./preloadme.js"></webview>
<script>/*just here to avoid #1117*/</script>
...
```

`preloadme.js`:

```JavaScript
document.body.appendChild(document.createTextNode("Hello!"));
```

`empty.html`:

```HTML
<!doctype html>
<html>
<head>
  <title></title>
</head>
<body></body>
</html>
```

The "hello" will fail to show. I imagine this comes from the same Chrome optimization mentioned in #1117 .

**Comment by zcbenz** [comment] 2015-10-26 02:35
This is a duplicate of #1117.

**Closed by zcbenz** 2015-10-26 02:35 UTC
