### ISSUE TITLE
Unable to use Pepper Flash plugin in packaged app (MacOS X)

### ISSUE THREAD

**Issue by wolfflow** [atom/electron#2457] opened 2015-08-09 20:07 UTC
I'm unable to harness PPAPI Flash in app packaged by electron packager under  MAC OS X
OS: MacOS X 10.10 Yosemite
Electron: 0.30.3

Sample app: https://github.com/hokein/electron-sample-apps/tree/master/pepper-flash-plugin

NOTE: Windows and Linux packaged apps work well

**Comment by zcbenz** [comment] 2015-08-24 04:00
Can you run your app in Terminal and paste the output?

**Comment by wolfflow** [comment] 2015-08-24 14:32
Hi, here's result of  execution
```
./PepperDemo.app/Contents/MacOS/Electron
[4388:0824/072931:INFO:renderer_main.cc(200)] Renderer process started
[4387:0824/072931:INFO:renderer_main.cc(200)] Renderer process started
[4385:0824/072932:WARNING:backend_impl.cc(1570)] Messed up entry found.
[4385:0824/072932:WARNING:backend_impl.cc(1778)] Destroying invalid entry.
[4385:0824/072953:INFO:CONSOLE(81)] "Uncaught Error: utils missing spinner", source: http://wwwimages.adobe.com/www.adobe.com/assets/globalnav/v1.1.4/js/globalnav.js (81)
[4385:0824/072954:INFO:CONSOLE(1)] "Uncaught TypeError: undefined is not a function", source: http://wwwimages.adobe.com/www.adobe.com/ubi/globalnav/_all/ims.js (1)
LaunchProcess: failed to execvp:
/Users/xflowwolf/Git/electron-sample-apps/pepper-flash-plugin/PepperDemo-darwin-x64/PepperDemo.app/Contents/Frameworks/PepperDemo Helper EH.app/Contents/MacOS/PepperDemo Helper EH
LaunchProcess: failed to execvp:
/Users/xflowwolf/Git/electron-sample-apps/pepper-flash-plugin/PepperDemo-darwin-x64/PepperDemo.app/Contents/Frameworks/PepperDemo Helper EH.app/Contents/MacOS/PepperDemo Helper EH
LaunchProcess: failed to execvp:
/Users/xflowwolf/Git/electron-sample-apps/pepper-flash-plugin/PepperDemo-darwin-x64/PepperDemo.app/Contents/Frameworks/PepperDemo Helper EH.app/Contents/MacOS/PepperDemo Helper EH
LaunchProcess: failed to execvp:
/Users/xflowwolf/Git/electron-sample-apps/pepper-flash-plugin/PepperDemo-darwin-x64/PepperDemo.app/Contents/Frameworks/PepperDemo Helper EH.app/Contents/MacOS/PepperDemo Helper EH
LaunchProcess: failed to execvp:
/Users/xflowwolf/Git/electron-sample-apps/pepper-flash-plugin/PepperDemo-darwin-x64/PepperDemo.app/Contents/Frameworks/PepperDemo Helper EH.app/Contents/MacOS/PepperDemo Helper EH
[4386:0824/072955:WARNING:ipc_message_attachment_set.cc(37)] MessageAttachmentSet destroyed with unconsumed descriptors: 0/1
[4386:0824/072955:ERROR:gles2_cmd_decoder.cc(11748)] [GroupMarkerNotSet(crbug.com/242999)!:A82A02EAD37F0000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[4386:0824/072955:ERROR:gles2_cmd_decoder.cc(6570)] [GroupMarkerNotSet(crbug.com/242999)!:A82A02EAD37F0000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[4386:0824/072955:ERROR:gles2_cmd_decoder.cc(11748)] [GroupMarkerNotSet(crbug.com/242999)!:A82A02EAD37F0000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[4386:0824/072955:ERROR:gles2_cmd_decoder.cc(6570)] [GroupMarkerNotSet(crbug.com/242999)!:A82A02EAD37F0000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[4386:0824/072955:ERROR:gles2_cmd_decoder.cc(11748)] [GroupMarkerNotSet(crbug.com/242999)!:A82A02EAD37F0000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[4386:0824/072955:ERROR:gles2_cmd_decoder.cc(6570)] [GroupMarkerNotSet(crbug.com/242999)!:A82A02EAD37F0000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[4386:0824/072955:ERROR:gles2_cmd_decoder.cc(11748)] [GroupMarkerNotSet(crbug.com/242999)!:A82A02EAD37F0000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[4386:0824/072955:ERROR:gles2_cmd_decoder.cc(6570)] [GroupMarkerNotSet(crbug.com/242999)!:A82A02EAD37F0000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[4386:0824/072955:ERROR:gles2_cmd_decoder.cc(11748)] [GroupMarkerNotSet(crbug.com/242999)!:A82A02EAD37F0000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[4386:0824/072955:ERROR:gles2_cmd_decoder.cc(6570)] [GroupMarkerNotSet(crbug.com/242999)!:A82A02EAD37F0000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[4386:0824/072955:ERROR:gles2_cmd_decoder.cc(11748)] [GroupMarkerNotSet(crbug.com/242999)!:A82A02EAD37F0000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[4386:0824/072955:ERROR:gles2_cmd_decoder.cc(6570)] [GroupMarkerNotSet(crbug.com/242999)!:A82A02EAD37F0000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[4386:0824/072955:ERROR:gles2_cmd_decoder.cc(11748)] [GroupMarkerNotSet(crbug.com/242999)!:A82A02EAD37F0000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[4386:0824/072955:ERROR:gles2_cmd_decoder.cc(6570)] [GroupMarkerNotSet(crbug.com/242999)!:A82A02EAD37F0000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[4386:0824/072955:ERROR:gles2_cmd_decoder.cc(11748)] [GroupMarkerNotSet(crbug.com/242999)!:A82A02EAD37F0000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[4386:0824/072955:ERROR:gles2_cmd_decoder.cc(6570)] [GroupMarkerNotSet(crbug.com/242999)!:A82A02EAD37F0000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[4386:0824/072955:ERROR:gles2_cmd_decoder.cc(11748)] [GroupMarkerNotSet(crbug.com/242999)!:A82A02EAD37F0000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[4386:0824/072955:ERROR:gles2_cmd_decoder.cc(6570)] [GroupMarkerNotSet(crbug.com/242999)!:A82A02EAD37F0000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
Flows-Mac:PepperDemo-darwin-x64 xflowwolf$ ./PepperDemo.app/Contents/MacOS/Electron 
[4402:0824/073003:INFO:renderer_main.cc(200)] Renderer process started
[4403:0824/073003:INFO:renderer_main.cc(200)] Renderer process started
[4400:0824/073004:INFO:CONSOLE(81)] "Uncaught Error: utils missing spinner", source: http://wwwimages.adobe.com/www.adobe.com/assets/globalnav/v1.1.4/js/globalnav.js (81)
[4400:0824/073007:INFO:CONSOLE(1)] "Uncaught TypeError: undefined is not a function", source: http://wwwimages.adobe.com/www.adobe.com/ubi/globalnav/_all/ims.js (1)
LaunchProcess: failed to execvp:
/Users/xflowwolf/Git/electron-sample-apps/pepper-flash-plugin/PepperDemo-darwin-x64/PepperDemo.app/Contents/Frameworks/PepperDemo Helper EH.app/Contents/MacOS/PepperDemo Helper EH
LaunchProcess: failed to execvp:
/Users/xflowwolf/Git/electron-sample-apps/pepper-flash-plugin/PepperDemo-darwin-x64/PepperDemo.app/Contents/Frameworks/PepperDemo Helper EH.app/Contents/MacOS/PepperDemo Helper EH
LaunchProcess: failed to execvp:
/Users/xflowwolf/Git/electron-sample-apps/pepper-flash-plugin/PepperDemo-darwin-x64/PepperDemo.app/Contents/Frameworks/PepperDemo Helper EH.app/Contents/MacOS/PepperDemo Helper EH
LaunchProcess: failed to execvp:
/Users/xflowwolf/Git/electron-sample-apps/pepper-flash-plugin/PepperDemo-darwin-x64/PepperDemo.app/Contents/Frameworks/PepperDemo Helper EH.app/Contents/MacOS/PepperDemo Helper EH
LaunchProcess: failed to execvp:
/Users/xflowwolf/Git/electron-sample-apps/pepper-flash-plugin/PepperDemo-darwin-x64/PepperDemo.app/Contents/Frameworks/PepperDemo Helper EH.app/Contents/MacOS/PepperDemo Helper EH
```

**Comment by wolfflow** [comment] 2015-08-24 14:42
Really, there's no sign of PepperFlash plugin inside the package. So this might be the packager's error for not including PepperFlash inside package. Manual copy does not solve problem at all, and `navigator.plugins` is still an empty list.

**Comment by zcbenz** [comment] 2015-08-25 12:23
Will flash plugin work if you just use the one from Chrome browser?

```js
app.commandLine.appendSwitch('ppapi-flash-path', '/Applications/Google Chrome.app/Contents/Versions/44.0.2403.157/Google Chrome Framework.framework/Internet Plug-Ins/PepperFlash/PepperFlashPlayer.plugin');
app.commandLine.appendSwitch('ppapi-flash-version', '18.0.0.232');
```

**Comment by wolfflow** [comment] 2015-08-25 16:34
Nope, even from this path. `navigator.plugins` is also empty.

**Comment by zcbenz** [comment] 2015-08-26 04:14
Can you open a fresh downloaded Electron and see if `navigator.plugins` is in the default app? I think you are disabling plugins in your app.

**Comment by wolfflow** [comment] 2015-08-26 08:16
Default app is not compressed btw, so `navigator.plugins` list is populated properly. The problem occurs only if app is packaged under MacOS X.
Actually, I don't disable any plugins at all, as it's seen in the sample: https://github.com/hokein/electron-sample-apps/tree/master/pepper-flash-plugin.

The build string is: `electron-packager ./ PepperDemo --platform=darwin --version=0.30.3 --arch=x64 --overwrite`

**Comment by zcbenz** [comment] 2015-08-26 08:35
Does file `PepperDemo.app/Contents/Frameworks/PepperDemo Helper EH.app/Contents/MacOS/PepperDemo Helper EH` exist on your machine? From the log you have generated a bad app.

**Comment by wolfflow** [comment] 2015-08-26 09:56
Sad but true, it does not exit, there's Electron Helper EH only file inside MacOS folder.
But, there is not any option for electron-packager to include or exclude plugins from app package.
So it is the packager's fault.

**Comment by zcbenz** [comment] 2015-08-27 01:32
The electron-packager seems to work fine on my machine, and you have to generate a correct app to make plugins work.

I'm closing since it is caused by app not correctly generated, please report back if you have correctly bundled your app and the plugins are still not working.

**Closed by zcbenz** 2015-08-27 01:32 UTC

**Comment by wolfflow** [comment] 2015-09-02 08:23
Do you use the same command string for packager as I do? 
Should I set the app-bundle-id and helper-bundle-id for getting the "correct" app build?

**Comment by spcBackToLife** [comment] 2018-08-21 06:59
@wolfflow have you solve this problem ？
