### ISSUE TITLE
bug with tabbing and focusing of elements

### ISSUE THREAD

**Issue by astoilkov** [atom/electron#4031] opened 2016-01-08 14:44 UTC
The simplest example is:
```html
<!DOCTYPE html>
<html>
  <body>
    <input>
  </body>
</html>
```

  1. Focus the input
  2. Hit Tab
  3. Start typing

The input won't be focused but you will see that you can actually edit the input. 

### Second issue:
`document.activeElement` returns `document.body` for which there is not way to blur `document.body` or detect that it have been focused (using addEventListener('blur')) so there is no way of making a loop where you hit tab on the last focused element to focus the first.

**Comment by zcbenz** [comment] 2016-01-11 03:51
This is actually a bug of Chrome, it is not impossible to reproduce in normal browser window since the focus will be switched to address bar, but you can reproduce it in Chrome app.

Steps:
* Download the hello-world app: https://gist.github.com/zcbenz/d041c65526156cb339cf
* Load it in Chrome
* You can see the exact problem in the Chrome app

I'm closing this since there is nothing we can do in Electron, it is most likely a bug in blink, but we don't have the resources of fixing the bug and pushing it to upstream. I suggest reporting it to [Chromium's issues list](https://crbug.com), but it is very likely to be low-priorly.

**Closed by zcbenz** 2016-01-11 03:51 UTC
