### ISSUE TITLE
Intermittent issues launching on Windows when using dual (heterogeneous) GPUs

### ISSUE THREAD

**Issue by rpavlik** [atom/electron#4148] opened 2016-01-18 15:33 UTC
Since I updated my desktop configuration to use both my Intel HD 4600 (on my Core i7-4700) and my discrete NVIDIA 635 GT OEM, roughly half the time I start Atom, I get an "Editor not responding" window. No other changes occurred at that time, and I did try re-installing with the installer from the web site.

Filing the issue here because I presumed it to be related to the GPU acceleration in the shell getting confused over which GPU to create resources on, since I had similar problems recently in my own code...

**Comment by zcbenz** [comment] 2016-01-19 20:18
The "Editor not responding" dialog can occur for many reasons, but it has never been caused by hardware issues. 

> since I had similar problems recently in my own code

Can you say more about it?

**Comment by zcbenz** [comment] 2016-02-02 09:26
Closing until more information is provided.

**Closed by zcbenz** 2016-02-02 09:26 UTC
Labels: more-information-needed

**Comment by rpavlik** [comment] 2016-02-02 16:48
Sorry about the lack of follow up - so it happens when I try to open a second Atom window - the first one always opens fine, but the second one will sometimes (often) open to just the default background before giving the timeout.

My own code: <http://osvr.github.io> though the specific code I'm thinking of isn't open source - doing directx rendering for virtual reality headsets using some vendor-specific calls.

When I switched my system to the hetgpu setup, it revealed that the code was assuming that the NVIDIA adapter was the default adapter, and thus calling `D3D11CreateDevice` with a null first parameter, and `D3D_DRIVER_TYPE_HARDWARE` second parameter, to let Windows choose the default adapter when creating the device.

Instead, we needed to do some magic calls to NVIDIA, and/or DirectX, so that we'd end up getting a specific `IDXGIAdapter`. For safety, then, we always (though really only needed in multi-gpu setups) pass that in the first parameter and thus `D3D_DRIVER_TYPE_UNKNOWN` in the second parameter (because that's what Microsoft says you have to do if you pass in a non-null adapter pointer)
