### ISSUE TITLE
Some properties passed in BrowserWindow object do not work correctly

### ISSUE THREAD

**Issue by Rustem** [atom/electron#2038] opened 2015-06-23 13:19 UTC
![selection_069](https://cloud.githubusercontent.com/assets/195228/8306950/adda0bac-19dd-11e5-846f-1d9d62cd223a.png)
`resizable` and `always-on-top` properties do not work correctly. BrowserWindow is appeared properly but properties are not applied. Tested on Ubuntu 12.04 precise and Ubuntu 14.04 trusty
```
dummyWindow = new BrowserWindow({
        'title': data.question,
        'always-on-top': false,
        'resizable': false,
        'width': 500,
        'height': 216,
        'frame': true,
      })
```

Small window from the right is set to be `{always-on-top: true, resizable: false}`

**Comment by zcbenz** [comment] 2015-06-23 14:47
This is a duplicate of #953.

**Closed by zcbenz** 2015-06-23 14:47 UTC
