### ISSUE TITLE
Unable load load local resource

### ISSUE THREAD

**Issue by MilesWarburton** [atom/electron#2154] opened 2015-07-08 11:51 UTC
![git](https://cloud.githubusercontent.com/assets/2363782/8569474/f28e798e-256f-11e5-8fe9-a065be46a0a0.png)

Documentation is a bit scant on how to fix this issue.

**Comment by zcbenz** [comment] 2015-07-09 03:06
You description is a bit scant on how to reproduce this issue.

**Comment by zcbenz** [comment] 2015-07-14 15:33
Closing due to lack of information.

**Closed by zcbenz** 2015-07-14 15:33 UTC
