### ISSUE TITLE
Is it possible to show contextMenu in Mac only on right-clicked to Tray Icon

### ISSUE THREAD

**Issue by tevfik6** [atom/electron#3162] opened 2015-10-21 00:53 UTC
I read that there is/was a problem on tray right-clicked event. It is/was triggering clicked as well. I'm not sure it's fixed or not. 

I'm trying to show the contextMenu only on right-clicked to tray icon in Mac. 

I tried to preventDefault from click and right-clicked events, no luck. If there is a contextMenu on a tray, It anyway shows the context menu and doesn't run the code i have in the clicked event (I'm showing/hiding the window by single click)

I'm looking a way/workaround to show the contextMenu when only right clicked.

Tev.

**Comment by zcbenz** [comment] 2015-10-21 01:22
It seems that we don't have a solution for this, we can probably add a `menu` parameter for `Tray.popUpContextMenu`.

**Comment by CyrisXD** [comment] 2015-10-22 04:42
I'm having this exact issue right now. Hopefully someone can figure out a fix.

**Comment by khomka** [comment] 2015-10-22 20:37
I'm having the same problem now.

**Comment by zcbenz** [comment] 2015-10-26 02:33
I just realized this is a duplicate of #2830.

**Closed by zcbenz** 2015-10-26 02:33 UTC
Labels: enhancement, tray
