### ISSUE TITLE
Websockets are stuck in CONNECTING state.

### ISSUE THREAD

**Issue by RonnChyran** [atom/electron#2098] opened 2015-07-01 21:44 UTC
I'm trying to connect to a local websocket server.

`socket = new WebSocket("ws://localhost:30003");`

The socket never connects properly. When I try to do `socket.send()`, it throws a DOMException:

`Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.`

It works fine in Chrome 43. I've also tried running this code inside the Atom editor, it doesn't work.

**Comment by anonrig** [comment] 2015-07-01 21:47
I've tried it with Socket.io, and it works.

**Comment by RonnChyran** [comment] 2015-07-01 21:49
https://github.com/websockets/ws works as well, but native WebSockets don't work.

**Comment by steelbrain** [comment] 2015-07-02 21:39
@RonnChyran what If I told you that `https://github.com/websockets/ws` doesn't use **any** fallbacks and relies solely on Native WebSockets :smiley:

**Comment by RonnChyran** [comment] 2015-07-02 22:15
[It reimplements WebSockets in node](https://github.com/websockets/ws/blob/master/lib/WebSocket.js). To clarify what I mean by "Native WebSockets", I mean the browser-based `window.WebSocket` in the Renderer process; the same WebSocket provided by Google Chrome. Those don't work in electron, the node module is required to have working WebSockets.

**Comment by steelbrain** [comment] 2015-07-05 03:31
@RonnChyran I think you are doing it incorrectly, it has reimplemented websockets using nodejs but only for servers and clients that don't have them natively and from what I understand is that you want to connect to a websocket server not be one, So you don't need any library for that.

**Comment by RonnChyran** [comment] 2015-07-05 22:37
My point is that the built-in WebSockets are stuck in CONNECTING. Thus, my only solution is to use the nodejs WebSockets. It doesn't really bother me, its just that it's a bug that the built-in WebSockets never connect.

**Comment by zcbenz** [comment] 2015-07-06 07:31
Due to #1450 user agent is not set in WebSockets, can you check if your server correctly handles this situation?

**Comment by zcbenz** [comment] 2015-07-10 03:07
Closing since it is very likely a duplicate of #1450.

**Closed by zcbenz** 2015-07-10 03:07 UTC
