### ISSUE TITLE
autoUpdater.quitAndInstall() doesn't relaunch app

### ISSUE THREAD

**Issue by svileng** [atom/electron#4488] opened 2016-02-15 17:05 UTC
When I call `autoUpdater.quitAndInstall()`, the app quits to install the update, but it doesn't start afterwards; when I start it manually, I can see that the update was applied successfully. This must have been broken in the last two or three releases of Electron, as I remember it was restarting the app correctly on `0.36.4`.

Currenty: Electron `0.36.7` on OSX `10.11`.

**Comment by zcbenz** [comment] 2016-02-16 13:39
There was no changes to OS X's autoUpdater in 0.35.x and 0.36.x, it could be caused by other things. I suggest reporting this to https://github.com/Squirrel/Squirrel.Mac instead, which is the auto updating library used by Electron. I'm closing this since we are not able to solve this on our side.

**Closed by zcbenz** 2016-02-16 13:39 UTC
