### ISSUE TITLE
Supporting prompt

### ISSUE THREAD

**Issue by alexandrev** [atom/electron#4134] opened 2016-01-16 17:22 UTC
I have seen that you close another issue related to this one about including prompt as an option inside your API to show dialog. I don't know why is the reason to discard this basic function, but I think you should reconsider it because it's a basic feature that make you discard this API or use different API to fulfill your needs.

Please, introduce an option to prompt a value to the user in the dialog API.

Thx,

**Comment by dkfiresky** [comment] 2016-01-17 00:30
@alexandrev Prompt dialogs have their own limitations, so it's rather simpler to implement new BrowserWindow with custom html form inside.

**Comment by alexandrev** [comment] 2016-01-17 01:14
HI @dkfiresky. You are probably right but that happens with any other dialog and I don't think the solution is to create your own component for everything (new browser with custom html code is custom component). 

That's a solution that doesn't create any problem to the electron API and it is supported for most of the other API's or even for all the languages.

**Comment by zcbenz** [comment] 2016-01-17 06:31
The reason why this is not supported has been explained in https://github.com/atom/electron/issues/472#issuecomment-60515607, I don't think it worths any effort to implement it.

I'm locking this since this is an exact duplicate of #472, we should limit the discussion in one issue.

**Closed by zcbenz** 2016-01-17 06:31 UTC
