### ISSUE TITLE
Loading a <webview> inside a <webview> fails

### ISSUE THREAD

**Issue by asaschachar** [atom/electron#3960] opened 2015-12-30 06:06 UTC
When a `<webview>` tag points to a page which tries to load another `<webview>` tag, the inner webview fails to load. Example below:

In main.js, we load a page webview_outer:
```javascript
mainWindow.loadURL('file://' + __dirname + '/webview_outer.html');
```

In webview_outer.html, we load another page webview_inner:
```html
<html>
<body onload='onload()'>
  <webview id="webview_outer"></webview>
  <script>
    onload = function() {
      // This loads a page with a webview inside
      var webview = document.querySelector('#webview_outer');
      webview.src = 'file://' + __dirname + '/webview_inner.html';

      webview.addEventListener('dom-ready', function() {
        webview.openDevTools();
      });
    }
  </script>
</body>
</html>
```

In webview_inner.html, we attempt to load a final web page (in this example the electron docs):
```html
<html>
<body onload='onload()'>
  <webview id="webview_inner"></webview>
  <script>
    onload = function() {
      // This webview never loads
      var webview = document.querySelector('#webview_inner');
      webview.src = 'http://electron.atom.io/docs/v0.36.0/';

      webview.addEventListener('dom-ready', function() {
        webview.openDevTools();
      });
    }
  </script>
</body>
</html>
```

The inner webview never loads. Is loading a `<webview>` inside a `<webview>` not supported by electron's architecture?

(OS X El Capitan 10.11.2, Electron 0.36.2 [using electron-prebuilt])

**Comment by zcbenz** [comment] 2015-12-30 08:20
This is a duplicate of #1130.

**Closed by zcbenz** 2015-12-30 08:20 UTC

**Comment by asaschachar** [comment] 2015-12-30 19:14
Thanks!
