### ISSUE TITLE
[windows] BrowserWindow.setPosition(0,0) is not in the top left corner

### ISSUE THREAD

**Issue by felicienfrancois** [atom/electron#4549] opened 2016-02-19 14:01 UTC
* Electron version: 0.36.8
* Operating system: Windows 10 64bit

Also, when the browserwindow is in the top left corner (or maximized), I get:
```
browserWindow.getBounds();
> {x: -8, y: -8, width: 2576, height: 1416}

screen.getPrimaryDisplay();
> {
    bounds: { height: 1440, width: 2560, x: 0, y: 0 },
    rotation: 0,
    scaleFactor: 1,
    size: { height: 1440, width: 2560 },
    touchSupport: "unknown"
    workArea: { height: 1440, width: 2560, x: 0, y: 0 }
    workAreaSize: { height: 1440, width: 2560 }
}
```

**Comment by zcbenz** [comment] 2016-02-21 10:50
This is a duplicate of #4045.

**Closed by zcbenz** 2016-02-21 10:50 UTC
