### ISSUE TITLE
Can not check TTY context

### ISSUE THREAD

**Issue by stefanbuck** [atom/electron#2432] opened 2015-08-06 05:40 UTC
The `isTTY` property on `process.stderr`, `process.stdout` and `process.stdin` returns `undefined` instead of a `boolean`.

Electron version: 30.0.2
Mac OS X 10.10.3

**Comment by zcbenz** [comment] 2015-09-06 08:15
This is a duplicate of #1647.

**Closed by zcbenz** 2015-09-06 08:15 UTC
Labels: bug
