### ISSUE TITLE
Set browser window background color

### ISSUE THREAD

**Issue by tommoor** [atom/electron#2313] opened 2015-07-23 16:28 UTC
Opening this up for a discussion, basically what i'd like to see is an API to set the background of the browser-window surrounding the web contents. When the user is resizing the window this shows up before the web contents fills the available space - if you are developing a dark application then this white border looks particularly bad.

For example I noticed that Spotify is able to achieve this by using a fill color that matches the rest of the app whilst the UI resizes.

**Comment by zcbenz** [comment] 2015-07-24 02:50
This is a duplicate of https://github.com/atom/electron/issues/861.

**Closed by zcbenz** 2015-07-24 02:50 UTC
Labels: enhancement
