### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by geeeeeeeeek** [atom/electron#4816] opened 2016-03-15 16:54 UTC
* Electron version: 0.36.9
* Operating system: OS X 10.0.2

The error showed on startup, and kept showing up for several times after clicking on OK. But when I opened my app the other time, the dialog did not reproduce. I think this might the with the electron itself.
```
Uncaught Exception:
TypeError: Cannot read property 'delete' of undefined
    at ObjectsRegistry.remove (/Applications/Electronic WeChat.app/Contents/Resources/atom.asar/browser/lib/objects-registry.js:53:31)
    at EventEmitter.<anonymous> (/Applications/Electronic WeChat.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:345:26)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/Applications/Electronic WeChat.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:123:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

**Comment by kevinsawicki** [comment] 2016-03-16 18:14
@zcbenz do you think this needs a fix similar to https://github.com/atom/electron/commit/927c3f34c3759e29948a1ffaa76a4985d38a1d69 ?

**Comment by zcbenz** [comment] 2016-03-27 03:05
This is a duplicate of #4733 under the hood, which has been fixed on the master branch.

**Closed by zcbenz** 2016-03-27 03:05 UTC
Labels: bug
