### ISSUE TITLE
Update from iojs to node.js v4

### ISSUE THREAD

**Issue by Kimura1** [atom/electron#2733] opened 2015-09-08 12:13 UTC
node.js v4 will be release soon.
So, Please update to node.js v4! (and enable some es6 feature by default!)

**Comment by magicae** [comment] 2015-09-08 20:01
Node.js v4  (with v8 v4.5.103) was released about an hour ago, which uses significantly less memory than any previous version of Node.

**Comment by paulcbetts** [comment] 2015-09-08 20:21
It's been out for like 5 hours, erry'body slow their roll

**Comment by frankhale** [comment] 2015-09-09 05:29
So Electron 0.32 just came out and it's at io.js 3.3.0. Why was 4.0 not used? I'm not trying to be difficult or an ass but I'm scratching my head at this.

**Comment by thomasjo** [comment] 2015-09-09 05:39
> So Electron 0.32 just came out and it's at io.js 3.3.0. Why was 4.0 not used? I'm not trying to be difficult or an ass but I'm scratching my head at this.

Because it's unlikely to be a simple matter of bumping the version. Almost surely there are going to be regressions, so why on earth would a release containing new features and bug fixes be postponed, potentially for days, just to bump to Node.js v4.0.0?

Along the sentiment by @paulcbetts; calm down... Node.js v4.0.0 hasn't even been out 12 hours yet.

**Comment by frankhale** [comment] 2015-09-09 05:44
Yeah yeah sure calm down, I get it. I'm just saying. I knew this was flame bait.

**Comment by frankhale** [comment] 2015-09-09 07:04
I'm sorry, my comment was in the @paulcbetts style but the opposite of what you were expecting. LOL!  I'm sure within a week or so we'll have 4.0 and Electron 0.32.1.

**Comment by zcbenz** [comment] 2015-09-09 07:25
I want to claim one thing here: most things you are excited about come from V8, like better performance and new ES6 features. And in Electron we are always using the V8 that shipped with Chromium, instead of the one that shipped by Node.js, so the Electron v0.32.0 is actually io.js v3.3.0 with V8 4.5, which have all the ES6 features you want in Node.js 4.0.0.

The changes in io.js/Node.js itself may break things sometimes, which you definitely do not want under most cases, so we do not update to the latest one immediately after the release. We usually update io.js/Node.js when: 1) there is a fix we need, 2) there are breaking API changes in V8, 3) the last io.js/Node.js have been stable enough. For the 4.0.0 release, I would like to wait for a few weeks because it is a major version update anyway.

I'm closing this because we have a regular plan of updating to latest io.js/Node.js, and we don't open issue for every update.

**Closed by zcbenz** 2015-09-09 07:25 UTC
