### ISSUE TITLE
Unresponsive OSX application menu after calling dock.show()

### ISSUE THREAD

**Issue by aackerman** [atom/electron#3739] opened 2015-12-09 03:55 UTC
Under very specific circumstances the application menu on OSX can become unresponsive.

I have a narrowed test case repo here [electron-unresponsive-menu-test](https://github.com/aackerman/electron-unresponsive-menu-test).

I happen to be running OSX `10.10.5` with Electron `0.33.2`.

After some cursory googling, the issue appears to stem from the implementation of the [DockShow](https://github.com/atom/electron/blob/053cd3dad0b09f1027139b443ec5149aa2cb7a92/atom/browser/browser_mac.mm#L69) in `browser_mac.mm`. This [SO post](http://stackoverflow.com/questions/7596643/when-calling-transformprocesstype-the-app-menu-doesnt-show-up) has possibly related info that could lead to a solution.

![unresponsive-menu](https://cloud.githubusercontent.com/assets/786640/11719236/6dcbd2e4-9f1f-11e5-8d47-7e0a0cc291b9.gif)

**Comment by zcbenz** [comment] 2015-12-10 06:14
I'm unable to reproduce on OS X 10.11 with Electron 0.35.x, can you try if the problem still exists in latest Electron? Otherwise it may have been fixed by OS X itself.

**Comment by aackerman** [comment] 2015-12-10 15:20
I was able to reproduce in Electron `0.35.4` still on OSX `10.10.5`. I'll attach an animation of the reproduction so the issue is clearer.

**Comment by jrehbein** [comment] 2015-12-17 20:03
Just put up a PR for this:
https://github.com/atom/electron/pull/3853
I confirmed both the bug and the fix (workaround) on 10.9, 10.10, and 10.11

**Comment by zcbenz** [comment] 2015-12-21 02:39
Fixed with #3853.

**Closed by zcbenz** 2015-12-21 02:39 UTC
Labels: bug, osx
