### ISSUE TITLE
webview.getUrl() is incorrect after redirecting

### ISSUE THREAD

**Issue by felicienfrancois** [atom/electron#1435] opened 2015-04-17 12:31 UTC
Set src to `http://github.com`,
The page redirects to https (`https://github.com`)
but the result of `webview.getUrl()` remains `http://github.com`.

**Comment by qq150871483** [comment] 2015-04-17 12:41
https://github.com/

**Comment by deepak1556** [comment] 2015-04-17 20:15
dupe https://github.com/atom/electron/issues/1364

**Comment by zcbenz** [comment] 2015-04-20 08:21
Closing as a duplicate of #1364.

**Closed by zcbenz** 2015-04-20 08:21 UTC
