### ISSUE TITLE
CSS hover styles not triggered when windows is unfocused on OSX

### ISSUE THREAD

**Issue by tommoor** [atom/electron#2797] opened 2015-09-16 01:20 UTC
Repro:

- Add something with a hover style in CSS
- Focus another window 
- Hover over the unfocused Electron window
- Usually the hover style will be seen for a split second before disappearing

This sounds like a small thing, and it is - but it's actually quite frustrating in our particular UI as we have buttons that appear on hover which you accidentally click when focusing. It also *looks* buggy as the hover style visually flashes.

Note: On Windows this works as expected, showing the hover styles in the Electron window continuously even when unfocused.

**Comment by ssreekanth** [comment] 2015-09-16 03:29
I noticed the same behavior with custom window control buttons on OS X.

**Comment by zcbenz** [comment] 2015-09-16 15:17
Can you dump your HTML page out and test if you can reproduce in Chrome? If it is a Chrome bug I suggest reporting it to Chromium's issues, we can not fix in on Electron's side.

**Comment by tommoor** [comment] 2015-09-16 16:11
You're right, this behaviour is also replicable in Chrome on any webpage - I can report it there but I can't imagine it getting fixed as this is far less of an issue (maybe not even expected behaviour?) for a webpage than it is for a native app.

**Comment by zcbenz** [comment] 2015-09-17 06:40
Yeah it would be a quite low priority bug in Chromium, but hopefully it would get fixed someday. Having it here won't do any help, this bug is hidden deeply in Chromium's source code and we have no `blink` or Chromium rendering expert here.

I'm closing this since we can't do anything about it.

**Closed by zcbenz** 2015-09-17 06:40 UTC

**Comment by eladams** [comment] 2017-09-02 18:47
@zcbenz  Is there anything new related to this issue? I want to help with some guidance :)

**Comment by zuoxinyu** [comment] 2017-11-02 05:53
This bug still remains on v1.7.9 , and it accursed on windows.
