### ISSUE TITLE
Black screen after first click on close button

### ISSUE THREAD

**Issue by green13** [atom/electron#4269] opened 2016-01-29 14:21 UTC
Black screen after first click on close button. Application closes after second click on close button.
Reload works fine.

![image](https://cloud.githubusercontent.com/assets/4918944/12677775/5f061698-c6ac-11e5-802c-e57d0942b250.png)

![image](https://cloud.githubusercontent.com/assets/4918944/12677834/b30ad2d8-c6ac-11e5-9d1f-251fdfa12e00.png)

electron-prebuilt 0.36.6
electron-rebuild 1.1.2
os windows 8.1

**Comment by frankhale** [comment] 2016-01-29 16:17
This also happens with Electron's default app so it definitely appears to be a bug in Electron.

**Comment by zcbenz** [comment] 2016-01-30 03:26
This is a duplicate of #4266.

**Closed by zcbenz** 2016-01-30 03:26 UTC
