### ISSUE TITLE
Electron creates the lockfile in %appdata% regardless of the path which was set in main.js

### ISSUE THREAD

**Issue by nxrighthere** [atom/electron#4807] opened 2016-03-15 07:43 UTC
Tested with this code:
```
app.setPath("appData", './test');
app.setPath("userData", './test');
```
* Electron version: 0.37.2
* Operating system: Windows 10

**Comment by zcbenz** [comment] 2016-03-15 11:38
This is a duplicate of #2668.

**Closed by zcbenz** 2016-03-15 11:38 UTC
