### ISSUE TITLE
Flash of white when window is shown

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#2172] opened 2015-07-09 16:05 UTC
When a window is shown it flashes white for a second before the content appears. This happens even if the window is transparent and frameless and has no content. Even if I show the window on loaded, dom ready or even using a timeout the white flash happens. So it's related to when the window is first shown that causes the flash.

I can replicate this issue on Windows 7 and OS X Yosemite.

Here's an example of the code:

~~~
mainWindow.webContents.on('did-finish-load', function() {
    setTimeout(function(){
        mainWindow.show();
    }, 4000);
});
~~~

4 seconds after the app has received the onload event, the window will show and flash white (even though the webpage has no content and has its background set to transparent). It only happens for a second and then appears transparent after the flash.

Is it perhaps because the transparent effect is applied AFTER the window is made visible?

**Comment by carlosperate** [comment] 2015-07-09 16:20
Don't really have an answer for you, but these related issues might help you understand the issue: https://github.com/atom/electron/issues/1397, https://github.com/atom/electron/issues/1626, https://github.com/atom/electron/issues/1391

**Comment by iamdriz** [comment] 2015-07-09 16:31
According to @zcbenz in that first linked issue, it's because WebView is a browser plugin... So the solution would be make that plugin ALWAYS have a transparent background so it doesn't flash white. Is that possible?

**Comment by iamdriz** [comment] 2015-07-29 11:01
I've also seen this happen when the window is re-sized.

For example: `mainWindow.setSize(240, displays[0].bounds.height);`

If the window was 100 wide previously, the new window space flashes white and then goes transparent again.

Has there been any progress on this?

**Comment by frankhale** [comment] 2015-07-29 15:01
Related issue: https://github.com/atom/electron/issues/861

I'm working on the white background when first loading and white background when resizing issue. I'm not specifically looking into any transparency issues though. I've had some success but it's going to take me a while longer to get to something that isn't a complete hack. I'm tracking my progress in the issue linked above.

Basically what is going on here is that the content window is layered and some of the layers are hard coded with a white background. This is in libchromiumcontent rather than Electron. I envision that once this is fixed each individual developer creating an app will have to explicitly set the background color himself that he wants otherwise it'll still default white. This is different than CSS element background colors so a JS API will have to be created to do it once libchromiumcontent is patched. Although at first I am creating a new command line option to override the base background color since this is the easiest approach and allows me to focus on the problem exclusively.

**Comment by zcbenz** [comment] 2015-10-04 13:01
I'm unable to reproduce this on Windows an OS X anymore, seems to have been fixed by Chrome 44 or 45.

**Closed by zcbenz** 2015-10-04 13:01 UTC
Labels: bug

**Comment by SMLVG** [comment] 2020-06-02 00:08
Can reproduce it in Chrome 8x, Linux and Windows

**Comment by m4heshd** [comment] 2023-06-25 00:15
Sadly the flashbang issue is still there in v25.

**Comment by fcstr** [comment] 2024-09-12 11:05
Still an issue up until now

**Comment by araujoarthur0** [comment] 2025-01-29 22:23
Still a problem in 2025

**Comment by fcstr** [comment] 2025-01-30 00:38
Almost all windows electron apps have this problem. Try open document dialog from any app, massive white flashes. Also even some "native* windows apps like outlook and the start menu.
