### ISSUE TITLE
Error installing electron on Mac El Capitan

### ISSUE THREAD

**Issue by AleffSouza** [atom/electron#3151] opened 2015-10-20 00:54 UTC
d:
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@0.34.0 postinstall /usr/local/lib/node_modules/electron-prebuilt
> node install.js

Downloading electron-v0.34.0-darwin-x64.zip
[============================================>] 100.0% of 37.94 MB (250.83 kB/s)
/usr/local/lib/node_modules/electron-prebuilt/install.js:15
  throw err
        ^
Error: EACCES, rename '/usr/local/lib/node_modules/electron-prebuilt/electron-tmp-download-15050-1445301881243/electron-v0.34.0-darwin-x64.zip'
    at Error (native)
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "electron-prebuilt" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.34.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@0.34.0 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Aleff/npm-debug.log

**Comment by joshaber** [comment] 2015-10-20 00:57
Looks like it could be a permission problem caused by El Cap's System Integrity Protection.

**Comment by zcbenz** [comment] 2015-10-20 03:27
This is a duplicate of https://github.com/mafintosh/electron-prebuilt/issues/48.

**Closed by zcbenz** 2015-10-20 03:27 UTC
