### ISSUE TITLE
preload script does not work if webview's src is just a png file link

### ISSUE THREAD

**Issue by ppoo24** [atom/electron#4355] opened 2016-02-04 02:09 UTC
I built a browser-like app, every tab is made by webview tag, when the users click any anchor in tab pages, i listened to the 'new-window' event and then will create a new tab to perform that link, and i tried to make a menu for every tab page by "`preload script`", normal tab page works fine, but when showing a image (like png) link, the menu will not slide out.
BUT, if i opened the devtool of that webview (the one that it's menu not shown), the menu can be shown by right click!
here goes the capture:
![image](https://cloud.githubusercontent.com/assets/1631659/12803567/4d1df562-cb26-11e5-95f2-2e28f570fc8d.png)

And i was considered to not creating menus in "preload script", but found that there is no way to access the `webContents` of `webview` (my purpose is to use the `webContents.savePage` function to act as "Save As", and, if in "preload-script", it's easy to trigger `savePage` by `require('remote').getCurrentWebContents()`).

So, i'm stucked, any suggestions?

**Comment by xywz** [comment] 2016-02-04 08:27
Duplicate of #1117.

**Comment by ppoo24** [comment] 2016-02-04 08:32
@xywz yep, but i wonder if there is a way to access its `webContents` by `webview` tag it self?

**Comment by xywz** [comment] 2016-02-06 01:58
@ppoo24 there isn't.

**Comment by zcbenz** [comment] 2016-02-15 02:08
Closing as a duplicate of #1117.

**Closed by zcbenz** 2016-02-15 02:08 UTC
