### ISSUE TITLE
Frameless Windows are not draggable when dev tools are docked and open.

### ISSUE THREAD

**Issue by bbondy** [atom/electron#4780] opened 2016-03-13 12:45 UTC
Steps to reproduce:
i) Do this gist: https://gist.github.com/jviotti/aadc0ba1d5962cfe19cf but add `frame: false` to BrowserWindow
ii) Notice you can drag the Window by clicking and ragging on Hello World
iii) Go to View Toggle dev tools so the dev tools are opened.
iv) Try to drag again.

Actual results: 
The window drag in step iv) won't work anymore.

Expected results:
The dragging continues to work.

**Comment by zcbenz** [comment] 2016-03-13 12:59
This is a duplicate of #3647.

**Closed by zcbenz** 2016-03-13 12:59 UTC
