### ISSUE TITLE
calling autoUpdater.checkForUpdates crashes the app

### ISSUE THREAD

**Issue by romangetman** [atom/electron#4915] opened 2016-03-25 15:04 UTC
* Electron version: 0.37.2 & 0.35.5
* Operating system: OSX 10.11

Part of the stack trace:
Responsible:           Electron [25499]
User ID:               502

Date/Time:             2016-03-25 17:01:48.270 +0200
OS Version:            Mac OS X 10.11.4 (15E65)
Report Version:        11
Anonymous UUID:        2C6BD5A7-8763-4740-F4C9-9AAAE37693B8

Sleep/Wake UUID:       F49F40D7-B263-4D40-9100-769091599763

Time Awake Since Boot: 210000 seconds
Time Since Wake:       24000 seconds

System Integrity Protection: enabled

Crashed Thread:        28  com.apple.NSURLConnectionLoader

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber length]: unrecognized selector sent to instance 0x29a37'
terminating with uncaught exception of type NSException
abort() called

Is there any way to debug this? Calling `setFeedURL` seems to work fine.

**Comment by romangetman** [comment] 2016-03-25 15:44
Wow, after waisting half a day on this, I figured it out. https://github.com/atom/electron/issues/3067

**Comment by kevinsawicki** [comment] 2016-03-25 23:29
Closing this out as a duplicate of #3067

**Closed by kevinsawicki** 2016-03-25 23:29 UTC
