### ISSUE TITLE
Socket IO Server Timeout

### ISSUE THREAD

**Issue by HeathNaylor** [atom/electron#1996] opened 2015-06-17 07:29 UTC
Is Electron capable of hosting a socket IO web server? I am currently trying to connect to my local systems internal IP over my local network (using a port specified by the Socket.IO server javascript) and my connection is timing out.

**Comment by zcbenz** [comment] 2015-06-17 08:44
There is some issues creating socket server, closing as a duplicate of https://github.com/atom/electron/issues/1968.

**Closed by zcbenz** 2015-06-17 08:44 UTC

**Comment by HeathNaylor** [comment] 2015-06-17 15:17
For the record I got this fixed, I believe the solution was simple, will investigate later today and try to post an update.

**Comment by mmastrac** [comment] 2015-06-19 18:45
@HeathNaylor What did you end up doing to fix it?

**Comment by HeathNaylor** [comment] 2015-06-19 21:24
@mmastrac Honestly I don't even remember at this point. There has been way too much code in front of me this week. I believe it was a simple syntax error in starting the server or the connection logic within my Android app (using the Socket IO java lib). If someone runs across this in the future just know that Electron handles Socket IO just fine.
