### ISSUE TITLE
Error: Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by bpasero** [atom/electron#4850] opened 2016-03-19 10:45 UTC
* Electron version: 0.37.2
* Operating system: Windows 10

Trying to access the id property of a window from the renderer side, I am getting this error:

```
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (c:\GitDevelopment\monaco\.build\electron\resources\atom.asar\browser\objects-registry.js:44:28)
    at EventEmitter.<anonymous> (c:\GitDevelopment\monaco\.build\electron\resources\atom.asar\browser\rpc-server.js:337:31)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at EventEmitter.<anonymous> (c:\GitDevelopment\monaco\.build\electron\resources\atom.asar\browser\api\web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (c:\GitDevelopment\monaco\.build\electron\resources\atom.asar\renderer\api\remote.js:170:13)
    at descriptor.get [as id] (c:\GitDevelopment\monaco\.build\electron\resources\atom.asar\renderer\api\remote.js:118:16)
    at new ElectronWindow (file:///C:/GitDevelopment/monaco/out/vs/workbench/electron-browser/window.js:25:32)
```

**Comment by mitchhentges** [comment] 2016-03-19 11:28
I got you, bud :wink:
https://github.com/atom/electron/pull/4847

**Comment by bpasero** [comment] 2016-03-19 11:49
Cool that is fast :+1:

**Comment by zcbenz** [comment] 2016-03-27 03:17
This is a duplicate of #4733.

**Closed** 2016-03-27 03:17 UTC

**Comment by bpasero** [comment] 2016-03-28 17:43
@zcbenz do you need help for a repro or are we good?

**Comment by zcbenz** [comment] 2016-03-31 10:53
@bpasero It should have been fixed in v0.37.3/v0.36.12, but if you are still seeing it, a repo would be appreciated.

**Comment by bpasero** [comment] 2016-03-31 11:36
Ok I am waiting for a release with node.js 5.9.x to also verify the V8 crash :+1:

**Comment by bpasero** [comment] 2016-04-08 12:11
Looks good.
