### ISSUE TITLE
<webview> preload doesn't take path relative to app folder

### ISSUE THREAD

**Issue by frozeman** [atom/electron#1958] opened 2015-06-12 15:15 UTC
I if want to preload a file for a webview tag and just pass in `./myFile.js` to make it relative to the apps folder, i get the `Only "file:" protocol is supported in "preload" attribute.` error.
```html
<webview src="http://page.com" preload="./myFile.js"></webview>
```

If i use the `file://` protocol i can't pass in a path which is relative to the electron app folder. I tried `file://./myFile.js` and `file://myFile.js`

**Comment by frozeman** [comment] 2015-06-12 15:49
Why enhancement? Shouldn't this be default behaviour? In which case i would ever not want to load files from inside my app folder?

Also the webview docs state that example, which is not working, as described above: https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md#preload

**Comment by frozeman** [comment] 2015-06-12 15:57
The error is the following when using `preload="./myFile.js"`:
```js
Only "file:" protocol is supported in "preload" attribute.

PreloadAttribute.getValue @ /usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/lib/web-view/web-view-attributes.js:271
WebViewImpl.buildAttachParams @ /usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/lib/web-view/web-view.js:191
WebViewImpl.attachWindow @ /usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/lib/web-view/web-view.js:199
(anonymous function) @ /usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/lib/web-view/web-view.js:131
g @ events.js:257
emitOne @ events.js:77emit @ events.js:166
```

**Comment by frankhale** [comment] 2015-06-15 07:35
In my app I use a path just like you are using in my webview's preload tag and I don't see any errors. My path is relative to my app folder just like yours. What version of Electron are you using?

**Comment by frozeman** [comment] 2015-06-15 08:14
0.26.0
But i'm using a templating engine, so the HTML is created later on the fly and not at the initial load. (which should make a difference)

**Comment by zcbenz** [comment] 2015-06-16 02:15
The url in `preload` attribute is resolved in the same way with the `href` attribute of `<a>` tag, so if your app's main page is a remote page with protocols other than `file://`, the url in `preload` will have the same protocol with your page.

If you are actually loading webview in a local page with `file://` protocol, please send a reproducible example.

**Closed by zcbenz** 2015-06-16 02:15 UTC

**Comment by frozeman** [comment] 2015-06-16 07:45
I solved it now by providing an absolute path passing down the `__dirname` to the render process.

But you should update you example, as its misleading:
```html
<webview src="https://www.github.com/" preload="./test.js"></webview>
```
https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md#preload

**Comment by DavidWells** [comment] 2016-04-14 05:18
@frozeman how did you pass the __dirname into the render process? 

Thanks!

**Comment by mbaer3000** [comment] 2016-09-12 07:50
As for how to pass the __dirname down: attach it to the app (`electron.app.dirname = __dirname`) and then use Electron's remote to access it from the renderer app (`electron.remote.app.dirname`) and the use it in your templates or wherever you build the src attribute of the webview elements.

**Comment by marcelfalliere** [comment] 2017-02-18 10:45
This solution does not work with "modern" (if you permit me) dev tools like webpack and the like. Thus, it may work in a development environment but not a production one ... Passing `__dirname` may work but I don't think it's a good idea.

I have the same problem as OP, in a webpack-dev-server with vue.js environment. I'm struggling with paths every time. Such a pain.

Will update this after a solution has been found.

**Comment by marcelfalliere** [comment] 2017-02-18 10:57
So my `webview` has the `preload=file://./assets/webviewInjectedScript.js`. Without `file://`, electron cries me an error.

Opening the dev tools for the webview, and with a breakpoint at `module.js#455` (where the `MODULE_NOT_FOUND` error is thrown), the search path seems to be :

/Users/marcelfalliere/my_app_electron_vue/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/exports

After extracting `electron.asar` (with [this tool](https://github.com/electron/asar)), there's no such file `webviewInjectedScript.js` so no wonder it finds it. 

How can I tell electron to pack `webviewInjectedScript.js` in this asar file ?

This is a headache, friends.

**Comment by MarshallOfSound** [comment] 2017-02-18 11:00
@marcelfalliere `electron.asar` is internal Electron logic / JS, none of your files should go in there.

The reason your search path is looking there is because `./` is relative to the CWD, in this case a path inside `electron.asar`.  You need to use `__dirname` to locate the actual path of the current file.

Using `webpack` with Electron has many problems, a few of which can be solved by setting `electron` as the target for webpack.  Worth noting that IMO `webpack` is designed to solve problems that aren't present in Electron so the pairing doesn't make complete sense.

**Comment by marcelfalliere** [comment] 2017-02-18 11:36
@MarshallOfSound `webpack` in conjuction with `vue.js` framework is really useful, for me at least, in (a) the development process : I get sweat Hot Module Replacement and ES6/7 and (b) in the long run, a big app with both components-oriented and flux-style architecture is the best IMHO. I started with `nw.js` and `vanillajs` but oh boy. Anyway, maybe that is another debate. I've used [this bootstrap](https://github.com/SimulatedGREG/electron-vue) by the way (what do you think?).

Ok I will test with `__dirname` but I'll have to double check that it works when building the electron app.

...

So in dev, it seems to work 👍 

When building it does not ! The devtools targeted at the webview says : `Cannot find module '<absolutePathToApp>/MyApp.app/Contents/Resources/app.asar/dist/libs/webviewInjectedScript.js'`
Extracting the `app.asar`... there is a `dist` folder, but inside no `webviewInjectedScript.js`. Webpack builds one file for each process. My file should be somewhere in the `main.js` built file ... but oh boy. This can be fixed by a switch in the source code, testing if we are in production or development env. Maybe this needs simply an execption : do not build the `webviewInjectedScript.js` file inside a `main.js` file, so I can require it no problem ?... A headache I'm telling tou 😀 


I have another problem now (in dev), but that's for another issue. But In short :
- the renderer process make an IPC call
- the main process catches it
- still in the main, it call an IPC that is destined to the webview (using [this technique](http://ourcodeworld.com/articles/read/201/how-to-send-retrieve-information-and-manipulate-the-dom-from-a-webview-with-electron-framework))
- but nothing is received in the preload script.!

Thanks !

**Comment by fineline** [comment] 2017-04-20 13:02
@marcelfalliere I am trying the same setup as you with electron-vue but I couldn't get the __dirname approach to work. I think it could be because I'm on a Mac and the files cannot be referenced inside the asar. I put my preload.js in the app/dist folder and with __dirname concatenated into the webview preload attribute it looks like this:

<webview src="http://localhost:9080/page.html" 
preload="file:///Users/xxxxx/yyyyy/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/preload.js" 
tabindex="-1" guestinstance="2"></webview>

Is that similar to what you see in Electron dev tools when you look at your webview? Thanks.

**Comment by fineline** [comment] 2017-04-20 22:42
@marcelfalliere I changed my dev configuration to reference the file directly in its location in my source project and that approach works for me.

**Comment by rageandqq** [comment] 2017-05-26 02:44
@fineline How did you manage to do this - specifying the file directly, if it's being served via localhost?

**Comment by ArpitKumar2092** [comment] 2019-02-09 12:40
Some where i read preload attribute works like require()  so if u have your file in root directory 
for example 
resource/app/pre-load.js
then you can just pass
<webview id="foo" src="https://www.ourinfofeeds.in/" preload="pre-load.js" ></webview>  

and it will work 
tested on electron v3.1.1

**Comment by cuijiudai** [comment] 2020-05-15 14:52
not resolved at all

**Comment by cuijiudai** [comment] 2020-05-16 08:26
@fineline how did it ? how to change the configuration ?

> @marcelfalliere I changed my dev configuration to reference the file directly in its location in my source project and that approach works for me.

**Comment by giovanni-bertoncelli** [comment] 2024-09-02 08:24
For those using Vite: https://electron-vite.org/guide/dev#webview
