### ISSUE TITLE
AutoUpdater failing at localhost URLs

### ISSUE THREAD

**Issue by kumarharsh** [atom/electron#4615] opened 2016-02-26 10:16 UTC
* Electron version: 0.36.7
* Operating system: Windows 10 x64

I'm trying to setup my app's `autoUpdater` by creating an express server in the main process which listens on port `3001` on the local machine, and then when the server has started, I call the `autoUpdater.checkForUpdates('http://localhost:3001/update_check')` route.

Here is the relevant code snippet:

```js
expressApp.use('/update_check', nuts.router);
function setupAutoUpdater() {
  autoUpdater.setFeedURL(`http://localhost:3001/update_check`);
  try {
    autoUpdater.checkForUpdates();
    autoUpdater.on('error', function cb(err) {
      logger.error('update error', err.message, err.stack);
    });
    autoUpdater.on('checking-for-update', function cb() {
      logger.verbose('checking for update', arguments);
    });
    autoUpdater.on('update-available', function cb() {
      logger.verbose('update available', arguments);
    });
    autoUpdater.on('update-not-available', function cb() {
      logger.verbose('update not available', arguments);
    });
    autoUpdater.on('update-downloaded', function cb() {
      logger.info('update downloaded', arguments);
    });
  } catch (e) {
    logger.debug('AutoUpdater init error', e.message, e.stack);
  }
}

expressApp.listen(3001, () => {
  logger.debug('update server up');
  setupAutoUpdater();
});
```

This causes Squirrel.Windows to throw an error:

```
debug: update server up
debug: CHECKING FOR UPDATES   // (coming from the auto-updater.js file in atom/browser/api/lib)
debug: http://localhost:3001/update_check  // (coming from the auto-updater.js file in atom/browser/api/lib)

Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Download>d__5d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Download>d__5d.MoveNext()<---


... and a lot more...
```

Does Squirrel.Windows not work with localhost URLs? Because I've seen some issues here which have localhost set as their update URLs. Or is it because of not having my app code-signed yet. If it's the latter, I think something should be added in the docs about this, where it was [removed earlier](https://github.com/atom/electron/commit/88b05cff3e21627fcf0ed1a7223cf325f68cd48a#diff-b15081258fdf3b454b01669d0913934bL11)

**Comment by zcbenz** [comment] 2016-02-26 14:16
The error is `The remote server returned an error: (404) Not Found`, you can log the requests in your express app and check which URL is going wrong. Also notice that the server requirement of `Squirrel.Windows` is a bit different from `Squirrel.Mac`.

**Comment by kumarharsh** [comment] 2016-02-27 17:51
The URL itself is working, which I tested by sending a curl request via terminal which starts the download for the new version.

**Comment by paulcbetts** [comment] 2016-02-27 18:07
On Windows, you don't need to set up a localhost server, just pass in a path to your update folder instead of a URL

**Comment by kumarharsh** [comment] 2016-02-27 21:36
Actually, in my usecase, I think I need a server... 

* I am uploading the artifacts (RELEASES, .nupkg, .exe) on Github.
* AutoUpdater does not have an interface to Github, so I used a third-party server called [nuts](https://github.com/gitbookio/nuts) to provide my app with the requested asset URL to download. Now I need to run this server somewhere, so I thought maybe localhost *can* work.
* When this failed, I tried with a small go server.
* In both cases, `checkForUpdates` fails even before it pings the `/update_check` route.

**Comment by baconface** [comment] 2016-02-27 21:55
You are needing a server to download from a GIT server so it can be downloaded onto a client? I am having difficulty figuring out what you are trying to do. It just doesn't sound like very good use of resources. Especially if you are pulling from Github all you need is to download straight from their HTTP interface.

**Comment by baconface** [comment] 2016-02-27 22:00
It looks like the idea of Nuts is to proxy file downloads from PRIVATE repos. Nuts server does not sit in your application but runs on it's own. Then your application's auto updater checks that server and downloads through it as a proxy. So it doesn't seem like you are using this for it's intended design. It isn't supposed to fetch updates from itself.

**Comment by paulcbetts** [comment] 2016-02-27 22:18
> Short of hosting a separate server, is there anyway I can make this work?

Download RELEASES and the NuGet files to a temporary directory using any means you want, then point AutoUpdater to that directory

**Comment by kumarharsh** [comment] 2016-02-27 22:33
@baconface there is a nuts-serve npm package which can be used in existing express servers.

**Comment by baconface** [comment] 2016-02-27 23:30
Exactly, that is meant to be ran on it's own. And your Electron app talks to it. Not it be embedded in your Electron app. Otherwise what is the point of all that complication and just have the application download directly from the repo.

**Comment by zcbenz** [comment] 2016-02-28 03:20
Closing since it is not a bug of Electron.

**Closed by zcbenz** 2016-02-28 03:20 UTC

**Comment by SamvelRaja** [comment] 2016-05-09 13:54
@kumarharsh  you still facing the problem. This goes for me when i created the next update with a delta update

**Comment by dpatra** [comment] 2016-06-16 11:46
I was getting the same errors with/without running a server. Since its the only place this issue is discussed, I am posting the fix here.

I fixed it by adding Mime types to the IIS

```
<mimeMap fileExtension="." mimeType="text/plain" />
<mimeMap fileExtension=".nupkg" mimeType="application/octet-stream" />
```

The full web.config in my case is something like the following

```
<?xml version="1.0" encoding="UTF-8"?>

<configuration>
	<system.webServer>
		<security>
			<requestFiltering allowDoubleEscaping="True"/>
		</security>
	</system.webServer>
    <system.webServer>
        <directoryBrowse enabled="true" />
		<staticContent>
             <mimeMap fileExtension="." mimeType="text/plain" />
			 <mimeMap fileExtension=".nupkg" mimeType="application/octet-stream" />
         </staticContent>
    </system.webServer>
</configuration>
```

Hope this helps...

**Comment by mkinawy** [comment] 2016-11-10 16:39
@dpatra you saved me!!! thank you very muc

**Comment by manpreetrsystems** [comment] 2017-07-26 08:12
@dpatra  where I can find my web.config?
