### ISSUE TITLE
Titlebar is not resizable on frameless window

### ISSUE THREAD

**Issue by Algram** [atom/electron#4139] opened 2016-01-17 17:32 UTC
Hello,

I have found that when I use the `frame: false` option and then create a custom titlebar with window control buttons I cannot resize the window on the top-side.
This might happen because you have to set the titlebar to be draggable with `-webkit-app-region: no-drag;`.

I am using electron-version v0.36.2 on Fedora 23 with Gnome-Shell.

Does anyone else experience this problem?

**Comment by etiktin** [comment] 2016-01-18 01:37
To set your custom title-bar to drag-able, you need to use `-webkit-app-region: drag;`, not `-webkit-app-region: no-drag;`.
Don't know about Linux, but it works fine on Windows.

**Comment by zcbenz** [comment] 2016-01-18 07:36
This is a duplicate of #3022.

**Closed by zcbenz** 2016-01-18 07:36 UTC
