### ISSUE TITLE
session.setProxy Authentication

### ISSUE THREAD

**Issue by TomAshley303** [atom/electron#4858] opened 2016-03-20 03:17 UTC
* Electron version: 0.37.2
* Operating system: Linux x64 (Or any)

The session.setProxy doesn't provide any example for proxy authentication. Is it possible? If so can we get an example. If not can we get authentication?

**Comment by deepak1556** [comment] 2016-03-20 14:10
You can use the [app#login](https://github.com/atom/electron/blob/master/docs/api/app.md#event-login) event to achieve it.

**Comment by kevinsawicki** [comment] 2016-03-21 21:32
Thanks @deepak1556 for the answer, closing this out.

**Closed by kevinsawicki** 2016-03-21 21:32 UTC
Labels: question

**Comment by georgiosd** [comment] 2016-11-26 12:23
I'm not getting the event triggered - any ideas?

**Comment by gch1p** [comment] 2016-12-27 16:58
I can confirm that the `login` event doesn't get triggered when using proxy with authentication.

**Comment by georgiosd** [comment] 2016-12-27 17:00
@gch1p I was able to get it working by listening to the app's `login` event and doing `event.preventDefault()`

**Comment by gch1p** [comment] 2016-12-27 18:41
@georgiosd can you provide an example app? I can't get it working. This is my code (in the main process):
```
    app.on('login', (event, webContents, request, authInfo, callback) => {
      console.log('login event')
      event.preventDefault()
      callback(proxyOpts.username, proxyOpts.password)
    })
```
No log message is printed and I get these errors in devTools (for <img>s):
`407 (Proxy Authentication Required)`

Or this is not supposed to work with `<img>`s?

**Comment by georgiosd** [comment] 2016-12-27 19:02
OK, this is what I got:
For the WebBrowser instances:

```
this.browser.webContents.session.setProxy({
                proxyRules: this.proxyUrl,
                pacScript: undefined,
                proxyBypassRules: 'localhost'
            }, () => {
                this.browser.loadURL(url);
            });
```

```
private onLogin(event: Event,
            request: Electron.LoginRequest,
            authInfo: Electron.LoginAuthInfo,
            callback: (username: string, password: string) => void): void {
                callback(agentUsername, this.proxyPassword);
                event.preventDefault();
        }
```

Then on app:
```
app.on('login', (event, webContents, request, authInfo, callback) => {
  event.preventDefault()
})
```

**Comment by gch1p** [comment] 2016-12-27 19:24
@georgiosd 
```
private onLogin(event: Event,
            request: Electron.LoginRequest,
            authInfo: Electron.LoginAuthInfo,
            callback: (username: string, password: string) => void): void {
                callback(agentUsername, this.proxyPassword);
                event.preventDefault();
        }

```
— this doesn't look like native JavaScript Electron API, what language/framework/anything this is?

**Comment by georgiosd** [comment] 2016-12-27 19:25
It's Typescript - so it's the same as JS but with type annotations - at least this part @gch1p

**Comment by gch1p** [comment] 2016-12-27 19:33
Okay, then what is `WebBrowser` and `onLogin` method? Electron has `BrowserWindow`, `WebContents` but no `WebBrowser`, this looks like some wrapper around Electron's API, can you give me a link or something, where I can explore how this `WebBrowser` works.

**Comment by georgiosd** [comment] 2016-12-27 19:35
@gch1p my bad, I meant `BrowserWindow` - it's just a typo, no wrappers.

**Comment by gch1p** [comment] 2016-12-27 19:39
@georgiosd when (from where) the `onLogin` method is called? I mean, definitely not from here:
```
app.on('login', (event, webContents, request, authInfo, callback) => {
  event.preventDefault()
})
```

**Comment by georgiosd** [comment] 2016-12-27 19:51
It's the handler for the `WebContents` `login` event:

```
contents.on('login', this.onLogin.bind(this));
```

**Comment by BFitzpatrick-Monotype** [comment] 2018-09-13 18:37
When I enable the proxy server with authentication, it works fine, unless the proxy authentication credentials are wrong (they are supplied by the user). In that case, this callback is called repeatedly:

`mainWindow.webContents.on('login', onWindowAuthLogin.bind(this));`

When I try to disable the proxy by doing this:

`mainWindow.webContents.session.setProxy({ proxyRules: '' }`

The webContents login callback is never fired again.  I cannot remove and re-add the app and webContents login events because they can only be added once.

My questions are:
1. If the authentication credentials are wrong, what is the expected behavior, and how do I prevent the callback from looping.
2. Am I unsetting the proxy correctly?
