### ISSUE TITLE
Uncaught Error: UnknownSystemError: Unknown system error, uv_pipe_open

### ISSUE THREAD

**Issue by tomashanacek** [atom/electron#1647] opened 2015-05-11 14:07 UTC
**Electron Version:** 0.25.3
**System:** Mac OS X 10.9.5

Steps to reproduce (video):
https://www.dropbox.com/s/i6zojbf5dfwrhhf/electron-bug.mov?dl=1

Repo:
https://github.com/tomashanacek/electron-bug

**Comment by zcbenz** [comment] 2015-05-20 05:14
The UnknownSystemError means something between OS X and Electron has interrupted the system call, it could be virus scanner or firewall software.

**Comment by tomashanacek** [comment] 2015-05-20 08:28
Hi, I don't use virus scanner or firewall software.
Problem starts with electron 0.22.0 (Upgrade to Chrome 41)

**Comment by Trixt0r** [comment] 2015-05-20 15:09
Getting this error as well on OS X Mavericks.
I have no virus scanners or firewalls installed.

**Comment by Granze** [comment] 2015-05-27 08:49
Same error here on OS X 10.9.4.
Runs fine on Ubuntu 15.04

**Comment by tomashanacek** [comment] 2015-05-29 14:29
@zcbenz ping

**Comment by petrbrzek** [comment] 2015-06-01 13:01
+1

**Comment by Trixt0r** [comment] 2015-06-09 10:05
Seems like this happens for me if if execute a child process from the renderer thread. Executing it from the browser process still raises the error, but can be ignored somehow...

**Comment by joshwnj** [comment] 2015-06-29 02:16
I'm getting this too. @tomashanacek did you come across any solution yet?

**Comment by joshwnj** [comment] 2015-07-02 03:46
In my case, we were using es6 in the webview via `require( "babel/register" )`.  After transpiling back to es5 at build and removing the `require( "babel/register" )` I no longer see the `uv_pipe_open` error and everything seems to work fine!

So I'm not sure exactly what in babel is causing the error but at least there is an easy way to sidestep it in this case.

**Comment by ZECTBynmo** [comment] 2015-07-23 19:25
+1

**Comment by nathansobo** [comment] 2015-07-30 01:22
I'm seeing this error when something tries to access the `process.stdout` property. It seems like node is attempting to create the stream with the file descriptor `1` and fails. In my case it's mocha attempting to see if we have a stdout and if it's a TTY.

**Comment by tdicola** [comment] 2015-08-28 20:34
Was this closed in error, or can someone provide an english explanation for the fix that closed this issue?  I'm hitting this problem with electron 0.30.4 on OSX Mavericks.  I'm using babel/register like joshwnj mentions so that's probably the issue, but this definitely seems like a valid issue or something broken in electron.

**Comment by nathansobo** [comment] 2015-08-28 20:54
@tdicola In my case something was trying to access `process.stdout`, which isn't currently accessible in Electron. @zcbenz I wonder if it makes sense to guard against this case in some way by directing `process.stdout` to the console?

**Comment by zcbenz** [comment] 2015-08-29 08:22
I'm reopening this since people are seeing this for various reasons.

@nathansobo Were you using OS X 10.9? The process.stdout is guarded under Windows, but seeing it on OS X is definitely not normal. I'm wondering whether it is a bug of OS X 10.9.

**Comment by nathansobo** [comment] 2015-08-29 14:11
I was on 10.8 when I saw it but have since upgraded. I can try to reproduce on 10.9.

**Comment by bpasero** [comment] 2015-08-30 11:34
@zcbenz I am on 10.10.5 and as mentioned before already, I start to see this error starting with electron 0.31.0 and 0.31.1. I tried today again many hours to find a reproducible scenario, but failed. I can make this error show up as soon as I cp.fork() a JS file from within a VS Code renderer window with the following code:

```javascript
var foo = typeof console;

process.on("message", function() {

});
```

Produces:

Error: UnknownSystemError: Unknown system error, uv_pipe_open

Somehow it is already sufficient to access the console property and my forked process blows up. I can not make this happen from a bare electron app though.

Interestingly, I still see this error when my code on the renderer side is as simple as this:

```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>Visual Studio Code</title>

		<!-- Helpers -->
		<script type="text/javascript">
			var cp = require('child_process');

			var res = cp.fork('/path to JS file');
			res.on('exit', function() {
				console.log('exit')
			})
		</script>
	</head>
	<body>
	</body>
</html>
```

This makes me wonder if anything on the main side could possibly have an impact on this issue. Any pointers as to what could that be would be appreciated.

**Comment by bpasero** [comment] 2015-08-30 14:37
Ok I think I got something to reproduce with a bare electron app. The tricky part was to understand that the issue reproduces when you run electron from the command line and not by dragging the app into the electron default window.

**main.js**
```javascript
var app = require('app');  // Module to control application life.
var BrowserWindow = require('browser-window');  // Module to create native browser window.
var cp = require('child_process');

// Report crashes to our server.
require('crash-reporter').start();

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the javascript object is GCed.
var amainWindow = null;

// Quit when all windows are closed.
app.on('window-all-closed', function() {
  if (process.platform != 'darwin')
    app.quit();
});

// This method will be called when Eolectron has done everything
// initialization and ready for creating browser windows.
app.on('ready', function() {

  function spawnSomething(cb) {
      var child = cp.spawn(process.env.SHELL, ['-ilc', 'env']);
     
      child.on('close', function (code, signal) {
          cb();
      });
  }

  spawnSomething(function() {
    
    // Create the browser window.
    mainWindow = new BrowserWindow({width: 800, height: 600, show: true});

    // and load the index.html of the app.
    mainWindow.loadUrl('file://' + __dirname + '/index.html');

    // Open the devtools.
    mainWindow.openDevTools();

    // Emitted when the window is closed.
    mainWindow.on('closed', function() {
      // Dereference the window object, usually you would store windows
      // in an array if your app supports multi windows, this is the time
      // when you should delete the corresponding element.
      mainWindow = null;
    });
  });
});
```

**index.html**
```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />

		<!-- Helpers -->
		<script type="text/javascript">
			var cp = require('child_process');

			var res = cp.fork(__dirname + '/script.js');
			res.on('exit', function() {
				console.log('exit')
			})
		</script>
	</head>
	<body class="monaco-shell vs-dark">
	</body>
</html>
```

**script.js**
```javascript
var foo = typeof console; // commentt his line to not have the forked process exit

process.on("message", function() {

});
```

Download electron 0.31.1 for Mac and run from command line:

.../Electron.app/Contents/MacOS/Electron ./atom-app

You will see "exit" printed immediately, although the forked app should not exit. Comment out the line with the "...typeof console" and you will not get the "exit" printed and everything works fine.

I see these issues only on Mac btw, not Windows or Linux. Somehow the spawn from the main side causes issues for the fork from the renderer side?

**Comment by tdicola** [comment] 2015-09-01 20:24
For what it's worth my issue was the same as joshwnj mentioned, using babel's register module in a web process causes the failure on OSX.  The workaround is to just transpile my ES6 & JSX data ahead of time to ES5 and remove the bable register usage.

**Comment by ssreekanth** [comment] 2015-09-02 04:09
I'm on 10.10.5 and started getting this same error after upgrading to electron 0.31.x.

[92344:0901/210453:INFO:CONSOLE(21157)] "Error: UnknownSystemError: Unknown system error, uv_pipe_open
    at Error (native)
    at new Socket (net.js:129:18)
    at createWritableStdioStream (node.js:601:18)
    at process.stdout (node.js:627:16)
    at /home/app/node_modules/chalk/node_modules/supports-color/index.js:29:13
    at Object.<anonymous> (/home/app/node_modules/chalk/node_modules/supports-color/index.js:50:3)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)", source: file:///home/app/gui/bower_components/ionic/release/js/ionic.bundle.js (21157)

**Comment by bpasero** [comment] 2015-09-02 13:16
@zcbenz ping. would be great to get some reply on the little repro I did. we typically adopt latest electron early in our milestones to get some good test coverage, but with this issue we are currently blocked on Mac.

**Comment by ssreekanth** [comment] 2015-09-02 18:38
@zcbenz Here is very simple code that causes the error. When you open the child window by clicking on the button in the main window, you would notice the error in the console logs.

However, if you remove all the console logs messages from main.js, then this error disappears. Looks like its definitely something to do with process.stdout(). Hope this helps..

**main.js**
```javascript
var app = require('app'),
    ipc = require('ipc'),
    BrowserWindow = require('browser-window');

var mainWindow = null;
    childWindow = null;

app.on('window-all-closed', function() {
    if (process.platform != 'darwin') {
        app.quit();
    }
});

app.on('ready', function() {
    mainWindow = new BrowserWindow({
        width: 480,
        height: 640,
    });
    mainWindow.loadUrl('file://' + __dirname + '/main.html');

    mainWindow.on('closed', function() {
        mainWindow = null;
    });

    ipc.on('child:open', function(event) {
        console.log('main.js :: ipc msg child:open received');
        openChildWindow();
    });

    openChildWindow = function() {
        if (!!childWindow) {
            console.log('main.js :: child window already open');
            childWindow.focus();
        } else {
            console.log('main.js :: create a new child window');
            childWindow = new BrowserWindow({
                width: 1080,
                height: 640,
            });
            childWindow.loadUrl('file://' + __dirname + '/child.html');

            childWindow.webContents.on('dom-ready', function() {
                console.log('main.js :: new child window loaded.');
                childWindow.show();
            });

            childWindow.on('closed', function() {
                console.log('main.js :: child window closed');
                childWindow = null;
            });
        }
    };
});
```

**main.html**
```html
<html>
<head>
    <title>Main window</title>
</head>
<body>
    <p>
    Sample text
    </p>
    <button onClick="openChild()"> open child window </button>

    <script>
        var ipc = require('ipc');
        var chalk = require('chalk');

        function openChild() {
            console.log('main :: open child button clicked. sending child:open ipc msg to main process');
            ipc.send('child:open');
        }
    </script>
</body>
</html>
```

**child.html**
```html
<html>
<head>
    <title>Child window</title>
</head>
<body>
    <p>Check console logs. You will see the error..</p>

    <script>
        var chalk = require('chalk');
    </script>
</body>
</html>
```

**Comment by paulcbetts** [comment] 2015-09-02 18:57
I've hopefully patched this in Chalk, which seems to be where most of these errors show up

**Comment by Qix-** [comment] 2015-09-02 18:59
For those of you seeing this with Chalk-enabled packages, have you tried passing `--no-color` to the electron process?

**Comment by ssreekanth** [comment] 2015-09-02 19:35
@paulcbetts I believe this is just a workaround. I would have preferred an actual fix in electron / iojs, so i could generate colored console logs, like i was with electron 0.30.5 or 0.30.6
![screen shot 2015-09-02 at 12 33 15 pm](https://cloud.githubusercontent.com/assets/1380334/9642051/e40c6f3a-516e-11e5-977c-2cc7f00828bd.png)

**Comment by ssreekanth** [comment] 2015-09-02 19:47
I use 'winston' module that also has the same issue. Unfortunately, that module uses a copy of support-colors.js, instead of declaring it as dependency in package.json. I'm not sure how many more modules have used a copy of support-colors.js. Hence, it is difficult to make workarounds in all those modules.

**Comment by zcbenz** [comment] 2015-09-03 07:55
@ssreekanth @bpasero Thanks for your demos, I can reproduce them and they really helped a lot.

**Comment by zcbenz** [comment] 2015-09-03 13:15
Seems that renderer process has inherited the stdout/stderr from parent process, and the type of stdout should be `TTY`, however Node.js mistakenly thought stdout's type was `pipe` in the renderer process, thus called wrong method for stdout.

**Comment by Qix-** [comment] 2015-09-03 14:46
@zcbenz is that a fix within electron, then?

**Comment by ssreekanth** [comment] 2015-09-03 18:02
@zcbenz glad to know that the demo code helped you in identifying the root cause of the issue.

Once a fix is provided in electron for this issue, we should revert the [workaround](https://github.com/chalk/supports-color/issues/30) made by @paulcbetts in 'supports-color' module.

**Comment by paulcbetts** [comment] 2015-09-03 18:44
@ssreekanth We can update it to only disable color in the renderer, something like:

```js
if (process.type === 'renderer') return 0
```

**Comment by Qix-** [comment] 2015-09-03 18:52
`process.type` isn't standard, and I'd be reluctant to keep the workaround in in the event a fix is made.

**Comment by ssreekanth** [comment] 2015-09-03 19:49
@paulcbetts, I would not keep the workaround either. Unless it is really an issue with supports-color, we should not make any change in there. If the issue is introduced in X module and not in chalk/supports-color, then it should be fixed in that particular X module. We should be glad that this workaround wasn't there earlier, otherwise we would have never unearthed this particular issue easily.

**Comment by paulcbetts** [comment] 2015-09-03 21:18
> process.type isn't standard, and I'd be reluctant to keep the workaround in in the event a fix is made.

Well I mean, that's the idea - you're using it both to detect the presence of Electron, and whether you're in the Renderer process (i.e. where your console.log statements are ideally going to Devtools)

**Comment by Qix-** [comment] 2015-09-03 21:38
I'm still sketchy about a permanent workaround for this on Chalk's end. I agree it probably hits most of those using ANSI styles but at the same time it's not something that really belongs in chalk.

That being said, it appears the problem is being narrowed down on electron's end. :+1:

**Comment by paulcbetts** [comment] 2015-09-03 22:10
> I'm still sketchy about a permanent workaround for this on Chalk's end. I agree it probably hits most of those using ANSI styles but at the same time it's not something that really belongs in chalk.

I mean, at the end of the day, Electron is a special case for writing terminal output, so it's worth considering handling that case explicitly. While we definitely want to at minimum make sure it's not taking down Electron instances, it'd be cool for Chalk to do stuff like write styled output to DevTools a-la https://plus.google.com/+AddyOsmani/posts/TanDFKEN9Kn

**Comment by Qix-** [comment] 2015-09-04 01:41
Keep in mind chalk isn't necessarily the place for that kind of stuff, though.

**Closed** 2015-09-07 15:02 UTC
Labels: bug, osx

**Comment by Qix-** [comment] 2015-09-07 16:50
@zcbenz was this resolved on Electron's side?

**Comment by zcbenz** [comment] 2015-09-08 05:20
@Qix- Yeah.

**Comment by Qix-** [comment] 2015-09-08 05:36
@sindresorhus are we go for removing the workaround from our end?

**Comment by sindresorhus** [comment] 2015-09-08 05:38
@Qix- I think the check is still valid though, as Electron users wouldn't want colors.

**Comment by etiktin** [comment] 2015-09-08 09:17
According to [this](https://github.com/atom/electron/issues/1647#issuecomment-137222279), Electron did support color output in previous versions (e.g. v0.30.5). If that's true, then I think the work around in `supports-color` should be removed.

**Comment by Qix-** [comment] 2015-09-08 14:48
I would have to agree. Can someone from the Electron team confirm? I don't know enough about it.

**Comment by ssreekanth** [comment] 2015-09-08 19:05
Now that Electron fixed this issue, we should remove the workaround from *supports-color*
