### ISSUE TITLE
dialog.showMessageBox without parameters throws error about buttons

### ISSUE THREAD

**Issue by adam-lynch** [atom/electron#4072] opened 2016-01-12 23:06 UTC
The [docs](http://electron.atom.io/docs/v0.36.0/api/dialog/) say the params are optional. Not sure if it's just that the docs are wrong or not.

**Comment by adam-lynch** [comment] 2016-01-12 23:06
Forgot the screenshot;

<img width="435" alt="screen shot 2016-01-12 at 23 05 18" src="https://cloud.githubusercontent.com/assets/1427241/12279778/221eb7b8-b981-11e5-93c9-f3dcfb0a6467.png">

**Comment by adam-lynch** [comment] 2016-01-12 23:10
Hmmm still doesn't work with `dialog.showMessageBox(BrowserWindow, {buttons: ['hello']}, function(){});` or `dialog.showMessageBox(BrowserWindow, {Buttons: ['hello']}, function(){});`. 

Also, is the module only usable in the main process?

**Comment by adam-lynch** [comment] 2016-01-12 23:14
Ok, `dialog.showMessageBox({buttons: ['hello']});` works.

**Comment by zcbenz** [comment] 2016-01-13 01:48
It is a mistake that the docs says `options` is optional, I'll fix it.

**Comment by zcbenz** [comment] 2016-01-13 01:49
Actually the docs had been fixed by afedce0, but the docs site is not updated for it yet.

**Closed by zcbenz** 2016-01-13 01:49 UTC

**Comment by adam-lynch** [comment] 2016-01-13 10:08
@zcbenz ok thanks. But I guess now it should say that `title` is optional? For example.

**Comment by adam-lynch** [comment] 2016-01-13 10:09
Also, that doesn't explain why `dialog.showMessageBox({buttons: ['hello']})` works but `dialog.showMessageBox(BrowserWindow, {buttons: ['hello']}, function(){});` doesn't.

**Comment by adam-lynch** [comment] 2016-01-13 10:12
Nevermind, just saw https://github.com/atom/electron/issues/4076#issuecomment-171129374. Thanks

**Comment by kuakman** [comment] 2016-08-18 20:23
Hi, this doesn't seems to work for me with Electron 1.3.3 running on Mac OSx

`Electron.dialog.showMessageBox([instance of BrowserWindow], {
    type: 'none',
    title: 'My Title',
    buttons: ['Hello'],
    defaultId: 0,
    noLink: true
}, function() { });`

I get the `Buttons must be an array` error.

In the other hand, the only way to avoid that exception is to specify the type to other than `none`.
But that's not what I want. Since it will open my browser window *AND* the native dialog, both at the same time (?). That seems a bug to me unless I'm missing something with the documentation or the way it's supposed to work.

An additional comment is that, the api is not consistent.
The way how I understand it, should be

First, if you pass a BrowserWindow instance, the options are not relevant anymore, since the intention here is that the user wants to build up the dialog all by their own by subclassing Browser Window (Class, buttons, titles, window size, actions and such should be up to the developer).

Second, if it's something quick and you want to use the native styles like ('question', 'info' and all those presets) you can pass the options the way the API was already defined. All good with that.

with a simple check (pseudo code):

`if(!([firstparam] instanceof BrowserWindow) {
  // use the BrowserWindow and don't validate the options
} else if({
  // Use the presets and run validations agains the options "thingy" and trigger native dialogs they way how they work now.
} else {
   // maybe error or try different cases ?? Not sure
}

Anyways, may I have some clarification how this suppose to work? Maybe this could help improve the docs for other people in the community.

Thanks in advance!

**Comment by kuakman** [comment] 2016-08-18 21:50
Ah my bad! never mind about the bug.
Found the answer at the bottom of the [dialog docs](http://electron.atom.io/docs/api/dialog/).
So, the browserWindow param is to "attach" the dialog to the instance specified as far as I understood.

Anyways, It would be nice to add documentation inline right next to the ```browserWindow - Optional``` param to explain what it does. (I had to go to the bottom of the page to figure it out).

I have seen the discussion about supporting customization of dialogs [here](https://github.com/electron/electron/issues/472), it's kinda of related to what I was looking for but it confirmed that we need to subclass from BrowserWindow to customize them.

Alright, Thanks again!
