### ISSUE TITLE
react-devtools addDevToolsExtension failed

### ISSUE THREAD

**Issue by chentsulin** [atom/electron#1733] opened 2015-05-20 04:17 UTC
I just follow  [DevTools extension](https://github.com/atom/electron/blob/master/docs/tutorial/devtools-extension.md#devtools-extension) document, and when I called below on my electron chrome console

```js
require('remote').require('browser-window').addDevToolsExtension('/some-directory/react-devtools')
// return "React Developer Tools"
```

But I got a TypeError log on terminal:

```
[1438:0520/120118:ERROR:CONSOLE(74)] "Uncaught TypeError: Cannot read property 'getURL' of undefined", source: chrome-extension://extension-1/agents/ReactInspectorAgent.js (74)
```

I went through `ReactInspectorAgent.js` [line 74](https://github.com/facebook/react-devtools/blob/master/agents/ReactInspectorAgent.js#L74):

```js
// agents/ReactInspectorAgent.js
var runtimeURL = chrome.extension.getURL(fileName);
```

It looks like `chrome.extension` is `undefined`, how this could be happened?

- Electron 0.25.1
- react-devtools 0.13.1

**Comment by zcbenz** [comment] 2015-05-20 09:27
This is a duplicate of #1644.

**Closed by zcbenz** 2015-05-20 09:27 UTC
