### ISSUE TITLE
-webkit-app-region: drag not working after hiding element on top of it with CSS transform

### ISSUE THREAD

**Issue by DerNivel** [atom/electron#4237] opened 2016-01-26 15:01 UTC
I'm hiding a button in my titlebar (`-webkit-app-region: drag`) with a CSS transform (for animation). The button has `-webkit-app-region: no-drag` for being clickable.
The issue is that after hiding the button the window isn't movable in the first try in that specific area of the titlebar.

Steps to reproduce with this gist: https://gist.github.com/DerNivel/0b850b89c6e510486f13
* Click on the button in the titlebar (button hides with CSS transform)
* Try to move the window in the area where the button was before hiding (The window isn't movable)
* Release the mouse and try again (Now it is movable)

OS: Windows 10 Version 1511

**Comment by zcbenz** [comment] 2016-01-27 11:07
The `-webkit-app-region` attribute doesn't work very well with complex CSS rules, and I can reproduce the same thing in Chrome extension. I suggest making an Chrome app that can reproduce this problem, and then report it to [Chromium's issues list](https://crbug.com).

I'm closing this since it is a bug of Chromium/blink, and we are not able to fix it on Electron's side.

**Closed by zcbenz** 2016-01-27 11:07 UTC
