### ISSUE TITLE
remote module may not expose function object's props

### ISSUE THREAD

**Issue by berlysia** [atom/electron#4957] opened 2016-03-30 20:25 UTC
* Electron version: v0.37.3
* Operating system: OSX 10.10.5

reproduce:

```js
function someFunc() {
  return 'foo';
}
someFunc.someProp = 'bar';

class Klass {
  static someStaticFunc(num) {
    return num * 2;
  }
}
Klass.someStaticValue = 123;

module.exports = {
  someFunc,
  Klass,
};
```

```js
const lib = require('remote').require('./lib');
lib.Klass.someStaticFunc; // undefined
lib.Klass.someStaticValue; // undefined
lib.someFunc(); // 'foo'
lib.someFunc.someProp; // undefined
```

not reproduce:

```js
...
module.exports = Klass;
```

```js
const Klass = require('remote').require('./Klass');
Klass.someStaticFunc; // function(num){ ... }
Klass.someStaticFunc(42); // 84
Klass.someStaticValue; // 123
```

not reproduce:

```js
...
module.exports = someFunc;
```

```js
const someFunc = require('remote').require('./Func');
someFunc.someProp; // 'bar'
```

**Comment by felixrieseberg** [comment] 2016-03-30 20:40
Hey, thanks for reporting! This is actually not a bug, but expected behavior - you're dealing with two different threads and not all objects make it across the inter-process communication bridge. In fact, only enumerable objects make it through.

You can find more information in the docs and here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties

I'm closing this in the meantime, but feel free to reopen if I misunderstood you and this is actually a bug.

**Closed by felixrieseberg** 2016-03-30 20:40 UTC

**Comment by berlysia** [comment] 2016-03-31 07:36
Hi @felixrieseberg , thanks for reaction.

I know that the remote module exposes enumerable props only, and now changed.
The remote module currently works without enumerability.
https://github.com/atom/electron/blob/master/lib/browser/rpc-server.js#L19

These codes related to the problem that ES6 class's methods are non-enumerable. see #4066.

In addition, exactly ES6 class's method is non-enumerable. But traditional-notated class's method is enumerable, also reproduce.


Back to this issue.
new simple example:

```js
class Klass{
  static func(){return 123}
}
Klass.prop = 345;
// and access Klass.func/prop in renderer via remote module

module.exports = { Klass }; // reproduce
// require('remote').require('./lib').Klass.prop
// > undefined

module.exports = Klass; // not reproduce
module.exports = [ Klass ] // not reproduce

module.exports = [ { Klass } ] // reproduce
// require('remote').require('./lib')[0].Klass.prop
// > undefined
```

Instantiation works. Accessing to property does not work.

According to this, if a callable object(function and consturctor) is in the object and the callable object has properties, the properties are not exposed.

**Comment by seanchas116** [comment] 2016-08-14 12:17
Hi, I'm facing the same problem.

> if a callable object(function and consturctor) is in the object and the callable object has properties, the properties are not exposed.

I think this weird behavior is obviously a bug.
