### ISSUE TITLE
Linux showMessageBox message gets selected (or focused)

### ISSUE THREAD

**Issue by webarchymeta** [atom/electron#3087] opened 2015-10-14 21:57 UTC
On a Ubuntu 14.04 64 bit box, the message inside of the popup window created by `showMessageBox` is completely selected, creating a unexpected experience. This could be common on other linux boxes.

**Comment by zcbenz** [comment] 2015-10-15 02:51
Can you provide a screenshot?

**Comment by webarchymeta** [comment] 2015-10-15 05:57
Sure, the following is
![screenshot](http://www.yiwg.net/media/images/screenshot.png "The screenshot")
(sorry, I can't upload an image inside my network environment, so a link is posted)

The dialog is invoked inside a render process via
```
var remote = require('remote');;
var dialog = remote.require('dialog');
dialog.showMessageBox({
    type: 'info',
    buttons: [],
    title: 'info',
    message: msg
});
```
After click the shadowed text, it becomes normal

**Comment by etiktin** [comment] 2015-10-15 14:19
Do you get other results when you use a buttons array that is not empty? How is the user supposed to close the dialog with no buttons?

**Comment by webarchymeta** [comment] 2015-10-15 20:17
OK, I see what you mean, the text is treated as the first button here. The reason for using no button is for the simplicity and lightness of a notification/info box since user do have the red cross on top to close it. I know this could be a system behavior (for e.g., on Windows it is fine on this) that is not under the control of Electron, but I do hope this could be done on inside Electron for Linux as well. If not possible, I am going to add a button and close the present request later ...

**Comment by etiktin** [comment] 2015-10-15 21:02
Oh, I thought that red button on the border was the border icon and not an exit button (on Windows the exit button is usually on the right).

Can you confirm that if you set `buttons = ["ok"]` the text is not selected?

**Comment by webarchymeta** [comment] 2015-10-15 23:11
Yes, after adding a button the focus is shifted to the added button and the text is normal.

**Comment by zcbenz** [comment] 2016-01-07 07:23
I'm closing this as won't fix since this is a bug or expected behavior of GTK+, if you really care about this, I would suggest reporting this to GTK+'s project instead.

**Closed by zcbenz** 2016-01-07 07:23 UTC
Labels: bug, linux
