### ISSUE TITLE
window.close in WebView no longer fires close event

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#2149] opened 2015-07-07 19:18 UTC
This worked in 0.28.3 but no longer works in 0.29.2 on Ubuntu where I tested it at least, working on a test for it at the moment:

1. Create a WebView tag, load any page
1. `$0.addEventListener('close', function() { console.log("It closed!") });`
1. `$0.openDevTools()`
1. In dev tools: `window.close()`

**Comment by zcbenz** [comment] 2015-07-10 02:37
Sorry I accidentally renamed it to `closed` in some other pull request, will change it back.

**Comment by paulcbetts** [comment] 2015-07-13 20:32
Still seeing this even though it doesn't repro on a clean WebView - it seems related to navigation? In the app, we use it in the login page, so we'll navigate a bunch, POST a form, then get redirected to a page whose contents is just `<html><script>window.close()</script></html>`. That `window.close()` doesn't end up firing either `close` or `closed`. I'm going to try to get a better unit test going

**Comment by zcbenz** [comment] 2015-09-17 14:14
It is probably related to the bug that POST request would make the page have no node integration, since that bug had already been fixed, and I'm not able to reproduce this anymore, I'm closing this issue.

**Closed by zcbenz** 2015-09-17 14:14 UTC
Labels: bug, webview
