### ISSUE TITLE
Custom protocols don't seem to be invoked by relative/aboslute script tags, when protocol is missing

### ISSUE THREAD

**Issue by frozeman** [atom/electron#4145] opened 2016-01-18 12:53 UTC
I added my own custom protocol, which i create a BrowserWindow from using `mist://interface`:

```js
protocol.registerHttpProtocol('mist', function(request, callback) {

    var call = {
        url: (request.url.indexOf('mist://interface') !== -1) ? global.interfaceAppUrl + request.url.replace('mist://interface','') : '',
        method: request.method,
        referrer: request.referrer
    };

    console.log(call);

    callback(call);

}, function (error) {
  if (error)
    console.error('Failed to register protocol')
});
```

It loads the initial page fine, but none of the linked scripts seemed to be loaded later.
I also tried adding a script tag using javascript manually:

````js
var script = document.createElement('script');
script.type = 'text/javascript';
script.src = '/packages/meteor.js?19730f4ff059088b3f7f14c0672d155218a1802d4';    

document.getElementsByTagName('body')[0].appendChild(script);
```

But i can't see this protocoll handler beeing called and the js doesn't load and execute.

Hint: this seems to happen if the url, is relative or absolute and not contains the protocol.
Though by web standards, relative or absolute URLs should get the protocol of the current location.

**Comment by frozeman** [comment] 2016-01-18 12:54
So this script tag worked:
```js
var script = document.createElement('script');
script.type = 'text/javascript';
script.src = 'mist://interface/packages/meteor.js?19730f4ff059088b3f7f14c0672d155218a1802d4';    

document.getElementsByTagName('body')[0].appendChild(script);
```

**Comment by frozeman** [comment] 2016-01-19 13:42
@zcbenz any idea?

**Comment by zcbenz** [comment] 2016-01-19 20:12
Have you tried [registering it as standard scheme](http://electron.atom.io/docs/v0.36.4/api/protocol/#protocol-registerstandardschemes-schemes)?

**Comment by frozeman** [comment] 2016-01-22 12:44
Yes, just tried, same behaviour.
Also registering as a standard scheme shouldn't make a difference (logicall), as i might not want it to be a standard scheme.

So basically, relative urls aren't going through the custom protocol handler.

**Comment by zcbenz** [comment] 2016-01-22 20:12
This is a duplicate of #1747.

**Closed by zcbenz** 2016-01-22 20:12 UTC
