### ISSUE TITLE
Navigating between menu items with keyboard

### ISSUE THREAD

**Issue by joshas** [atom/electron#3952] opened 2015-12-29 19:29 UTC
In native applications you can navigate between adjacent menu items using left and right arrow keys. In Electron this is impossible. Only up/down navigation works to select items from current open menu.

Windows 7, 64-bit
Electron 0.36.2

**Comment by bengotow** [comment] 2015-12-29 21:12
This seems to be working for me on Mac OS X—is there any chance your app catches the left/right arrow key events?

**Comment by joshas** [comment] 2015-12-29 22:30
Tested with electron-quick-start - same issue. Could be platform specific. Same problem on Linux.

**Comment by zcbenz** [comment] 2015-12-31 03:02
This is a duplicate of #2504.

**Closed by zcbenz** 2015-12-31 03:02 UTC
