### ISSUE TITLE
fs.realpath fails for any file in the unpacked section of an ASAR archive

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#4610] opened 2016-02-26 02:34 UTC
* Electron version: 0.36.1
* Operating system: OS X

Calling `fs.realpath` on a file which is in the `app.asar.unpacked` folder will result in it throwing ENOENT, when the file should be there. `realpath` seems to work on files that _are_ in the archive, just not ones in the unpacked section.

**Comment by positlabs** [comment] 2016-02-29 19:10
I think the problem is that the asar.unpacked dir isn't included in the list of nodejs-searchable dirs. Maybe there is some way to configure this, but I found that editing the path works just as well. Kind of a pain, but it works.

`__dirname.replace('app.asar', 'app.asar.unpacked') + '/path/to/thing';`

**Comment by paulcbetts** [comment] 2016-02-29 20:24
Nope, even if you do the app.asar.unpacked lie, you'll still blow up

**Comment by kevinsawicki** [comment] 2016-03-07 23:31
Closing for now, could not reproduce and talked to @paulcbetts in slack about it. Will reopen if we can reproduce it in the future.

Added some specs for this case in #4711

**Closed by kevinsawicki** 2016-03-07 23:31 UTC
Labels: asar, beginner, bug
