### ISSUE TITLE
min-width/min-height behave wrongly on high DPI systems

### ISSUE THREAD

**Issue by Ivshti** [atom/electron#2153] opened 2015-07-08 10:50 UTC
On Windows 8.1, with a high DPI screen, min-width/min-height behave wrongly - the value is multiplied by the current DPI over standard DPI, resolving in higher actual values.

For example, when the min-width is set to 1000, the system has a resolution width 2560, but Electron renders as if the width of the screen is around 1330 (so that things do not appear to small), the actual window width based on min-width resolves in around 1500px, but the actual window comes up wider than the screen because the width is already re-calculated according to this.

The point is, min-width/min-height shouldn't be re-calculated according to DPI since  width/height of the window already are.

Labels: windows, bug

**Comment by paulcbetts** [comment] 2015-07-08 17:10
We've seen this too, min-width/min-height go bananas on High DPI

**Comment by Ivshti** [comment] 2015-08-05 18:45
This should be traceable - I already tried the electron repo but I cannot find it, I'm guessing it might be in another component like brightray or libchromiumcontent @paulcbetts

**Comment by zcbenz** [comment] 2015-08-26 08:59
This is a duplicate of #1806.

**Closed by zcbenz** 2015-08-26 08:59 UTC
Labels: bug, windows
