### ISSUE TITLE
Input restriction tooltips don't show up

### ISSUE THREAD

**Issue by Juribiyan** [atom/electron#3936] opened 2015-12-28 16:36 UTC
When a user enters invalid data in an input field which has some restriction (for example, `type="number"`) it prevents form from submitting (no event is fired) but there's no visual indication of what is wrong. Is it done on purpose or is it just a bug?

**Comment by zcbenz** [comment] 2015-12-29 03:14
This is a duplicate of #1043.

**Closed by zcbenz** 2015-12-29 03:14 UTC
