### ISSUE TITLE
transform:scale() doens't behave propertly on webview element

### ISSUE THREAD

**Issue by rokyed** [atom/electron#4737] opened 2016-03-10 12:28 UTC
Here's the example:
[http://imgur.com/j53FLmE](http://imgur.com/j53FLmE)

So I applied (e.g.):
```css
transform: scale(0.5);
```

The element scales propertly, but its content inside as you can see the body is the dotted outline of the document inside that webview.

The project: 
[https://github.com/rokyed/cocoChanelJS](https://github.com/rokyed/cocoChanelJS)

If more information needed, I will provide anything I will be asked concerning this project.

Thanks for the answers.

* Electron version: 0.36.10
* Operating system: Linux Mint

**Comment by zcbenz** [comment] 2016-03-10 12:33
This is a duplicate of #4562.

**Closed by zcbenz** 2016-03-10 12:33 UTC
