### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _RSA_generate_key

### ISSUE THREAD

**Issue by boxofrad** [atom/electron#1988] opened 2015-06-16 14:42 UTC
I'm having some issues using the [ursa](https://github.com/quartzjer/ursa) module on electron.

I installed the module using npm like so:

```
npm install --save ursa
```

Then rebuilt the native extensions for electron like so:

```
./node_modules/.bin/electron-rebuild
```

This seemed to exit immediately / not actually do anything, and when I ran the app I got the usual error message:

```
Error: Module version mismatch. Expected 44, got 14.
```

So I rebuild the native extension manually using node-gyp like so:

```
HOME=~/.electron-gyp node-gyp rebuild --target=0.28.1 --arch=ia64 --dist-url=https://atom.io/download/atom-shell
```

And I now get the following error message:

```
dyld: lazy symbol binding failed: Symbol not found: _RSA_generate_key
  Referenced from: /Users/daniel/work/kuddl/electron-client/node_modules/ursa/build/Release/ursaNative.node
  Expected in: dynamic lookup

dyld: Symbol not found: _RSA_generate_key
  Referenced from: /Users/daniel/work/kuddl/electron-client/node_modules/ursa/build/Release/ursaNative.node
  Expected in: dynamic lookup
```

Here's my code:

```javascript
var ursa = require('ursa');
var key = ursa.generatePrivateKey(2048, 65537);
```

I think this may be related to this issue: https://github.com/atom/electron/issues/1410

Version Numbers:

<table>
  <tr>
    <th>Electron Version</th>
    <td>v0.28.1</td>
  </tr>

  <tr>
    <th>Operating System</th>
    <td>Mac OSX 10.10.0</td>
  </tr>

  <tr>
    <th>ursa</th>
    <td>v0.8.5</td>
  </tr>
</table>

**Comment by zcbenz** [comment] 2015-06-17 03:41
Yeah it is a duplicate of #1410.

**Closed by zcbenz** 2015-06-17 03:41 UTC
