### ISSUE TITLE
console.log and .error are not complete in the log output

### ISSUE THREAD

**Issue by zaggino** [atom/electron#1567] opened 2015-05-04 03:34 UTC
following code
```
console.log("a", "b", "c");
```
shows `a b c` both in the browser and in node but in the log output of electron this is
```
[18220:0504/133340:INFO:CONSOLE(4)] "a", source: /Users/username/dev/test/app/preload.js (4)
```

Using `"electron-prebuilt": "0.25.2"`

**Comment by zcbenz** [comment] 2015-05-04 04:11
This is a duplicate of https://github.com/atom/electron/issues/1368.

**Closed by zcbenz** 2015-05-04 04:11 UTC
