### ISSUE TITLE
Chrome appears for frameless windows when resizing and on first load, and content is clipped

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#734] opened 2014-10-22 10:03 UTC
When using a frameless window you see the default Windows chrome on first load and then when resizing the window it occasionally bleeds through and causes parts of the content to be clipped when resizing quickly (normal user behaviour).

Is this a known bug? Or some sort of performance issue on my machine?

Here's a screenshot of the window chrome appearing as I enlarge the window:

![image](https://cloud.githubusercontent.com/assets/801252/4734446/dfbe045e-59d3-11e4-8ad1-e4b6f3f9b13d.png)

And if I make the window smaller it clips the content:

![image](https://cloud.githubusercontent.com/assets/801252/4734458/0231deac-59d4-11e4-8bbb-7e058f8c636c.png)

The content fixes itself AFTER I STOP resizing, but during the resizing the above happens!

**Comment by TemaSM** [comment] 2015-10-10 01:53
Some news? Maybe we can see on how it implemented in NW.js? NW doesn't have the same glitch :pensive:

**Comment by fritx** [comment] 2015-10-23 06:13
In NW.js 0.12.3 with transparecy turned on, the side-effect went away.

**Comment by zcbenz** [comment] 2016-01-06 14:11
I'm closing this as won't fix since it is impossible to fix this without side effect.

There are basically two types of windows on Windows, one is window with frame (which has `WS_THICKFRAME` and `WS_CAPTION` styles), one is pure frameless window (which doesn't have those styles), Electron uses the former type for frameless window, that's why there is chrome showing when resizing window.

Does removing `WS_THICKFRAME ` and `WS_CAPTION` styles work? We used to remove those styles, but then there were new problems, like there is no animation when minimizing and maximizing window, and maximized window will cover the taskbar. Basically if one window doesn't have `WS_THICKFRAME ` and `WS_CAPTION` styles, Windows will not treat it as normal window.

But there is still work around, after setting `backgroundColor` for `BrowserWindow`, the chrome will be covered with the background color, which is not perfect, but should have solved this problem,

**Closed by zcbenz** 2016-01-06 14:11 UTC
Labels: bug, windows

**Comment by lukeapage** [comment] 2016-06-02 13:03
@zcbenz we need to fix this (We find this very visible in our particular UI) and may be able to spare some dedicated resource to make a PR.
would it be an option to pass something down with BrowserWindow thats says "I don't care about animations when resizing and the title bar being covered when full screen" so that `WS_THICKFRAME` and `WS_CAPTION` can be left off ? Is the problem that this has to happen globally and can't be window dependent?
Would it help if we investigated how nw.js manages to solve this problem?

**Comment by zcbenz** [comment] 2016-06-03 04:49
@lukeapage I'm good adding a option for it.

**Comment by bobrippling** [comment] 2016-07-26 16:21
I've been looking into this to see if I can make @lukeapage's use case viable. In particular, I'm just interested in disabling `WS_THICKFRAME` (and `WS_CAPTION`).

I'm a little unsure about removing the window styles. From [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ms632600(v=vs.85).aspx):
> After the window has been created, these styles cannot be modified, except as noted.


Unfortunately, `WS_THICKFRAME` (aka `WS_SIZEBOX`) has no exception, and using Spy++ I see that `WS_THICKFRAME` remains despite our attempted removal. So I imagine we need to modify the initial call to `CreateWindow`. 

This led me into `GetAcceleratedWidget()`, which leads into libchromiumcontent/brightray (via `views::Widget`). Building in debug mode brings down libchromiumcontent, and a `grep` on this doesn't show any CreateWindow calls, although admittedly this may not find CreateWindow calls inside pre-compiled libraries.

At this stage I don't know enough about libchromiumcontent or its dependencies to know if it's possible to create a window in electron without `WS_THICKFRAME` - I assume this is how NW.js handles it? If there's anything I've missed or existing API to create a window without the `WS_THICKFRAME` style, I'd be interested in knowing about it, although I imagine without providing the plumbing through to the window creation, this can't really be done?

**Comment by lukeapage** [comment] 2016-07-26 16:47
Strange - this from nw.js: https://github.com/nwjs/nw.js/issues/3108
Seems to imply it can be removed but not added..

**Comment by lukeapage** [comment] 2016-07-26 16:53
And i know its not the source of truth, but this so artical suggests it can be removed afterwards: http://stackoverflow.com/questions/2398746/removing-window-border

**Comment by zcbenz** [comment] 2016-07-27 00:36
We recently have added the `thickFrame` option which can be used to create window without `WS_THICKFRAME` style.

**Comment by lukeapage** [comment] 2016-07-27 02:58
Thanks, I missed that.

**Comment by s-kulitsky** [comment] 2020-01-30 12:37
> We recently have added the `thickFrame` option which can be used to create window without `WS_THICKFRAME` style.

The main issue which still stay is that win.maximize() DOES NOT change isMaximized() flag and those DOES NOT trigger maximize event. What is worse, double clicking on '-webkit-app-region: drag' element DOES. So there is no simple way to process window maximizing/unmaximizng (the worst effect is when you are trying to drag the window after win.maximize() the window IS NOT resized as it is expected).

However, after all, with thickFrame: false the workaroud for the issue is much simpler.
