### ISSUE TITLE
Request: API to Chromium's "print to pdf" feature 

### ISSUE THREAD

**Issue by skoji** [atom/electron#805] opened 2014-11-10 06:38 UTC
I want to use chromium's "print to pdf" feature from application.on atom-shell.
atom-shell supports printing, but seems not to support the feature.

**Comment by polarathene** [comment] 2015-02-03 06:59
+1 currently using phantomjs just for this feature. I'm using a slightly different html page than the user version, so hopefully could silently load the page via a new window and save a pdf render to disk?

**Comment by scotttesler** [comment] 2015-04-27 23:48
:+1:

**Comment by fraserxu** [comment] 2015-06-17 08:55
This is great! Just saw this being merged 4 hours ago.

@zcbenz When will you do the new release? We need this desperately!

**Comment by zcbenz** [comment] 2015-06-17 09:04
@fraserxu Probably tomorrow, it is a little late today.

**Comment by fraserxu** [comment] 2015-06-17 09:16
Ah, cool! Thanks a lot!

**Comment by fraserxu** [comment] 2015-06-18 07:36
Got the new build. However I got a few issue with the `printToPDF` api, if I create a new `window-browser` instance in my rendered main process like this

```
var BrowserWindow = remote.require('browser-window');
var win = new BrowserWindow({ width: 800, height: 600, show: false });
win.on('closed', function() {
  win = null;
});

win.loadUrl(tplPath);
win.show();

win.printToPDF({
  landscape: true
}, function(err, data) {
  // fs.writeFile(path, data, function(err) {})
})
```

It works fine when there's only 20 pages. But I'm using this api to render and generate a 1000 pages report PDF, it only generate the first 22 pages, not the others.

I also tried to use the `win.print()` in the main rendered process, it's the same.

**However**, if I run the `window.print()` from the console in the opened sub `browser-window` instance , there's no issue render and generate 1000 pages.

I believe there's certain limitation with the memory usage when calling from the main rendered process?

@zcbenz @hokein Any idea about this would be appreciated!

**Comment by fraserxu** [comment] 2015-06-18 09:02
I also did another test on Windows with the following code
```JavaScript
var remote = require('remote')

var browserWindow = remote.require('browser-window')
var fs = remote.require('fs')
var path = remote.require('path')

var win = new browserWindow({
  width: 800,
  height: 600,
  show: false
})

win.loadUrl('https://fraserxu.me')
win.show()

win.printToPDF({
  landscape: true
}, function(err, data) {
  var dist = 'C:\\Users\\fraserxu\\Desktop\\test.pdf'
  fs.writeFile(dist, data, function(err) {
    if(err) alert('genearte pdf error', err)
  })
})
```

It generate an empty PDF :( @hokein did it work for you on Windows?

**Comment by hokein** [comment] 2015-06-19 02:03
@frankhale 
You need to call the printToPDF API only after the webcontents finished. See the code below:

```
  win.webContents.on('did-finish-load', function() {
    console.log('finish loading');
    mainWindow.printToPDF({
      landscape: true
    }, function(err, data) {
      var dist = '/tmp/test.pdf'
      console.log(data);
      fs.writeFile(dist, data, function(err) {
        if(err) alert('genearte pdf error', err)
      })
    })
  });
```

> It works fine when there's only 20 pages. But I'm using this api to render and generate a 1000 pages report PDF, it only generate the first 22 pages, not the others.

Can you provide a reproduced sample for me? I just test the website `https://fraserxu.me/` on OS X, it generates 39 page PDF, which looks good to me.

It's not a good way to generate the large PDF in renderer side, since `electron` copy the pdf data from main process to renderer process. Can you try to make it on main process to see what happen? Again remember do it after webcontents get loaded.

**Comment by fraserxu** [comment] 2015-06-19 02:51
@hokein Ah, that's the reason!! Thanks a lot @hokein 

The link here is just an dummy example of what my actually data would become.

And thanks for the tip to generate the PDF in the main process, I'll have a try!

**Comment by hokein** [comment] 2015-06-19 04:52
> The link here is just an dummy example of what my actually data would become.

I didn't see the link here.

**Comment by fraserxu** [comment] 2015-06-19 04:57
Aha, I mean `https://fraserxu.me/` is an example, sorry for the confusion.

I'm generating a 1000 pages PDF in Myanmar language with Electron on a Windows machine, your tip save my day! Thanks again!

**Comment by steelbrain** [comment] 2015-07-03 08:56
This is already fixed in master https://github.com/atom/electron/blob/master/docs/api/browser-window.md#browserwindowprinttopdfoptions-callback

**Comment by hokein** [comment] 2015-07-03 11:50
Close it since printToPDF API is implemented right now.

**Closed by hokein** 2015-07-03 11:50 UTC
Labels: enhancement

**Comment by azisunmul** [comment] 2016-03-27 04:33
how do I call a function printToPDF API And in angular button controller
