### ISSUE TITLE
inline style with float value is corrupted, dot becomes comma?

### ISSUE THREAD

**Issue by jespermjonsson** [atom/electron#3731] opened 2015-12-08 17:12 UTC
Using electron > 0.32.0 makes inline style corrupt that contain float values.

Running the following code in the console:

	window.location = "http://www.google.com";
	document.querySelector('.content').style.paddingBottom = "100.50px";

Will print "100.50px", but if I re-query the value:

	document.querySelector('.content').style.paddingBottom

It will print "100,50px" instead?! Also, looking in the elements tab and selecting the "class=content" node, shows the css value with a warning sign and "Invalid property value" note. How come that the "." is changed to ","?

It worked until electron 0.31.2.
I'm running OS X 10.10.5 with Swedish system language.

**Comment by Kilhog** [comment] 2015-12-08 17:14
#3001 :+1: I think the chrome V47 fix this bug

**Comment by zcbenz** [comment] 2015-12-09 05:53
This is a duplicate of #3001.

**Closed by zcbenz** 2015-12-09 05:53 UTC

**Comment by Kilhog** [comment] 2015-12-11 08:11
The bug is still present with chrome V47 😟

**Comment by Kilhog** [comment] 2015-12-11 08:17
Weird thing, when you do ```open ./node_modules/electron-prebuilt/dist/Electron.app``` the bug is present but when you open it by double clicking on Electron.app, the bug disappears.

**Comment by jespermjonsson** [comment] 2015-12-21 16:07
I can add to @Kilhog's findings, double clicking on Electron.app in Finder works with no bug, but opening the exact same app from the terminal with `Electron.app/Contents/MacOS/Electron` and the bug is there! :)

**Comment by manudurgoni** [comment] 2016-10-06 11:31
The bug is still present with : Electron: 1.4.2, Chromium: 53.0.2785.113, V8: 5.3.332.45.

I created a fork of the electron-quick-start : https://github.com/manudurgoni/electron-css-issue

I'm just doing that : 
```
//Set a "normal" css float number !
document.body.style.height = "1025.48px";

//The result in app on the body tag is : style="height: 1025,48px;"
```

I don't get it, is it a chromium or electron problem ?
