### ISSUE TITLE
Calling fs.readdirSync on an SSHFS directory freezes application

### ISSUE THREAD

**Issue by nathansobo** [atom/electron#4900] opened 2016-03-24 06:17 UTC
* Electron version: 0.36.11
* Operating system: OS X 10.11.3

In researching https://github.com/atom/atom/issues/11214, I've discovered at least one reproducible way to completely lock the Electron render process when reading directory entries from an SSHFS network drive mount.

* Open the dev tools and start a timeline or a profile.
* In the render process, execute a `fs.readdirSync` with a path to a directory on an SSHFS mount.

I've created a [demonstration application](https://github.com/nathansobo/demonstrate-fuse-bug) with instructions on its `index.html`. This may not be the exact error condition Atom users are encountering, but it seems highly likely to be related.

/cc @zcbenz @iolsen @lee-dohm

**Comment by kevinsawicki** [comment] 2016-03-24 15:53
@nathansobo are you able to reproduce on the latest Electron release, 0.37.x?

**Comment by nathansobo** [comment] 2016-03-24 16:59
Yeah, I can. The quick-start's `electron-prebuilt` is still set to 0.36.x so I got lazy but I just reproduced on 0.37.x by dragging the linked demo app into 0.37.2.

**Comment by zcbenz** [comment] 2016-03-31 07:13
I'm closing this since the original issue #11214 has been fixed. It is still possible that we have troubles with SSHFS in Electron, so if anyone sees this, please ask to reopen here.

**Closed by zcbenz** 2016-03-31 07:13 UTC
