### ISSUE TITLE
Can't disable the draggable area in a frameless window

### ISSUE THREAD

**Issue by sunabozu** [atom/electron#3804] opened 2015-12-13 20:12 UTC
Electron 0.36.0
OS X 10.10.3
BrowserWindow with `'title-bar-style'` set to  `'hidden-inset'`.

**Problem:**
There is always a draggable area at the top, even if I don't place any elements there. It has a standard size for this type of windows in OS X (see *System Preferences*). And I can't disable it for my buttons or other elements by using `-webkit-app-region: no-drag;`.

I'm not sure but I think there wasn't such an issue in 0.35.

![adv0gldx9e](https://cloud.githubusercontent.com/assets/135717/11769011/74f76366-a1e6-11e5-8126-1dcec3d2bd2e.gif)

**Comment by zcbenz** [comment] 2015-12-14 12:08
This is unfortunate a side effect of the `title-bar-style` option, I'm closing this as a duplicate of #3009.

**Closed by zcbenz** 2015-12-14 12:08 UTC

**Comment by sunabozu** [comment] 2015-12-14 12:27
Ok, I see. But which project this side effect belongs to? I mean, we should solve it somehow.
