### ISSUE TITLE
IME Problem in WebView

### ISSUE THREAD

**Issue by sng2c** [atom/electron#1051] opened 2015-01-24 08:47 UTC
Hello, I am Korean and made some desktop application with atom-shell.

I found a problem for IME in WebView on OSX
![2015-01-24 5 38 42](https://cloud.githubusercontent.com/assets/594524/5886695/21886a4e-a3f0-11e4-94ef-5c988c2d0b60.png)

Charaters did not composite each other.
I had seen it when using some applications on OSX before, anyway..
Did I do something wrong? 

I just coded like below with atom-shell-v0.20.7-darwin-x64.
```html
<!DOCTYPE html>
<html>
<head>
  <title>SmartNamer</title>
<style>
body{ background-color: #aaa;}
#guest {
  border:none;
  position: absolute;
  top: 100px;
  bottom: 0;
  left: 0;
  right: 0;
  height: 80%;
  width: 100%;
  min-width: 400px;
  overflow:hidden;
}
</style>

<script type="text/javascript" src="app.js"></script>
</head>
<body>
  <input type="text">
  <webview id="guest"
  httpreferrer="http://www.mabook.com/smartnamer/#app"
  src="http://www.mabook.com/smartnamer/index.php"></webview>
</body>
</html>
```

**Comment by sng2c** [comment] 2015-01-24 09:02
Additional Info.

![2015-01-24 5 59 24](https://cloud.githubusercontent.com/assets/594524/5886768/dbbdd604-a3f2-11e4-9614-101110a3f681.png)

I just tested more condition.
* In Main Browser, no problem.
* In IFRAME, no problem.
* In WebView, problem!!

main.html
```html
<!DOCTYPE html>
<html>
<head>
<style>
iframe,webview {
  height:50px;
  display:block;
}
</style>
<script type="text/javascript" src="app.js"></script>
</head>
<body>
  <p>main
    <input type="text">
  </p>

  <p>iframe
    <iframe
    httpreferrer="http://www.mabook.com/smartnamer/#app"
    src="test.html"></iframe>
  </p>

  <p>webview
    <webview
    httpreferrer="http://www.mabook.com/smartnamer/#app"
    src="test.html"></webview>
  </p>
</body>
</html>
```

test.html
```
<html>
	<style>
	body{background-color:white;}
	</style>
	<body>
		<input type="text">
	</body>
</html>
```

Please check it out.

**Comment by zcbenz** [comment] 2015-01-24 22:42
I can reproduce this bug in the `<webview>` of Chrome extensions, I suggest [reporting it to upstream Chromium](https://code.google.com/p/chromium/issues/list) because it can not be fixed on atom-shell side.

**Comment by sng2c** [comment] 2015-01-25 23:12
OK. Thanks for your suggestion.
I am going to report this to upstream Chromium.
When it has been solved,  I will close this issue.

**Comment by sng2c** [comment] 2015-01-27 02:20
@zcbenz 
I reported this problem to [upstream Chromium](https://code.google.com/p/chromium/issues/detail?id=452336).
Thanks.

**Comment by zcbenz** [comment] 2015-11-10 03:23
It has been fixed in recent Chrome versions.

**Closed by zcbenz** 2015-11-10 03:23 UTC
Labels: blocked, bug, osx
