### ISSUE TITLE
Mac OS spinning pinwheel when launching Tray app from CLI, but not from .app

### ISSUE THREAD

**Issue by maxogden** [atom/electron#1333] opened 2015-03-30 16:32 UTC
On Mac OS if I launch an app with a Tray icon from the CLI, about half the time it pinwheels for ~10 seconds before continuing to work. It seems like a race condition or a timeout or something to me, but I haven't been able to figure out the cause.

Here is a minimal test case (you will have to put an Icon.png in the folder with it for the icon to show up in the tray)

```js
var path = require('path')
var app = require('app')
var Tray = require('tray')

app.on('ready', function ready () {
  var tray = new Tray(path.join(__dirname, 'Icon.png'))  
})
```

Then run `atom-shell app.js` and you should get a pinwheel within the first few tries when you try and click on the icon in the tray.

The weird part is, if I package the app in a .app (using https://www.npmjs.com/package/atom-shell-packager) it never pinwheels on startup.

I've been able to replicate this on multiple Mac OS machines so far.

**Comment by zcbenz** [comment] 2015-04-01 02:43
What would happen if you move `tray` out of the `ready` callback like the following?

```js
var tray;
app.on('ready', function ready () {
  tray = new Tray(path.join(__dirname, 'Icon.png'))  
})
```

In your code `tray` will be garbage collected after some time.

**Comment by maxogden** [comment] 2015-04-02 02:24
@zcbenz I am still able to reproduce the spinning pinwheel issue with your suggestion

**Comment by zcbenz** [comment] 2015-09-17 14:52
Not able to reproduce on v0.33.0, seems to have been fixed by previous Chrome updates.

**Closed by zcbenz** 2015-09-17 14:52 UTC
Labels: blocked, bug, osx
