### ISSUE TITLE
localStorage doesn't persist on Linux + Windows

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#1731] opened 2015-05-19 20:59 UTC
To repro:

1. Open Electron on Ubuntu 14.04 32-bit (at least, prob. other places too)
1. `localStorage.setItem('foo', 'bar')`
1. Close the app
1. Reopen the app
1. `localStorage.getItem('foo')`
1. `>> undefined`

**Comment by magicae** [comment] 2015-05-20 10:17
On ArchLinux, it's all right.

**Comment by CharlieHess** [comment] 2015-05-20 17:40
This is more severe; it's actually happening on all platforms.

**Comment by frankhale** [comment] 2015-05-20 17:51
@CharlieHess, by 'all platforms" do you mean all OSes Electron supports because I just tested Electron 0.26 x64 on Windows 10 preview and ran through the steps @paulcbetts mentioned and 'foo' is persisting for me.

**Comment by CharlieHess** [comment] 2015-05-20 18:22
@frankhale: Tested on Windows 8.1 and Yosemite. We're accessing `localStorage` from the renderer process (if that matters).

**Comment by frankhale** [comment] 2015-05-20 19:13
I assumed (most likely incorrectly) in @paulcbetts steps to reproduce that it was implied to open up Dev Tools and set / get 'foo' using the console.

**Comment by paulcbetts** [comment] 2015-05-20 20:52
@frankhale Yep, that's what I meant

**Comment by zcbenz** [comment] 2015-05-21 07:16
I haven't looked into it yet, but if the app crashes when quitting, or you use other ways like `process.exit` instead of `app.quit` to quit, the localStorage will not be persisted.

**Comment by CharlieHess** [comment] 2015-05-21 18:42
_So_, it turns out that we were calling out to `app.exit` instead of `app.quit`. I can't find any documentation on this method, but modifying all of our calls to use quit make `localStorage` persist as expected. I think we can close this one out. :sweat_smile:

**Closed** 2015-05-21 18:46 UTC
Labels: bug, linux, windows

**Comment by haoxins** [comment] 2015-09-01 06:57
When I run app on win10 VM, localStorage still not persist.

**Comment by nicozhang** [comment] 2015-11-06 09:24
I meet the same problem with plantform of win10. When I am using an mapapi , it's js will judge whether the localstorage works, but the result is localstorage does not work. electron 0.34.2.

**Comment by riadd** [comment] 2016-01-30 20:14
Also does not persists for me on win 10.

**Comment by bansalvks** [comment] 2016-05-26 07:58
using electron 1.1.0 and **lcoalStorage** is not persisting. Any help is kindly appreciated. I am accessing local storage from browser window (rendered process)

**Comment by paulcbetts** [comment] 2016-05-26 16:26
LocalStorage won't persist if you kill the app via Ctrl-C or some other violent means, this is almost certainly the bug y'all are seeing

**Comment by Lt0** [comment] 2018-10-12 19:54
I have the same issue on win10 when I reinstall my electron app. I just remove C:\Users\Lt0\AppData\Roaming\my-app-name to make it work.

**Comment by 3DEsprit** [comment] 2019-04-08 05:03
I'm running into this with my Linux builds when using app.quit(), though the Windows and OSX builds have no issues persisting at all.

**Comment by knaos** [comment] 2021-11-25 14:21
So what if we want to prevent this behaviour? Is it still a bug.

**Comment by anaisbetts** [comment] 2021-11-25 15:17
> So what if we want to prevent this behaviour? Is it still a bug.

If you want to prevent this behavior, exit your application correctly and it won't happen 💃

**Comment by mcharytoniuk** [comment] 2021-12-07 15:02
Even closing an application with "X" window button does not persist local storage, which seems to be the correct way to close an app. Electron needs a little help to prevent this. This is the helpful answer that resolved the issue for me: https://github.com/electron/electron/issues/5708#issuecomment-531492039

Calling `app.quit()` in this event might be even more reliable: https://nodejs.org/api/process.html#event-beforeexit

**Comment by amoscatelli** [comment] 2022-01-22 22:27
> Even closing an application with "X" window button does not persist local storage, which seems to be the correct way to close an app. Electron needs a little help to prevent this. This is the helpful answer that resolved the issue for me: [#5708 (comment)](https://github.com/electron/electron/issues/5708#issuecomment-531492039)
> 
> Calling `app.quit()` manually in this event might be even more reliable: https://nodejs.org/api/process.html#event-beforeexit

Are using localestorage from main process or renderer process ?

Even when using 
process.on('exit', () => app.quit());

my renderer process seems to lose data in localstorage when closing the application with "X"
