### ISSUE TITLE
Notifications on Windows does not work with URLs

### ISSUE THREAD

**Issue by evgenyzinoviev** [atom/electron#3717] opened 2015-12-07 21:18 UTC
If I specify remote url of notification's icon, it works on OS X, but not on windows. This is not working on windows (notification will not be shown at all):
```
new Notification(title, { icon: 'http://site.com/image.jpg' })
```
base64-encoded data urls aren't working either. It seems that only file:// urls are working so far.

I'm using Electron 0.35.2 on Windows 8.1.

Is it a bug or expected behavior? I can of course try to download and save to disk every image I want to pop up but I'm afraid it will be a bit expensive.

**Comment by kurisubrooks** [comment] 2015-12-08 05:00
Windows Notifications always use the icon of the packaged app. 
Unfortunately this is the expected behaviour.

**Comment by evgenyzinoviev** [comment] 2015-12-08 11:17
@kurisubrooks apparently not always, because it's possible to specify local path to the image (with file:// protocol) and it will work.

**Comment by felixrieseberg** [comment] 2015-12-09 00:08
Yeah, that is correct - there's currently no way to use a URL. We could try some funny business inside Brightray and download an image, save it to disk, and then serve it - but I don't think that that would be decent solution, given that we'd just moving the work to a lower level. Saving it to disk yourself is the correct solution here.

I'm closing this for now, as it's not a bug, just the current behavior.

**Closed by felixrieseberg** 2015-12-09 00:08 UTC
