### ISSUE TITLE
[webview] window.open throw errors even when new-window events are handled

### ISSUE THREAD

**Issue by felicienfrancois** [atom/electron#1864] opened 2015-06-04 11:41 UTC
When calling window.open in a webview that handles new-window events, I still get the following error, even if the new window is successfully handled.
```error
It is not allowed to open new window from this WebContents
```

```javascript
webview.addEventListener('new-window', function(e) {
 // something here that open the new window
});
```

**Comment by frankhale** [comment] 2015-06-04 12:00
I was getting this as well but this is fixed in master by #1850 if my
memory serves me correctly.

**Comment by deepak1556** [comment] 2015-06-18 15:54
@zcbenz what is the expected behaviour here ? should we emit the event, even if there is no window [creation](https://github.com/atom/electron/blob/master/atom/browser/lib/guest-window-manager.coffee#L44)

**Comment by zcbenz** [comment] 2015-06-19 07:33
@deepak1556 It should emit the `new-window` event, but there were some implementation problems since you can not send synchronous messages from webview to host.

**Comment by felicienfrancois** [comment] 2015-06-23 13:20
@frankhale this is not fixed yet. Still happening in 0.28.3

**Comment by frankhale** [comment] 2015-06-23 14:13
Looks like I was wrong. I just went back to check my own app. This issue has not been closed so it's all good.

**Comment by kjlaw89** [comment] 2015-06-24 15:59
Would it be possible to tag webviews to have the capability to open new windows with window.open in the same way that the BrowserWindow can? Maybe a new tag on webview like "allow-popups" or something? If it's not specified then you'd fall back onto the new-window event (or possible do both if that attribute is provided).

This would be useful for us, since we have quite a few places in our code that do window.open () with various settings and right now we're getting the same message @felicienfrancois was getting:

    It is not allowed to open new window from this WebContents

**Comment by felicienfrancois** [comment] 2015-06-24 16:27
@kjlaw89 this tag could also be automatically toggled when adding an event listener to window-open.

**Closed** 2015-09-22 13:52 UTC
Labels: bug, webview
