### ISSUE TITLE
ipc.sendSync() breaks drop/dragEnd event handling

### ISSUE THREAD

**Issue by mkscrg** [atom/electron#3747] opened 2015-12-09 20:59 UTC
Repro gist: <https://gist.github.com/mkscrg/9adea6ea14464876460c>

Calling `electron.ipcRenderer.sendSync()` within a `drop` event handler causes odd behavior with `dragEnd` event handlers.

Given this code in a `BrowserWindow`:

```html
<!DOCTYPE html>
<html lang="en">
  <body>
    <script>
window.allowDrop = function(e) {
  e.preventDefault();
};
window.drop = function() {
  console.log('DROP (1)');
  require('electron').ipcRenderer.sendSync('sync-message');
  console.log('DROP (2)');
};
window.dragEnd = function() {
  console.log('DRAG END (3)');
};
    </script>
    <div draggable="true" ondragend="dragEnd(event)" style="width: 50px; height: 50px; background: blue;"></div>
    <div ondragover="allowDrop(event)" ondrop="drop(event)" style="width: 100px; height: 100px; margin-top: 50px; background: red;"></div>
  </body>
</html>
```

When the blue box is dragged to the red box, the console shows:

```
DROP (1)
DRAG END (3)
DROP (2)
```

Workaround: avoid calling IPC in drag/drop event handlers.

FWIW: this appeared for us as a bunch of React and ReactDnD invariant violations. We were calling `remote.getGlobal` from a React `render` method, and causing a re-render from a `drop` handler.

**Comment by mkscrg** [comment] 2015-12-09 21:02
I've reproduced this on 0.34.3 and 0.35.4.

**Comment by zcbenz** [comment] 2015-12-10 10:35
This is essentially a duplicate of #1966, when calling `sendSync` current execution of JavaScript is paused but the `dragEnd` event jumped in because it is on the next tick of message loop.

**Closed by zcbenz** 2015-12-10 10:35 UTC

**Comment by mkscrg** [comment] 2015-12-10 12:14
Ok, thanks for taking a look!
