### ISSUE TITLE
Cookie is not enabled in browser

### ISSUE THREAD

**Issue by pmcfernandes** [atom/electron#3360] opened 2015-11-06 22:31 UTC
Hi everyone,

I trying auth with facebook and after login facebook callback said Cookie is not enabled in browser. Exists ayway to activate cookies by default in electron?

**Comment by zcbenz** [comment] 2015-11-07 03:24
Cookies are enabled in Electron by default, it is very likely caused by other problems that made Facebook think cookie is not enabled.

**Comment by zcbenz** [comment] 2015-11-16 14:31
Closing until more information is provided.

**Closed by zcbenz** 2015-11-16 14:31 UTC
Labels: more-information-needed

**Comment by arcman77** [comment] 2016-07-20 18:17
@pmcfernandes did you find a fix for this?

**Comment by pmcfernandes** [comment] 2016-07-20 19:34
@arcman77 i don't tested in lastest versions.

**Comment by odegraciajr** [comment] 2016-08-25 21:24
Still not working on 1.3.4 version.

**Comment by vincelwt** [comment] 2016-09-10 10:26
Same problem with some users.
When using Spotify Oauth and login via Facebook, Facebook sometimes complain because Cookies are not enabled

**Comment by bundyo** [comment] 2017-03-28 08:21
Google Analytics also complains about cookies not enabled, when loading the app from file protocol. This is probably related to the fact that cookies are disabled for file protocol in Chrome by default and can be enabled with the "enable-file-cookies" switch.

Look here:
https://bugs.chromium.org/p/chromium/issues/detail?id=535
