### ISSUE TITLE
Duplicate Icon on Windows 10

### ISSUE THREAD

**Issue by bnb** [atom/electron#2012] opened 2015-06-19 01:18 UTC
Continuing from this discussion: https://discuss.atom.io/t/double-icon-when-pinned/17320/24

I've got Atom installed on Windows 10. I open the application, then right click the icon in the taskbar, then click Pin to Taskbar. This creates a duplicate (second) icon on the taskbar. The first icon is the actual instance of the app running, and it goes away when the app is closed. The second icon stays permanently. If I click the second icon while Atom is closed, it adds the first icon back to my taskbar.

Any ideas as to what I can do to fix this?

**Comment by zcbenz** [comment] 2015-06-19 07:38
This is a duplicate of #1954.

**Closed by zcbenz** 2015-06-19 07:38 UTC
