### ISSUE TITLE
Encrypting source files within ASAR

### ISSUE THREAD

**Issue by ArktekniK** [atom/electron#4359] opened 2016-02-04 12:13 UTC
Hi,

We've been looking for a way to protect the packaged ASAR from cursory inspection (with asar -extract) and wanted to encrypt files within it before packaging. Obviously modifying and rebuilding Electron is necessary, therefore myself and a colleague have been trawling through source to find the point at which the ASAR package is mounted / read

What we'd like to do is obfuscate and bake the decryption key within the Electron executable itself, then decrypt files within the ASAR when a seek within the ASAR happens (url_request_asar_job.cc)?

Can anyone with experience of the source point us to where this might be?
Otherwise provide any other advice?

Thanks.

**Comment by paulcbetts** [comment] 2016-02-04 18:27
Dupe of #3041 - this isn't built-in, you'll have to do this yourself

**Closed by paulcbetts** 2016-02-04 18:27 UTC

**Comment by ArktekniK** [comment] 2016-02-04 19:17
Hi @paulcbetts, 

This wasn't a request for implementation, I was asking whether, as the active developers of the project, there were any pointers or general advice on the loading of the asar in electron source. I am aware this is only going to offer security through obscurity.

I would of course be making the changes myself and offering them back to the community as I understand there is resistance against the electron team committing to implementation.

Thanks for your help

Rob

**Comment by timfish** [comment] 2016-02-05 13:42
@ArktekniK 

I personally think you'd get just as useful code protection from decent obfuscation. 

It would however be helpful to get feedback from the team over what approaches would be most likely to be accepted as pull requests.

The simplest decryption code would probably go in `atom/browser/net/asar/url_request_asar_job.cc`. There's currently no way to flag a file in an asar as encrypted so this decryption would be applied to every file from every asar which would only be good enough for personal use.

One approach would require changes to asar. Add the encryption hook, add a header to show what encryption was used, add tests and then do a pull request. This feature has been [turned down before](https://github.com/atom/asar/issues/46) but it may be more likely to be accepted with code + tests. Bear in mind it does add functionality most will not use. The great thing with the design of asar is that the header is JSON so adding to it shouldn't break existing clients.

Another possibly cleaner approach requiring no changes to asar would be to encrypt the entire archive file and add new protocol handler to electron (see `atom/browser/net/asar/asar_protocol_handler`). The new handler would decrypt the stream and pass it into the existing asar code. There might be issues here with seeking within the stream and the decrypted file may need to be cached entirely in memory.

**Comment by paulcbetts** [comment] 2016-02-05 17:54
> This wasn't a request for implementation, I was asking whether, as the active developers of the project, there were any pointers or general advice on the loading of the asar in electron source. I am aware this is only going to offer security through obscurity.

Sure, I'm just noting that there's no designed-for-this-purpose hook to do this feature, you'd have to design the hook infrastructure and author the hook

**Comment by zcbenz** [comment] 2016-02-15 04:11
@ArktekniK Encrypting ASAR archive looks a reasonable solution to me, but you need to be careful to remove the possibility to open devtools.

For implementing this, you need to change both the C++ and JavaScript implementation, related code can be found at:
* `atom/common/asar/archive.cc`
* `atom/common/lib/asar.js`

Currently implementations make use of the fact that the layout of files is flat, so lots of operations are implemented by just seeking the file.

**Comment by andrewex** [comment] 2016-03-18 23:12
@ArktekniK did you make any progress with this? I am also going to be working on implementing on a similar solution.

**Comment by ArktekniK** [comment] 2016-03-19 10:55
Unfortunately not due to project time constraints. I am still planning to look into it though, but can't commit to a timeline.

**Comment by kumarom1203** [comment] 2017-01-25 19:28
Hi everyone,
Is any way to protect ASAR file from unpackaging(generated by electron atom) so other can not able to modify my code.
If any one has any idea or other option to protect my code please suggest
Thanx in advance

**Comment by XiaohuChen** [comment] 2017-04-08 14:27
@ArktekniK   Hi, Rob, have you solve this problem? I think there are many people like me  want to know how to fix it. so if you have dealt with this, could you please show us how to ?

**Comment by dunhamsteve** [comment] 2017-09-30 20:52
Just a quick note for anyone thinking of doing this - you can implement read random access with files encrypted in CBC mode (e.g. AES256-CBC). Essentially, the previous encrypted block acts as the IV and you have to deal with the padding in the last block (assuming PKCS7).  I've implemented CGDataProvider in this way in the past. 

Also, if you want to attack this system, just scan the process memory for an expanded AES key.   (Or, if they're using dynamic-linked crypto library, log the keys with dtruss.)

**Comment by zhbzhbzhbz** [comment] 2018-03-17 08:52
Is the encryption function still not applied in the current Electron?

**Comment by sucrose** [comment] 2019-07-08 17:18
Just an observation... in the prior version of GitKraken it was possible to extract the Javascript contents of the `App.asar` file. The current version extracts everything _except_ for the Javascript contents, so it does seem possible to protect certain directories within from being modified and/or extracted.

**Comment by maziyarpanahi** [comment] 2019-09-16 18:02
@sucrose Have you found out how they managed to do that? Thank you.

**Comment by sucrose** [comment] 2019-09-16 21:15
> @sucrose Have you found out how they managed to do that? Thank you.

No sir, I prevented the GitKraken client from upgrading passed 5.0.4 (the last version before the _ASAR_ obscurity) by adding the following line to my system's `HOSTS` file on Windows:

```
127.0.0.1 api.gitkraken.com
```

**Comment by kidsonfilms-python-rules** [comment] 2022-01-02 18:18
@sucrose I installed Version 8.2.1 of GitKraken and I managed to extract a lot of JS files, with the main process file being located at (relative to `package.json`) `./src/main/static/main.bundle.js`.

Either they screwed up and didn't do the asar hiding/encryption method you described or they now have all critical code in a `.node` file which I also found, located at `C:\Users\------\AppData\Local\gitkraken\app-8.2.1\resources\app.asar.unpacked\src\main\static\21ea812a389c54c398580378b0c240ab.node`

If you did find a version where they did hide the JS files, could you please share which version?

**Comment by Omar25py** [comment] 2023-04-19 06:27
you can protect code with enigma virtual box, this have an API you can use to code inside to increase security, and i test this ...i tried to read renderer.js and virtual box dont show file
