### ISSUE TITLE
menu drop down doesn't dismiss when clicking after changing menus

### ISSUE THREAD

**Issue by petersalas** [atom/electron#3748] opened 2015-12-09 23:01 UTC
When I click a menu (e.g. File), mouse over to a different menu (e.g. Edit) and click again, I expect the menu to be dismissed.  Instead, it flickers and I need to click again to dismiss it.  If I click the same menu I clicked the first time (File in the example above), the drop down is dismissed as expected.

I'm using Atom 1.2.4 on Windows 10.  The bug is also present in Visual Studio Code.

**Comment by zcbenz** [comment] 2015-12-10 06:47
This is a duplicate of #2243.

**Closed by zcbenz** 2015-12-10 06:47 UTC
