### ISSUE TITLE
Checking whether another instance of the same application is already running

### ISSUE THREAD

**Issue by hhammoud01** [atom/electron#2940] opened 2015-09-30 10:22 UTC
Hey guys,
I just wanted to ask how do we check whether there already are any instances of the same application running.
Thank you,
Regards,

**Comment by zcbenz** [comment] 2015-09-30 10:26
This is a duplicate of #648, for questions you can seek the [community](https://github.com/atom/electron#community) for help.

**Closed by zcbenz** 2015-09-30 10:26 UTC
