### ISSUE TITLE
Support for native file transfer / clipboard support

### ISSUE THREAD

**Issue by bpasero** [atom/electron#2853] opened 2015-09-21 08:31 UTC
My use case is to better integrate my Electron app into the desktop environment. This includes being able to copy a file to clipboard and paste it to the native OS explorer/finder as well as to drag and drop between the app and the desktop.

As of today the closest I can get is by leveraging Chrome's own support for dragging out files to the desktop (http://www.thecssninja.com/javascript/gmail-dragout). However this support seems limited to the OS explorer/finder and does not work to drag something into another application (eg. Sublime).

Opening this issue to gather some ideas how to support this kind of feature and maybe other developers have found solutions already?

**Comment by zcbenz** [comment] 2015-09-21 13:26
This is a duplicate of #2244, we have to introduce new APIs for accessing native file.

**Closed by zcbenz** 2015-09-21 13:26 UTC

**Comment by UziTech** [comment] 2018-01-29 22:09
@zcbenz I don't think this is a duplicate. #2244 is about pasting image data from the clipboard not files.

There is still no way to copy a file from the OS to an electron app or vice versa.

https://github.com/atom/tree-view/issues/569

/cc @50Wliu
