### ISSUE TITLE
Module not found in render process

### ISSUE THREAD

**Issue by npenin** [atom/electron#3043] opened 2015-10-09 04:36 UTC
Hi,

I think I have the same issue as #2494 in electron 0.33.6 on ARM (raspberry pi 2). I guess my global paths are wrong, but don't know what to do against that.  am loading a remote page in my browser-window, maybe it can help to diagnose.

```js
require('module').globalPaths
["/home/pi/mediacenter/node_modules/electron-prebuilt/dist/resources/atom.asar/common/api/lib", 
"/home/pi/mediacenter/node_modules/electron-prebuilt/dist/resources/atom.asar/renderer/api/lib"]
```
Any clue ?

**EDIT**
It actually seems to happen when a script is dynamically added to the remote web page, and that script tries a require.

**Comment by zcbenz** [comment] 2015-10-09 08:08
Can you provide an example app?

**Comment by npenin** [comment] 2015-10-09 08:12
Well not easily as it is my own domotic platform. The code is open source at https://github.com/npenin/domojs, but it is not straight forward to use. I'll try to make a sample app with the issue this evening

**Comment by zcbenz** [comment] 2015-10-20 03:13
Closing until more information is provided.

**Closed by zcbenz** 2015-10-20 03:13 UTC
Labels: more-information-needed

**Comment by hermwong** [comment] 2015-10-22 21:51
Hi @zcbenz,

I'm running into an issue where my `require` statements can't find my node modules; but it only happens on my compiled Win32 binary.

Everything works fine on my compiled Darwin (OSX) binary.

I'm trying to load a 3rd party node module called [`gaze`](https://www.npmjs.com/package/gaze) and also the [`connect-phonegap`](https://www.npmjs.com/package/connect-phonegap) node module.

![screen shot 2015-10-22 at 2 48 09 pm](https://cloud.githubusercontent.com/assets/107754/10679220/eca4eada-78cb-11e5-842c-b33976c2f027.png)

The code & instructions to build my project can be found [here](https://github.com/phonegap/phonegap-app-desktop/tree/0.2.0).

**Comment by hermwong** [comment] 2015-10-27 22:13
My issue was caused by executing the Win32 exe from a shared directory hosted on my OSX partition; once I copied my Win32 exe file into my Windows VM, I was able to run my app without any errors.
