### ISSUE TITLE
autoUpdater: An SSL error has occurred. kCFStreamErrorDomainSSL, -9802

### ISSUE THREAD

**Issue by dylang** [atom/electron#3505] opened 2015-11-19 03:40 UTC
Hi, I've been using Electron for a few months, but autoupdate started returning an error after `0.33.4`. I've been using the same endpoint hosted by Github.

## Error message

```bash
2015-11-18 22:31:12.249 Electron[71075:3518387] NSURLSession/NSURLConnection 
HTTP load failed (kCFStreamErrorDomainSSL, -9802)
[DeskDrive] Uncaught exception: Error: An SSL error has occurred and a secure
connection to the server cannot be made.: (null) Error: An SSL error has occurred
and a secure connection to the server cannot be made.: (null)
    at Error (native)
^C
```

(*DeskDrive* is the name of the app I'm working on.)

## Repro Code

```js
const autoUpdater = require('auto-updater');
autoUpdater.setFeedURL('https://raw.githubusercontent.com/dylang/DeskDrive-releases/master/auto_updater.json');
autoUpdater.checkForUpdates();
```

**Note:** App must be built *and signed* for `autoUpdater` to show this error.

## Versions

* Was working in 0.33.4, but has been failing in every build up to 0.35
* Testing in OS X 11.1 (El Capitan)
* Tested with and without firewall/proxy/etc.

**Comment by zcbenz** [comment] 2015-11-19 08:57
This is a duplicate of #3442.

In brief, Electron now links with OS X 10.11 SDK, which requires SHA-2 signatures for HTTPS connection, while S3's certificate is only signed with SHA-1.

**Closed by zcbenz** 2015-11-19 08:57 UTC
