### ISSUE TITLE
Unique Session Per Webview?

### ISSUE THREAD

**Issue by kjlaw89** [atom/electron#2426] opened 2015-08-05 12:47 UTC
Is it possible to create a unique session per webview? I've got a situation where I need to open up tabs to multiple sites on the same server, but I want each tab to be its own session. It would be quite convenient if I could control this on a per-tab basis, so I could make two tabs share the same session where two other tabs would have their own session entirely.

**Comment by zcbenz** [comment] 2015-08-05 13:04
This is a duplicate of #959.

**Closed by zcbenz** 2015-08-05 13:04 UTC

**Comment by gajus** [comment] 2015-08-30 07:49
@zcbenz I don't understand why this task, along with https://github.com/atom/electron/issues/2032, have been closed as a duplicate of #959. The latter issue is completely different (although with a misleadingly similar title). It talks about being able to persist session and restore it. Not about being able to have multiple active sessions in concurrence in different tabs.

**Comment by geeeeeeeeek** [comment] 2016-02-19 10:13
Any update on this? Or is there any solution to this? @gajus @zcbenz

**Comment by geeeeeeeeek** [comment] 2016-02-19 10:54
I think this issue should be open since there is no solution to this.

**Comment by gajus** [comment] 2016-02-19 11:53
@geeeeeeeeek https://github.com/atom/electron/pull/3514 ?

**Comment by geeeeeeeeek** [comment] 2016-02-19 12:07
@gajus 

I tried `partition:A` and `partition:B` for two BrowserWindows. However when I delete cookies in one of the two sessions, cookies in the other session are also deleted. Behaves like they still share the same session.

Code:

```
  let ses = windows[name].webContents.session;
  ses.cookies.remove("https://wx.qq.com", "wxuin", ()=>{})
```

I have passed different partition strings to new BrowserWindow object.

Anything wrong with my code? Could you share yours?

**Comment by mafrost** [comment] 2016-06-15 07:53
I am also interested in this. Any updates? I can't seem to get it to work either using different partitions

**Comment by SamVerschueren** [comment] 2018-07-08 11:49
So this was just closed and two years later, nobody of the core team cared enough to reopen it? 

I'm looking for this functionality as well. I have one URL where I want to sign in with multiple accounts at the same time. This issue prevents me from doing that because the session is shared between all the webviews. I looked into the docs of [webview](https://electronjs.org/docs/api/webview-tag) and tried to set a different `partition` and `guestinstance`, but no dice, it just doesn't work.

**Comment by wuyuedefeng** [comment] 2018-07-25 08:23
I'm looking for this functionality as well, how solve?

**Comment by chevonc** [comment] 2018-07-26 19:47
Would love to know how to do this as well.

**Comment by OlgaSukhoverkhaya** [comment] 2020-01-24 06:33
Not sure what you are looking for, but maybe this helps.
This <webview src="https://github.com" partition="persist:github"></webview> creates a separate session, for this partition name. You can access this session by partition name, or change a session by removing partition attribute, or adding a new one.
