### ISSUE TITLE
Electron windows v0.35.2 cannot use shell.moveItemToTrash

### ISSUE THREAD

**Issue by 25512345** [atom/electron#3656] opened 2015-12-02 06:48 UTC
Method shell.moveItemToTrash work for electron Mac OSX but in electron-v0.35.2-win32-ia32,  this method cannot move item to recycle bin and always return false
// OS: Windows 7

**Comment by zcbenz** [comment] 2015-12-02 09:22
I can confirm on Windows 7, seems to be a regression of #3337.

**Comment by oh-ren** [comment] 2015-12-02 17:57
... so it seems (if it's indeed a regression of #3337) this issue exists since [v0.34.3](https://github.com/atom/electron/releases/tag/v0.34.3) which is the base for Atom 1.3.0.
Then (to accommodate Atom 1.3.0 at least) I reckon this should also be fixed in the 0.34.x branch?

atom/atom#9909

**Comment by tylergibson** [comment] 2015-12-24 04:01
Thanks for the ping, Windows pre-8 check added with alternate flags.  Tested on Windows 7 Enterprise N.  Would much appreciate if someone can verify the check and alt flags works properly on Vista/8/8.1/10.  I'll start verifying tomorrow across the OS matrix just to be sure.

**Closed** 2015-12-24 07:32 UTC
Labels: bug, windows

**Comment by bpasero** [comment] 2015-12-29 08:22
@zcbenz would it be low effort to release v0.35.5 with a fix for this? this would give consumers a chance to benefit from this (imho severe) regression without jumping on 0.36.0 with the updated Chrome and node.js.

**Comment by zcbenz** [comment] 2015-12-31 02:04
@bpasero Sure thing, I'll publish a new release today.

**Comment by bpasero** [comment] 2015-12-31 06:29
@zcbenz Thanks!

**Comment by oh-ren** [comment] 2016-01-08 12:35
Wouldn't it also be worthwhile to do a 0.34 release with this fix (and perhaps other fixes)?
Atom is still @ 0.34, and I guess the upcoming Atom 1.4 will also be based on 0.34?

There's this: atom/atom/pull/9627, but I'm not sure how long that (still) may take, or if the Electron upgrade is targeted towards a certain Atom release (guess not?)
