### ISSUE TITLE
Crash reporter on OS X Yosemite (crashpad) doesn't send additional info (version, etc.)

### ISSUE THREAD

**Issue by Ivshti** [atom/electron#2230] opened 2015-07-15 09:50 UTC
The crash reporter on OS X (crashpad) does not send any data in the post request except:
```
{"guid":"c0466949-3045-4b52-afaa-daffa6997ab6"}
```

Meanwhile the Windows one sends all documented properties
```
{"_companyName":"Stremio","_productName":"Stremio","_version":"2.1.1","platform":"win32","process_type":"browser","prod":"Electron","ptime":"296","rept":"electron-crash-service","ver":"0.29.2"}
```

**Comment by zcbenz** [comment] 2015-07-16 09:38
Can you show how your server receives crash report? Our test works well:
https://github.com/atom/electron/blob/master/spec/api-crash-reporter-spec.coffee

**Comment by Ivshti** [comment] 2015-07-16 09:43
We use connect-multiparty
```
app.use(require("connect-multiparty")())
// other app initializations..

var minidump = require("minidump");
minidump.addSymbolPath.apply(minidump, require("electron-debug-symbols").paths);
router.post("/submit-crash", function(req, res)  {
    if (! req.files.upload_file_minidump) return res.send(404);

    minidump.walkStack(req.files.upload_file_minidump.path, "pool/symbols", function(err, report) {
        if (err) { console.error(err); res.send(500); }
        res.send(200);

        mailTransport.sendMail({
            from: "Stremio Support <support@strem.io>",
            to: "ivo@linvo.org",
            subject: "Stremio crashed at "+(new Date()).toString(),
            text: JSON.stringify(req.body) + "\n\n" + report.toString(),
        }, function(error, response) { if (error) console.error(error) });
    });
});
```

But I also tried about 2-3 other middlewares and all receive only guid: under req.body

**Comment by zcbenz** [comment] 2015-07-16 09:53
Can you paste the result by parsing the request like this?

```js
      form = new formidable.IncomingForm()
      form.parse req, (error, fields, files) ->
        console.log(fields);
```

**Comment by Ivshti** [comment] 2015-07-16 10:03
```
{ guid: 'c0466949-3045-4b52-afaa-daffa6997ab6' }
```
I even disabled all other middleware so as to not interfere with it.
```javascript
    var form = new require("formidable").IncomingForm();
    form.parse(req, function(err,fields,files){console.log(fields)})
```

Formidable 1.0.17

**Comment by zcbenz** [comment] 2015-07-16 10:20
This is weird, can you share how you call `crash-reporter`?

**Comment by Ivshti** [comment] 2015-07-16 10:29
```javascript
var pathname = "/submit-crash?symbols="+process.versions.electron;
  require("crash-reporter").start({ 
    productName: PRODUCT_NAME,
    companyName: PRODUCT_NAME,
    submitUrl: argv["local-crash-report"] ? "http://localhost:3000"+pathname : "http://www.strem.io"+pathname,
    autoSubmit: true,
    extra: { version: require("./package").version/*, macAddress: mac*/ }
  });
```

I've went through a lot of iterations of calling it, most time without extra: object - I added it simply because I wasn't receiving a version.

**Comment by Ivshti** [comment] 2015-07-16 10:50
@zcbenz as I said, the absolutely same code reports all data on Windows.

**Comment by zcbenz** [comment] 2015-07-16 11:10
@Ivshti Can you try running this app on your machine and paste the output in terminal? https://gist.github.com/zcbenz/9c75ccda4f925faf92ca

**Comment by Ivshti** [comment] 2015-07-16 11:27
Ok. Doing this now.

Does the crash reporter have to be started both on the renderer and the main process?

**Comment by Ivshti** [comment] 2015-07-16 11:29
```
Ivos-iMac:test-app ivogeorgiev$ ./node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron main.js 
[0716/142850:ERROR:file_io.cc(30)] read: expected 40, observed 0
[47474:0716/142851:INFO:renderer_main.cc(200)] Renderer process started
{ _companyName: 'GitHub, Inc',
  _productName: 'Electron',
  _version: '',
  guid: '57e1c9c1-1f6f-4a78-a63d-e800d6f90432',
  platform: 'darwin',
  process_type: 'renderer',
  prod: 'Electron',
  ver: '0.29.2' }
Ivos-iMac:test-app ivogeorgiev$ [0716/142852:ERROR:http_transport_mac.mm(186)] The network connection was lost. (NSURLErrorDomain -1005)
```

**Comment by zcbenz** [comment] 2015-07-16 11:30
> Does the crash reporter have to be started both on the renderer and the main process?

Yeah it is the side effect of switching to crashpad.

**Comment by zcbenz** [comment] 2015-07-16 11:31
So the test app works as expected, can you find out which call in your app has caused the different behavior?

**Comment by Ivshti** [comment] 2015-07-16 11:38
I've made the following changes
1. on the main process, call .start( when app is ready instead of before it
2. on the renderer process, init the crash reporter with the same args

Now I'm not getting a report at all.
I'll tell you when I figure it out.

**Comment by zcbenz** [comment] 2015-07-16 17:21
You can change my test app to make it reproduce this problem, otherwise it would be impossible for me to fix it.

**Comment by Ivshti** [comment] 2015-07-18 20:11
@zcbenz just excluded the server as a reason - I tried your server code and I still get only guid.

**Comment by Ivshti** [comment] 2015-08-03 13:59
Could be because of HTTP server initiated before app ready?

**Comment by zcbenz** [comment] 2015-08-27 09:26
We really can't do anything if there is no reproducible example, and anyway both the test and the demo app work fine, so I'm closing this until we get an app that reproduce this problem.

**Closed by zcbenz** 2015-08-27 09:26 UTC

**Comment by hongrich** [comment] 2015-08-28 22:11
I'm also seeing some OS X crash reports with no additional information, but I'm unable to reproduce it locally. Interestingly, all the ones with no additional information all have this same stack trace:

```
Thread 0 (crashed)
 0  libsystem_kernel.dylib + 0x16286
 1  libsystem_c.dylib + 0x5db53
 2  libnode.dylib!uv_sem_post [thread.c : 232 + 0x5]
 3  Electron Framework!atom::NodeBindings::~NodeBindings() [node_bindings.cc : 118 + 0x8]
 4  Electron Framework!atom::NodeBindingsMac::~NodeBindingsMac() [node_bindings_mac.cc : 27 + 0x5]
 5  Electron Framework!atom::NodeBindingsMac::~NodeBindingsMac() [node_bindings_mac.cc : 26 + 0x5]
 6  Electron Framework!atom::NodeBindingsMac::~NodeBindingsMac() [node_bindings_mac.cc : 26 + 0x5]
 7  Electron Framework!base::DefaultDeleter<atom::NodeBindings>::operator()(atom::NodeBindings*) const [scoped_ptr.h : 128 + 0xe]
 8  Electron Framework!base::internal::scoped_ptr_impl<atom::NodeBindings, base::DefaultDeleter<atom::NodeBindings> >::~scoped_ptr_impl() [scoped_ptr.h : 222 + 0x5]
 9  Electron Framework!base::internal::scoped_ptr_impl<atom::NodeBindings, base::DefaultDeleter<atom::NodeBindings> >::~scoped_ptr_impl() [scoped_ptr.h : 218 + 0x5]
10  Electron Framework!scoped_ptr<atom::NodeBindings, base::DefaultDeleter<atom::NodeBindings> >::~scoped_ptr() [scoped_ptr.h : 312 + 0x5]
11  Electron Framework!scoped_ptr<atom::NodeBindings, base::DefaultDeleter<atom::NodeBindings> >::~scoped_ptr() [scoped_ptr.h : 312 + 0x5]
12  Electron Framework!atom::AtomRendererClient::~AtomRendererClient() [atom_renderer_client.cc : 86 + 0x15]
13  Electron Framework!atom::AtomRendererClient::~AtomRendererClient() [atom_renderer_client.cc : 85 + 0x5]
14  Electron Framework!atom::AtomRendererClient::~AtomRendererClient() [atom_renderer_client.cc : 85 + 0x5]
15  Electron Framework!base::DefaultDeleter<content::ContentRendererClient>::operator()(content::ContentRendererClient*) const [scoped_ptr.h : 128 + 0xe]
16  Electron Framework!base::internal::scoped_ptr_impl<content::ContentRendererClient, base::DefaultDeleter<content::ContentRendererClient> >::~scoped_ptr_impl() [scoped_ptr.h : 222 + 0x5]
17  Electron Framework!base::internal::scoped_ptr_impl<content::ContentRendererClient, base::DefaultDeleter<content::ContentRendererClient> >::~scoped_ptr_impl() [scoped_ptr.h : 218 + 0x5]
18  Electron Framework!scoped_ptr<content::ContentRendererClient, base::DefaultDeleter<content::ContentRendererClient> >::~scoped_ptr() [scoped_ptr.h : 312 + 0x5]
19  Electron Framework!scoped_ptr<content::ContentRendererClient, base::DefaultDeleter<content::ContentRendererClient> >::~scoped_ptr() [scoped_ptr.h : 312 + 0x5]
20  Electron Framework!atom::AtomMainDelegate::~AtomMainDelegate() [atom_main_delegate.cc : 27 + 0x12]
21  Electron Framework!atom::AtomMainDelegate::~AtomMainDelegate() [atom_main_delegate.cc : 26 + 0x5]
22  Electron Framework!AtomMain [atom_library_main.mm : 24 + 0x5]
```

**Comment by SofianHn** [comment] 2015-09-28 22:58
I am seeing the same issue in 0.27.3. Locally all data comes fine but lots of the OSX reports wont contain any information beside the crash dump. I can't reproduce this locally, but what else can we do to help trace this issue?
