### ISSUE TITLE
electron 64bit  can't run in win7 64bit

### ISSUE THREAD

**Issue by jt6562** [atom/electron#2126] opened 2015-07-06 02:23 UTC
I tried electron v0.28.1 and v0.28.3. When I double-click electron.exe, nothing happened.
It should open a default app about file drop-drap, but no any window opened.

I tried put `console.log` in app.on('ready') function in default_app，and run `electron` in windows console. No debug info output.

PS: It work find in win8.

Can anyone help me?

**Comment by zcbenz** [comment] 2015-07-06 08:35
Do you have any anti-virus program installed? And does the 32bit build work on your machine? I can not reproduce on a fresh Windows 7 machine, and it is impossible to figure out what actually happened from your descriptions.

**Comment by jt6562** [comment] 2015-07-06 09:48
Yes, 32bit build work.

And I trid on a fresh win7 VM of vbox, it works, but not on another 3 real machines

How to get some low-level debug info?

**Comment by zcbenz** [comment] 2015-07-07 02:46
You can use windbg to debug this if you are familiar with it. But since it works in a fresh VM I believe it is more likely caused by the anti-virus softwares, can you try turning off all the security softwares? Some anti-virus programs [are treating electron as malware](https://github.com/atom/atom/issues/3927).

**Comment by zcbenz** [comment] 2015-07-10 03:07
Closing since I believe it is caused by anti-virus softwares.

**Closed by zcbenz** 2015-07-10 03:07 UTC

**Comment by evernaut** [comment] 2015-11-17 16:47
I know this is an old, closed issue, but I just wanted to say that I ran into this as well. Fresh parallels install of a Win7x64 Enterprise. An app that I built in 32bit-mode works fine, 64bit-mode does not. However, if I copy the 64bit-mode build onto a later OS (8/8.1/10) it opens fine. No anti-virus installed. UAC set to lowest level allowed.

**Comment by demeyr** [comment] 2016-01-16 09:52
I have the same issue but on Windows 8.1.

32 bit works but 64 bit doesn't.
I'm for example stuck on the Docket Kitemac built that's only available on 64 bit.

Anti-virus is symantec but no warning or anything in the logs + I added the necessary exceptions.

**Comment by MrVil** [comment] 2016-01-31 14:40
Same issue on Windows 10
It work fine on my laptop, but not on my main PC.
32 bits works.
I don't have any anti-virus neither.

**Comment by bbondy** [comment] 2016-01-31 15:27
Try clearing out your `external_binaries`.  The bootstrap script won't redownload after you build x86 so it'll grab the wrong msvcrt binaries.

**Comment by minggo** [comment] 2016-09-21 09:07
What's `external_binaries `? Do you mean `libchromiumcontent`? If so i think it will mean linking errors.

**Comment by nantas** [comment] 2016-09-21 09:54
I've got similar issue, double click electron.exe and nothing happens.

OS: Windows 10
Arch: x64

Only debug build has this issue, release build works fine.

**Comment by Rafi993** [comment] 2016-12-11 16:08
same here. Hope it gets fixed soon

**OS**: Windows 10
**Arch**: X64
