### ISSUE TITLE
Mac App Store

### ISSUE THREAD

**Issue by wisesascha** [atom/electron#2067] opened 2015-06-27 00:12 UTC
Has anyone successfully attempted to patch Electron in a similar manner to how trevorlinton did for NW.js [here](https://github.com/nwjs/chromium.src/pull/17). Is a patch of this manner even required any more, as there was mention of many private apis being removed from a recent version of chromium.

**Comment by zcbenz** [comment] 2015-06-29 05:08
This is a duplicate of #249.

**Closed by zcbenz** 2015-06-29 05:08 UTC
