### ISSUE TITLE
focus() doesn't focus web view for window at start

### ISSUE THREAD

**Issue by foolyoghurt** [atom/electron#1773] opened 2015-05-26 08:10 UTC
This problem is similar to [issue#382](https://github.com/atom/electron/issues/382), but it doesn't solve the problem.

**Environment**
> OSX: 10.0.9 
> Electron: 0.26.0

When I  **first start** my app, `focus()` and `focusOnWebView()` doesn't really focus on the web view of the window. And keyboard press event listening doesn't work until I click the web page. But If I then switch to other app and switch back, it works.

**Comment by zcbenz** [comment] 2015-05-27 08:20
I'm not able to reproduce this, I opened `http://robertwhurst.github.io/KeyboardJS/` and the keyboard listener in it works.

**Comment by zcbenz** [comment] 2015-05-28 07:30
Closing until there is more information provided.

**Closed by zcbenz** 2015-05-28 07:30 UTC

**Comment by foolyoghurt** [comment] 2015-05-28 19:25
@zcbenz Sorry, there is nothing wrong with keyboard listener. The problem is when I open my app, the web view of the window can not get focus. So I need to **click** the web view **first** to make it focused before I can use any key that I bind in the program.

**Comment by steelbrain** [comment] 2015-05-28 19:28
@foolyoghurt Are you looking for the focus event for browser-window?

**Comment by foolyoghurt** [comment] 2015-05-28 20:02
@steelbrain no, I just want to focus on my html content area at the time I open my app. And now it just focus on the browser window not the html content area, so the corresponding key event handler will not be triggered after I press the key.

**Comment by zcbenz** [comment] 2015-05-29 10:01
The keyboard listener linked I posted can only work when the web view is focused, if it is working for you then the web view is focused without problem. You should check your code.

**Comment by foolyoghurt** [comment] 2015-05-29 16:13
@zcbenz The problem is web view can not be focused automatically when I open my app, I need to click the web view to make it focused.

**Comment by brunze** [comment] 2015-06-24 18:56
I have the same problem here.

I have the `autofocus` attribute on an input but it doesn't automatically focus after start. I'm also using the `<dialog>` element which the browser automatically closes when you press Esc but that doesn't happen until I click the window first. 

Menu items with accelerators trigger just fine but I have one command that is supposed to focus an input but it doesn't do it, despite the visual cue in the menu bar telling me the command was run.

But here's an interesting twist: if I launch the app from the command line, the bug doesn't happen; everything works as expected. The bug only occurs when launching from the icon or Spotlight.

**Comment by javan** [comment] 2016-02-07 00:49
I'm not sure if this is the same issue, but I've been trying to figure out why the emoji picker on OS X is often positioned incorrectly inside a `<webview>` and it seems related. What I've found is that the host html page must be focused first (clicking works), then the webview's page must be focused, and *then* it will position correctly.

Here's a recording of the behavior. The `<webview>` has a red background. Each page's background is yellow while the mouse is down.

![focus](https://cloud.githubusercontent.com/assets/5355/12870231/0b6d6cf8-cd09-11e5-8d31-f99cb0b3c1e2.gif)

Tested on OS X 10.11.3 with Electron 0.36.7 using this code:  https://gist.github.com/javan/be0bfcfe237f7583d2e4

As an aside, I noticed adding `autofocus` to the input element in the `<webview>` has no effect. The input is not focused when loaded.

In some ways, my issue sounds similar to https://github.com/atom/electron/issues/382:

> The window is focused but I cannot trap keyboard press using mousetrap until I make a click on the web view inside the window.

**Comment by michaeldegroot** [comment] 2016-05-24 17:59
I have this issue only when I execute `mainWindow.webContents.openDevTools()` @ `app.on('ready', () => {`

**Comment by tolmasky** [comment] 2016-09-12 05:03
I am also experiencing this, with or without openDevTools().

**Comment by mjackson** [comment] 2016-10-22 00:37
I ran into this same issue today. To reproduce, just render a `<webview>` in the currently focused `webContents` that renders a page with an `<input autofocus/>`. It won't be focused until you click into it.

@zcbenz Can you please reopen?

**Comment by mjackson** [comment] 2016-10-22 00:41
Oh snap. I just discovered a fix.

```js
const webview = document.getElementById('my-webview')

webview.addEventListener('dom-ready', () => {
  webview.focus()
})
```

**Comment by snene** [comment] 2016-10-25 18:53
Thank you @mjackson! That worked and solved my problem!

**Comment by hrishimk** [comment] 2017-08-12 09:03
This worked for me
```
const webview = document.getElementById('my-webview')

webview.addEventListener('dom-ready', () => {
  window.blur();
  window.focus();
});
```

**Comment by liurenqiu520** [comment] 2018-12-11 11:52
> This worked for me
> 
> ```
> const webview = document.getElementById('my-webview')
> 
> webview.addEventListener('dom-ready', () => {
>   this.focus();
>   window.blur();
>   window.focus();
> });
> ```

it's worked for me

**Comment by salfredogonzalez** [comment] 2018-12-11 14:14
> const webview = document.getElementById('my-webview') webview.addEventListener('dom-ready', () => { this.focus(); window.blur(); window.focus(); });

Would yo please clarify, where are you using this values, i got the same issue but not in a webview, i did try using with the script tag in the bottom of my first page, didnt work.
Also i did try using inside of the main function of the BrowserWindow, also inside of the ready-to-show, didnt work.
Thanks

**Comment by LeBlackDonut** [comment] 2020-11-26 23:49
I recently had this same problem and turns out that when the window is draggable then it wont select the input on click

**Comment by Y2zz** [comment] 2020-12-31 02:58
This method doesn't work for me

**Comment by aspdev91** [comment] 2021-05-23 01:50
> I recently had this same problem and turns out that when the window is draggable then it wont select the input on click

This fixed it for me. Thanks @LeBlackDonut. Closing dev tools didn't help. I couldn't enter text into inputs on a window and had to add this to the html body:

```
  <body style="-webkit-app-region: no-drag">
  </body>
```

**Comment by andersk** [comment] 2021-11-19 22:18
Reopened as #31918 with a concrete test case.
