### ISSUE TITLE
Flash fullscreen doesn't work properly

### ISSUE THREAD

**Issue by radarek** [atom/electron#1942] opened 2015-06-11 17:03 UTC
When I enter to fullscreen mode with flash it stops refreshing. Screen is freezed but audio works ok. The same happens to both youtube player (flash version) and twitch.tv. In Chrome it works ok. Is it electron fault or bug in flash?

Below is index.html and index.js files to reproduce problem:

index.js
```javascript
var app = require('app');
var BrowserWindow = require('browser-window');

require('crash-reporter').start();

var mainWindow = null;

app.on('window-all-closed', function() {
  if (process.platform != 'darwin') {
    app.quit();
  }
});

app.on('ready', function() {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    "web-preferences": {
      "plugins": true
    }
  });

  mainWindow.loadUrl('file://' + __dirname + '/index.html');
  mainWindow.on('closed', function() {
    mainWindow = null;
  });
});
```

index.html
```html
<!DOCTYPE html>
<html>
  <body>
    <object width="640" height="390">
      <param name="movie"
             value="https://www.youtube.com/v/M7lc1UVf-VE?version=3&autoplay=1"></param>
      <param name="allowScriptAccess" value="always"></param>
      <embed src="https://www.youtube.com/v/M7lc1UVf-VE?version=3&autoplay=1&fs=1"
             type="application/x-shockwave-flash"
             allowscriptaccess="always" allowfullscreen="true"
             width="640" height="390"></embed>
    </object>
  </body>
</html>
```

**Comment by deepak1556** [comment] 2015-06-11 21:26
Could you specify the OS, was unable to reproduce on OSX(10.9.5) with both NPAPI and PPAPI. From your config seems like you are relying NPAPI plugin and on OSX yosermite there is an unconfimed [issue](https://code.google.com/p/chromium/issues/detail?id=484584) . Suggestion would be to try PPAPI flash plugin.

**Comment by radarek** [comment] 2015-06-12 07:41
Yes, it is OSX 10.10.3 (Yosemite). Could you tell me how can I use PPAPI flash plugin? Is there any documentation for that part?

**Comment by deepak1556** [comment] 2015-06-12 08:03
You can check https://github.com/atom/electron/blob/master/docs/tutorial/using-pepper-flash-plugin.md on how to use ppapi flash plugin.

**Comment by zcbenz** [comment] 2015-06-12 08:11
I'm closing this since NPAPI support is going to be removed soon so we won't fix any NPAPI related bugs.

**Closed by zcbenz** 2015-06-12 08:11 UTC

**Comment by coreybruce** [comment] 2018-09-28 11:15
is flash being removed? can it just be kept in the code for people who want to continue to use flash for example lagacy applications for flash ect?
