### ISSUE TITLE
Hooking windows messages

### ISSUE THREAD

**Issue by omrilitov** [atom/electron#3217] opened 2015-10-26 11:10 UTC
There are many native features that will require listening to windows messages and alter them.
It's important to hook to the original wndproc so we'll be able to alter messages as well.
After digging in I noticed there is a PreHandleMSG in here https://github.com/atom/electron/blob/master/atom/browser/native_window_views_win.cc#L81
And after a bit of testings I managed to affect the messages a windows is receiving.

I wonder if it is the best way to hook into the wndproc
Any thoughts?

**Comment by paulcbetts** [comment] 2015-10-26 15:53
I would be :+1: on having a way to do this

**Comment by zcbenz** [comment] 2015-10-27 02:43
This is a duplicate of #1121.

**Closed by zcbenz** 2015-10-27 02:43 UTC
