### ISSUE TITLE
preload only gets run before first loadUrl

### ISSUE THREAD

**Issue by maxogden** [atom/electron#2141] opened 2015-07-07 03:59 UTC
my goal is to create a browser window, have it load multiple pages (e.g. clicking links, loading new page etc in same window) but having the ipc available from the window on each page it loads so I can send data back to the server process

I have a `preload` script that does `global.ELECTRON_IPC = require('ipc')` and I have `node-integration: false` to not expose anything else

When I create a browser window and call `loadUrl`, then wait for `dom-ready`, the `ELECTRON_IPC` variable is there

However, when I click on a link (causing the window to navigate to a new url), and wait for `dom-ready` again, the `ELECTRON_IPC` variable is not there this time.

I'm guessing this behavior is because preload only gets called when the browser window is created. Would it make sense to call it before each load? e.g. after `will-navigate`?

Another way to ask the question would be: how else could I only expose IPC communications from the renderer to the server (but nothing else) in a way that is available across `loadUrl` calls?

**Comment by zcbenz** [comment] 2015-07-08 03:02
I saw similar problems in the past and all of them had been fixed, can you create a simple demo? It might be a new bug.

**Comment by maxogden** [comment] 2015-07-08 17:09
`app.js`

```js
var app = require('app')
var BrowserWindow = require('browser-window')
var path = require('path')

app.on('ready', function () {
  var win = new BrowserWindow({
    "web-preferences": {
      "web-security": true
    },
    "node-integration": false,
    preload: path.resolve(path.join(__dirname, 'preload.js')),
    show: true
  })
  
  win.loadUrl('http://hoytarboretum.gardenexplorer.org/taxalist.aspx')  
})
```

`preload.js`

```js
global.ELECTRON_IPC = require('ipc')
```

When I run (with `0.29.2`) `electron app.js`, and then open DevTools, the variable `ELECTRON_IPC` is there. When I click on one of the letters, then go back to the console, `ELECTRON_IPC` is undefined.

**Comment by maxogden** [comment] 2015-07-08 17:12
Very weird, it seems to only happen on `http://hoytarboretum.gardenexplorer.org/taxalist.aspx`, e.g. if I change it to `https://github.com` it works as expected. Hmm....

**Comment by maxogden** [comment] 2015-07-08 23:03
@zcbenz Upon further inspection it looks like the only case where I can prevent the `preload` from running is clicking the links on http://hoytarboretum.gardenexplorer.org/taxalist.aspx, which are actually `<input>`s that POSTs a form through an `onclick`:

```
<input type="button" name="ctl00$ContentPlaceHolder1$Repeater1$ctl05$btnLetter" value=" F " onclick="javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder1$Repeater1$ctl05$btnLetter&quot;, &quot;&quot;, false, &quot;&quot;, &quot;taxalist-F.aspx&quot;, false, true))" id="ctl00_ContentPlaceHolder1_Repeater1_ctl05_btnLetter" class="button buttonauto noprint" style="font-weight:bold;">
```

Not sure what about this would be causing Electron to not load the `prebuilt` though, it's a pretty weird bug

**Comment by maxogden** [comment] 2015-07-08 23:16
Most minimal test case I can come up with at this time is:

```js
var app = require('app')
var BrowserWindow = require('browser-window')
var path = require('path')

app.on('ready', function () {
  var win = new BrowserWindow({
    show: true
  })
  
  win.loadUrl('http://hoytarboretum.gardenexplorer.org/taxalist-A.aspx')  
})
```

Note this is the `taxalist-A` link directly. Works on first load (e.g. `require` is defined), but when you click on one of the other letters (making it submit the POST and loading the new page) `require` is no longer defined.

**Comment by zcbenz** [comment] 2015-07-09 03:42
This is a duplicate of #1959.

**Closed by zcbenz** 2015-07-09 03:42 UTC
