### ISSUE TITLE
Global Shortcut Numpad

### ISSUE THREAD

**Issue by Crunk** [atom/electron#4147] opened 2016-01-18 15:06 UTC
I can't seem to get any numpad shortcuts .. tried '1' and it really just fires on the '1' key.
Would expect something like 'numpad0' to 'numpad9'.

Guess it's a missing feature so far?

**Comment by Crunk** [comment] 2016-01-19 14:31
That was actually pretty stupid, sorry.
NumPad[0..9]

**Comment by zcbenz** [comment] 2016-01-19 19:54
This is a duplicate of #3332.

**Closed by zcbenz** 2016-01-19 19:54 UTC
