### ISSUE TITLE
Auto Updater fails to spawn

### ISSUE THREAD

**Issue by MarshallOfSound** [atom/electron#4697] opened 2016-03-06 22:34 UTC
* Electron version: `0.36.7`
* Operating system: `Windows x86`

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/282

My `uncaughtException` has picked this one up a few times now.  It occurs seemingly randomly and I've only seen it on like 5 machines out of thousands so it's obscenely rare.

Is there anything I can do to prevent this error?

**Comment by paulcbetts** [comment] 2016-03-07 00:22
@MarshallOfSound It's probably Antivirus kicking in, signing your app will help but costs $$

**Comment by MarshallOfSound** [comment] 2016-03-07 00:35
The app is signed with `sha1` and `sha256` digests :)

**Comment by paulcbetts** [comment] 2016-03-07 00:36
In that case, this is just The Reality Of Developing Software On Windows :(

**Comment by ZakariaRidouh** [comment] 2016-03-07 00:37
@MarshallOfSound is it anti-virus then? I'll dig through the Electron issues to see if this is just a problem with Electron or with the actual app.

**Comment by MarshallOfSound** [comment] 2016-03-07 00:53
@paulcbetts I suspected as much, you gotta love windows :cry:

**Comment by zcbenz** [comment] 2016-03-07 04:50
Closing since it is caused by anti-virus programs and we are unable to fix this.

**Closed by zcbenz** 2016-03-07 04:50 UTC

**Comment by GitFlip** [comment] 2018-04-27 13:50
Sorry to comment on a closed issue, but I'm hoping to just get a couple questions answered because I have this issue.

I'm not signing my app, as I'm just testing things out right now. How can I verify that it's the antivirus kicking in that is causing this issue? I don't have any 3rd party antivirus programs, I only use Windows Defender on Windows 10.

Is there anything that I can do to prevent this from happening? It seems like @MarshallOfSound still saw the issue when signing the app.

Lastly, should I be calling `autoUpdater.checkForUpdates();` as soon as possible, or should I only call it after the app has emited the 'ready' event?

Thank you!
