### ISSUE TITLE
[Windows] Missing unmaximize event

### ISSUE THREAD

**Issue by etiktin** [atom/electron#2405] opened 2015-08-02 20:42 UTC
When you maximize a window and then try to drag it down from the border (or in my case a header div with `-webkit-app-region: drag;` style), the window will unmaximize, but instead of getting the `unmaximize` event you'll just get the `resize` event.
If you do the same using the restore button (either through the border or using the taskbar menu item), you will get the `unmaximize` event and then the `resize` event, like you get with the rest of the size-change events.

This was tested on Windows 8.1 (64 bit) using Electron v0.30.2.

**Comment by zcbenz** [comment] 2015-08-03 07:57
This is a duplicate of #1381.

**Closed by zcbenz** 2015-08-03 07:57 UTC
