### ISSUE TITLE
Notifications appearing as Alerts on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by madhav-datt** [atom/electron#4489] opened 2016-02-15 17:57 UTC
Apologies in advance if this is a duplicate. 

This is more about the aesthetics of the notifications (functionally, no problems). Even when I try to create them manually with `new Notification("abc")`, I get an alert box instead of the notification one.

This does not seem like an OS issue as `$ notify-send abc xyz` and other applications give notifications as expected.

**Comment by zcbenz** [comment] 2016-02-16 13:22
This is a duplicate of #465.

**Closed by zcbenz** 2016-02-16 13:22 UTC
