### ISSUE TITLE
"Cmd+Plus" accelerator ends up as "Shift+Cmd+="

### ISSUE THREAD

**Issue by Arcnor** [atom/electron#2458] opened 2015-08-09 23:18 UTC
As the title says, the accelerator "Cmd+Plus" (or `CmdOrCtrl`) ends up as "Shift+Cmd+=". I understand that to get "+" you need to press "Shift+=" on a US keyboard. However, there is also another `Plus` key on the numeric part of the keyboard that doesn't work if the binding is not "Cmd+Plus". Why is Electron doing this transformation without being asked? Can this be avoided?

**Comment by zcbenz** [comment] 2015-08-10 07:34
This is a duplicate of https://github.com/atom/electron/issues/1507.

**Closed by zcbenz** 2015-08-10 07:34 UTC
