### ISSUE TITLE
Script tag behaviour problem

### ISSUE THREAD

**Issue by EduardJS** [atom/electron#4703] opened 2016-03-07 12:48 UTC
* Electron version: 0.36.10
* Operating system: Windows 8.1 64bit

Hello ! I have just created a simple window which loads an url.

The problem is that while visiting the URL in chrome or any other browser, everything is fine, but when opening it in Electron, it says jQuery is not defined.

The problem comes from here:

<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<script type="text/javascript">
	// some code using jQuery
</script>

Returning `Uncaught ReferenceError: $ is not defined`.
if I would set a timeout, everything works. But, wasn't that supposed to happen when `async` tag is set to true ?

This behaviour looks pretty much like `async="true"` on script tags.
I have also tried setting that `async` tag to `false` but still, same behaviour.

I decided not to use a local `index.html` file that would contain a `webview` because of the white background that appears, and then, the `did-finish-loading` which gets triggered when the local page loads but not the webview ( which is to be expected )

Therefore I am running the app like the following `window.loadURL('https://tribul.net')`;

Is it an expected behaviour ?

**Comment by kevinsawicki** [comment] 2016-03-07 23:37
I believe this is a duplicate of https://github.com/atom/electron/issues/254

That issue explains a workaround to get this working.

**Closed by kevinsawicki** 2016-03-07 23:37 UTC
