### ISSUE TITLE
exe link error --> Unexpected PDB error

### ISSUE THREAD

**Issue by ashengwang** [atom/electron#2902] opened 2015-09-25 09:46 UTC
hi 
I just get the master code yesterday. but build failed.anyone can give me some hints?

E:\github\electron>python script\build.py -c R
ninja: Entering directory `out\R'
[1/1] LINK_EMBED electron.exe
FAILED: C:\Program Files\Python27\python.exe gyp-win-tool link-with-manifests en
vironment.x86 True electron.exe "C:\Program Files\Python27\python.exe gyp-win-to
ol link-wrapper environment.x86 False link.exe /nologo /OUT:electron.exe @electr
on.exe.rsp" 1 mt.exe rc.exe "obj\electron.electron.exe.intermediate.manifest" ob
j\electron.electron.exe.generated.manifest ..\..\atom\browser\resources\win\atom
.manifest
wm.lib(wm.base_focus_rules.obj) : fatal error LNK1318: Unexpected PDB error; OK
(0) ''
Traceback (most recent call last):
  File "gyp-win-tool", line 316, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 169, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "C:\Program Files\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Program Files\Python27\python.exe gyp
-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:electron.exe
@electron.exe.rsp electron.exe.manifest.res' returned non-zero exit status 1318
ninja: build stopped: subcommand failed.

**Comment by ashengwang** [comment] 2015-09-25 09:49
OS is win7. code is after pull request #2875 .

**Comment by zcbenz** [comment] 2015-09-26 13:26
Can you try removing the `out` folder and then build again?

**Comment by zcbenz** [comment] 2015-10-03 05:50
Closing until more information is provided.

**Closed by zcbenz** 2015-10-03 05:50 UTC
Labels: more-information-needed

**Comment by rushikesh90** [comment] 2016-02-06 12:45
Hi I got the same error and after removing out folder I am getting following error:
ninja: fatal: chdir to 'out\R' - No such file or directory
ninja: Entering directory `out\R'

**Comment by dvillarraga** [comment] 2016-03-24 02:39
Hi, I got the same error, unfortunately I couldn't get the reason, there are some information it may help:

OS: Win7/32Bits
Phyton 2.7
NodeJS 4.4.0
Visual Studio 2013 Community Edition

Anybody knows what can I do ?

**Comment by evgenyzinoviev** [comment] 2016-03-30 23:28
In my case OP-like `Unexpected PDB error blah-blah` happened because my machine had not enough RAM.

**Comment by rushikesh90** [comment] 2016-03-31 05:27
I have 4GB RAM, and I am sure the program dont need that much. The problem is RAM use keeps on increasing till it consumes all of the RAM. I am sure this is the problem with the project itself.

**Comment by zcbenz** [comment] 2016-03-31 12:28
Running Electron doesn't need that much RAM, but building the Release version of Electron requires at least 8GB RAM.
