### ISSUE TITLE
dev-tools source maps not working 0.27.x

### ISSUE THREAD

**Issue by stumitchell** [atom/electron#1872] opened 2015-06-05 05:14 UTC
Hi it seems that the chrome dev tools in 0.27.x do not see source maps 

I am programming with clojurescript and when I use the chrome dev-tools on in 0.26.1 I can see both the `.js` files and the `.cljs` files.

In 0.27.0 and 0.27.2 I only can see the `.js` files

**Comment by zcbenz** [comment] 2015-06-05 05:25
This is a duplicate of #1842 and has been fixed, the fix will be shipped in next release.

**Closed by zcbenz** 2015-06-05 05:25 UTC

**Comment by stumitchell** [comment] 2015-06-07 23:34
Thx

**Comment by Dashed** [comment] 2015-06-12 00:27
:+1:  Thanks @zcbenz!
