### ISSUE TITLE
Notifications on Windows

### ISSUE THREAD

**Issue by Subash** [atom/electron#262] opened 2014-05-07 08:14 UTC
webkitNotifications api seems to be implemented in mac build but not in windows build.

**Comment by FLasH3r** [comment] 2015-05-02 14:23
+1

**Comment by shripathee** [comment] 2015-05-27 12:11
Any roadmap for resolution of this issue? This is a pretty big deterrent for using Electron.

**Comment by JonathanPierce** [comment] 2015-05-27 23:21
Agreed. Native notifications are a big deal, they are even advertised on the Electron homepage. The fact that they don't work on Windows is hugely disappointing.

**Comment by paulcbetts** [comment] 2015-05-27 23:36
I mean, it's hugely disappointing that Windows makes it a total PITA to implement notifications, sooooooooooo

**Comment by Glavin001** [comment] 2015-06-03 13:37
What about using the [Windows Toast Notifications support from Node-Notifier](https://github.com/mikaelbr/node-notifier#usage-windowstoaster)?

**Comment by paulcbetts** [comment] 2015-06-03 17:58
@Glavin001 You have to create a dummy shortcut in users' start menus to use that, it's a pretty big drawback

**Comment by Glavin001** [comment] 2015-06-03 18:05
@paulcbetts Oh wow. Thanks for letting me know. Bummer.

I am usually not a Windows user, let alone Windows app developer, however I recently won a Microsoft Surface and realize I really miss not being able to receive SMS notifications on my Surface from my iPhone, like my Macbook does. I hope to develop this project with Electron, although this lack of Windows notification support puts a speed bump in that plan.

**Comment by hleumas** [comment] 2015-06-23 20:12
Hi guys,

my app is using web notifications but it does not work on windows (because of this ticket). Can I shim notification API somehow, so it does tray bubble instead?

The thing is, I can't change the clientside code, cause I am loading it from public url. The app is just packaged webapp.

However, if I were able to shim Notification API from the main script, it would be awesome. Do you know whether something like that is possible?

Thanks a lot!

**Comment by iSuslov** [comment] 2015-06-29 00:16
+1 for this. Any workaround without end-user troubles?

**Comment by hleumas** [comment] 2015-06-29 06:13
Ok, it works this way:

    webContents.executeJavascript(`
      ipc = require('ipc');
      Notification = function(title, options) {
        ipc.send('notify', {title: title, options: options});
      }
      Notification.permission = 'granted'
    `

This way I can listen in main thread on `notify` messages and do whatever I want with them.

**Comment by xenyou** [comment] 2015-07-10 15:09
+1

**Comment by s-a** [comment] 2015-08-05 19:09
Hi,
I am experimenting with a toaster at https://github.com/s-a/electron-toaster.  
It aims to work with electron tools and to have an identical look across different platforms. 

I tried to design it close the chrome rich text notifications, but i' am not the best designer :smile: Regardless to restrictions and features of different native notification systems we could build something that mimics chrome rich text notifications.

![image](https://cloud.githubusercontent.com/assets/1270662/9094963/2079a426-3bb5-11e5-8399-d188fa9a8296.png)

So far it fits my needs. If any one is interested. Would be cool to hear your thoughts about this.

**Comment by clay-morgan** [comment] 2015-08-13 21:35
I'm interested in where that is going for sure.  This is a definite roadblock to us using Electron at the moment.

**Comment by jmesquita** [comment] 2015-08-18 00:48
@s-a that's nice! but... I am not a windows user but I am assuming it is not able to detect that other notifications are in place and therefore it would be placed on top of other notifications creating a kinda weird user experience? Just asking...

**Comment by s-a** [comment] 2015-08-18 05:00
@jmesquita ty for your feedback. When I remember back I cannot remember such a situation, but in fact you are absolutely right.

**Comment by seriema** [comment] 2015-11-08 08:30
I tried @hleumas idea and it worked well for me. So I made [electron-notification-shim](https://github.com/seriema/electron-notification-shim) in case someone else wants to use it. You can install it from [npm](https://www.npmjs.com/package/electron-notification-shim).

```
// Require and run in rendering process.
// Put it in a `if(process.platform === 'win32')` if you only want it for Windows.
require('electron-notification-shim')();
```

```
// Get events in main process.
ipc.on('notification-shim', (e, msg) => { ... });
```

From there you can pop up toasters with @s-a's [electron-toaster](https://github.com/s-a/electron-toaster), or [node-notifier](https://github.com/mikaelbr/node-notifier) which worked out of the box for me (not sure what @paulcbetts meant). The event also worked well for adding badges to the app icon, and counting missed notifications in the rendering view by using `e.returnValue =` or `e.sender.send()` from the main process. It's been so useful I'm wondering if `electron` triggering a `notification` event would be the way forward?

**Comment by felixrieseberg** [comment] 2015-11-11 15:11
![professor-dance1](https://cloud.githubusercontent.com/assets/1426799/11094127/443d3168-888e-11e5-953c-4acb4dbbb473.gif)

Good news everyone! Notifications for Windows 8, 8.1, and 10 have arrived in Brightray. Until @zcbenz cuts a new release of Electron, you'll have to build it yourself to use it today, but we can close this issue for now. If you're looking for some documentation, [I added some here](https://github.com/atom/electron/blob/master/docs/tutorial/desktop-environment-integration.md#notifications-windows-linux-os-x).

**Closed by felixrieseberg** 2015-11-11 15:11 UTC
Labels: enhancement, windows

**Comment by lipis** [comment] 2015-11-19 10:42
@felixrieseberg Is this suppose to work out of the box in the version `0.35.0` or is not there yet?

**Comment by lipis** [comment] 2015-11-19 10:48
That could be related: https://github.com/atom/brightray/commit/3b89c68e83648b39c7ddf58d8e462c4b73e744f0

**Comment by felixrieseberg** [comment] 2015-11-19 14:22
Yeah, should work out of the box in 0.35. We did indeed have a small issue with notifications that contain icons (which is already fixed and will be part of the next electron release). There are some caveats on everything that isn't Windows 10 - check out https://github.com/atom/electron/blob/master/docs/tutorial/desktop-environment-integration.md#notifications-windows-linux-os-x for details!

**Comment by lipis** [comment] 2015-11-19 14:51
@felixrieseberg Our notifications contain an icon.. so we might have to wait until the next release.. :)

**Comment by fantasticsid** [comment] 2016-03-31 21:51
@felixrieseberg does notification work on Windows 8.1? It doesn't seem to do so even if I have a shortcut  with `appUserModelId` set and also call `electron.app.setAppUserModelId` at start up..

any suggestions what could be wrong?

If the implementation for Windows 8.1 is complete but somehow it's not working properly, I can also dig into it and see what's going on..

**Comment by felixrieseberg** [comment] 2016-03-31 21:57
Something really simple that should work: Download electron.exe, run, open up dev tools, run `new Notification('Hi!')`. If you're not seeing anything, it's very likely that notifications on your system or for your user are somehow disabled.

**Comment by fantasticsid** [comment] 2016-03-31 22:11
Not seeing anything with electron.exe

I'm interested to knowing how notification is implemented on Windows 8.1, since it doesn't have a notification center as Win 10..

**Comment by fantasticsid** [comment] 2016-03-31 22:20
Oh I did see a `Notifications` section in `Settings`, they are all enabled though..

**Comment by felixrieseberg** [comment] 2016-03-31 22:46
Hold on, we might have a regression here.

**Comment by felixrieseberg** [comment] 2016-03-31 23:09
Upon inspection, we don't have a regression, but getting 8.1 setup to accept notifications is a bit tricky and the documentation I wrote is not nearly as detailed as it has to be. I'll add some docs there, but in the meantime, here are the important steps:

 * Your app needs a shortcut in the start menu
 * The shortcut needs a the property `system.appusermodel.id` set to your AppId
 * Your appId needs to be set

The good news: Squirrel handles that all for you.

**Comment by fantasticsid** [comment] 2016-03-31 23:27
That's weird, I think I'm doing these correctly. My update.exe file verison is '1.2.5.0', I think it's pretty new..

**Comment by fantasticsid** [comment] 2016-03-31 23:41
Is it possible to test things out with electron.exe?

Here's my attempt at getting notification to work for it:

1. I downloaded electron from https://github.com/atom/electron/releases
2. I created a shortcut by 'right click on electron.exe -> create shortcut'
3. I edited the app UserModelId to `com.squirrel.electron.electron` (I used the trick here to edit the property: http://winaero.com/blog/how-to-show-more-details-for-shortcuts-in-windows-8-1-windows-8-and-windows-7/)
4. I dragged the shortcut to windows start menu (literally dragged the shortcut on to the windows start icon at bottom left..)
5. I clicked open the shortcut from start screen to launch electron.exe
6. I opened devtool and typed in this:
`
electron = require('electron');
electron.remote.app.setAppUserModelId('com.squirrel.electron.electron');
`
7. I typed in
`
var n = window.Notification('hi');
`
8. I wasn't able to see notification : - |

Is it because by the time I setAppUserModelId it was too late? Does it matter?

**Comment by paulcbetts** [comment] 2016-04-01 00:04
@fantasticsid You can't set the app user model ID via remote, you need to call it before you open a window

**Comment by felixrieseberg** [comment] 2016-04-01 00:15
And the shortcut *has* to be inside the Start Menu folder inside the user's appdir. It's a horrible system (which is why it's no longer in Windows 10), and my documentation isn't great.

Once //build is over, I'll make another pass at the docs and make this stuff more clear.

**Comment by fantasticsid** [comment] 2016-04-01 00:48
I rebuilt my app to call `app.setAppUserModelId` before a window is created.

I'm using squirrel.windows to generate installer (noMsi, it generates a Setup.exe).

I did find a shortcut to my app under `%APPDATA%/Roaming/Microsoft/Windows/Start Menu/Programs/Myapp/Myapp.lnk`, which points to Update.exe

Notification still does not show from my app, I also used dev console to confirm this.

I'm running Windows 8.1 in vmware, if that matters.

At this point just a screenshot of notification working on Windows 8 would make me so much better..

Seriously though does it matter that the lnk file points to squirrel binary?

**Comment by fantasticsid** [comment] 2016-04-01 00:52
Also according to this https://msdn.microsoft.com/en-us/library/dn449300(v=winembedded.82).aspx

I did not see my app's Application User Model ID listed, perhaps it needs to register during installation, and squirrel somehow did not do that?

**Comment by felixrieseberg** [comment] 2016-04-01 16:05
In addition to all this mess: https://github.com/atom/electron/issues/4973

**Comment by fantasticsid** [comment] 2016-04-01 17:47
I'm gonna try 0.35.0 where notification support is first implemented..
Remember the bug where if notification fails brightray crashes? I think there must be something wrong/missing that makes the OS to deny the notification request.

Unfortunately I only have a VM for windows 8 so it's gonna be a PITA to build brightray & electron in the VM.

**Comment by rubencodes** [comment] 2016-04-14 23:58
To everyone who might be looking to do notifications in Windows 7: 
I had good success using [electron-notification-shim](https://github.com/seriema/electron-notification-shim) in conjunction with [electron-toaster](https://github.com/s-a/electron-toaster).
In my main file, I had:
```
import { app, BrowserWindow, Menu, ipcMain } from 'electron';
import Toaster from 'electron-toaster';
const toaster = new Toaster();

app.on('ready', function () {
    var mainWindow = new BrowserWindow({
        width: 1000,
        height: 600 
    });
    toaster.init(mainWindow);

    // Listen for notification events.
    ipcMain.on('notification-shim', (e, msg) => {
        mainWindow.webContents.executeJavaScript(`
            ipc.send('electron-toaster-message', {
                title: '${msg.title}',
                message: '${msg.options.body}',
                width: 440
            });
        `);
    });
});
```

And in the browser, I ran:
```
require('electron-notification-shim')();
ipc = require('electron').ipcRenderer;
```

(FWIW: I also tried this all using node-notifier with success)
And voila! Thanks for all your hard work guys/gals.

**Comment by hsz** [comment] 2016-05-11 20:41
I have created a notification on Windows 10 and it works correctly except one thing - when it disapears after a few seconds it's not available in the notifications list.
When notification is still visible - icon next to the system clock is fully white - after it hides - icon is again transparent...

When notification is visible and I click the system notifications icon - it's on the list. But after I close the list and open again - it's gone.

**Comment by rubencodes** [comment] 2016-07-07 18:14
**Update on Windows <=7 notifications:** The above code works, but we're currently having issues with it causing a change of the active window (e.g. if the Electron app is in the background and I'm in a different app, receiving a custom notification on Windows <= 7 seems to make the Electron app active without any user input). Wondering if it's something with `mainWindow.webContents.executeJavaScript` making the window active... Will update if I find out anything.

**Comment by seriema** [comment] 2016-07-08 11:39
@rubencodes is the solution you're trying related to [electron-notification-shim](https://github.com/seriema/electron-notification-shim)? Feel free to [log an issue there](https://github.com/seriema/electron-notification-shim/issues) and I'll take a look.

**Comment by akashnimare** [comment] 2016-08-02 22:13
Does anyone know how to override the default native notifications with node-notifier or electron-notification-shim? I am using electron-notification-shim with [electron-notify](https://github.com/hankbao/electron-notify) and both works perfect. The only problem is I am not able to hide/override the native notifications.

**Comment by MarshallOfSound** [comment] 2016-08-03 02:12
@akashnimare If you want to disable the built in Notification implementation simply doing something like

```js
class NullNotification {

}
window.Notification = NullNotification
```

Will make it not work (just override the Notification constructor)

**Comment by lbenitez3000** [comment] 2016-11-28 20:36
@MarshallOfSound I'm assuming that's in the renderer process?

**Comment by alkuzad** [comment] 2017-02-16 10:47
@akashnimare maybe this will shed light on this problem ? https://github.com/RocketChat/Rocket.Chat.Electron/pull/199

We switched to Rocket.Chat and it's working in there with some custom notification layout.

**Comment by moeinrahimi** [comment] 2017-08-02 16:32
if you tried all the ways and still notifications not working on windows 10 make sure you quiet hours is turn off
