### ISSUE TITLE
shell.openExternal causes Atom to freeze with Chromium as browser

### ISSUE THREAD

**Issue by subesokun** [atom/electron#1431] opened 2015-04-16 19:39 UTC
When trying to open a link via `shell.openExternal('https://www.google.com')` it causes Atom to freeze in case the default browser is Chromium (`chromium-browser`).

After getting the prompt that Atom has freezed and hitting the kill button I get the following dump on my console on which I've invoked Atom

```text
[9784:0416/151609:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
App load time: 224ms
...
The setuid sandbox is not running as root. Common causes:
  * An unprivileged process using ptrace on it, like a debugger.
  * A parent process set prctl(PR_SET_NO_NEW_PRIVS, ...)
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 789 error_code 3 request_code 40 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

I'm running Xubuntu 14.10 (64bit) with the latest Chromium installed available via apt-get and Atom 0.192.0

Edit: See also discussion here https://discuss.atom.io/t/open-url-in-external-browser/16179/5

**Comment by subesokun** [comment] 2015-04-17 08:12
Sorry, I need to correct myself. I'm running Atom 0.191.0 at the moment.

**Comment by zcbenz** [comment] 2015-04-20 08:14
This is a duplicate of #1348.

**Closed by zcbenz** 2015-04-20 08:14 UTC
