### ISSUE TITLE
session.setDownloadPath broken

### ISSUE THREAD

**Issue by MichaelOstermann** [atom/electron#2987] opened 2015-10-05 09:02 UTC
Currently `BrowserWindow.webContents.session.setDownloadPath` does nothing.

index.html

```html
<html>
<head></head>
<body>
    <a href="https://www.google.at/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png" download>Test</a>
</body>
</html>
```

main.js

```javascript
var app = require('app');
var BrowserWindow = require('browser-window');

app.on('ready', function() {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600
  });
  mainWindow.webContents.session.setDownloadPath(
      app.getPath('home')
  );
  mainWindow.loadUrl('file://' + __dirname + '/index.html');
});
```

The file dialog opens, but it is set to the default "downloads" folder.

Tested on OSX 10.10.2 with Electron v0.33.5

**Comment by etiktin** [comment] 2015-10-05 17:20
This also happens on Windows using the v0.33.6.

It seems that `browser_context_->prefs()->SetFilePath(prefs::kDownloadDefaultDirectory, path)` doesn't do anything. If you try to call get on the same value directly after (e.g. `browser_context_->prefs()->GetFilePath(prefs::kDownloadDefaultDirectory)`), you get an empty string even even though `path` is not empty.

**Comment by etiktin** [comment] 2015-10-05 23:15
The issue is that `AtomBrowserContext::RegisterPrefs` is never called, so the download directory is never registered in the pref service which means that changes to it are ignored.

If I hard code the preferences in BrowserContext (the parent class), then it works. For example:
```javascript
void BrowserContext::RegisterInternalPrefs(PrefRegistrySimple* registry) {
  InspectableWebContentsImpl::RegisterPrefs(registry);
  
  // This works
  registry->RegisterFilePathPref("download.default_directory",
                                      base::FilePath());
  registry->RegisterFilePathPref("selectfile.last_directory",
                                      base::FilePath());
}
```
This is a bit weird, since session is supposed to work with AtomBrowserContext which is a subclass of BrowserContext, but only the parent function (`BrowserContext::RegisterPrefs`) is called.

@zcbenz, @hokein what do you think might cause this?

**Comment by hokein** [comment] 2015-10-06 02:01
I believe this is a regression issue, it works on v0.30.X and v0.31.X(#2855).

@etiktin Thanks for the detailed investigation on it!
The result is a little surprising. After a closer look, it is caused by calling a virtual function in a class's constructor. In a constructor, the virtual call mechanism is disabled because the derived class is created only after the parent class is constructed.

**Comment by zcbenz** [comment] 2015-10-06 14:45
Fixed by https://github.com/atom/brightray/pull/152.

**Closed by zcbenz** 2015-10-06 14:45 UTC
Labels: bug

**Comment by etiktin** [comment] 2015-10-06 15:06
@hokein, thanks for the explanation :beers:
