### ISSUE TITLE
Electron 'Permissions Context' potentially causing Renderer Crash

### ISSUE THREAD

**Issue by AndrejHronco** [atom/electron#2669] opened 2015-08-31 23:49 UTC
I'm using the Web MIDI API within an Electron app and trying to send Sysex messages (System Exclusive) in order to send/receive a MIDI device device-specific-messages like ID Requests, etc. The Web MIDI API requires a secure connection when sending Sysex messages and the protocol within an Electron app appears to be 'file:' 
Attempting to send the message crashes the Electron renderer. All other MIDI messages and the Web MIDI API seem to work as expected and sending/receiving Sysex is successful in the Chrome browser (with https).
 
I've filed a bug with [Chromium] (https://code.google.com/p/chromium/issues/detail?id=526243) and it's looking like this could be a Electron issue instead. The latest response to that issue is below:

>Even though file:// is treated as a-priori secure (via chrome/browser/permissions/permission_context_base.h's IsRestrictedToSecureOrigins), it still has to get directed through the [MidiPermissionContext to grant access] ( https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/media/midi_permission_context.cc&rcl=1440948402&l=19 ).

>The permission context in Chrome is handled by chrome/browser/media , but perhaps Electron is not properly promulgating a permission context through. Either way, sounds like an Electron bug, not Chromium.

**Comment by etiktin** [comment] 2015-09-01 00:46
This is a shot in the dark but have you tried playing with the security options? Specifically the 2 registerUrlScheme methods mentioned in [web-frame](https://github.com/atom/electron/blob/874367e2c5b7a91c620285322488b04a57569110/docs/api/web-frame.md#webframeregisterurlschemeassecurescheme). If that doesn't work you can try disabling websecurity completely by setting `web-security` to false in BrowserWindow initialization (see [here](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions)).

**Comment by AndrejHronco** [comment] 2015-09-01 01:12
I did try and use the web-security object in BrowserWindow to no effect. I will try the two web-frame methods, is there more documentation on web-frame and using these two methods? Is there a different way that Electron(libchromiumcontent) handles permissions compared with Chromium?

It's unclear as to what the issue is. I'm not prompted to allow permission to use sysex, like i am in Chrome, which seems fine, but it does seem that a requirement to sending sysex messages is the secure protocol 'https:'

**Comment by zcbenz** [comment] 2015-09-01 03:24
Are you using OS X? If so can you paste the crash report that can be found in `Console.app`?

**Comment by AndrejHronco** [comment] 2015-09-01 05:45
This gets logged each time the crash happens:
`Aug 29 20:00:06 computer-name kernel[0]: Sandbox: Electron(5338) System Policy: deny file-write-unlink /Users/user/Library/Saved Application State/com.github.electron.savedState/restorecount.plist`

This is from Electron Helper crash log:
`Process:               Electron Helper [5474]
Path:                  /Users/USER/Documents/*/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper
Identifier:            com.github.electron.helper
Parent Process:        Electron [5472]
3   Electron Framework            	0x00000001113d2122 0x10f7e2000 + 29294882
4   Electron Framework            	0x00000001102be238 0x10f7e2000 + 11387448
5   Electron Framework            	0x00000001102be786 0x10f7e2000 + 11388806
6   Electron Framework            	0x0000000110106ef1 0x10f7e2000 + 9588465
7   Electron Framework            	0x0000000110107402 0x10f7e2000 + 9589762
8   Electron Framework            	0x000000010f9318b8 0x10f7e2000 + 1374392
9   Electron Framework            	0x0000000110109b49 0x10f7e2000 + 9599817
10  Electron Framework            	0x000000011010964a 0x10f7e2000 + 9598538
11  Electron Framework            	0x000000010f9318b8 0x10f7e2000 + 1374392
12  Electron Framework            	0x000000010f94d94f 0x10f7e2000 + 1489231
13  Electron Framework            	0x000000010f94dd36 0x10f7e2000 + 1490230
14  Electron Framework            	0x000000010f92a381 0x10f7e2000 + 1344385
20  Electron Framework            	0x000000010f92a854 0x10f7e2000 + 1345620
21  Electron Framework            	0x000000010f92a1ec 0x10f7e2000 + 1343980
22  Electron Framework            	0x000000010f95c0f3 0x10f7e2000 + 1548531
23  Electron Framework            	0x000000010f94d26d 0x10f7e2000 + 1487469
24  Electron Framework            	0x00000001102b8e46 0x10f7e2000 + 11365958
25  Electron Framework            	0x000000010fd65f52 0x10f7e2000 + 5783378
26  Electron Framework            	0x000000010fd655f6 0x10f7e2000 + 5780982
27  Electron Framework            	0x000000010f7e440d AtomMain + 77
28  com.github.electron.helper    	0x000000010f7daf2a main + 58
1   Electron Framework            	0x00000001103a91cd 0x10f7e2000 + 12349901
2   Electron Framework            	0x000000010f929740 0x10f7e2000 + 1341248
3   Electron Framework            	0x000000010f95c0f3 0x10f7e2000 + 1548531
4   Electron Framework            	0x000000010f94d26d 0x10f7e2000 + 1487469
5   Electron Framework            	0x000000010f97af3f 0x10f7e2000 + 1675071
6   Electron Framework            	0x000000010f97739b 0x10f7e2000 + 1659803
1   Electron Framework            	0x000000010fc5d549 0x10f7e2000 + 4699465
2   Electron Framework            	0x000000010f97a73c 0x10f7e2000 + 1673020
3   Electron Framework            	0x000000010f97739b 0x10f7e2000 + 1659803
1   Electron Framework            	0x000000010fc5d549 0x10f7e2000 + 4699465
2   Electron Framework            	0x000000010f97a73c 0x10f7e2000 + 1673020
3   Electron Framework            	0x000000010f97739b 0x10f7e2000 + 1659803
1   Electron Framework            	0x0000000110927278 0x10f7e2000 + 18109048
2   Electron Framework            	0x0000000110913119 0x10f7e2000 + 18026777
3   Electron Framework            	0x0000000110913416 0x10f7e2000 + 18027542
4   Electron Framework            	0x000000011090b676 0x10f7e2000 + 17995382
5   Electron Framework            	0x0000000110900383 0x10f7e2000 + 17949571
6   Electron Framework            	0x00000001108ffe63 0x10f7e2000 + 17948259
7   Electron Framework            	0x00000001108ffdea 0x10f7e2000 + 17948138
8   Electron Framework            	0x000000010f95c0f3 0x10f7e2000 + 1548531
9   Electron Framework            	0x000000010f94d26d 0x10f7e2000 + 1487469
10  Electron Framework            	0x000000010f97af3f 0x10f7e2000 + 1675071
11  Electron Framework            	0x000000010f97739b 0x10f7e2000 + 1659803
5   Electron Framework            	0x000000010f92a5cf 0x10f7e2000 + 1344975
6   Electron Framework            	0x000000010f92a1ec 0x10f7e2000 + 1343980
7   Electron Framework            	0x000000010f95c0f3 0x10f7e2000 + 1548531
8   Electron Framework            	0x000000010f94d26d 0x10f7e2000 + 1487469
9   Electron Framework            	0x000000010f97af3f 0x10f7e2000 + 1675071
10  Electron Framework            	0x000000010f97739b 0x10f7e2000 + 1659803
1   Electron Framework            	0x000000010f88cd3f atom::NodeBindings::EmbedThreadRunner(void*) + 63
1   Electron Framework            	0x000000010f969feb 0x10f7e2000 + 1605611
2   Electron Framework            	0x000000010f97c80c 0x10f7e2000 + 1681420
3   Electron Framework            	0x000000010f97ccb0 0x10f7e2000 + 1682608
4   Electron Framework            	0x000000010f97739b 0x10f7e2000 + 1659803
5   Electron Framework            	0x000000010f92a5cf 0x10f7e2000 + 1344975
6   Electron Framework            	0x000000010f92a1ec 0x10f7e2000 + 1343980
7   Electron Framework            	0x000000010f95c0f3 0x10f7e2000 + 1548531
8   Electron Framework            	0x000000010f94d26d 0x10f7e2000 + 1487469
9   Electron Framework            	0x000000010f97af3f 0x10f7e2000 + 1675071
10  Electron Framework            	0x000000010f97739b 0x10f7e2000 + 1659803
1   Electron Framework            	0x000000010f969feb 0x10f7e2000 + 1605611
2   Electron Framework            	0x000000010f97c80c 0x10f7e2000 + 1681420
3   Electron Framework            	0x000000010f97ccb0 0x10f7e2000 + 1682608
4   Electron Framework            	0x000000010f97739b 0x10f7e2000 + 1659803
       0x10f7da000 -        0x10f7daff5 +com.github.electron.helper (0) <B06FAAF5-D736-3DAC-96E4-BC9F4A693378> /Users/USER/Documents/*/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper
       0x10f7e2000 -        0x11223cf51 +Electron Framework (0) <8505C2DD-76D8-39E5-AEEE-1156A492F20E> /Users/USER/Documents/*/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
       0x11281d000 -        0x112832ff7 +com.github.Squirrel (1.0 - 1) <85C10AB5-0538-3E6C-A73B-9D4E55378A5B> /Users/USER/Documents/*/Electron.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
       0x11284f000 -        0x1128b2ff7 +org.reactivecocoa.ReactiveCocoa (1.0 - 1) <701B20DE-3ADD-3643-B52A-E05744C30DB3> /Users/USER/Documents/*/Electron.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
       0x11292b000 -        0x11293ffff +org.mantle.Mantle (1.0 - ???) <31915DD6-48E6-3706-A076-C9D4CE17F4F6> /Users/USER/Documents/*/Electron.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
       0x112951000 -        0x11331fff3 +libnode.dylib (0) <A70B058A-3305-3486-92FC-7D0E76A65058> /Users/USER/Documents/*/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib
       0x118335000 -        0x118555fe7 +ffmpegsumo.so (0) <333A2A7D-7472-301F-9BA7-979B4009AB8C> /Users/USER/Documents/*/Electron.app/Contents/Frameworks/Electron Framework.framework/Libraries/ffmpegsumo.so`

**Comment by zcbenz** [comment] 2015-09-01 08:03
Can you give some sample code that can show the problem? Calling `navigator.requestMIDIAccess` seems to work find.

**Comment by AndrejHronco** [comment] 2015-09-01 18:00
The web midi api seems to work with everything other than sending sysex, which is the only feature of the API that requires any special conditions. Here is an example of sending sysex, which crashes the app every time:
```javascript
navigator.requestMIDIAccess({sysex: true}).then(onMIDISuccess, onMIDIFailure);
// midi is the returned midiAccess object from requestMIDIAccess
var outputPort = midi.outputs.get(outputport.id); //loop over each output to get access to each port
// send simple sysex message
outputPort.send([240, 126, 127, 6, 1, 247]); // device id request
```
`{sysex: true}` is what prompts the user for permission in the browser context, the protocol must be 'https:' In the context of an Electron app, no permission prompt is given. The sysex message above pings the device, then the device returns a message with info about itself. The message can be in hexadecimal literal format `0xF7` or in the decimal equivalent, `240`. It can also be an Uint8Array.

[Here is more info on sending messages] (https://webaudio.github.io/web-midi-api/#sending-midi-messages-to-an-output-device)

**Comment by toyoshim** [comment] 2015-09-05 04:59
Hi, I confirmed that the browser kills a renderer because of bad IPC message, reason 34, at https://code.google.com/p/chromium/codesearch#chromium/src/content/browser/media/midi_host.cc&q=MH_SYS_EX_PERMISSION&sq=package:chromium&type=cs&l=109.

The permission for each renderer is managed by ChildProcessSecurityPolicy, and should be set for sysex at https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/media/midi_permission_context.cc&sq=package:chromium&type=cs&l=32&rcl=1441409197. If this isn't set correctly, the browser kills a renderer on receiving sysex in order to protect the browser from broken renderers.

So the point to fix this issue seems to implement Electron version of midi_permission_context.cc.

**Comment by toyoshim** [comment] 2015-09-05 05:42
I took a quick look and wrote a fix for this.
brightray's PermissionManager seems to be the right place to handle the ChildProcessSecurityPolicy for Electron. I can send a pull request to the brightray. I'm looking the process for code contribution.

**Comment by toyoshim** [comment] 2015-09-05 06:02
Sent a pull request to atom/brightray.

**Comment by AndrejHronco** [comment] 2015-09-08 19:29
Thanks for working on this [toyoshim](https://github.com/toyoshim), looking forward to using Web MIDI in Electron.

**Closed** 2015-09-09 05:35 UTC
Labels: bug, crash
