### ISSUE TITLE
Access violation in 0.35.0 (crash)

### ISSUE THREAD

**Issue by flexpaper** [atom/electron#3578] opened 2015-11-25 06:17 UTC
Getting multiple reports on access violation causing crashes on Windows 32 machines using 0.35.0. Pasting in the crashdump. The crash dump doesn't seem to contain very much, is this enough info to be able to take this error further?

Operating system: Windows NT
                  6.1.7601 Service Pack 1
CPU: amd64
     family 6 model 58 stepping 9
     4 CPUs

Crash reason:  EXCEPTION_ACCESS_VIOLATION
Crash address: 0xffffffffffffffff

Thread 0 (crashed)
 0  ntdll.dll + 0x4df6a
    rip = 0x7748df6a   rsp = 0x0018cb48   rbp = 0x00000002

Thread 1
 0  ntdll.dll + 0x4df6a
    rip = 0x7748df6a   rsp = 0x046bfa78   rbp = 0x00000000

Thread 2
 0  ntdll.dll + 0x4f2ba
    rip = 0x7748f2ba   rsp = 0x0512fb88   rbp = 0x00000000

Thread 3
 0  ntdll.dll + 0x4da4a
    rip = 0x7748da4a   rsp = 0x0548f728   rbp = 0x0548f8d0
 1  0x1fcd5f
    rip = 0x001fcd60   rsp = 0x0548f8e0   rbp = 0xffffffff

Thread 4
 0  ntdll.dll + 0x4d9fa
    rip = 0x7748d9fa   rsp = 0x052af998   rbp = 0x00000000

Thread 5
 0  ntdll.dll + 0x4df6a
    rip = 0x7748df6a   rsp = 0x057cf028   rbp = 0x00000001

Thread 6
 0  ntdll.dll + 0x4d9fa
    rip = 0x7748d9fa   rsp = 0x059af7e8   rbp = 0x00000000

Thread 7
 0  ntdll.dll + 0x4d9fa
    rip = 0x7748d9fa   rsp = 0x05aaf638   rbp = 0x00000000

Thread 8
 0  ntdll.dll + 0x4da4a
    rip = 0x7748da4a   rsp = 0x05c0ef28   rbp = 0x05c0f0d0

Thread 9
 0  ntdll.dll + 0x4da4a
    rip = 0x7748da4a   rsp = 0x055aef58   rbp = 0x055af100

Thread 10
 0  ntdll.dll + 0x4d9fa
    rip = 0x7748d9fa   rsp = 0x05ecf838   rbp = 0x00000000

Thread 11
 0  ntdll.dll + 0x4f2aa
    rip = 0x7748f2aa   rsp = 0x05dafd78   rbp = 0x001f0e38

Thread 12
 0  ntdll.dll + 0x4d9fa
    rip = 0x7748d9fa   rsp = 0x060ff8f8   rbp = 0x00000000

Thread 13
 0  ntdll.dll + 0x4df6a
    rip = 0x7748df6a   rsp = 0x0620f548   rbp = 0x00000001

Thread 14
 0  ntdll.dll + 0x4df6a
    rip = 0x7748df6a   rsp = 0x0648f438   rbp = 0x00000001

Thread 15
 0  ntdll.dll + 0x4d9fa
    rip = 0x7748d9fa   rsp = 0x0633fd58   rbp = 0x00000000

Thread 16
 0  ntdll.dll + 0x4f2aa
    rip = 0x7748f2aa   rsp = 0x05fcf298   rbp = 0x001e8298

Thread 17
 0  ntdll.dll + 0x4f2aa
    rip = 0x7748f2aa   rsp = 0x0667f2b8   rbp = 0x0667f420
 1  0xfffffffe
    rip = 0xffffffff   rsp = 0x0667f430   rbp = 0x04c16990

Thread 18
 0  ntdll.dll + 0x4f2aa
    rip = 0x7748f2aa   rsp = 0x0944f3f8   rbp = 0x001e8298

Thread 19
 0  ntdll.dll + 0x4f2aa
    rip = 0x7748f2aa   rsp = 0x095ff3c8   rbp = 0x001e8298

Thread 20
 0  ntdll.dll + 0x4dcfa
    rip = 0x7748dcfa   rsp = 0x0b16c4d8   rbp = 0x0b16c680

Thread 21
 0  ntdll.dll + 0x4dcfa
    rip = 0x7748dcfa   rsp = 0x0b00f7f8   rbp = 0x00000000

Thread 22
 0  user32.dll + 0x19e6a
    rip = 0x76ed9e6a   rsp = 0x0b2cfa78   rbp = 0x00000000

Thread 23
 0  ntdll.dll + 0x4f2ba
    rip = 0x7748f2ba   rsp = 0x0c53f978   rbp = 0x00000000

Thread 24
 0  ntdll.dll + 0x4f2ba
    rip = 0x7748f2ba   rsp = 0x0ca5f668   rbp = 0x00000000

Thread 25
 0  ntdll.dll + 0x4f2ba
    rip = 0x7748f2ba   rsp = 0x0cbbf918   rbp = 0x00000000

Thread 26
 0  ntdll.dll + 0x4d9fa
    rip = 0x7748d9fa   rsp = 0x092ef748   rbp = 0x0000000d

Thread 27
 0  ntdll.dll + 0x4da4a
    rip = 0x7748da4a   rsp = 0x0c76fc38   rbp = 0x00000000

Loaded modules:
0x503a0000 - 0x513f5fff  mshtml.dll  9.0.8112.16717  (main)
0x710d0000 - 0x710fefff  ATL90.dll  9.0.30729.6161
0x71100000 - 0x711d2fff  msvcp90.dll  9.0.30729.6161
0x711e0000 - 0x71282fff  msvcr90.dll  9.0.30729.6161
0x76d70000 - 0x76ebafff  urlmon.dll  9.0.8112.16717
0x76ec0000 - 0x76fb9fff  user32.dll  6.1.7601.17514
0x76fc0000 - 0x770dffff  kernel32.dll  6.1.7601.19045
0x770e0000 - 0x772ebfff  iertutil.dll  9.0.8112.16717
0x772f0000 - 0x77435fff  wininet.dll  9.0.8112.16717
0x77440000 - 0x775e8fff  ntdll.dll  6.1.7601.19045
0x77600000 - 0x77606fff  psapi.dll  6.1.7600.16385
0x77610000 - 0x77612fff  normaliz.dll  6.1.7600.16385
0x13fbd0000 - 0x144110fff  FlexPaper_Desktop_Publisher.exe  0.35.0.0
0x7feebee0000 - 0x7feec25cfff  OverlayIcon64.dll  1.0.0.1
0x7feec260000 - 0x7feecdeffff  node.dll  4.1.1.0
0x7feee590000 - 0x7feee635fff  msvcp120.dll  12.0.21005.1
0x7feef8a0000 - 0x7feef98efff  msvcr120.dll  12.0.21005.1
0x7feefbb0000 - 0x7feefd46fff  DWrite.dll  6.2.9200.17461
0x7fef0560000 - 0x7fef058ffff  PeerDist.dll  6.1.7600.16385
0x7fef0670000 - 0x7fef06eafff  StructuredQuery.dll  7.0.7601.17514
0x7fef0ab0000 - 0x7fef0bbdfff  QvodWebBase64.dll  1.0.0.47
0x7fef1990000 - 0x7fef1a2bfff  mscms.dll  6.1.7601.17514
0x7fef1ca0000 - 0x7fef1d26fff  ieproxy.dll  9.0.8112.16717
0x7fef2890000 - 0x7fef28a0fff  rtutils.dll  6.1.7601.17514
0x7fef28b0000 - 0x7fef28cbfff  rasman.dll  6.1.7600.16385
0x7fef28d0000 - 0x7fef2931fff  rasapi32.dll  6.1.7600.16385
0x7fef2b50000 - 0x7fef2ba3fff  oleacc.dll  7.0.0.0
0x7fef2bb0000 - 0x7fef3619fff  ieframe.dll  9.0.8112.16717
0x7fef3d20000 - 0x7fef3d28fff  SensApi.dll  6.1.7600.16385
0x7fef4840000 - 0x7fef49dbfff  NetworkExplorer.dll  6.1.7601.17514
0x7fef4e70000 - 0x7fef4f5dfff  actxprxy.dll  6.1.7601.17514
0x7fef5140000 - 0x7fef51bffff  ntshrui.dll  6.1.7601.17755
0x7fef51c0000 - 0x7fef59cffff  GrooveIntlResource.dll  14.0.7007.1000
0x7fef59d0000 - 0x7fef5de9fff  OFFICE.ODF  14.0.7109.5000
0x7fef5df0000 - 0x7fef645efff  GROOVEEX.DLL  14.0.7113.5005
0x7fef6e70000 - 0x7fef6ea3fff  shdocvw.dll  6.1.7601.18222
0x7fef6f40000 - 0x7fef6f74fff  EhStorShell.dll  6.1.7600.16385
0x7fef6f80000 - 0x7fef7154fff  d3d11.dll  6.2.9200.16570
0x7fef73e0000 - 0x7fef73ebfff  linkinfo.dll  6.1.7600.16385
0x7fef73f0000 - 0x7fef7429fff  msls31.dll  3.10.349.0
0x7fef75c0000 - 0x7fef75fafff  winmm.dll  6.1.7600.16385
0x7fef77b0000 - 0x7fef780cfff  dxgi.dll  6.2.9200.16492
0x7fef7b00000 - 0x7fef7b1cfff  mssprxy.dll  7.0.7600.16385
0x7fef7b30000 - 0x7fef7b48fff  pnrpnsp.dll  6.1.7600.16385
0x7fef7b50000 - 0x7fef7b5afff  winrnr.dll  6.1.7600.16385
0x7fef7b60000 - 0x7fef7b74fff  NapiNSP.dll  6.1.7600.16385
0x7fef7b80000 - 0x7fef7b8efff  cscapi.dll  6.1.7601.17514
0x7fef7ca0000 - 0x7fef7d5cfff  PortableDeviceApi.dll  6.1.7601.17514
0x7fef7f40000 - 0x7fef7f66fff  EhStorAPI.dll  6.1.7601.17514
0x7fef8a30000 - 0x7fef8a37fff  rasadhlp.dll  6.1.7600.16385
0x7fef8a40000 - 0x7fef8ab0fff  winspool.drv  6.1.7601.17514
0x7fef9b60000 - 0x7fef9bc3fff  webio.dll  6.1.7601.17725
0x7fef9bd0000 - 0x7fef9c40fff  winhttp.dll  6.1.7601.17514
0x7fefa790000 - 0x7fefa7a7fff  dhcpcsvc.dll  6.1.7600.16385
0x7fefa7b0000 - 0x7fefa7c0fff  dhcpcsvc6.DLL  6.1.7601.17970
0x7fefa950000 - 0x7fefa9a2fff  FWPUCLNT.DLL  6.1.7601.18283
0x7fefab10000 - 0x7fefab1afff  winnsi.dll  6.1.7600.16385
0x7fefab30000 - 0x7fefab56fff  IPHLPAPI.DLL  6.1.7601.17514
0x7fefae20000 - 0x7fefae37fff  mpr.dll  6.1.7600.16385
0x7fefb230000 - 0x7fefb239fff  davhlpr.dll  6.1.7600.16385
0x7fefb240000 - 0x7fefb25cfff  davclnt.dll  6.1.7601.18912
0x7fefb260000 - 0x7fefb281fff  ntlanman.dll  6.1.7601.17514
0x7fefb2b0000 - 0x7fefb3d4fff  dbghelp.dll  6.1.7601.17514
0x7fefb400000 - 0x7fefb409fff  drprov.dll  6.1.7600.16385
0x7fefb4d0000 - 0x7fefb4dafff  slc.dll  6.1.7600.16385
0x7fefb780000 - 0x7fefb794fff  nlaapi.dll  6.1.7601.17964
0x7fefb8c0000 - 0x7fefb8ecfff  ntmarta.dll  6.1.7600.16385
0x7fefbb50000 - 0x7fefbb56fff  msimg32.dll  6.1.7600.16385
0x7fefbb90000 - 0x7fefbba4fff  wkscli.dll  6.1.7601.17514
0x7fefbbb0000 - 0x7fefbbbbfff  netutils.dll  6.1.7601.17514
0x7fefbbc0000 - 0x7fefbbd5fff  netapi32.dll  6.1.7601.17887
0x7fefbc70000 - 0x7fefbcbefff  AudioSes.dll  6.1.7601.18741
0x7fefbd00000 - 0x7fefbe60fff  WindowsCodecs.dll  6.2.9200.17251
0x7fefbe70000 - 0x7fefbea4fff  xmllite.dll  1.3.1001.0
0x7fefbeb0000 - 0x7fefbec7fff  dwmapi.dll  6.1.7600.16385
0x7fefbed0000 - 0x7fefbf1afff  MMDevAPI.dll  6.1.7600.16385
0x7fefbf70000 - 0x7fefbfb2fff  duser.dll  6.1.7600.16385
0x7fefbfc0000 - 0x7fefc0b1fff  dui70.dll  6.1.7600.16385
0x7fefc0c0000 - 0x7fefc2d5fff  GdiPlus.dll  6.1.7601.19054
0x7fefc2e0000 - 0x7fefc335fff  uxtheme.dll  6.1.7600.16385
0x7fefc340000 - 0x7fefc46bfff  propsys.dll  7.0.7601.17514
0x7fefc4a0000 - 0x7fefc693fff  comctl32.dll  6.10.7601.18837
0x7fefc990000 - 0x7fefc9bbfff  powrprof.dll  6.1.7600.16385
0x7fefc9c0000 - 0x7fefc9d0fff  wtsapi32.dll  6.1.7600.16385
0x7fefcac0000 - 0x7fefcac6fff  WSHTCPIP.DLL  6.1.7600.16385
0x7fefcbe0000 - 0x7fefcbfdfff  userenv.dll  6.1.7601.17514
0x7fefccd0000 - 0x7fefccf2fff  srvcli.dll  6.1.7601.17514
0x7fefce20000 - 0x7fefce2bfff  version.dll  6.1.7600.16385
0x7fefced0000 - 0x7fefcf16fff  rsaenh.dll  6.1.7600.16385
0x7fefcfe0000 - 0x7fefd03afff  dnsapi.dll  6.1.7601.17570
0x7fefd240000 - 0x7fefd246fff  wship6.dll  6.1.7600.16385
0x7fefd250000 - 0x7fefd2a4fff  mswsock.dll  6.1.7601.18254
0x7fefd2b0000 - 0x7fefd2c7fff  cryptsp.dll  6.1.7601.18741
0x7fefd310000 - 0x7fefd31afff  secur32.dll  6.1.7601.19045
0x7fefd3a0000 - 0x7fefd3cefff  authz.dll  6.1.7600.16385
0x7fefd550000 - 0x7fefd574fff  sspicli.dll  6.1.7601.19045
0x7fefd730000 - 0x7fefd786fff  apphelp.dll  6.1.7601.17514
0x7fefd790000 - 0x7fefd79efff  CRYPTBASE.dll  6.1.7601.19045
0x7fefd7a0000 - 0x7fefd830fff  sxs.dll  6.1.7601.17514
0x7fefd840000 - 0x7fefd87cfff  winsta.dll  6.1.7601.18540
0x7fefd880000 - 0x7fefd893fff  RpcRtRemote.dll  6.1.7601.17514
0x7fefd8a0000 - 0x7fefd8aefff  profapi.dll  6.1.7600.16385
0x7fefd940000 - 0x7fefd94efff  msasn1.dll  6.1.7601.17514
0x7fefd950000 - 0x7fefd985fff  cfgmgr32.dll  6.1.7601.17514
0x7fefda30000 - 0x7fefda49fff  devobj.dll  6.1.7600.16385
0x7fefda50000 - 0x7fefdbbcfff  crypt32.dll  6.1.7601.18741
0x7fefdbc0000 - 0x7fefdbfafff  wintrust.dll  6.1.7601.18741
0x7fefdc00000 - 0x7fefdc6bfff  KERNELBASE.dll  6.1.7601.19045
0x7fefdc70000 - 0x7fefdd06fff  comdlg32.dll  6.1.7601.17514
0x7fefdd10000 - 0x7fefde18fff  msctf.dll  6.1.7601.18731
0x7fefde20000 - 0x7fefdef6fff  oleaut32.dll  6.1.7601.18679
0x7fefdf00000 - 0x7fefdf98fff  clbcatq.dll  2001.12.8530.16385
0x7fefe020000 - 0x7fefe086fff  gdi32.dll  6.1.7601.18898
0x7fefe090000 - 0x7fefe0dcfff  ws2_32.dll  6.1.7601.17514
0x7fefe0e0000 - 0x7fefe20cfff  rpcrt4.dll  6.1.7601.19045
0x7fefe210000 - 0x7fefe2d8fff  usp10.dll  1.626.7601.18454
0x7fefe2e0000 - 0x7fefe350fff  shlwapi.dll  6.1.7601.17514
0x7fefe360000 - 0x7fefe3fefff  msvcrt.dll  7.0.7601.17744
0x7fefe400000 - 0x7fefe407fff  nsi.dll  6.1.7600.16385
0x7fefe410000 - 0x7fefe612fff  ole32.dll  6.1.7601.18915
0x7fefe620000 - 0x7fefe671fff  Wldap32.dll  6.1.7601.17514
0x7fefe6a0000 - 0x7feff428fff  shell32.dll  6.1.7601.18952
0x7feff430000 - 0x7feff606fff  setupapi.dll  6.1.7601.17514
0x7feff610000 - 0x7feff61dfff  lpk.dll  6.1.7601.18985
0x7feff620000 - 0x7feff6fafff  advapi32.dll  6.1.7601.18247
0x7feff700000 - 0x7feff71efff  sechost.dll  6.1.7600.16385
0x7feff720000 - 0x7feff74dfff  imm32.dll  6.1.7600.16385

**Comment by flexpaper** [comment] 2015-11-25 07:01
I think you can ignore this dump, it seem to be triggered when the browser window is closed, not so sure this is a real crash

**Comment by zcbenz** [comment] 2015-11-26 03:17
It is likely a duplicate of #3580.

**Closed by zcbenz** 2015-11-26 03:17 UTC
