### ISSUE TITLE
Ability to change title/label of confirmation button inside an open dialog

### ISSUE THREAD

**Issue by jstejada** [atom/electron#4876] opened 2016-03-22 01:53 UTC
* Electron version: 0.36.7

I would like to be able to customize the button title for an `open dialog` (https://github.com/atom/electron/blob/master/docs/api/dialog.md#dialogshowopendialogbrowserwindow-options-callback)

For example, to say `Choose` instead of `Open`:
<img width="713" alt="screen shot 2016-03-21 at 6 52 12 pm" src="https://cloud.githubusercontent.com/assets/1271509/13939892/116feb12-ef96-11e5-95ce-6f15ffa49517.png">

**Comment by zcbenz** [comment] 2016-03-27 13:37
This is a duplicate of #1531.

**Closed by zcbenz** 2016-03-27 13:37 UTC
Labels: enhancement
