### ISSUE TITLE
js.global:require -> type: nil

### ISSUE THREAD

**Issue by joelpinheiro** [atom/electron#4935] opened 2016-03-29 10:18 UTC
* Electron version: v0.35.1
* Operating system: darwin (Mac-OSX YOSEMITE 10.10.4 (14E46))

Hi all,

I am trying to use a VM os Lua in Electron's Node.js.

When I am using it from REPL (Node version: 4.2.1) I have the expected result:
```
$ mkdir tmp
$ cd tmp
$ npm install lua.vm.js
/home/joelpinheiro/tmp
└── lua.vm.js@0.0.1 

npm WARN enoent ENOENT: no such file or directory, open '/home/daurnimator/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.
$ cat > test.js << EOF
> console.log("loaded");
> module.exports = { foo: function() { return "bar" } };
> EOF
$ node
> var luavm = require("./lua.vm.js");
undefined
> luavm.L.execute("return type(js.global.require)")
[ 'userdata' ]
> luavm.L.execute("local test = js.global:require('./test.js'); return test:foo()")
loaded
[ 'bar' ]
```

However when I try to run the following code from Electron's Node.js (v4.2.2):
```
var luavm = require("lua.vm.js"); -- this comes from node_modules (am I using the correct import?)
luavm.L.execute("print('type: ' .. type(js.global.require))")
luavm.L.execute("local test = js.global:require('./test.js'); print('foo: ' .. test:foo())")
```

I got this:
```
type: nil

/Users/joelpinheiro/Dropbox/iTrading/electron_app/node_modules/lua.vm.js/dist/lua.vm.js:2
var Module;if(typeof Module==="undefined")Module={};if(!Module.expectedDataFileDownloads){Module.expectedDataFileDownloads=0;Module.finishedDataFileDownloads=0}Module.expectedDataFileDownloads++;((function(){var loadPackage=(function(metadata){function runWithFS(){var fileData0=[];fileData0.push.apply(fileData0,[45,45,32,77,97,107,101,32,119,105,110,100,111,119,32,111,98,106,101,99,116,32,97,32,103,108,111,98,97,108,10,119,105,110,100,111,119,32,61,32,106,115,46,103,108,111,98,97,108,59,10,10,100,111,32,45,45,32,67,114,101,97,116,101,32,106,115,46,105,112,97,105,114,115,32,97,110,100,32,106,115,46,112,97,105,114,115,32,102,117,110,99,116,105,111,110,115,46,32,97,116,116,97,99,104,32,97,115,32,95,95,112,97,105,114,115,32,97,110,100,32,95,95,105,112,97,105,114,115,32,111,110,32,74,83,32,117,115,101,114,100,97,116,97,32,111,98,106,101,99,116,115,46,10,9,108,111,99,97,108,32,95,80,82,79,88,89,95,77,84,32,61,32,100,101,98,1
Lua.Error
    at /Users/joelpinheiro/Dropbox/iTrading/electron_app/node_modules/lua.vm.js/dist/lua.vm.js:16:18422
    at /Users/joelpinheiro/Dropbox/iTrading/electron_app/node_modules/lua.vm.js/dist/lua.vm.js:16:27153
    at Object.<anonymous> (/Users/joelpinheiro/Dropbox/iTrading/electron_app/node_modules/lua.vm.js/dist/lua.vm.js:21:35)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at EventEmitter.<anonymous> (/Users/joelpinheiro/Dropbox/iTrading/electron_app/main.js:79:17)
```

Is it possible to call this` js.global:require(...)` from Electron?

Why I'm having different results from node.js REPL and Electron?

**Comment by zcbenz** [comment] 2016-03-31 11:15
I'm afraid only authors of lua.vm.js would have answers for this, this module is complex enough that we have to spend lots of time studying its code to be able to find out why it doesn't work in Electron.

I'm closing this since we can not solve compatibility issues for every single node module.

**Closed by zcbenz** 2016-03-31 11:15 UTC

**Comment by joelpinheiro** [comment] 2016-03-31 12:44
The issue is in `js.global:require(...)` not in lua.vm.js itself.

**Comment by daurnimator** [comment] 2016-04-12 10:13
(lua.vm.js maintainer here) The issue as @joelpinheiro describes it is that `global.require` in electron is `undefined` (unlike in node.js).

**Comment by zcbenz** [comment] 2016-04-13 00:17
That's weird, probably the op is not using the normal environment of Electron. A reproducible example would be helpful.
