### ISSUE TITLE
HTML5 Constraint API Bubble don't show

### ISSUE THREAD

**Issue by layane** [atom/electron#1974] opened 2015-06-15 11:23 UTC
Using and example code from http://www.html5rocks.com/ in the body of my index.html. Don't show the bubble when i click the button (the input change the focus and the border glow but don't show the bubble). 
```
<form>
    <input type="text" required value="" />
    <input type="submit" value="Submit" />
</form>
```

The buble that don't show with Electron:
![Bubble](http://www.html5rocks.com/static/images/tutorials/constraintvalidation/Chrome.png)

I'm using the prebuild v0.209 from: https://github.com/atom/atom/releases/tag/v0.209.0

**Comment by layane** [comment] 2015-06-15 11:29
I'm trying too:
```javascript
myinput.setCustomValidity('My custom error message');

console.log(myinput.validity.customError);  //return true
```

**Comment by zcbenz** [comment] 2015-06-16 03:04
This is a duplicate of #1043.

**Closed by zcbenz** 2015-06-16 03:04 UTC
