### ISSUE TITLE
run a flash page, a cmd window show NOT SANDBOXED

### ISSUE THREAD

**Issue by builden** [atom/electron#3753] opened 2015-12-10 08:00 UTC
OS: win8 + 64
Electron: 0.35.4
```js
app.commandLine.appendSwitch('ppapi-flash-path', __dirname + '/pepflashplayer.dll');
app.commandLine.appendSwitch('ppapi-flash-version', '10.0.0.245');
```

when open a page which have flash object. a cmd window show 'NOT SANDBOXED' than quickly closed auto.
![image](https://cloud.githubusercontent.com/assets/9499016/11710010/0dad245c-9f57-11e5-8508-937361bd19c1.png)

how can i configure to stop show the cmd window

**Comment by zcbenz** [comment] 2015-12-10 10:09
This is a duplicate of #1779.

**Closed by zcbenz** 2015-12-10 10:09 UTC
