### ISSUE TITLE
Can't build with Xcode 7

### ISSUE THREAD

**Issue by kndl** [atom/electron#2765] opened 2015-09-11 18:49 UTC
```
ninja: Entering directory `out/R'
[22/282] CC obj/vendor/crashpad/util/obj/vendor/crashpad/util/crashpad_util.gen/util/mach/crashpad_util.child_portUser.o
FAILED: ../../vendor/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/vendor/crashpad/util/obj/vendor/crashpad/util/crashpad_util.gen/util/mach/crashpad_util.child_portUser.o.d -DENABLE_WEBRTC -DNDEBUG -DV8_USE_EXTERNAL_STARTUP_DATA -DSK_SUPPORT_LEGACY_GETTOPDEVICE -DSK_SUPPORT_LEGACY_BITMAP_CONFIG -DSK_SUPPORT_LEGACY_DEVICE_VIRTUAL_ISOPAQUE -DSK_SUPPORT_LEGACY_N32_NAME -DSK_SUPPORT_LEGACY_SETCONFIG -DSK_IGNORE_ETC1_SUPPORT -DSK_IGNORE_GPU_DITHER -DUSE_OPENSSL -I../../vendor/crashpad -Iobj/vendor/crashpad/util/crashpad_util.gen -I/Users/kendall/code/third-party/electron/vendor/brightray/vendor/download/libchromiumcontent/src -I../../vendor/crashpad/compat/mac -I../../vendor/crashpad/compat/non_win -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fasm-blocks -mpascal-strings -O2 -gdwarf-2 -Werror -mmacosx-version-min=10.9 -arch x86_64 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-deprecated-declarations -Wno-unneeded-internal-declaration -std=c99 -fcolor-diagnostics -fno-inline -fno-omit-frame-pointer -fno-builtin -fno-optimize-sibling-calls  -c obj/vendor/crashpad/util/crashpad_util.gen/util/mach/child_portUser.c -o obj/vendor/crashpad/util/obj/vendor/crashpad/util/crashpad_util.gen/util/mach/crashpad_util.child_portUser.o
In file included from obj/vendor/crashpad/util/crashpad_util.gen/util/mach/child_portUser.c:9:
In file included from obj/vendor/crashpad/util/crashpad_util.gen/util/mach/child_port.h:65:
In file included from ../../vendor/crashpad/util/mach/child_port_types.h:18:
../../vendor/crashpad/compat/mac/mach/mach.h:56:2: error: Update this file for new exception types
#error Update this file for new exception types
 ^
1 error generated.
[22/282] CC obj/vendor/crashpad/util/obj/vendor/crashpad/util/crashpad_util.gen/util/mach/crashpad_util.child_portServer.o
FAILED: ../../vendor/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/vendor/crashpad/util/obj/vendor/crashpad/util/crashpad_util.gen/util/mach/crashpad_util.child_portServer.o.d -DENABLE_WEBRTC -DNDEBUG -DV8_USE_EXTERNAL_STARTUP_DATA -DSK_SUPPORT_LEGACY_GETTOPDEVICE -DSK_SUPPORT_LEGACY_BITMAP_CONFIG -DSK_SUPPORT_LEGACY_DEVICE_VIRTUAL_ISOPAQUE -DSK_SUPPORT_LEGACY_N32_NAME -DSK_SUPPORT_LEGACY_SETCONFIG -DSK_IGNORE_ETC1_SUPPORT -DSK_IGNORE_GPU_DITHER -DUSE_OPENSSL -I../../vendor/crashpad -Iobj/vendor/crashpad/util/crashpad_util.gen -I/Users/kendall/code/third-party/electron/vendor/brightray/vendor/download/libchromiumcontent/src -I../../vendor/crashpad/compat/mac -I../../vendor/crashpad/compat/non_win -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fasm-blocks -mpascal-strings -O2 -gdwarf-2 -Werror -mmacosx-version-min=10.9 -arch x86_64 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-deprecated-declarations -Wno-unneeded-internal-declaration -std=c99 -fcolor-diagnostics -fno-inline -fno-omit-frame-pointer -fno-builtin -fno-optimize-sibling-calls  -c obj/vendor/crashpad/util/crashpad_util.gen/util/mach/child_portServer.c -o obj/vendor/crashpad/util/obj/vendor/crashpad/util/crashpad_util.gen/util/mach/crashpad_util.child_portServer.o
In file included from obj/vendor/crashpad/util/crashpad_util.gen/util/mach/child_portServer.c:12:
In file included from obj/vendor/crashpad/util/crashpad_util.gen/util/mach/child_portServer.h:65:
In file included from ../../vendor/crashpad/util/mach/child_port_types.h:18:
../../vendor/crashpad/compat/mac/mach/mach.h:56:2: error: Update this file for new exception types
#error Update this file for new exception types
 ^
1 error generated.
[22/282] CXX obj/vendor/node/src/node.node_javascript.o
ninja: build stopped: subcommand failed.
```

Python: `2.7.10`
Node: `v0.12.7`
Xcode: `7A218`

This seems to have to do with Xcode 7. The last time it was working, I was building with Xcode 6.

**Comment by hokein** [comment] 2015-09-14 00:13
Chromium doesn't support xcode 7 build yet: https://code.google.com/p/chromium/issues/detail?id=517914. We need to wait until the upstream gets it fixed.

**Comment by zcbenz** [comment] 2015-09-17 13:18
This is a duplicate of #2315.

**Closed by zcbenz** 2015-09-17 13:18 UTC
Labels: blocked, bug, osx
