### ISSUE TITLE
Electron hangs when two instances are docked next to each other - Windows 10

### ISSUE THREAD

**Issue by benjaminRomano** [atom/electron#3501] opened 2015-11-18 23:18 UTC
When two instances of Electron are docked next to each other  one of the electron instances will become unresponsive. 

Below is a picture of how I had my electron instances configured.
![image](https://cloud.githubusercontent.com/assets/9221137/11176488/31238848-8c03-11e5-8ba9-e817b9729b75.png)

I've already filed this bug in the atom/atom repo, here: https://github.com/atom/atom/issues/9616#issue. 

However, this bug also occurred when I had Slack open next to Atom so I believe it is actually an electron issue.

**Comment by brenca** [comment] 2015-11-19 00:08
Weird, I can't reproduce this on Windows10 Pro 64bit, tried with 2 atom windows, slack and the default electron app too.

**Comment by benjaminRomano** [comment] 2015-11-19 00:41
@brenca Here's a video of the bug happening. https://www.youtube.com/watch?v=YtUJh-FQXaA

When I switch the places of Atom and Slack, Slack will become unresponsive until I resize the window. 

It seems like the easiest way to reproduce the bug is using the snap-assist feature in windows 10; however, this bug can also occur when just using the windows + arrow keys to snap a window to one of the sides.

**Comment by brenca** [comment] 2015-11-19 02:18
@benjaminRomano I've turned on the snap assist and indeed one of the atom windows froze until I moved it.

**Comment by brenca** [comment] 2015-11-19 02:32
https://m.reddit.com/r/chrome/comments/3jmqc7/chrome_windows_keeps_freezing_when_i_use_aero_snap/ this could be relevant

**Comment by brenca** [comment] 2015-11-19 02:41
It's a chromium bug, it has been fixed in newer versions https://code.google.com/p/chromium/issues/detail?id=516234

**Comment by zcbenz** [comment] 2015-12-08 11:49
Fixed by #3714.

**Closed by zcbenz** 2015-12-08 11:49 UTC
Labels: bug, fixed-in-upstream
