### ISSUE TITLE
Using CSS transform scale() on <webview> sometimes causes double scaling

### ISSUE THREAD

**Issue by li-cn** [atom/electron#3749] opened 2015-12-09 23:09 UTC
**How to reproduce this issue:**

Apply `transform: scale(0.8)` style on a `<webview>` element, and then resize the screen. The webview contents take up an area smaller than the expected size based on the CSS transform. The issue also also occurs when a script changes the style attribute of the webview or its ancestor elements.

**Example:**

For this example I used a webview with `style="height: 100%; width: 100%;"`, but I've experimented with webviews with different style configurations and the issue seems to occur regardless of how the page is set up.

Before scaling:
![screen shot 2015-12-09 at 6 09 35 pm](https://cloud.githubusercontent.com/assets/5552308/11701846/0c14ad0c-9ea0-11e5-9c97-d93b22a0ab99.png)

After scaling, before resize:
![screen shot 2015-12-09 at 5 56 02 pm](https://cloud.githubusercontent.com/assets/5552308/11701545/24cbd0c0-9e9e-11e5-82b0-31bd16c41f3f.png)

After resize: 
![screen shot 2015-12-09 at 5 53 54 pm](https://cloud.githubusercontent.com/assets/5552308/11701501/e87a7a5e-9e9d-11e5-86ff-4070eb108a92.png)

**Comment by li-cn** [comment] 2015-12-09 23:17
Just discovered that this is a known Chromium bug: https://code.google.com/p/chromium/issues/detail?id=492182

**Comment by zcbenz** [comment] 2015-12-10 10:08
This is a duplicate of #2168.

**Closed by zcbenz** 2015-12-10 10:08 UTC
