### ISSUE TITLE
Website mentions npm run

### ISSUE THREAD

**Issue by MajorBreakfast** [atom/electron#3320] opened 2015-11-03 19:01 UTC
http://electron.atom.io/ mentions `npm install && npm run`, but `npm run` is not a thing :) Should be changed to `npm start`.

**Comment by johnmuhl** [comment] 2015-11-03 19:22
Duplicate of https://github.com/atom/electron-quick-start/issues/5

**Comment by jlord** [comment] 2015-11-03 21:08
My bad, wrong npm script in my head. Closing here and fixing on the website 👍 Thanks!

**Closed by jlord** 2015-11-03 21:08 UTC

**Comment by jlord** [comment] 2015-11-03 21:11
🔗 https://github.com/atom/electron.atom.io/commit/ca6866da2ff700a07c5735843740d989ca293e10
