### ISSUE TITLE
`showOpenDialog` works incorrect along with `angularjs` in `0.35.1`

### ISSUE THREAD

**Issue by leftstick** [atom/electron#3589] opened 2015-11-26 07:51 UTC
The code is extremely simple:

```html
<!DOCTYPE html>
<html lang="en" ng-app="app">
<head>
    <meta charset="UTF-8">
</head>
<body ng-controller="TestController">

    <input type="text" ng-model="state.addr" ng-click="openDialog()">

    <script src="angular.js" charset="utf-8"></script>
    <script src="app.js" charset="utf-8"></script>
</body>
</html>
```

*app.js*

```javascript
var mainWindow = require('electron').remote.getCurrentWindow();
var dialog = require('electron').remote.require('dialog');

var app = angular.module('app', []);

app.controller('TestController', function($scope) {
    $scope.state = {};
    $scope.openDialog = function() {
        dialog.showOpenDialog(mainWindow, {
            title: 'open file',
            properties: [
                'openDirectory'
            ]
        }, function(files) {
            if (files && files.length) {
                $scope.state.addr = files[0];
                $scope.$apply();
            }
        });
    };
});
```

My expectation:

1. User can click in the `input` element, a `dialog` would be shown.
2. User can select a directory or just cancel the `dialog`
3. The selected directory path will be placed in the `input` element.

But actually:

Once i click the `input`, no matter i select a directory or cancel the `dialog`, following error occurs:
![snip20151126_2](https://cloud.githubusercontent.com/assets/1059956/11417866/6606f630-9455-11e5-856d-ca6b9014f781.png)
 
But the code works just perfect in `0.35.0`. This error gets hurt me while i upgraded to `0.35.1`

**Comment by zcbenz** [comment] 2015-11-26 08:11
This is a duplicate of #3565, the fix will be included in next release.

**Closed by zcbenz** 2015-11-26 08:11 UTC
