### ISSUE TITLE
Background transparency fails on small window (< 160px)

### ISSUE THREAD

**Issue by ButzYung** [atom/electron#3014] opened 2015-10-06 19:23 UTC
Background transparency fails on small window when neither width nor height >= 160 pixels.

128x128 => transparency FAILED
168x168 => transparency OK
160x160 => transparency OK
160x32 => transparency OK

This issue is easily reproducible with codes like these.

    mainWindow = new BrowserWindow(width:128, height:128, frame:false, transparent:true, resizable:false});
    mainWindow.loadUrl('file://' + __dirname + '/blank.html');

"blank.html" has background color set to "transparent".

Tested on:
- Windows 10 Home 64-bit
- electron-v0.33.4-win32-ia32 (prebuilt version)

**Comment by zcbenz** [comment] 2015-10-08 01:20
This is a duplicate of #1392.

**Closed by zcbenz** 2015-10-08 01:20 UTC
