### ISSUE TITLE
Is there a way to restart my electron app from the html page?

### ISSUE THREAD

**Issue by ahgan84** [atom/electron#3524] opened 2015-11-20 10:03 UTC
I want to restart the whole electron app when I press a button from the index.html. It is not just reload the html page. I want to restart the whole electron app. Is there a way?

**Comment by jean-emmanuel** [comment] 2015-11-20 18:50
You can do it from the the main process this way:
```
var exec = require('child_process').exec
exec(process.argv.join(' ')) // execute the command the launched the currently running app
app.quit() // quit currently running app
```

**Comment by ahgan84** [comment] 2015-11-21 15:32
jean-emmanuel, I still can't make it work because I do not know how to call your restart function in the main process from the html page. And I can't find any exmaple from the web.
Can you provide some example?

**Comment by jean-emmanuel** [comment] 2015-11-21 17:01
It seems the app is terminated before being restarted; the only thing I can think of now is to wrap the last line in a setTimeout function to ensure the command has had enough time to be executed before killing the app:
```
var exec = require('child_process').exec
exec(process.argv.join(' ')) // execute the command that was used to run the app
setTimeout(function(){
  app.quit()
},50) // wait 50ms before killing the app
```

**Comment by kamesh-a** [comment] 2015-11-21 17:23
setTimeout might not be a viable workaround we have already tried it. As it might differ with different machine performance, you can better use spawn and detach the process, let it kill the app and start back the app , shell or bat based on OS

Hope this info helps

**Comment by ahgan84** [comment] 2015-11-21 17:32
kamesh-a, use spawn? Could you explain more? Any example on using it to restart the app?

**Comment by kamesh-a** [comment] 2015-11-22 09:02
sure.

Step 1 :
```
var child = require('child_process').exec;
var path = require('path');

var applicationPath, endIndex = process.resourcesPath.indexOf('/Contents');
applicationPath = process.resourcesPath.substring(0, endIndex); // Entire app path. param 1
var appToKill = 'Electron'; // assuming appName for testing purpose, param 2

console.log('Application Path to START : ' + applicationPath);
//we are passing process id for future reference
var daemon = child('sh restart.sh ' + applicationPath + ' ' + appToKill, function(err, stdout, stderr) {
    if (err) {
        console.log(err);
    }
    console.debug("STDOUT :", stdout);
    console.warn("STDERR : ", stderr);
});

```
Step 2 , restart.sh : 
```
appToOpen=$1; # app to open, simulating  restart ( entire path of app )
killall -9 $2; #app Name, will come here ex : "Electron"
open -nF $appToOpen;

```

Windows: 
Yes, you can take the params dynmically, just for example i have hardcoded.
```
taskkill /f /fi "imagename eq Electron.exe"
start "TEST" /high "Electron.exe"

```
App will restart, In case of windows, similar code but some tools quiet.exe will help to start .bat process in hidden mode.

**Comment by zcbenz** [comment] 2015-11-23 08:38
This is a duplicate of #539.

**Closed by zcbenz** 2015-11-23 08:38 UTC

**Comment by arn-ob** [comment] 2021-10-18 09:21
User ipcMain and ipcRenderer for reloading the electron application
I face reloading problems by using the Angular 11 build.

Then is add ipcMain from electron application, ( index.js or main.js )

```
ipcMain.on('hello-ipc-send', () => {
    app.relaunch({ args: process.argv.slice(1).concat(['--relaunch']) })
    app.exit(0)
});
```

After that, I use ipcRenderer from the Html file
Here is send the event to the electron application. From Html, ipcRenderer send the event and ipcMain receive the event

```
window.addEventListener("message", event => {
    if (event.origin === "file://" && event.source === window) {
        console.log("addEventListener", event.data)
        ipcRenderer.send("hello-ipc-send")
    }
});
```

That's how it worked
