### ISSUE TITLE
Frameless window not draggable on Mac OSX 10.8.5

### ISSUE THREAD

**Issue by kawa-marcin** [atom/electron#3329] opened 2015-11-04 10:42 UTC
I'm not sure if it's known issue but the frameless window doesn't react on drag at all. Exactly the same code runs correct way  on Windows[window is draggable]. Does anyone have got similar issue?

I'm aware of assigning the `-webkit-app-region: drag;` class to the draggable element.

**Comment by zcbenz** [comment] 2015-11-04 10:46
Which version of Electron are you using?

**Comment by kawa-marcin** [comment] 2015-11-04 11:15
```javascript
> console.log(process.versions['electron']);
> v0.34.2
```

**Comment by zcbenz** [comment] 2015-11-04 11:25
Does v0.34.0 work for you?

**Comment by kawa-marcin** [comment] 2015-11-04 11:50
Yes it does work for v0.34.0. Nicely spotted I haven't thought of downgrading it. Do you have some clues what causes the issue?

**Comment by zcbenz** [comment] 2015-11-04 12:15
It is very likely to be caused by #3163, we probably need to add the old way back for OS X 10.8.

**Comment by L-A** [comment] 2015-11-11 16:16
Sorry to add this, but elements with `-webkit-app-region: drag` don't seem to register properly on OS X 10.11.x either.

0.34.2 and 0.34.3: Window doesn't move.
0.34.0: Works as expected.

Can be reproduced by adding this line in `electron-quick-start/index.html`, and starting it frameless:

```html
<div style="-webkit-app-region: drag; height:100px; background-color:#DDD">
  This can't be dragged on OS X.
</div>
```

**Comment by zcbenz** [comment] 2015-11-12 04:31
I'm closing this since [Chrome is ending the support for OS X10.8](http://chrome.blogspot.ca/2015/11/updates-to-chrome-platform-support.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed:+blogspot/Egta+(Google+Chrome+Blog)), and we are not going to fix OS X 10.8 related bugs.

**Closed by zcbenz** 2015-11-12 04:31 UTC
Labels: wontfix

**Comment by zcbenz** [comment] 2015-11-12 04:56
@L-A The draggable area won't work if you have devtools opened.

**Comment by L-A** [comment] 2015-11-12 14:39
@zcbenz That's exactly it. Good to know.

**Comment by devployment** [comment] 2016-03-11 18:54
Looks like this is still an issue. Just tried exactly the same. No dragging on OS X 10.11.3 and electron 0.36.11. @zcbenz, devtools aren't opened. 

Can anybody else (@L-A ?) confirm that there is still an issue?

**Comment by L-A** [comment] 2016-03-11 19:45
@devployment Draggable regions will work even if your devtools are open, as long as they are detached from the window. I don't know if this is documented @zcbenz?

Example:
![dev tools](https://cloud.githubusercontent.com/assets/861964/13713615/dfcb340a-e797-11e5-929a-6eab48abda41.gif)

**Comment by devployment** [comment] 2016-03-11 20:27
Strange. My problem is that nothing is draggable at all. devtools are NOT open. 

I basically took the electron-quick-start and added what is documented

`<body style="-webkit-app-region: drag">
</body>` 

Running the same on a Windows box works as expected.

**Comment by devployment** [comment] 2016-03-12 10:33
Don't know what I did. But now it works. Deleted the whole electron-quick-start folder. Did a fresh clone. npm install && npm start and now it works.

**Comment by L-A** [comment] 2016-03-14 13:55
@devployment Don't quote me on this, but you usually have to restart Electron for the dragging behaviour to come back.

**Comment by WolfieWerewolf** [comment] 2016-03-26 23:13
I've experienced this same issue and just noticed something that I thought I would share.  I've only tested this on OSX 10.11.  With devtools open, when the issue is present, if you hover the edge of the BrowserWindow so that the re-size pointer appears, click and drag in the un-resizable direction, then you can actually drag the window.  For example, to drag horizontally, get the resize pointer on the top edge of the window and drag left or right.  After the initial drag it's possible to move the window in any direction.  The same applies to the right or left edge dragging up or down.  I've attached a little screen recording of this behaviour.

**Comment by L-A** [comment] 2016-03-29 13:55
@WolfieWerewolf That's an OS feature. I don't think Electron (or Chromium for that matter) can – or should – intervene on that behaviour.

**Comment by WolfieWerewolf** [comment] 2016-03-29 14:04
You're absolutely right.  I wasn't suggesting that anyone should take any action at all.  Just pointing out an observation that may make a developer's life easier :-)
