### ISSUE TITLE
BrowserWindow.setTitle throws an exception when set on a frameless window

### ISSUE THREAD

**Issue by aackerman** [atom/electron#2171] opened 2015-07-09 14:04 UTC
```
Uncaught Exception:
TypeError: Error processing argument 0.
    at TypeError (native)
```

A mostly unhelpful error message.

**Comment by deepak1556** [comment] 2015-07-09 18:28
Unable to reproduce, `TypeError (native)` happens when a JS -> C++ type conversion fails, be sure to check your arguments to function are of the required type (maybe you are passing undefined or null).

**Comment by zcbenz** [comment] 2015-07-10 05:41
As @deepak1556 said this error means you have passed a non-String to setTitle, so I'm closing this.

**Closed by zcbenz** 2015-07-10 05:41 UTC
