### ISSUE TITLE
OS X: title-bar-style: hidden-inset does not work in fullscreen mode

### ISSUE THREAD

**Issue by PalmerAL** [atom/electron#3230] opened 2015-10-27 00:39 UTC
OS X 10.11.1 (also happens in 10.11.0), Electron 0.34.0

Steps to reproduce:

 - Create a new browser window with ```"title-bar-style": "hidden-inset"```.
 - Enter fullscreen mode.

The titlebar is not hidden in fullscreen mode, meaning there is a blank bar on the top of the screen:

<img width="662" alt="screen shot 2015-10-26 at 7 37 44 pm" src="https://cloud.githubusercontent.com/assets/10314059/10746443/12cf9084-7c19-11e5-9599-f322376b5d3c.png">

This should have the same behavior as ``"title-bar-style": "hidden"``` - The title bar is hidden, and mousing over the top of the window reveals a small title bar with window controls.

**Comment by zcbenz** [comment] 2015-10-27 03:02
This is a duplicate of #2810.

**Closed by zcbenz** 2015-10-27 03:02 UTC
