### ISSUE TITLE
script/bootstrap.py fails on io.js because of runas

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#1516] opened 2015-04-28 17:50 UTC
Runas blows up because it's using old nan, but upgrading it to latest doesn't seem to help, yet when I just run `npm install`, it all works >:|   It'd be cool if we could get on official io.js for building so we could just replace all references of node.js everywhere in the docs

**Comment by zcbenz** [comment] 2015-04-29 10:42
I believe this is a duplicate of #1511.

**Closed by zcbenz** 2015-04-29 10:42 UTC
