### ISSUE TITLE
disable-renderer-backgrounding command line switch not working

### ISSUE THREAD

**Issue by brian-mann** [atom/electron#4317] opened 2016-02-02 01:22 UTC
I am running this prior to instantiating any `BrowserWindow` objects.

```javascript
app.commandLine.appendSwitch("disable-renderer-backgrounding")
```

But as soon as I minimize the app or just background it (by bringing another app in front) I can tell it is immediately throttled which causes all kinds of problems in my app.

In my situation I have a multi-window app, but as per https://github.com/atom/electron/issues/3225#issuecomment-152989623 I believe I'm doing it correctly.

**Comment by zcbenz** [comment] 2016-02-02 02:27
My original comment can be wrong since I didn't test it, the safest choice is to put it before the ready event of `app`. For per window you can take the [WebAudio hack](https://github.com/atom/atom/pull/9485/files).

**Comment by brian-mann** [comment] 2016-02-02 02:46
I am putting it before the `ready` event.

```coffeescript
app        = require("electron").app
init       = require("./handlers/init")

## prevent chromium from throttling
app.commandLine.appendSwitch("disable-renderer-backgrounding")

module.exports = ->
  app.on "ready", ->
    ## ...do things...
```

I will try the audio hack as well.

**Comment by brian-mann** [comment] 2016-02-02 03:07
I implemented:

```javascript
  var context = new AudioContext()
  var source = context.createBufferSource()
  source.connect(context.destination)
  source.start(0)
```

And I still see my process being backgrounded both in Chrome 48 and in Electron `0.36.7`.

I can tell it is being backgrounded because I'm using Promises everywhere and they go from taking `0.004 sec` each turn of the run loop up to `1 sec`.

**Comment by zcbenz** [comment] 2016-02-02 03:08
@brian-mann Can you make a test case for it? It is probably caused by other things since `disable-renderer-backgrounding` did work for other people.

**Comment by brian-mann** [comment] 2016-02-04 17:12
I'll see about getting this together. I agree - need to reduce the case.

**Comment by nathansobo** [comment] 2016-03-02 00:37
@zcbenz: I can confirm that this is broken, so I'm going to reopen the issue. I've created a [test case repository](https://github.com/nathansobo/disable-renderer-backgrounding-test-case) that demonstrates animation frames taking multiple seconds to fire even when using the `--disable-renderer-backgrounding` flag and the web audio hack.

Here's where this comes up in Atom. Here's two test suite windows that were started at the same time, except one was hidden and therefore throttled:

![screen shot 2016-03-01 at 3 13 17 pm](https://cloud.githubusercontent.com/assets/1789/13445300/a40c7798-dfc8-11e5-8044-3dd539272c2b.png)

More importantly, this is causing problems on CI such as [this one](https://github.com/atom/atom/issues/11019).

It would be great if we could find some way to make sure pages don't get throttled. If I'm doing something wrong in my example, please let me know.

**Comment by zcbenz** [comment] 2016-03-05 10:41
@nathansobo It is actually another issue, `disable-renderer-backgrounding` did prevent lowering the priority of renderer process, however for background pages Chromium has another throttling system for animations, I'll try to find a way to disable it.

**Comment by nathansobo** [comment] 2016-03-09 00:05
@zcbenz should we file an issue with the Chrome team about adding another flag? Is something you could maybe hack in?

**Comment by zcbenz** [comment] 2016-03-09 12:39
@nathansobo I tried to patch a few places related to throttling but none of them works for animations, so filing an issue would probably be the only choice.

**Comment by zcbenz** [comment] 2016-03-27 02:44
I have created #4925 for the `requestAnimationFrame` throttling problem, closing this issue now.

**Closed by zcbenz** 2016-03-27 02:44 UTC
Labels: bug
