### ISSUE TITLE
powerSaveBlocker crash

### ISSUE THREAD

**Issue by Ivshti** [atom/electron#2728] opened 2015-09-07 17:32 UTC
```
Error: Parse Error
    at Error (native)
    at TLSSocket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:520:20)
    at EventEmitter.ipc.sendSync (/Users/ivogeorgiev/linvo-cinematic/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at RemoteMemberFunction [as stop] (/Users/ivogeorgiev/linvo-cinematic/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:131:29)
    at EventEmitter.<anonymous> (file:///Users/ivogeorgiev/linvo-cinematic/services/player-core.js:106:46)
```

I get this message when using the power-save-blocker module, like this:
```
powerSaveBlocker.start("prevent-display-sleep")
```

**Comment by zcbenz** [comment] 2015-09-08 05:21
Can you share a full example? The error is apparently from renderer process, but `powerSaveBlocker` is only available in the main process.

**Comment by Ivshti** [comment] 2015-09-08 06:03
It's simply required before that with remote.

**Comment by zcbenz** [comment] 2015-09-08 07:33
I can't reproduce, and from the stack trace the place that crash is from your code, not from Electron.

**Comment by Ivshti** [comment] 2015-09-08 07:39
@zcbenz no, it is not. The last time my code worked in that stack trace is line 106 in player-core, which is:
```
        else if (blocker) { powerSaveBlocker.stop(blocker); blocker = null; }
```
And powersaveblocker is
```
var powerSaveBlocker = remote.require("power-save-blocker");
```

And it's not easy to reproduce because it doesn't happen often.

**Comment by zcbenz** [comment] 2015-09-09 07:38
From the stack trace the exception came from `net` or `http` module. Due to #1966 Node's message loop is still running when calling a remote method while waiting for browser process to response, the exception happened to occur when calling `powerSaveBlocker.start("prevent-display-sleep")`.

I suggest rechecking your code that use `net` or `http` module and catch all the errors in sockets and clients, it is very likely you didn't catch errors for a http request.

I'm closing this because the error apparently came from the client side and we can really do nothing if there is no reproducible example.

**Closed by zcbenz** 2015-09-09 07:38 UTC
