### ISSUE TITLE
Get tray icon position (bounds) without click event.

### ISSUE THREAD

**Issue by wiziple** [atom/electron#3884] opened 2015-12-21 09:11 UTC
Hello,

I'm building a tray (menubar) app using electron.
I know that there is a way of getting tray icon bounds through tray.on('click' function(event, bounds){}) event, but sometimes I want to show a BrowserWindow without tray.on('click') event.

For example, when I want to show the BrowserWindow when pressing the GlobalShortcut, it doesn't pass tray.on('click'), so technically there is no way to get bounds of tray icon.

To do this, there is two possible way.
1) Get a tray position and call BrowserWindow.setBounds()
2) Call a tray.click event so I can get a tray bounds.

I would appreciate if someone give me any way to resolve this issue.
Thanks.

**Comment by zcbenz** [comment] 2015-12-21 10:42
This is a duplicate of #2469.

**Closed by zcbenz** 2015-12-21 10:42 UTC
