### ISSUE TITLE
Windows: window.setThumbarButtons throws error

### ISSUE THREAD

**Issue by adam-lynch** [atom/electron#4411] opened 2016-02-07 19:27 UTC
```javascript
  mainWindow.setThumbarButtons([
    {
      tooltip: "Example",
      icon: 'C:\\Users\\Digital\\Desktop\\1.png',
      click: function() { console.log("Example button clicked"); }
    }
  ]);
```

![image](https://cloud.githubusercontent.com/assets/1427241/12874701/a8441226-cdd0-11e5-83c5-3caac657d8cd.png)

Windows 8.1. Electron 0.36.7.

**Comment by MarshallOfSound** [comment] 2016-02-08 02:46
Your icon path is probably wrong, try using `path.resolve` on a relative path.

**Comment by adam-lynch** [comment] 2016-02-08 10:11
@MarshallOfSound Is there are restrictions on the size of the PNG? If not, I doubt it. I did use `path.resolve` as well as hard coded absolute path.

**Comment by MarshallOfSound** [comment] 2016-02-08 10:20
I am not aware of any restrictions on the size, my first debugging step here though would be to run

```js
console.log(fs.existsSync(path.resolve('you/path/here')));
```

You can also read the docs on `NativeImage`

https://github.com/atom/electron/blob/master/docs/api/native-image.md

**Comment by kevinsawicki** [comment] 2016-02-08 22:41
@adam-lynch does it work if you use a `NativeImage` directly? This seems somewhat similar to #4335 which was being caused by a specific image for unknown reasons.

**Comment by adam-lynch** [comment] 2016-02-12 16:57
@kevinsawicki pretty sure I did yeah

**Comment by zcbenz** [comment] 2016-02-16 04:18
Usually it is because `C:\\Users\\Digital\\Desktop\\1.png` does not exist, but without an actual example app it is impossible to say.

**Comment by zcbenz** [comment] 2016-02-21 14:04
Closing until more information is provided.

**Closed by zcbenz** 2016-02-21 14:04 UTC
Labels: more-information-needed
