### ISSUE TITLE
transparent max window will not fill screen

### ISSUE THREAD

**Issue by sartrey** [atom/electron#1740] opened 2015-05-21 05:47 UTC
Transparent window will not fill screen when max.
It will keep a gap between window border and screen edge.

![](https://cloud.githubusercontent.com/assets/3841135/7603152/e2034e22-f960-11e4-93ac-10a30ea0478e.png)
This is a top-right corner of my test window,
the white and light gray border is gap.

**OS: Windows 8.1**
**electron: v0.26.0**

Code:
**index.html**
```
<!DOCTYPE html>
<html>
<head>
    <title>test</title>
    <style type="text/css">
        html, body {
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            background: #000;
        }
    </style>
</head>
<body style="-webkit-user-select:none;-webkit-app-region:drag"></body>
</html>
```

**app.js**
```
var app = require("app");
var browserWindow = require("browser-window");

var window = null;

app.on("window-all-closed", function () {
    if (app.listeners("window-all-closed").length == 1)
        app.quit();
});

app.on("ready", function () {
    window = new browserWindow({
        "width": 600, "height": 400,
        "frame": false, "transparent": true,
        "node-integration": true
    });
    window.loadUrl("file://" + __dirname + "/index.html");
    window.on("closed", function () {
        window = null;
    });
});
```
run the code, and set the window max:
![image](https://cloud.githubusercontent.com/assets/3841135/7742269/b6542c64-ffbf-11e4-820f-a50c43a93f10.png)

**Comment by sartrey** [comment] 2015-05-21 05:50
#1671 is original version of the problem

**Comment by zcbenz** [comment] 2015-05-21 07:09
This is a duplicate of #1690.

**Closed by zcbenz** 2015-05-21 07:09 UTC
