### ISSUE TITLE
Multi-session support for BrowserWindow and webview

### ISSUE THREAD

**Issue by k2xl** [atom/electron#959] opened 2014-12-26 03:13 UTC
When I use a webview and log in to a website (let's say github) it appears the session/cookie information is lost after restarting the application. Is there a way to enable this on the webview?

**Comment by 5paceManSpiff** [comment] 2015-02-18 21:24
Wouldn't it be possible to persist cookie data through injected javascript?

**Comment by hokein** [comment] 2015-06-16 12:21
@spolu How is this going now?

**Comment by spolu** [comment] 2015-06-16 15:59
@hokein unfortunately didn't get the time to work on this. Would love to though

**Comment by gajus** [comment] 2015-06-23 08:39
Without knowing anything about Electron architecture, shouldn't this be as easy as starting a separate process for each browser-window? or even better, have browser-process class that could be used to start windows using separate processes and allow communication between them.

**Comment by maxogden** [comment] 2015-07-10 21:37
My current workaround is deleting `~/Library/Application Support/Electron/Local Storage` and `~/Library/Application Support/Electron/Cache`, but this seems like the 'nuclear option'. Would be nice if there was a way to clear all cached state for both `browser-window` and `<webview>`

**Comment by gajus** [comment] 2015-07-24 17:42
This has been open for a long time. Has it been assigned any whatsoever priority?

**Comment by 5paceManSpiff** [comment] 2015-08-06 02:16
Wouldn't it be possible to extract the cookies from the browser context into the node context and save them to a file before closing?

**Comment by spolu** [comment] 2015-08-09 18:46
Setting them back up would be challenging at best

**Comment by gajus** [comment] 2015-11-14 16:16
@zcbenz this is assigned to you. Do you have any timelines for this issue?

**Closed** 2015-11-20 02:23 UTC
Labels: enhancement, webview

**Comment by zcbenz** [comment] 2016-07-03 23:41
@goddyZhao It works fine for me, can you provide a minimal app that can reproduce the problem?

**Comment by goddyZhao** [comment] 2016-07-04 03:04
Hi, @zcbenz ,

Here it is:

```javascript
const electron = require('electron');
const { app, BrowserWindow } = electron;

let mainWindow;

function createWindow () {
  mainWindow = new BrowserWindow({
    width: 1000,
    height: 600,
    webPreferences: {
      partition: 'persist:xxx'
    }
  });
  mainWindow.loadURL('https://github.com');

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

app.on('ready', createWindow);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (mainWindow === null) {
    createWindow();
  }
});

```

And the steps I did are:

1. `electron .` to start the app
2. Login the github and then quit the app (command+q on Mac)
3. restart the app again
4. It still shows that I am not login

BTW, I am using electron#1.2.5

Thanks!

**Comment by zcbenz** [comment] 2016-07-04 03:19
@goddyZhao That's weird, my login status is successfully remembered with the test case. Can you check whether the `~/Library/Application\ Support/Electron/Partitions/xxx/` directory is created?

**Comment by goddyZhao** [comment] 2016-07-04 05:06
Hi, @zcbenz , there is no `Electron` folder under `~/Library/Application\ Support`

**Comment by goddyZhao** [comment] 2016-07-04 05:10
By the way, start my application in the following ways (maybe that's the cause but I need your confirm and suggestion):

1. I actually start the app with npm script:
```javascript
"scripts": {
  "start": "electron ."
}
```
2. And I install `electron-prebuilt` module locally not globaly

I don't know whether that's why I don't have `Electron` folder. I looks like the `Electron` folder will only be created if I have an application named `Electron`, am I right?

Anyway, could you please help on that? Thanks

**Comment by zcbenz** [comment] 2016-07-04 10:39
@goddyZhao Is your login status saved if you don't set `partition`? And can you try running your pasted app with a globally installed `electron-prebuilt`? I think the problem is in other parts of your app.

**Comment by goddyZhao** [comment] 2016-07-04 13:58
Thanks @zcbenz , I tried the pasted app (the app has only package.json with no dependecies and a main.js with the above content I paste here, so the app is clean) with globally `electron-prebuilt`, it works. But there still no `Electron` folder under `~/Library/Application\ Support/`. I just wonder whether it is really persist session and where the session is saved?

**Comment by zcbenz** [comment] 2016-07-05 00:12
The default session is saved under `~/Library/Application\ Support/YOUR_APP_NAME`, and the persistent partition is saved under `~/Library/Application\ Support/YOUR_APP_NAME/Partitions/PARTITION_NAME`.

**Comment by goddyZhao** [comment] 2016-07-05 14:25
Thanks @zcbenz !

**Comment by goodhyun** [comment] 2016-07-23 13:24
I have the same symptom @goddyZhao already had, but a bit different. 
A portion of cooke is not persistent, for example, a login of facebook popup is continuously asking a password with the ID already filled in. I first thought it's facebook's peculiarity but 

`loginWindow.webContents.session.cookies.get({domain: ".facebook.com"}`
is obviously changing after a login popup, but if I restart app it all returns to the previous state. 

I tried to set it up with cache: false with 
`const ses = session.fromPartition('persist:facebook', {cache: false,});`
and also tried to flush but both all in vain.
`loginWindow.webContents.session.flushStorageData()`

looks like cache files are saved under the `~/Library/` though

What am I missing ?

**Comment by JosephusZhou** [comment] 2017-03-23 08:03
@zcbenz I create several webviews in a BrowserWindow, and every webview use a different partition to enable multi-session, I want to learn about where the different session data saved on the Windows platform, or it's saved temporarily?  The code is: 
`<webview id="wv_1" partition="ss_1" src="https://www.github.com/" disablewebsecurity="on" nodeintegration="on" style="display: inline-flex; width: 800px; height: 600px;" tabindex="-1" guestinstance="1"></webview>`
`<webview id="wv_1" partition="ss_1" src="https://www.github.com/" disablewebsecurity="on" nodeintegration="on" style="display: inline-flex; width: 800px; height: 600px;" tabindex="-1" guestinstance="2"></webview>`

**Comment by Hum4n01d** [comment] 2017-03-26 18:45
@zcbenz @goddyZhao What did you end up using? My code is here: [Amango](https://github.com/Amangoapp/Amango) and I want to save the session of the app's webviews or the whole thing if its easier. How should I go about this?

**Comment by sregger** [comment] 2020-01-31 10:57
I hit a similar problem. But I found that when I renamed

~/Library/Application\ Support/YOUR_APP_NAME/Partitions/PARTITION_NAME

to 

~/Library/Application\ Support/YOUR_APP_NAME/Partitions/OLD_PARTITION_NAME

then restarted the app it created a new partition name folder and started to work as expected.

Not sure what caused the problem. Could have been permission related, could have manifested after a app id rename, or other. But that's guess work.

**Comment by dimaslanjaka** [comment] 2021-12-04 04:19
This is all you need:
View html render with multiple webview https://github.com/dimaslanjaka/dimaslanjaka.github.io/blob/be17458dc7444993225b83fa05738c809ed9225a/packages/traffic-generator/src/views/webview-multi.html
Window electron builder with multiple proxy webview https://github.com/dimaslanjaka/dimaslanjaka.github.io/blob/be17458dc7444993225b83fa05738c809ed9225a/packages/traffic-generator/src/webview-multiple.ts
The Proxies https://github.com/dimaslanjaka/dimaslanjaka.github.io/blob/be17458dc7444993225b83fa05738c809ed9225a/packages/traffic-generator/src/proxies/index.ts

**Comment by leoAnimesh** [comment] 2023-07-10 12:03
keep the same persist:name, for both web preferences of the main browser window and the web views which are rendered this will able to share the cookies within multiple web view instances. It worked like a charm for me. Thank you
