### ISSUE TITLE
0.26.0, OS X. Don't work app-region attribute anymore

### ISSUE THREAD

**Issue by MaxGraey** [atom/electron#1661] opened 2015-05-12 12:41 UTC
If we use frameless window and set '-webkit-app-region: drag' for some div it's no longer in effect. I think problem with 'standard-window' which default set to true.

**Comment by joshaber** [comment] 2015-05-13 00:59
Hmm, I can't reproduce this. If I set `frame: false` on the default app the drag region seems to work.

**Comment by asamiller** [comment] 2015-05-15 17:44
I had this same issue after upgrading to 0.26 (from 0.24). Setting the window property to `'standard-window': false` fixed it for me. Otherwise it seems like the standard titlebar height (22px) is blocking the app-region even though the toolbar isn't shown. If I make my div height taller than that, I can grab the area below it.

**Comment by joshaber** [comment] 2015-05-19 01:24
Does #1670 look like the right fix?

**Comment by zcbenz** [comment] 2015-05-19 07:51
Fixed by #1670.

**Closed by zcbenz** 2015-05-19 07:51 UTC
