### ISSUE TITLE
Inspector does not allow viewing of cookies

### ISSUE THREAD

**Issue by tommoor** [atom/electron#2089] opened 2015-06-30 21:38 UTC
The following message is displayed in the inspector:

![image](https://cloud.githubusercontent.com/assets/380914/8442728/98befb6c-1f35-11e5-9451-a0506f37df8d.png)

However cookies are stored and retrievable via code. I haven't tried using the flag, but it seems that these should be viewable by default in Electron if possible?

**Comment by frankhale** [comment] 2015-07-01 15:53
I tried the command line switch from the command line and it has no effect. I also rebuilt Electron explicitly enabling this switch and it also had no effect. The inspector still says the message as the above screenshot shows. I'm going to play around with this for a little while and see if I can figure anything out. I'll report back if I do.

**Comment by deepak1556** [comment] 2015-07-01 16:40
@frankhale the commandline flag is deprecated , heres the discussion https://groups.google.com/a/chromium.org/forum/#!topicsearchin/net-dev/cookie/net-dev/47jdSKRnbqA . Best thing would be to patch this [line](https://code.google.com/p/chromium/codesearch#chromium/src/net/cookies/cookie_monster.cc&l=1771) to allow `file://` scheme in the default cookieable schemes. Since they have plans to remove the apis which allows to achieve the same [effect](https://code.google.com/p/chromium/codesearch#chromium/src/net/cookies/cookie_monster.cc&l=2411) . @zcbenz thoughts ?

**Comment by frankhale** [comment] 2015-07-01 17:15
Thanks @deepak1556!

I've been digging a bit into this and here is a little more to go with what you just said. The kEnableFileCookies switch will eventually take you to a file in the CookieMonster class named SetEnableFileScheme(bool accept). This has been block by #if defined(OS_ANDROID) in our version of Chromium.

Now looking at the comments are interesting:

```cpp
  // Resets the list of cookieable schemes to kDefaultCookieableSchemes with or
  // without 'file' being included.
  //
  // There are some unknowns about how to correctly handle file:// cookies,
  // and our implementation for this is not robust enough (Bug 1157243).
  // This allows you to enable support, and is exposed as a public WebView
  // API ('CookieManager::setAcceptFileSchemeCookies').
  //
  // TODO(mkwst): This method will be removed once we can deprecate and remove
  // the Android WebView 'CookieManager::setAcceptFileSchemeCookies' method.
  // Until then, this method only has effect on Android, and must not be used
  // outside a WebView context.
```

and this:

```cpp
// This assumes "file" is always at the end of the array. See the comment
// above kDefaultCookieableSchemes.
//
// TODO(mkwst): We're keeping this method around to support the
// 'CookieManager::setAcceptFileSchemeCookies' method on Android's WebView;
// if/when we can deprecate and remove that method, we can remove this one
// as well. Until then, we'll just ensure that the method has no effect on
// non-android systems.
```

So perhaps we shouldn't even enable it via patching since it's not robust enough based on the comments above?

Reference:

https://chromium.googlesource.com/chromium/src.git/+/43.0.2357.65/net/cookies/cookie_monster.h
https://chromium.googlesource.com/chromium/src.git/+/43.0.2357.65/net/cookies/cookie_monster.cc

**Comment by paulcbetts** [comment] 2015-07-01 17:18
> However cookies are stored and retrievable via code.

Really? Is that something Electron is doing recently? We had to patch this in explicitly

**Comment by tommoor** [comment] 2015-07-01 17:20
We've only been using Cookies in webviews, but that works correctly. In all honesty I haven't tested cookies in the standard browser window as our application uses localStorage instead for this shared state.

**Comment by zcbenz** [comment] 2015-07-05 14:03
This is a duplicate of https://github.com/atom/electron/issues/1852.

> Best thing would be to patch this line to allow file:// scheme in the default cookieable schemes.

I'm good patching this line.

**Closed by zcbenz** 2015-07-05 14:03 UTC
