### ISSUE TITLE
Exit code 3221225477

### ISSUE THREAD

**Issue by DerNivel** [atom/electron#3570] opened 2015-11-24 15:22 UTC
It works all fine but I get the exit code `3221225477`every time which causes npm to display an error if ran with a npm-script.

OS: Windows 10 Version 1511
Electron: 0.35.1

**Comment by paulcbetts** [comment] 2015-11-24 16:39
```
notepad+0x18ef0:
00000001`40018ef0 4883ec28        sub     rsp,28h
0:000> .formats 0n3221225477
Evaluate expression:
  Hex:     00000000`c0000005
  Decimal: 3221225477
  Octal:   0000000000030000000005
  Binary:  00000000 00000000 00000000 00000000 11000000 00000000 00000000 00000101
  Chars:   ........
  Time:    ***** Invalid
  Float:   low -2 high 0
  Double:  1.5915e-314

0:000> !error c0000005
Error code: (NTSTATUS) 0xc0000005 (3221225477) - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.
```

Looks like a crash in native code

**Comment by DerNivel** [comment] 2015-11-24 18:05
If I remove the code for `app.makeSingleInstance` it does not crash.

**Comment by DerNivel** [comment] 2015-11-24 18:11
I can't see from where the error is coming. Also happens with empty HTML-page and only the code to open the BrowserWindow.

**Comment by DerNivel** [comment] 2015-11-24 19:10
Ok, found it. Only happens if using `babel-core/register`

**Comment by zcbenz** [comment] 2015-11-26 02:50
Can you provide a reproducible example?

**Comment by DerNivel** [comment] 2015-11-26 11:08
Repo: https://github.com/DerNivel/electron-3221225477

Steps to reproduce:
1. Run with `npm start`
2. Wait at least 5 seconds after the window opened
3. Close the window
4. Exit code `3221225477` will show up by npm

Doesn't happens if you comment out the first line (`require('babel-core/register');`) in `index.js`.

OS: Windows 10 Update 1511
Electron: 0.35.1

**Comment by DerNivel** [comment] 2015-11-26 12:16
Getting this when enabling `ELECTRON_ENABLE_STACK_DUMPING`. But only if I wait at least 5 seconds:

```
Backtrace:
        v8::ResourceConstraints::stack_limit [0x00007FFCA8D0C14D+1845341]
        icu_54::TimeZoneNames::`vftable' [0x00007FF6FCDEF5A0+8111264]
        (No symbol) [0x000001490D661080]
```

**Comment by zcbenz** [comment] 2015-11-27 02:02
It is very likely a duplicate of #3580.

**Comment by zcbenz** [comment] 2015-11-30 12:35
After some investigation this is actually an unrelated bug to #3580, so I'm reopening this.

**Closed** 2015-11-30 14:40 UTC
Labels: bug, crash, windows

**Comment by SimoneTosato** [comment] 2017-08-03 17:17
I'm getting this exit code too from a child process using ref and node-ffi with a dll file, everything works fine in node, the package is tested and working on windows/linux/mac, when used in an electron app i get this error on windows only, eveything works fine with mac and linux. 👍 following this hoping for some solution

**Comment by BONDbATIF** [comment] 2018-05-29 14:10
@SimoneTosato  

I am also using same ref and ffi and facing same problem like you .When User is closing app getting below error 
shutdown request1npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! spot-pro@0.0.0 start: `electron electron/index.js "Home" "FieryXFConnec
tion" "10.212.80.112" "admin" "Fiery.1" "en_US"`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the spot-pro@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Users\gotam.b\AppData\Roaming\npm-cache\_logs\2018-05-29T13_56_3
8_747Z-debug.log

**Do you got any solution ?**

**Comment by mullen00** [comment] 2018-10-19 12:46
I got the same quetion  when using the pointer in c
