### ISSUE TITLE
Minimizable Method w/ RequestAnimationFrame

### ISSUE THREAD

**Issue by Dillybob92** [atom/electron#4940] opened 2016-03-29 18:44 UTC
Hey guys, thank you for adding the setMinimizable option [here](https://github.com/atom/electron/pull/4156)

One weird thing though. When we use that and minimize the window by using WindowKey+D RequestAnimationFrame is still working. **Which is a good thing for me!** Since I want it to always be running for my game, but is that intended? Because I don't want to install / use a new version of electron and then it will come back and bite me in my ass :)

**Comment by Dillybob92** [comment] 2016-03-29 18:47
It's funny because I've been trying to solve why Chromium disables RequestAnimationFrame when we minimize, but it doesn't when we use WindowsKey+D.  Which is a good thing in my case because my game is multiplayer and I need RAF to be running 24/7.   So using the setMinimizable option fixes that for me, but I hope it stays and doesn't turn into a bug and get's patched later down the road :(

**Comment by mbilker** [comment] 2016-03-29 21:22
Not to sound rude, but should game logic be tied to render events? Would it be better to use a Service Worker or Web Worker for that kind of background stuff?

**Comment by Dillybob92** [comment] 2016-03-29 21:44
Oh, yeah I use Web workers for some game logic too. But, the main issue is the arcade physics is tied to RAF. So if a player joins a game and starts shooting fireballs to attack a mob and then if another player joins and that player is alt-tabbed (window is not active), he won't receive notification of those fireballs being sent on his screen. (The server will send them, but his client won't get updated of them until he activates his screen again).

**Comment by zcbenz** [comment] 2016-03-31 12:22
Duplicate of #4925.

**Closed by zcbenz** 2016-03-31 12:22 UTC
