### ISSUE TITLE
how to access the node api from a remote page in electron?

### ISSUE THREAD

**Issue by sureone** [atom/electron#3133] opened 2015-10-19 05:04 UTC
In my electron app , I load the remote page(index.html) from remote url like("http://xxxx/index.html"), then I am trying to send a ipc event to the main process then handle it , and failed, but if I put the the index.html in local fs and it is OK.

So my question is how to enable the page to access the node api (like require,ipc, etc.) from the remote page.

------ (main process)
```javascript
  mainWindow = new BrowserWindow({width: 800, height: 600});
  // and load the index.html of the app.
  mainWindow.loadUrl('http://localhost:8080');
  //mainWindow.loadUrl('file://' + __dirname + '/index.html');
var ipc = require('ipc');
  ipc.on('spawn-ext-process', function () {
  console.log("spawn-ext-process");
});
```
--------- http://localhost:8080/index.html (render process)
```javascript
<script>
    var ipc = require('ipc');
    ipc.send('spawn-ext-process');
</script>
```

**Comment by MichaelOstermann** [comment] 2015-10-19 06:29
Have you tried using the [remote](https://github.com/atom/electron/blob/master/docs/api/remote.md) feature? As the docs say:

> In Electron, only GUI-unrelated modules are available in the renderer process.

Try using `var ipc = require('remote').require('ipc')`!

**Comment by zcbenz** [comment] 2015-10-19 09:09
Can you open devtools and see whether the code in `index.html` is updated? Sometimes browser cache will fool you for `http` pages.

If you can verify it is not caused by cache, please provide a full example app.

**Comment by zcbenz** [comment] 2015-10-27 12:56
Closing until more information is provided.

**Closed by zcbenz** 2015-10-27 12:56 UTC
Labels: more-information-needed
