### ISSUE TITLE
odd issue prevent me to copy or paste into text fields, only at times

### ISSUE THREAD

**Issue by adv0r** [atom/electron#4107] opened 2016-01-14 19:32 UTC
I'm finding a very odd issue that I was able to replicate on multiple machines.

I have an html+js app that I wrapped around with Electron. I am having problem with the MacOS distribution. 
There is one HTML text field that won't let me paste text into it. This bug only happens after I follow the procedure to distribute the app (copy my app/ folder into Electron.app).

In all the other instances, I can copy or paste just fine : 

* when I run it via npm start (mac and win)
* when I run it by doubleclicking electron.app and dragging app/ over it
* on windows

I wonder, what can be the difference there? How can I debug something like this?

**Comment by zcbenz** [comment] 2016-01-15 14:51
This is very likely a duplicate of #1151.

**Closed by zcbenz** 2016-01-15 14:51 UTC

**Comment by adv0r** [comment] 2016-01-15 16:29
Thanks for pointing that out. 

in #1151 the problem seems to be related to focus. This isn't happening to me, in fact I can type freely into the field. I just cannot paste into it.

The solution moreover seems to be specific to Atom, while I am not using it at all here : 

> specifying the full path to the Atom command within Atom.app solved the issue for me.

**Comment by zcbenz** [comment] 2016-01-16 03:37
Can you provide an example app?

**Comment by adv0r** [comment] 2016-01-18 14:28
not as-is, let me try to reduce it to the minimum

**Comment by adv0r** [comment] 2016-01-18 16:00
@zcbenz  here you can try to reproduce it yourself 

(http://gofile.me/6nytF/6RM4yvTI)[http://gofile.me/6nytF/6RM4yvTI]  . I had to stripe down quickly most unrelated files and html elements. Some fonts and css and js are still there so you can reproduce it . 

Try to run it with npm start (mac)  , and then by placing it inside Electron.app .

Basically cmd+a, cmd+c and cmd+v are disabled (only in the second case) .. 

additional note, maybe un-related maybe not. When ran with `npm start` ,I get an error in console the first time I select any text in that form :
``` 
2016-01-18 16:22:32.485 Electron Helper[29342:6918638] Couldn't set selectedTextBackgroundColor from default () 
```

**Comment by zcbenz** [comment] 2016-01-19 20:24
The link says "Unable to download file(s).".

I guess you are not creating an application menu for your app, the default app of Electron will create a default application menu when running an app, but once packaged the default application menu will be gone. All the default accelerators rely on the application menu to work.

**Comment by adv0r** [comment] 2016-01-19 21:49
the link expired, sorry for the inconvenience. [here](http://gofile.me/6nytF/aixazexs) is the new link, validity extended for a week  

> I guess you are not creating an application menu for your app
You are right, I am not creating it. Should I try creating one following [this tutorial](
http://electron.atom.io/docs/v0.36.4/api/menu/)?

**Comment by zcbenz** [comment] 2016-01-20 20:47
> Should I try creating one following this tutorial?

Yeah, the template in [Menu docs](http://electron.atom.io/docs/v0.36.4/api/menu/) is a good start, you might want to remove the devtools related items in final product.

**Comment by adv0r** [comment] 2016-01-21 15:43
Thanks, I tried:  I added a basic application menu to my application. 

As a result now I am unable to cmd+[a|c|v] also when launched via `npm start` 

I packed the sample app and re-uploaded here [here](http://gofile.me/6nytF/4xbUJ6OD)

**Comment by zcbenz** [comment] 2016-01-21 22:06
That's because you didn't add menu items for copy/paste.

**Comment by adv0r** [comment] 2016-01-22 14:34
That fixed it, thanks
