### ISSUE TITLE
--ignore-connections-limit switch not working

### ISSUE THREAD

**Issue by javan** [atom/electron#4391] opened 2016-02-06 18:26 UTC
I've been exploring the `ignore-connections-limit` switch in hopes of a performance boost, but can't see that it's having any effect.

My basic usage is:
```coffee
app.commandLine.appendSwitch("ignore-connections-limit", "example.com,example2.com")

app.on "ready", ->
  ...
```
Running Electron 0.36.7, the app loads a local .html file in a `BrowserWindow`, which in turn loads example.com in a `<webview>` tag. example.com loads assets from example2.com (its CDN).

When I inspect the network traffic in a debugger, I see no difference in loading. The 7th network request and beyond reveal some queueing, which seems to imply that Chrome's maximum connection limit (6) is still in place.

<img width="528" alt="screen shot 2016-02-06 at 1 09 12 pm" src="https://cloud.githubusercontent.com/assets/5355/12868421/6164b8f8-ccd4-11e5-80e9-36f7b4d6c378.png">

Am I missing anything? Thanks for your time! :heart:

**Comment by deepak1556** [comment] 2016-02-11 00:41
trace with `log-net-log` shows when the switch is not present it does hit the `SOCKET_POOL_STALLED_MAX_SOCKETS_PER_GROUP` but not otherwise so the switch works as expected. Based on this [comment](https://code.google.com/p/chromium/issues/detail?id=476749#c11)

The scenarios that cause queue and stall time
1) handling disk cache entries
2) delayed by resource scheduler due to  max connection rules
3) delayed by resource handler due to asset type & priority
4) waiting for a TCP socket in net stack  

For 1) we can disable-http-cache and the gain is negligent here, 3) is handled where we assign a higher priority for requests in `network_delegate`, 4) We allow creation of new sockets beyond on the six per group name, 2) is the main cause for queue time here, no direct way to control other than patching the schedule algorithm in `resource_scheduler.cc`.

@zcbenz thoughts ?

**Comment by javan** [comment] 2016-02-11 01:11
> 2) delayed by resource scheduler due to max connection rules

Isn't that what the `--ignore-connections-limit` switch is supposed to disabled? I assumed so based on name and wasn't able to find clarification.

**Comment by deepak1556** [comment] 2016-02-11 02:01
Sorry for not being clear, this is a bug with `ignore-connections-limit`. The resource scheduler is responsible for handling requests from renderer and it has a limit per host (6 connections) beyond which the request is queued. The number of sockets that can be created in the network layer was also limited to (6 for normal connections and some 2xx for websockets) , you can find information `client_socket_pool_base.cc` , beyond which chromium would wait for idle sockets to reuse or create one when socket is destroyed after its idle timeout. But with `ignore-connection-limit` we allowed creation of additional sockets beyond the limit but the queue caused by resource scheduler is still in place.

**Comment by javan** [comment] 2016-02-11 02:34
Gotcha. So `ignore-connection-limit` is doing *something* currently, but not allowing exceeding the max 6 connections?

**Comment by deepak1556** [comment] 2016-02-11 03:01
Yup, not sure about the ideal way to fix this. Will look into it.

**Comment by zcbenz** [comment] 2016-02-15 14:14
The `ignore-connection-limit` is for enabling unlimited concurrent long connections, which was introduced for chat clients. What you asked is to enable unlimited concurrent requests, which has been marked as won't fix long time ago: https://code.google.com/p/chromium/issues/detail?id=12066.

Chromium does have some private method to set maximum socket number, but it is not public and to use it we have to patch Chromium. I'm closing this since I don't think it worths the effort just for possible performance improvement.

**Closed by zcbenz** 2016-02-15 14:14 UTC
