### ISSUE TITLE
webview - allow to set background color while loading

### ISSUE THREAD

**Issue by bpasero** [atom/electron#1397] opened 2015-04-10 14:39 UTC
This might be a similar request to asking for BrowserWindow to have a way to set a background color. For a webview as long as the contents are loading I see white background. Since I load a dark thing later on, this results in some ugly white flash for a brief moment. Would be cool to be able to set the background color to be used while a webview loads the contents.

**Comment by mnquintana** [comment] 2015-04-10 14:49
:+1:

I can think of a few possible workarounds:
- [Atom's current approach - set a background color on index.html directly](https://github.com/atom/atom/blob/master/static/index.html#L2)
- Maybe a preload script? https://github.com/atom/atom-shell/blob/master/docs/api/browser-window.md#new-browserwindowoptions

**Comment by bpasero** [comment] 2015-04-10 15:40
The workaround does not fix the problem entirely. I am now hiding the
webview until after I set the contents and I still get white flashing.

I also saw the same behavior on a BrowserWindow where I see white flash
although my index.HTML had a background set.
Am 10.04.2015 4:49 nachm. schrieb "Machiste N. Quintana" <
notifications@github.com>:

**Comment by bpasero** [comment] 2015-04-10 15:42
Two more comments:
- I don't think the preloaded script has Dom access until the dom is loaded
- I see a dark theme option which would be perfect for me, but I guess that
is not for this particular problem
Am 10.04.2015 5:40 nachm. schrieb "Benjamin Pasero" <
benjamin.pasero@gmail.com>:

**Comment by Tribex** [comment] 2015-04-10 23:01
@bpasero How about opening a PR for setting the user-agent stylesheet for a webview? That would simplify changing the background color, as well scrollbars, buttons, etc.

**Comment by zcbenz** [comment] 2015-04-13 04:42
The webview is loaded as a browser plugin, and the white background you saw is actually the color of plugin holder.

**Comment by iamdriz** [comment] 2015-07-09 16:32
@zcbenz Is it possible to have this plugin holder be transparent so it doesn't show itself?

**Comment by zcbenz** [comment] 2015-07-10 05:32
@iamdriz It is possible, but I'm not familiar with related code in Chromium.

**Comment by frankhale** [comment] 2015-07-10 05:42
I had this problem as well, I decided to use jQuery to grab the browser plugin element which is in the webview and I set it's background color to something that was acceptable for my app. In my case I set it to black. It seemed to work for me. Maybe this will work for you?

**Comment by frankhale** [comment] 2015-07-10 05:46
Of course I could be totally off base, I don't seem to have to do this anymore, maybe because of the strategy I employ before I show my webview. I'm not sure but I thought I'd mention it.

**Comment by iamdriz** [comment] 2015-07-10 09:05
@frankhale Can you share your code for this? Although I'm not sure how this would fix the issue, as I don't show the window until the webview has loaded its content using:

~~~
mainWindow.webContents.on('did-finish-load', function() {
    setTimeout(function(){
        mainWindow.show();
    }, 4000);
});
~~~

And it STILL shows the white background even after 4 seconds after the load event.

**Comment by frankhale** [comment] 2015-07-10 15:48
When I was doing it it was just standard jQuery to grab the element (browser-plugin) or whatever it's name is, can't remember off the top of my head. Then I'd just set it's background color using the css function. In my particular case I set it to black. Maybe it worked, maybe it didn't but now in my app I don't have to do it anymore so that's why I said I may be totally off base by providing this. 

In my app I have the webview's visibility set to hidden, I load it while it's hidden and then I show it once it's ready. I don't see a white flash and I don't need to do any crazy setting of background colors. This is just my experience with webview but I'm sure it's not a valid solution for everyone.

**Comment by Triztian** [comment] 2015-11-26 11:58
Hey I just want to point out that the `<webview>` does become transparent if we don't give a fixed (px) width and height on the tag's styles.

It seems that the issue has been fixed on the chromium source

 * [Issue 553378:	Chrome webview allowtransparency does not work correctly when webview or its parent containers are defined with exact widths and heights in px](https://code.google.com/p/chromium/issues/detail?id=553378&q=status%3Aunconfirmed&sort=-id&colspec=ID%20Stars%20Area%20Feature%20Status%20Summary%20Modified%20OS)

 * [Issue 529899: Webview transparency regression](https://code.google.com/p/chromium/issues/detail?id=529899)

Not sure if the files mentioned on at the end of issue 529899 are part of atom or are compiled into the linked libs.

Or what would be the process to patch Electron

**Closed** 2016-03-15 12:12 UTC
Labels: enhancement, webview
