### ISSUE TITLE
Glitches in transparent mode since 0.36 (OS X)

### ISSUE THREAD

**Issue by evgenyzinoviev** [atom/electron#4157] opened 2016-01-19 18:03 UTC
0.35.6: https://www.youtube.com/watch?v=ZFDBxcNj2hg
0.36.0: https://www.youtube.com/watch?v=ts0qshKRDbo

**Comment by zcbenz** [comment] 2016-01-20 16:41
It should be a regression of Chrome 47, I'm closing this because I'm afraid there is nothing we can do in Electron since the transparent window rendering code is completely inside Chromium and we don't have the resources to fix the bug ourselves.

I suggest making a Chrome app with `alphaEnabled` option which reproduces the problem, and then report it to Chromium's issues list. It is basically the same with Electron's `transparent` option.

**Closed by zcbenz** 2016-01-20 16:41 UTC

**Comment by evgenyzinoviev** [comment] 2016-01-24 16:32
It seems that `alphaEnabled` only works on Windows. I created Chrome app with alpha enabled and required permissions, on Windows it looks ok (and no rendering bugs), on OS X it's not transparent, it's just like a window without a frame. So I can't even report them a bug. :((

I was going to implement this #3002, but it depends on transparency and since 0.36 it looks terrible.

**Comment by zcbenz** [comment] 2016-01-25 10:02
Chrome disables `alphaEnabled` on OS X and Linux because transparent window works terribly on these platforms, so before Chrome officially supports transparent window on OS X and Linux, you have to use it at your own risk.

**Comment by evgenyzinoviev** [comment] 2016-01-25 10:37
Is there a way to force-enable alpha in chrome app on OS X? To make a bug report somehow.

**Comment by zcbenz** [comment] 2016-01-25 10:47
It is hardcoded in Chromium by https://chromium.googlesource.com/chromium/src/+/7ec744bb44a15ceb8fe1a455568f4b7e9c635ca0. From the past experiences on reporting transparent related issues, I doubt they would mark this as won't fix anyway.

**Comment by evgenyzinoviev** [comment] 2016-01-25 14:34
Maybe you should add a note to the docs that `transparent` is not stable on Linux and OS X.

**Comment by evgenyzinoviev** [comment] 2016-01-25 14:40
Since you're saying that #4208 is not possible then apparently we have no other choice but backporting new features to 0.35.6 to use transparency and latest features. :)

**Comment by evgenyzinoviev** [comment] 2016-03-20 16:55
0.37 seems to be a little better but glitches still happen sometimes. Just to note.

**Comment by MentalGear** [comment] 2016-06-26 09:53
Does anyone knows what's the current status for current chromium codebase ?

**Comment by evgeniyzinoviev** [comment] 2016-06-26 10:00
51 is no better than 49. But sometimes usable. It depends on the layout and CSS somehow. You should try, maybe it will be OK for your app.

**Comment by MentalGear** [comment] 2016-06-26 10:12
Thanks for the quick reply! Could share some best practices you found out about and quirks to avoid ?

**Comment by sgarbesi** [comment] 2016-07-03 07:50
@MentalGear I believe it's from the translate3d property in CSS, although I could be wrong. If you disable GPU rendering, it fixes the problem on OS X. See my comments here: https://github.com/electron/electron/issues/381
