### ISSUE TITLE
Taking screenshoots using win.capturePage causes to electron take up all memory until it crashes

### ISSUE THREAD

**Issue by macbury** [atom/electron#4738] opened 2016-03-10 14:04 UTC
* Electron version: v0.36.8
* Operating system: Linux olimp 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64 GNU/Linux

http://electron.atom.io/docs/v0.36.8/api/browser-window/#wincapturepagerect-callback

My app takes periodically screenshot every one second. After one hour electron memory usage is 6GB and then it crashes

**Comment by zcbenz** [comment] 2016-03-11 10:17
This is a duplicate of #4086.

**Closed by zcbenz** 2016-03-11 10:17 UTC
