### ISSUE TITLE
EPERM while access to userData folder.

### ISSUE THREAD

**Issue by cumajkeee** [atom/electron#4484] opened 2016-02-15 08:52 UTC
Hi,

Windows 7, Electron 0.36.7

Received EPERM error while attempt to read userData folder using fs. App packaged using asar. Is it possible to avoid?

ps: on mac everything work fine.

**Comment by zcbenz** [comment] 2016-02-16 13:03
I think it is because you don't have access to that folder, can you try using Node.js to access the same folder?

**Comment by cumajkeee** [comment] 2016-02-17 13:25
Nope. It's weird, cause it's not first my manipulation with this file. Firstly I created a folder, created file inside, then write data there. After all this operations I try to readFileSync and it fails.

**Comment by zcbenz** [comment] 2016-02-17 15:11
I'm closing this since it is a Windows problem, not an Electron issue, I don't know the cause of the problem though.

**Closed by zcbenz** 2016-02-17 15:11 UTC
Labels: more-information-needed

**Comment by sr258** [comment] 2021-12-13 19:13
@cumajkeee I know the is a super necropost, but I'm having the same issue. It looks like this only happens if users are on enterprise Windows installation with an domain and profile sync. Have you ever found a cause?
