### ISSUE TITLE
Not able to install in Corporate Network

### ISSUE THREAD

**Issue by MisterFantastic** [atom/electron#1666] opened 2015-05-12 16:11 UTC
I tried installing the electron-prebuilt in corporate network and I get CERT_UNTRUSTED error. I even modified the .npmrc file to accept http://registry.npmjs.org/. Help me to fix this.

**Comment by zcbenz** [comment] 2015-05-19 07:49
This is possible duplicate of https://github.com/mafintosh/electron-prebuilt/issues/21.

**Closed by zcbenz** 2015-05-19 07:49 UTC
