### ISSUE TITLE
default window background color

### ISSUE THREAD

**Issue by yongkangchen** [atom/electron#861] opened 2014-11-25 05:28 UTC
![display](https://cloud.githubusercontent.com/assets/704762/5178438/d410e3f4-74a6-11e4-8e7a-242944aaa413.gif)

I run a quick start demo, and set index.html background:
```
<!DOCTYPE html>
<html style="background: #232323">
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    We are using node.js <script>document.write(process.version)</script>
    and atom-shell <script>document.write(process.versions['atom-shell'])</script>.
  </body>
</html>
```
There is a flash when start application. Is there any way to set the default window background color?

**Comment by bpasero** [comment] 2015-03-28 09:15
+1 for a way to set the native background color

**Comment by oneeezy** [comment] 2015-04-29 11:57
+1, yes. I'm glad that when I googled "Atom Default Background", this was the first page I found. 

Nice to know that others are thinking along the same lines ;)

User Experience is where it's at!

**Comment by tommoor** [comment] 2015-07-25 17:13
The background color also shows through when resizing a window as flashes of white around the edge, this is very obvious if your app's background isn't white. @zcbenz any thoughts on where this issue stands in priority - I noticed that it also affects Atom Editor :wink:

**Comment by frankhale** [comment] 2015-07-26 01:16
This isn't a complete answer to this issue but for people that may want to get their hands dirty I have successfully changed the background color of the Electron window for Windows by editing the native_window_views.cc file. In the NativeWindowViews constructor I added the following:

At line 320 where #if defined(OS_WIN) is defined

```cpp
HBRUSH brush = ::CreateSolidBrush(RGB(255, 0, 0));
::SetClassLongPtr(GetAcceleratedWidget(), GCLP_HBRBACKGROUND, (LONG)brush);
```

This changes the background to red. Now when I start Electron's default app and resize it I see a red background as the Chrome content window tries to keep up with the resize. 

If anyone is willing could you investigate similar ways to do this for Linux/Mac maybe even within the native_window_views.cc. 

Aside from doing this in Electron's code it can also be done from Chromium if need be. I'm sure similar techniques can be employed.

Additionally, Electron's default app loads too fast on my machine so I cannot see a red background as the app is loading. Does anyone have a sample Electron app that can simulate a very slow loading app that can cause the Chromium content window to load slowly so the background shows like in the animated gif above?

**Comment by frankhale** [comment] 2015-07-26 02:08
Actually my hack doesn't work totally, I just checked my own app (instead of the Electron default app). I suspect this will need to be patched in Chromium because the content window will still show white while the Electron window will be changed.

**Comment by frankhale** [comment] 2015-07-26 03:27
Changing this in chromium\src\ui\gfx\win\window_impl.cc seems to be out of the question, doesn't work. I'm looking at chromium\src\content\browser\renderer_host\render_widget_host_view_base.cc now. I don't know if this will be it either. Throw me a bone guys, LOL!

**Comment by frankhale** [comment] 2015-07-26 03:38
chromium\src\content\browser\renderer_host\render_widget_host_view_base.cc doesn't seem to work either. I'll try again tomorrow. We have to isolate exactly which window the content window is and then set the background color there. This is fun! LOL!

**Comment by frankhale** [comment] 2015-07-27 20:31
I got this bright idea to call insertCSS on the browser window before loadUrl but that doesn't work because apparently webContents is not initialized or if it is the insertCSS is ignored. This can be best illustrated by just commenting out your LoadUrl and what you'll see is a nice white background. You can open Dev tools and see a whole lot of nothing in any of the tabs. No ability to inspect the underlying content if there is any (which I suspect there isn't). 

I can certainly hand jam libchromiumcontent to make the background any color but this doesn't work universally (yet as I have not isolated every place the background of the window is set, there are a lot), for instance when resizing a page that has a webview you'll still see a white background. I've spent 8 hours today looking into this. LOL!

Additionally I've updated my last post to this issue and added some corresponding Chromium and CEF patches.

**Comment by ervumlens** [comment] 2015-07-28 01:23
@frankhale That's fantastic and incredibly encouraging. :trophy: Thanks for running with it even this far.

**Comment by frankhale** [comment] 2015-07-28 01:26
@ervumlens, there is a lot more research left but I'm making progress! =)

**Comment by frankhale** [comment] 2015-07-29 01:36
Just to recap this issue as far as Chromium goes. One hurdle to solve this is that Chromium hard codes Sk_ColorWHITE for a lot of backgrounds in the various components. Plus there are other areas of the code that don't use the SkColor.h. There is also at least one other header file that defines base colors used. 

Take some of what I wrote above with a grain of salt, in other words what I wrote is fully correct and I will try to provide some clarity soon. Yesterday I changed so much code in libchromiumcontent that I totally lost track of all my changes and now cannot reproduce what I have in my animated gif above. I'm working on it though. What I'm attempting to do in the short term as far as Electron goes is expose a new command line switch to override the base background color. This is the path of least resistance as far as an API goes and allows me to focus on the problem which is that god awful white background color. LOL!

**Comment by frozeman** [comment] 2015-08-13 09:12
+1 for this, would be very nice if we could set the default bg color!

**Comment by frankhale** [comment] 2015-08-19 21:17
There are multiple issues going on here. I've been looking at this for quite a long time. This particular comment isn't going to talk about the white window on app load although I am still looking into that one and have spent 10's of hours on it. This comment is a continuation of that. In my app I use a webview and the webview creates an object inside of it within a shadow-root. This object is white and when resizing will expose that gawd awful white window as the webview object tries to keep up with the resize. This object cannot be styled so you cannot just set it's background color, similarly I have not been able to select this object using jQuery. Seems the shadow-root is well.... shadowed, LOL!

On a whim I was like lets just make that object inside the webview an iframe instead of an object because I could then set it's background color to whatever I wanted. So I hacked web-view.coffee to do that. Everything still seems to function correctly, I can set the background color of that iframe inside the webview, pass along the webview src and all is well. Now resizing the window will show the color I want instead of the nasty white. Here is where I need a sanity check. Is there a specific reason the object inside the webview is an object? I mean, I made it an iframe and my app functions perfectly fine. It's not violating the sandboxing, eg. It's not getting node integration because of this change. It's still safely tucked away in that shadow-root inside the webview for which I have not enabled node-integration. No errors in the console, functionality is the same. Life is good. Is this insane? Can anyone comment on this?

**Comment by frankhale** [comment] 2015-08-19 21:34
In native_window_views.cc in the constructor I think we should provide a way to set an initial background color eg, through perhaps an option in the browser window creation.

At the end of the constructor I have put the following as an illustration. This gets us some of the way there but does not address the white window flash when everything is loading up. This does appear to help alleviate the white on resize issue. We'll need a way for users to specify their own custom color though. We'll need a way to translate a nice hex color string to the appropriate value for passing to this function. Additionally this uses Chrome code so should work on Linux and Mac. I only tested on Windows.

```cpp
// Here we just hard code the background to black to see if we can gain some control over the 
// elusive white window showing on resize. 
web_view_->set_background(views::Background::CreateSolidBackground(0xFF000000));
```

**Comment by frankhale** [comment] 2015-08-26 14:30
Here is something more concrete and usable. This doesn't solve the initial white window background but will help alleviate the issue once everything loads. This also won't solve the white background behind a webview because the webview uses the object tag and you cannot set the background color using CSS styling. I'm still working on the two issues I just mentioned.

Add to native_window_views.cc NativeWindowViews constructor (I added it at the bottom)

```cpp
  auto command_line = base::CommandLine::ForCurrentProcess();
  auto base_background_color = command_line->GetSwitchValueNative(switches::kSetBaseBackgroundColor);
  if(!base_background_color.empty()) {
    auto color = std::stoul(base_background_color, nullptr, 0);    
    web_view_->set_background(views::Background::CreateSolidBackground(color));
  }
```

Add to option_switches.h

```cpp
extern const char kSetBaseBackgroundColor[];
```

Add to options_switches.cc

```cpp
const char kSetBaseBackgroundColor[] = "set-base-background-color";
```

**Comment by bpasero** [comment] 2015-09-15 05:53
Nice progress! Setting the color through the exe would not really work for us though. We would need to set the background color right before the browser window, so having it as option in the constructor would be ideal!

**Comment by gabriel** [comment] 2016-01-20 00:13
Here is a PR for backgroundColor support on mac here:
https://github.com/atom/electron/pull/4161

**Comment by jordwalke** [comment] 2016-03-08 07:19
@gabriel - Does that pull request (4146) make Atom (and other electron apps) capable of setting the fill color when resizing? Or is there something else still missing?

**Comment by erusev** [comment] 2016-03-11 14:00
@gabriel I'd very much like to know that as well.

**Comment by gabriel** [comment] 2016-03-11 19:14
I think so? Because the background color can be set on transparent window natively, I think resizing in OS X should be normal when resizing?

I'm not totally familiar with the issue you are describing though (which might mean yeah it's fixed)

**Comment by frankhale** [comment] 2016-03-11 19:18
At least on Windows the native background color is white. The Chromium content layer's background color is determined differently. When resizing the Window the Chromium content layer is slower to resize so the native window background color shows up as the Chromium content layer's resize code runs and catches up. I dug into this extensively but in the end could not find a solution that was adequate.

**Comment by frankhale** [comment] 2016-03-11 19:34
Just as a side note and for anyone coming here that may need this. The screenshot in the original question is easily fixed by not showing the window until it completely loads. One need to set an event handler for "did-finish-load" and then show the Window. There won't be any white background flash at this point.

**Comment by frankhale** [comment] 2016-03-11 19:43
There is a second scenario where one may see a white background when resizing and that is when you use a webview. The underlying element is an HTML object which doesn't allow you to set the base color. The color is white. If you resize the window with a webview (or object tag) you will see a white layer trying to catch up as you resize the window. I looked into fixing this for weeks but I couldn't figure.

**Comment by jordwalke** [comment] 2016-03-11 20:09
@frankhale I'm not understanding - do you think @gabriel's diff will fix the resize issue?

**Comment by erusev** [comment] 2016-03-11 20:14
> The screenshot in the original question is easily fixed by not showing the window until it completely loads.

This approach has a drawback, though, as it makes apps look slower to launch.

**Comment by frankhale** [comment] 2016-03-11 20:14
@jordwalke, Sorry I was riffing off of the white background on window resize issue.

**Comment by frankhale** [comment] 2016-03-11 20:15
@erusev, yes I would agree with this.

**Comment by erusev** [comment] 2016-03-11 20:24
@frankhale Did you had a chance to see the PR of @gabriel and figure out if affects any of these issues?

**Comment by frankhale** [comment] 2016-03-11 20:54
@erusev, I am not a Mac user. This PR states in the title it's for Mac. Does it work on non Mac systems?

**Comment by erusev** [comment] 2016-03-11 21:07
@frankhale It seems to be Mac specific, indeed, I did not know that you're not a Mac user.

**Closed** 2016-04-03 04:44 UTC
Labels: enhancement

**Comment by atmosuwiryo** [comment] 2016-04-28 09:03
It is flickering on resize and change tab.
We are using node 5.10.0, 
Chromium 49.0.2623.75, 
and Electron 0.37.7.
![electron](https://cloud.githubusercontent.com/assets/13653687/14880709/8360a4fa-0d5a-11e6-80b9-c01729dfe307.gif)


Can't find workaround yet. :(

**Comment by mrtdeh** [comment] 2016-05-28 16:08
Hi i founded the best answer:
set trnasparent:true in main.js and run your electron app....

**Comment by z-ax** [comment] 2016-06-10 15:15
@mrtdeh, also tried first, but have problems with shadow then with frameless window.

**Comment by Hum4n01d** [comment] 2016-11-08 01:12
Hey guys, I found this and solved the issue: http://www.christianengvall.se/electron-white-screen-app-startup/

**Comment by riseremi** [comment] 2016-12-26 23:17
@Hum4n01d thank you!

**Comment by Hum4n01d** [comment] 2016-12-26 23:27
@riseremi no problem

**Comment by matthiasg** [comment] 2017-04-01 08:48
with electron 1.6.4 i still get a white splash on windows 10. Is this supposed to be solved ?

**Comment by coreyman** [comment] 2017-05-16 18:19
So using @Hum4n01d 's solution I can not seem to set the background-color to transparent. Wanted to put a drop shadow on one of my windows.

**Comment by Aceix** [comment] 2017-08-11 04:29
BrowserWindow now has a property, 'backgroundColor' for setting a background color before rendering the page

**Comment by tbogard** [comment] 2017-11-28 20:15
@Aceix that work pearls. When resizing an transparent window, it left a ugly white render. applying the `backgroundColor` parameter to BrowserWindow solved the issue

**Comment by wesamco** [comment] 2018-01-19 08:09
use the `backgroundColor` property on BrowserWindow, I set it to `'#00FFFFFF'` (top white top transparency) worked wonders for my app's use case.
but using the `show` property with the `'ready-to-show'` is a better way for most apps.

**Comment by matthiasg** [comment] 2018-01-31 12:18
This is not working though with kiosk mode enabled.

**Comment by Ph0enixKM** [comment] 2018-02-04 09:32
`win.setBackgroundColor("#222");`

That's it guys... 😄

**Comment by programmin1** [comment] 2018-10-25 06:55
Even on a wellknown Electron app like VS Code the bug pops up once in awhile where there is nothing in the window but transparent view of what is behind it.

**Comment by felixturner** [comment] 2022-06-07 01:05
Still seeing a white flash on startup with electron 15 / macos. Setting `backgroundColor` does not help.
