### ISSUE TITLE
Electron 0.36.6 throw error for electron-quick-start

### ISSUE THREAD

**Issue by grandtiger** [atom/electron#4268] opened 2016-01-29 14:20 UTC
I just gave the latest version a try, but the [electron-quick-start](https://github.com/atom/electron-quick-start) app threw error when I try to close the app, or even close the DevTools.

I switched back to 0.36.5 and it works fine. I wonder if electron-quick-start needs some update, or there are breaking changes (or bugs) introduced in 0.36.6. Thanks!

```
[19508:0129/091353:FATAL:scoped_handle.cc(44)] Check failed: false.
Backtrace:
        (No symbol) [0x000000014026E401]
        (No symbol) [0x000000014026787C]
        (No symbol) [0x00000001402A8569]
        (No symbol) [0x000000014029C2AB]
        (No symbol) [0x000000014029BA7E]
        (No symbol) [0x00000001401F0819]
        (No symbol) [0x00000001401F0ABC]
        (No symbol) [0x000000014017991B]
        (No symbol) [0x0000000140179D3F]
        v8::TypeSwitch::match [0x000007FED0A1BA2B+727259]
        v8::Locker::IsLocked [0x000007FED08CD7B7+1036007]
        v8::Locker::IsLocked [0x000007FED08CCB52+1032834]
        (No symbol) [0x0000038634608B1F]

[36412:0129/091418:FATAL:scoped_handle.cc(44)] Check failed: false.
Backtrace:
        (No symbol) [0x000000014026E401]
        (No symbol) [0x000000014026787C]
        (No symbol) [0x00000001402A8569]
        (No symbol) [0x000000014029C2AB]
        (No symbol) [0x000000014029BA7E]
        (No symbol) [0x00000001401F0819]
        (No symbol) [0x00000001401F0ABC]
        (No symbol) [0x000000014017991B]
        (No symbol) [0x0000000140179D3F]
        v8::TypeSwitch::match [0x000007FED0A1BA2B+727259]
        v8::Locker::IsLocked [0x000007FED08CD7B7+1036007]
        v8::Locker::IsLocked [0x000007FED08CCB52+1032834]
        (No symbol) [0x000001442AE08B1F]
``

**Comment by felicienfrancois** [comment] 2016-01-29 14:33
Duplicates #4266 ?

**Comment by zcbenz** [comment] 2016-01-30 03:25
This is a duplicate of #4266.

**Closed by zcbenz** 2016-01-30 03:25 UTC
